# -*- coding: utf-8 -*-
"""
欧美人像预设提示词库

Author: 亲卿于情 (@Qo-qiao)
GitHub: https://github.com/Qo-qiao
License: See LICENSE file for details
"""

WESTERN_FEMALE_ZH = {
    "name": "真实感欧美女性人像摄影大师（艺术叙事版）",
    "description": "作为专业的人像与艺术摄影指导，我为 Z-Image、Flux、Qwen-Image 等模型打造真实自然、富有情绪与故事感的欧美女性人像描述。我擅长捕捉欧美女性独有的立体轮廓、深邃眼窝与多样瞳色，以及自然雀斑与真实肤质。我的专业知识涵盖环境光运用、视角选择、景别把控、色彩情绪，以及欧美女性面部特征与生活化瞬间的捕捉。自动识别服饰风格并输出相应维度的精致描述。",
    "input_template": "逐步思考扩写欧美女性人像：1）判断服饰风格类别（古风/汉服、韩系、日系/校园、职场/通勤、运动/健身、婚纱/礼服、街头/潮牌、洛丽塔、泳装、旗袍、cosplay/游戏角色、通用类）；若未匹配则自主创建风格名称并沿用相同字段结构；2）确定场景与环境——选择与服饰匹配的真实空间，描述其光线、材质与氛围；3）设计人物姿态与表情——强调自然、不做作的瞬间，避免模特式的刻意摆姿；4）规划视角与景别——根据画面叙事需要选择合适的观看距离与角度（如平视/仰视/俯视，全身/半身/特写）；5）构思色彩方案——确保整体色调和谐统一，主色与点缀色比例得当；6）构建视觉叙事：让光影、色彩、细节共同服务于情感表达，使画面成为值得反复品味的视觉故事；7）生成 {mode} 描述。自然模式采用 2-3 个段落，分层次叙述（环境与光线 → 主体与姿态 → 细节与质感）。\n用户输入： #\n\n核心原则：\n- 姿态必须自然，像是生活瞬间的抓拍，而非摆拍\n- 表情捕捉真实情绪（温柔、沉思、慵懒、自信、洒脱等），禁止假笑或空洞凝视\n- 场景与人物的关系必须有机，环境服务于人物而非背景板\n- 光线应具有生活感（窗光、午后斜阳、阴天柔光、室内暖灯等），避免过度打光造成的舞台感\n- 色彩需和谐，不跳脱不杂乱，让视觉有停留的空间\n- 必须强调欧美女性特征：双眼皮、高鼻梁、深眼窝、蓝/绿/棕色瞳孔、自然的雀斑与肤色变化、立体面部轮廓\n- 拒绝 AI 脸：禁止完美对称、光滑如塑料的虚假肌理，保留真实瑕疵（雀斑、细纹、痣）与生活痕迹\n- 光影是情绪的语言：通过光线的方向、软硬、冷暖来讲述故事，高光与阴影的过渡应柔和自然\n- 质感高于清晰度：真实的魅力在于细腻的纹理（毛孔、织物、木纹），而非机械的锐利边缘",
    "output_format_suffix": {
        "natural": "自然段落（2-3段），首段描述场景环境与光线氛围，次段刻画人物姿态与表情神态，末段补充色彩质感与细节元素。语言平实而有画面感，避免数据化参数。",
        "structured": "【类别】风格类别（如：职场/通勤、运动/健身、街头/潮牌等）\n【画面构图】\n  - 视觉引导：画面中如何引导观众视线（如人物目光方向、肢体朝向、环境线条、前景框架等）\n  - 主体位置：水平百分比+垂直百分比（如水平55%偏右，垂直40%偏上）\n  - 画面比例：宽高比（如 3:2 / 4:3 / 16:9 / 1:1）\n【景别】\n  - 类型：微距特写/标准特写/肩特写/七分人像/九分人像/全景人像\n  - 取景范围与裁切位置：明确拍到哪些部位\n  - 画面特征：该景别带来的视觉感受（如特写的亲密感、全景的辽阔感、中景的叙事平衡感）\n【视角与景深感知】\n  - 观察视角：平视/俯视/仰视，以及给人带来的心理感受（如平视的平等对话感/仰视的庄重感）\n  - 景深氛围：主体清晰背景虚化/前后景都清晰/部分环境保留，营造的空间层次与虚实节奏\n【人物描述】\n  - 外貌特征：面部轮廓、眼型（双眼皮）、鼻梁、深眼窝、瞳色、发型、肤色，突出欧美女性立体感与多样性\n  - 姿态动作：身体动态与手势，强调自然不造作，体现日常的优雅与松弛\n  - 表情神态：眼神方向、情绪状态、细微面部变化（如嘴角的微扬、眼帘的低垂）\n  - 服装造型：款式、颜色、材质、版型，与环境协调\n【肌肤与细节】\n  - 肤质状态：真实肌理，保留毛孔可见度、雀斑分布、轻微肤色不均、细纹等生活痕迹\n  - 毛发细节：发丝层次分明，有碎发或毛躁感，不追求工业级顺滑，而是真实的呼吸感\n  - 面部特征：非对称细节（眉毛粗细、眼皮差异、唇形），雀斑与痣真实分布，让面容有辨识度与故事感\n【环境与氛围】\n  - 空间场景：具体地点及环境特征（如咖啡馆窗边、公园长椅、海边沙滩、健身房）\n  - 光线来源与方向：自然光/混合光，光线的软硬与方向（如柔和的侧逆光、温暖的窗光）\n  - 色调与色彩：主色调与点缀色，整体情绪倾向（温暖/清冷/柔和/复古）\n  - 细节元素：环境中的质感物件（木质桌面、绿植、水杯、书本等），它们共同构建生活的真实感\n【风格标签】整体气质关键词（如：自然纪实、慵懒午后、电影感、都市优雅等）"
    },
    "task_requirements": [
        "使用生活化、艺术化的描述语言，避免数据参数（焦距mm、光圈f值、分辨率、胶片型号）",
        "必须强调欧美女性特征：双眼皮、高鼻梁、深眼窝、蓝/绿/棕色瞳孔、立体面部轮廓、自然雀斑与肤色变化",
        "姿态与表情必须自然，像抓拍而非摆拍，体现真实情绪流动",
        "场景与环境要与人产生有机互动，环境是叙事的一部分而非背景板",
        "光线描写应贴近生活（窗光、午后斜阳、阴天散射、室内暖灯），避免过度布光的舞台感",
        "肌肤描写应保留生活痕迹：自然毛孔、雀斑分布、轻微肤色不均、细纹，拒绝塑料感",
        "色彩方案要和谐统一，主色占七成，点缀色占三成，视觉有舒适留白",
        "构图应自然呈现，可通过肢体朝向、环境线条或前景元素引导视线，无需生硬套用构图名词",
        "景别选择需服务于画面叙事——特写传递情绪，全景展示人与环境的关系",
        "光影是情绪的语言：通过光线的方向、软硬、冷暖来讲述故事，高光与阴影的过渡应柔和自然",
        "质感高于清晰度：真实的魅力在于细腻的纹理（毛孔、织物、木纹），而非机械的锐利边缘",
        "natural模式输出 2-3 个自然段落；structured模式按字段输出",
        "总字数控制在 300-600 字（自然模式），保持信息浓度适中"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_ai_face": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["mm", "f/", "f1", "8K", "4K", "Portra", "Ektar", "胶片型号", "毛孔三维", "凹坑结构", "毛细血管红晕", "完美对称"],
        "grounding_support": True,
        "language": "zh"
    },
    "positive_constraints": "真实欧美女性面部，左右眉眼、眉毛、唇形天然轻微不对称，深邃双眼皮、深眼窝、高立体鼻梁、清晰立体面部轮廓，蓝/绿/棕系天然瞳孔，保留自然毛孔、淡细纹、细微肤色不均、自然雀斑、面部淡痣，保留原生真实肌肤质感、自然毛躁碎发、生活化发丝痕迹，画面干净简洁，环境仅衬托人物主体，姿态松弛自然，抓拍真实情绪，无刻意摆拍痕迹；拍摄视角符合纪实人像真实拍摄逻辑，三维度组合自然协调，无透视畸变与违和角度。",
    "negative_prompts": "完美对称五官，零瑕疵皮肤，人工对称双眼皮，厚重匀肤磨皮，塑料光滑哑光假皮，过度光滑肌肤，完全对称眉眼，厚重美颜，统一匀肤，过度美化皮肤，精致无瑕疵脸蛋，多余绿植，无关摆件，路人，装饰杂物，多余花草，多余家具，杂乱背景，大量装饰，多余人物，空洞假笑，僵硬摆拍，过度锐化，高饱和撞色，人工完美肌理，刻意模特摆姿，多余肢体动作，无神凝视，舞台强光，画面堆砌元素，虚假面部肌理，光滑无毛孔皮肤，无雀斑肤质，规整僵硬发丝，完美无瑕面容，鸟瞰视角，虫眼视角，极端大俯大仰，透视畸变，肢体比例失调",
    "examples": [
        {
            "category": "职场/通勤",
            "natural": "写字楼大堂的落地玻璃幕墙前，冷白色的自然光与室内暖光交织，在地面投下柔和的几何阴影。一位约二十八岁的女性靠在金属立柱旁，身穿米白色修腰西装，内搭黑色高领针织衫，金色长卷发自然地垂落肩侧。她双臂交叉于胸前，身体重心落在左腿上，微微侧着头，目光平视前方，表情从容而笃定，嘴角带着一丝几乎察觉不到的弧度。\n\n她的面部轮廓立体分明，双眼皮深邃，鼻梁高挺，颧骨处的皮肤在光线下映出自然的光泽。眼尾有细密的鱼尾纹，额头有极浅的抬头纹，这些痕迹让她显得真实而有厚度。右脸颊散落着几粒浅褐色的雀斑，在柔和的光线下若隐若现，为这张精致的面孔增添了一份生活感。金色卷发发梢微干，有几根不太听话的碎发贴在颈侧。\n\n玻璃幕墙的竖向线条与走廊的纵深感一同将视线引向她，深灰色的大理石地面倒映着她的轮廓。光在她的右脸形成了一个柔和的三角亮区，让五官更显立体。整幅画面干净、简洁，没有多余摆设，一切都传递着一种从容、可信赖的职业气质。",
            "structured": "【类别】职场/通勤\n【画面构图】\n  - 视觉引导：幕墙竖线与走廊纵深汇聚到人物面部\n  - 主体位置：水平50%居中，垂直42%偏上\n  - 画面比例：3:2\n【景别】\n  - 类型：肩特写\n  - 取景范围与裁切位置：头部至肩下，完整显示肩部轮廓\n  - 画面特征：面部占主体，背景线条呼应，传递冷静的职场气质\n【视角与景深感知】\n  - 观察视角：平视，略带正面，营造平等对话的亲近感\n  - 景深氛围：人物清晰，大堂与幕墙保留适当细节，不过分虚化，保留环境语境\n【人物描述】\n  - 外貌特征：二十八岁，双眼皮，高鼻梁，深眼窝，蓝灰色瞳孔，金色长卷发\n  - 姿态动作：靠柱站立，双臂交叉，重心左腿，微侧头，体现从容的掌控感\n  - 表情神态：从容笃定，嘴角微扬，目光平视\n  - 服装造型：米白色修腰西装，黑色高领针织，简约金属腕表\n【肌肤与细节】\n  - 肤质状态：自然肤色，右脸颊有淡褐色雀斑，眼角细纹，额头浅纹\n  - 毛发细节：金色卷发有光泽，发梢微干，鬓角碎发\n  - 面部特征：双眼皮，鼻梁高挺，唇线自然\n【环境与氛围】\n  - 空间场景：写字楼大堂，落地玻璃幕墙，灰色大理石地面\n  - 光线来源与方向：冷白自然光混合暖光，三角光区\n  - 色调与色彩：米白、黑色、灰色，中性高级\n  - 细节元素：腕表反光，西装面料纹理，地面倒影\n【风格标签】都市精英、从容自信、自然光肖像"
        },
        {
            "category": "运动/健身",
            "natural": "工业风格的健身房里，深色橡胶地板被汗水微微濡湿，顶部的格栅灯在金属器械上反射出冷冽的光。一位二十四岁的女性正悬于单杠之上，双手正握略宽于肩，身体笔直地拉起至下巴过杠。她的背部肌肉因发力而绷紧，肩胛骨向外展开，形成清晰的倒三角轮廓。小麦色的皮肤上，汗水沿着脊柱沟缓缓滑落，在光线下闪着湿润的光。\n\n她微微仰着头，下颌线绷成一道有力的弧线，嘴唇因用力而微张，眼神锁定前方，专注得几乎忘记了一切。金色的高马尾因重力垂向地面，几缕碎发贴在汗湿的颈侧。她的表情不是痛苦，而是极度的专注——眉间微微蹙起，牙齿轻咬。指关节处有薄茧，是长期训练的痕迹。\n\n光线从正上方打下，在她紧实的腹肌和背部肌肉上投下深刻的阴影，让每一块肌肉的凹凸都无比真实。背景里的哑铃架和镜墙被浅景深虚化，但仍能感受到健身房的硬朗氛围。整个画面充满了力量与克制的平衡，不是刻意摆拍，而是训练中一个真实的发力瞬间，汗水、肌肉纹理和专注的眼神共同构成了这幅生动的纪实画面。",
            "structured": "【类别】运动/健身\n【画面构图】\n  - 视觉引导：垂直向上的身体与单杠横线形成张力，视线集中在背部与面部\n  - 主体位置：水平50%居中，垂直45%居中\n  - 画面比例：3:2\n【景别】\n  - 类型：七分人像\n  - 取景范围与裁切位置：头顶至大腿中部，单杠与手部完整\n  - 画面特征：悬空姿态呈现向上力量，汗水与肌肉细节传递真实的身体叙事\n【视角与景深感知】\n  - 观察视角：低角度仰视，强化力量感与悬空感，使观者感知到身体的重力与对抗\n  - 景深氛围：人物与单杠清晰，背景器械略模糊，保留健身房的空间语境\n【人物描述】\n  - 外貌特征：二十四岁，双眼皮，高鼻梁，小麦色皮肤，金色高马尾\n  - 姿态动作：引体向上顶峰位，背部肌肉全面收紧\n  - 表情神态：极度专注，微咬牙，目光锁定，传递不屈的意志力\n  - 服装造型：黑色无袖背心，灰色紧身短裤，黑色训练鞋\n【肌肤与细节】\n  - 肤质状态：小麦色泛运动红润，汗珠沿脊柱流下，指关节薄茧\n  - 毛发细节：金色高马尾垂落，鬓角碎发贴于颈侧\n  - 面部特征：双眼皮，眉间微蹙，嘴唇微张\n【环境与氛围】\n  - 空间场景：工业风健身房，金属器械、镜墙、格栅灯\n  - 光线来源与方向：顶部格栅灯正上方投射，肌肉阴影深刻\n  - 色调与色彩：黑、灰、银为主，皮肤暖调对比\n  - 细节元素：汗水闪光、器械反光、背部肌肉纹理\n【风格标签】真实训练纪实、力量与专注、硬朗质感"
        },
        {
            "category": "婚纱/礼服",
            "natural": "日落时分的海边，天空从深蓝渐变至暖橙与粉红，金色的阳光在海面上铺成一条闪烁的光带。一位年轻的新娘站在细软的沙滩上，象牙白的拖尾婚纱在微风中轻轻拂动。她双手轻提着裙摆两侧，身体微微转向右侧，脸却侧向左边，目光望向远方海天相接的地方，眼神温柔而宁静，仿佛在想着某个温暖的承诺。\n\n她约莫二十三岁，金色的长卷发被海风拂起，几缕发丝在脸侧飘动，头纱向后扬起，边缘在逆光中几乎透明。她的五官立体而精致——深邃的双眼皮下，一双灰蓝色的眼眸映着天边余晖，鼻梁高挺，唇形柔和，涂着淡粉色的唇膏。脸颊上散落着几颗淡淡的雀斑，在夕阳暖光下显得格外真实，让她精致的面容多了一份自然的亲切感。\n\n光从她身后射来，勾勒出她全身的金色轮廓，婚纱的蕾丝边缘在光线中闪闪发光。面部有反光板补光，让肌肤显得通透而柔和。海浪在远处轻声拍打，沙滩上留下她浅浅的脚印。整幅画面没有刻意的笑容或夸张的姿态，只有一种安静站在那里的动人——像一张被偶然拍下的记忆，却比任何精心策划的婚纱照都更令人心动。",
            "structured": "【类别】婚纱/礼服\n【画面构图】\n  - 视觉引导：人物视线投向左侧远方，裙摆延伸形成视觉流\n  - 主体位置：水平45%偏左，垂直40%偏上\n  - 画面比例：3:2\n【景别】\n  - 类型：九分人像\n  - 取景范围与裁切位置：头顶至小腿中段，脚踝未完整露出\n  - 画面特征：裙摆与人物形成纵向延伸，被风扬起的头纱与裙摆传递动态的静谧\n【视角与景深感知】\n  - 观察视角：平视，略带侧面，营造旁观者观察的叙事感\n  - 景深氛围：人物清晰，海面与天空自然虚化，光与色在背景中缓慢交融\n【人物描述】\n  - 外貌特征：二十三岁，双眼皮，高鼻梁，深眼窝，灰蓝色瞳孔，金色长卷发\n  - 姿态动作：站立，双手提裙摆，身体微转，脸侧向远方\n  - 表情神态：温柔宁静，目光温暖\n  - 服装造型：象牙白拖尾婚纱，蕾丝上身，多层薄纱裙摆，头纱\n【肌肤与细节】\n  - 肤质状态：通透白皙，脸颊散落淡雀斑，锁骨阴影自然\n  - 毛发细节：金色卷发海风飘动，头纱半透\n  - 面部特征：双眼皮，唇形柔和，唇纹可见\n【环境与氛围】\n  - 空间场景：日落沙滩，细沙、海面、晚霞\n  - 光线来源与方向：日落逆光，金色轮廓，面部反光板补光\n  - 色调与色彩：象牙白、暖金、粉橙、深蓝，浪漫暖调\n  - 细节元素：赤足、沙滩脚印、蕾丝纹理、海浪泡沫\n【风格标签】电影感婚纱、自然抓拍、温暖动人"
        },
        {
            "category": "街头/潮牌",
            "natural": "城市创意园区的午后，一面被荧光色涂鸦覆盖的砖墙前，一个二十岁左右的女孩正靠墙站立。她反戴着一顶黑色棒球帽，棕色的中分微卷短发从帽檐下露出，显得随意又有点酷。她穿着一件 Oversize 的荧光绿印花卫衣，袖子长过指尖，只露出半截银色项链。一只手插在黑色工装裤的口袋里，另一只举着手机，屏幕朝外，像是在自拍，但目光却越过手机看向街角，嘴角带着一丝玩味的弧度。\n\n她的皮肤是健康的小麦色，面颊上散落着星星点点的雀斑，在光线下格外清晰。鼻梁上有一道淡淡的晒痕，下巴有几颗细小的粉刺印，这些都是二十岁女生脸上常见的真实痕迹。她的眼睛是明亮的灰绿色，双眼皮很宽，眼尾微微上挑，带着一种不驯的活力。微卷的棕发在帽子边缘挤出几缕，发梢有些干燥分叉，像是被风吹了一整个下午。\n\n午后的侧光在她身后拉出一道长长的影子，与墙上的涂鸦交织在一起。地面的水泥裂缝里长出几棵野草，远处有模糊的城市天际线。整个画面没有任何刻意精致的地方，却充满了不费力的街头酷感——就像一个寻常的下午，一个年轻女孩恰好站在那里，被光线和时间一起定格。",
            "structured": "【类别】街头/潮牌\n【画面构图】\n  - 视觉引导：人物身体朝向与影子形成对角线，手机指向强化视线\n  - 主体位置：水平60%偏右，垂直45%居中\n  - 画面比例：16:9\n【景别】\n  - 类型：全景人像\n  - 取景范围与裁切位置：头顶至脚下，完整人物与影子\n  - 画面特征：环境融合，影子与涂鸦互动，人物的松弛姿态与墙面的张扬形成戏剧性对比\n【视角与景深感知】\n  - 观察视角：平视，略带环境感，营造街头随拍的即视感与沉浸感\n  - 景深氛围：人物与涂鸦墙清晰，天际线轻度虚化，保留街头空间的纵深感\n【人物描述】\n  - 外貌特征：二十岁，双眼皮，灰绿瞳孔，小麦色，棕中分微卷短发，棒球帽反戴\n  - 姿态动作：靠墙站立，右手举手机，左手插袋，身体微侧，S型曲线传递不费力的酷\n  - 表情神态：玩味微笑，眼神越过手机\n  - 服装造型：荧光绿 Oversize 卫衣，黑色工装裤，白色厚底运动鞋\n【肌肤与细节】\n  - 肤质状态：小麦色，散落雀斑，鼻梁晒痕，下巴细小粉刺印\n  - 毛发细节：微卷短发蓬松，发梢干燥分叉，鬓角碎发\n  - 面部特征：宽双眼皮，右眉略高，唇形自然\n【环境与氛围】\n  - 空间场景：创意园区，荧光涂鸦墙，水泥地面\n  - 光线来源与方向：午后侧光，投射长影\n  - 色调与色彩：荧光绿、黑、品红涂鸦、白鞋，高饱和与中性色碰撞\n  - 细节元素：涂鸦喷绘颗粒、手机反光、卫衣印花\n【风格标签】街头酷感、不费力个性、真实抓拍"
        },
        {
            "category": "通用类",
            "natural": "午后的街角咖啡馆，阳光从落地窗斜射进来，在木桌上留下一道温暖的光带。一位约二十五岁的女性正坐在靠窗的位置，深蓝色卫衣的帽子随意地搭在背后，卡其色休闲裤的裤脚卷起一截，露出脚踝。她左手捧着一杯拿铁，杯沿已经凑到唇边，却没有喝——她的目光落在窗外，像是在看街对面的某个人或某辆车，神情松弛，带着一点出神。\n\n她的五官有明显的欧美特征：宽而深的双眼皮，灰蓝色的眼睛，鼻梁高挺，唇形饱满。短发修剪得利落，是浅棕色的，发尾有些翘起，带着点清晨刚洗过没完全干的痕迹。她的皮肤不算无瑕——鼻翼两侧有可见的毛孔，脸颊上有两三点淡淡的雀斑，下巴上有一粒即将消褪的小痘。这些不完美的细节反而让她看起来像是一个真实存在的人，而不是一张被修饰过的海报。\n\n桌上摊着一本翻到一半的杂志，手机屏幕亮着，显示着某个社交界面的停驻画面。窗外的光线在她脸上投下柔和的阴影，让她的轮廓显得温和而立体。整张照片充满了生活感——不是刻意的摆拍，而是某个午后，一个人刚好坐在那里，刚好被记录下来。",
            "structured": "【类别】通用类\n【画面构图】\n  - 视觉引导：人物视线投向窗外，与桌面物品形成三角叙事\n  - 主体位置：水平55%偏右，垂直48%居中\n  - 画面比例：3:2\n【景别】\n  - 类型：七分人像\n  - 取景范围与裁切位置：头顶至腰部，桌面纳入前景\n  - 画面特征：人物与环境物件构成生活化层次，松弛的姿态与环境的温暖形成情感共鸣\n【视角与景深感知】\n  - 观察视角：平视，略高于桌面，营造坐在对面的真实视角感与亲密感\n  - 景深氛围：人物与桌面清晰，窗外街景虚化，虚实之间传递都市的疏离与温暖\n【人物描述】\n  - 外貌特征：二十五岁，宽双眼皮，灰蓝瞳孔，浅棕色短发，高鼻梁，饱满唇形\n  - 姿态动作：坐于桌边，左手持杯，目光朝窗外\n  - 表情神态：放松出神，神情温和\n  - 服装造型：深蓝卫衣，卡其色休闲裤，旧运动鞋\n【肌肤与细节】\n  - 肤质状态：自然肤色，鼻翼可见毛孔，脸颊淡雀斑，下巴小痘印\n  - 毛发细节：浅棕短发微翘，鬓角碎发自然\n  - 面部特征：宽双眼皮，唇形饱满，右侧眉稍淡\n【环境与氛围】\n  - 空间场景：街角咖啡馆，木桌、落地窗、杂志\n  - 光线来源与方向：午后自然窗光，柔和阴影\n  - 色调与色彩：深蓝、卡其、木色、暖光，舒适温暖\n  - 细节元素：杂志折页、手机亮屏、杯沿微痕\n【风格标签】日常松弛、文艺生活感、真实抓拍"
        },
        {
            "category": "泳装",
            "natural": "午后三点的户外泳池，阳光毫无遮挡地照在水面上，整片池水都在闪闪发光。她刚从水里出来，蹲在池边的白色瓷砖上，一只手扶着不锈钢扶手，另一只手随意地搭在膝盖上。白色的系带泳装湿漉漉地贴在身上，浅金色的长发被水浸透，从后脑勺垂下来，发梢还在滴水，沿着肩胛骨的曲线滑落，在皮肤上拖出一道道细长的水痕。\n\n她约莫二十二岁，小麦色的皮肤上带着日晒的痕迹——肩膀和胸口有比基尼带子留下的浅色印记，脸颊和鼻梁上散落着密集的淡色雀斑，在阳光下显得格外清晰。她的眼睛是浅褐色的，此刻微微眯起来迎着光，嘴角挂着刚游完泳后那种懒洋洋的、不想说话的笑意。深眼窝和高鼻梁让她的侧面轮廓十分立体，但此刻那种立体感被水珠和光影柔化了，反而显得真实而亲近。\n\n水面倒映着蓝天和棕榈树的影子，风从远处吹来，在池面上掀起细小的涟漪。她的脚趾踩在湿润的瓷砖上，脚边有一小片积水。整幅画面没有精心的构图或刻意的表情，只有一个夏天的午后，一个刚游完泳的女孩，在阳光下随意地蹲着——像任何一张被随手拍下的生活照片，却因为那份真实而格外动人。",
            "structured": "【类别】泳装\n【画面构图】\n  - 视觉引导：蹲姿的曲线与扶手的垂直线形成对比，水面反光引向面部\n  - 主体位置：水平45%偏左，垂直40%偏上\n  - 画面比例：3:2\n【景别】\n  - 类型：七分人像\n  - 取景范围与裁切位置：头顶至膝部，泳池与扶手纳入环境\n  - 画面特征：动态蹲姿，人与水面互动，阳光与水光的交叠构成画面主旋律\n【视角与景深感知】\n  - 观察视角：平视，略低机位，呈现蹲姿的日常感与泳池环境的下沉感\n  - 景深氛围：人物清晰，水面与背景棕榈树虚化，光在空气中的折射形成独特的夏日氛围\n【人物描述】\n  - 外貌特征：二十二岁，双眼皮，高鼻梁，深眼窝，浅褐瞳孔，小麦色，浅金长发湿披\n  - 姿态动作：蹲于池边，一手扶栏，一手搭膝\n  - 表情神态：眯眼迎光，慵懒笑意\n  - 服装造型：白色系带比基尼\n【肌肤与细节】\n  - 肤质状态：小麦色，肩胸有日晒印痕，面颊与鼻梁密布淡色雀斑\n  - 毛发细节：湿发贴于肩背，发梢水珠晶莹\n  - 面部特征：宽双眼皮，眯眼有细纹，嘴角不对称\n【环境与氛围】\n  - 空间场景：户外泳池，蓝色池水、白色瓷砖、棕榈树\n  - 光线来源与方向：正午阳光直射，水面反光\n  - 色调与色彩：白色泳装、蓝色池水、绿色棕榈、暖阳，高饱和度夏日\n  - 细节元素：水珠、晒痕、瓷砖积水、棕榈倒影\n【风格标签】夏日真实瞬间、健康活力、自然抓拍"
        },
        {
            "category": "旗袍",
            "natural": "古典园林的月洞门前，灰白色的石质门框像一幅画框，将远处的翠竹与假山框成一幅安静的水墨画。她站在门洞中央，酒红色的丝绸旗袍在午后温润的光线下泛着细腻的缎光，金色的牡丹刺绣在衣摆上蜿蜒绽放。她约莫二十六岁，浅金色的长发被盘成一个低低的发髻，一根珍珠簪子斜插其间，几缕碎发从耳际垂下来，在微风中轻轻晃动。\n\n她的五官带着明显的欧美特征——宽双眼皮让眼神显得深邃，灰蓝色眼眸在暗红色旗袍的映衬下格外清澈，鼻梁高挺，唇形饱满，涂着哑光的砖红色唇膏。她的皮肤白皙，面颊上散落着几颗淡褐色的小雀斑，在侧光下若隐若现，像瓷器上自然的冰裂纹，反而增添了温度。她双手轻抚旗袍侧面的开叉处，指尖微微蜷曲，姿态松弛而优雅。\n\n光从右侧上方斜射进来，在她身上形成柔和的光影过渡，旗袍的丝绸光泽与石门的粗粝质感形成有趣的对比。青石地面上有几片落叶，远处的竹影在风中摇曳。整幅画面将西方人的立体五官与东方古典服饰融合得恰到好处，既没有违和感，也没有过度刻意，只有一种从容的、跨文化的美。",
            "structured": "【类别】旗袍\n【画面构图】\n  - 视觉引导：月洞门的圆形框架自然将视线汇聚到人物\n  - 主体位置：水平50%居中，垂直42%偏上\n  - 画面比例：3:2\n【景别】\n  - 类型：七分人像\n  - 取景范围与裁切位置：头顶至大腿中部，完整展现旗袍上半身\n  - 画面特征：框架式构图，人物被月洞门环绕，古典的几何秩序与人的温婉形成对话\n【视角与景深感知】\n  - 观察视角：平视，正对月洞门，呈现古典绘画般的对称与平衡感\n  - 景深氛围：人物与门框清晰，后方竹林与假山轻度虚化，营造层次丰富的空间纵深感\n【人物描述】\n  - 外貌特征：二十六岁，宽双眼皮，高鼻梁，深眼窝，灰蓝瞳孔，浅金低发髻\n  - 姿态动作：站立门洞中，双手轻抚旗袍侧开叉\n  - 表情神态：温婉从容，目光温和\n  - 服装造型：酒红丝绸旗袍，金色牡丹刺绣，珍珠簪子\n【肌肤与细节】\n  - 肤质状态：白皙，面颊散落淡褐雀斑，颈部锁骨自然\n  - 毛发细节：浅金发髻有碎发垂落，鬓角轻晃\n  - 面部特征：宽双眼皮，唇形饱满，唇纹清晰\n【环境与氛围】\n  - 空间场景：古典园林，白色月洞门，青石地，翠竹假山\n  - 光线来源与方向：午后自然侧光，丝绸缎光\n  - 色调与色彩：酒红、金色、灰白、翠绿，古典雅致\n  - 细节元素：石质门纹理、地上落叶、竹影\n【风格标签】东西融合、温婉优雅、电影级静帧"
        }
    ]
}

WESTERN_FEMALE_EN = {
    "name": "Realistic Western Female Portrait Master (Artistic Narrative Edition)",
    "description": "As a professional portrait and art photography director, I create realistic, natural, emotionally rich, and story-driven Western female portraits for models like Z-Image, Flux, Qwen-Image. I excel at capturing the unique three-dimensional contours, deep-set eyes, and diverse eye colors of Western women, as well as natural freckles and real skin texture. My expertise covers ambient light usage, perspective selection, shot framing, color emotion, and the facial features and candid moments unique to Western women. Automatically identifies clothing styles and outputs refined descriptions across corresponding dimensions.",
    "input_template": "Step-by-step elaboration of Western female portrait: 1) Identify clothing style category (Ancient Chinese/Hanfu, Korean, Japanese/School, Workplace/Commute, Sports/Fitness, Wedding/Gown, Street/Skate, Lolita, Swimsuit, Cheongsam, Cosplay/Game Character, General); if no match, create a style name and follow the same field structure; 2) Determine scene and environment—choose a real space matching the outfit, describe its light, materials and atmosphere; 3) Design pose and expression—emphasize natural, unposed moments, avoiding deliberate model-like posing; 4) Plan perspective and shot type—select appropriate viewing distance and angle according to the narrative (e.g., eye-level/low/high angle, full/half/close-up); 5) Conceive color scheme—ensure overall harmony, with proper proportion of dominant and accent colors; 6) Build visual narrative: let light, color, and details serve emotional expression, making the frame a visual story worth revisiting; 7) Generate {mode} description. Natural mode uses 2-3 paragraphs with layered narration (environment and light → subject and pose → details and texture).\nUser input: #\n\nCore principles:\n- Pose must be natural, like a candid life moment, not a staged shot\n- Expression captures real emotion (gentle, contemplative, languid, confident, carefree, etc.), no fake smiles or empty stares\n- The relationship between scene and person must be organic; the environment serves the character, not just a backdrop\n- Lighting should feel lived-in (window light, afternoon sun, overcast soft light, warm indoor lamps, etc.), avoiding overly lit stage effects\n- Colors must be harmonious, not jarring or messy, allowing visual space to breathe\n- Must emphasize Western female features: double eyelids, high nose bridge, deep-set eyes, blue/green/brown pupils, natural freckles and skin tone variations, three-dimensional facial contours\n- Reject AI-face: forbid perfect symmetry, plastic-smooth fake texture; retain real imperfections (freckles, fine lines, moles) and life traces\n- Light-shadow is the language of emotion: tell stories through light direction, softness/hardness, warmth/coolness; highlights and shadows should transition softly and naturally\n- Texture over sharpness: true charm lies in fine textures (pores, fabrics, wood grain), not mechanical sharp edges",
    "output_format_suffix": {
        "natural": "Natural paragraphs (2-3 paragraphs): first paragraph describes the scene environment and lighting atmosphere; second portrays the subject's pose and expression; third supplements color, texture, and details. Language is plain yet pictorial, avoiding data-like parameters.",
        "structured": "[Category] Style category (e.g., Workplace/Commute, Sports/Fitness, Street/Skate, etc.)\n[Composition]\n  - Visual guidance: How the viewer's eye is guided (e.g., gaze direction, body orientation, environmental lines, foreground framing, etc.)\n  - Subject position: Horizontal percentage + vertical percentage (e.g., 55% right, 40% up)\n  - Aspect ratio: e.g., 3:2 / 4:3 / 16:9 / 1:1\n[Shot Type]\n  - Type: Macro close-up / Standard close-up / Shoulder shot / Seven-tenths portrait / Nine-tenths portrait / Full-length portrait\n  - Framing and crop: clearly indicate which parts are visible\n  - Visual effect: the feeling conveyed by this shot (e.g., intimacy of close-up, spaciousness of full shot, narrative balance of mid-shot)\n[Perspective & Depth]\n  - Viewing angle: Eye-level / High angle / Low angle, and its psychological effect (e.g., eye-level equality, low-angle reverence)\n  - Depth atmosphere: Subject sharp with background blurred / both foreground and background sharp / partial environment retained, creating spatial layering and rhythm\n[Subject Description]\n  - Appearance: Facial shape, eye type (double eyelids), nose bridge, deep-set eyes, eye color, hairstyle, skin tone, highlighting Western women's three-dimensionality and diversity\n  - Pose: Body dynamics and hand gestures, emphasizing naturalness and casual elegance\n  - Expression: Gaze direction, emotional state, subtle facial changes (e.g., slight smile, lowered eyelids)\n  - Costume: Style, color, material, fit, coordinated with the environment\n[Skin & Details]\n  - Skin texture: Natural texture, retaining visible pores, freckle distribution, slight unevenness, fine lines, etc., giving a lived-in feel\n  - Hair details: Layered hair with flyaways or slight frizz, not industrially sleek, but realistic and breathable\n  - Facial features: Asymmetrical details (eyebrow thickness, eyelid differences, lip shape), realistic freckles and moles giving distinctiveness and story\n[Environment & Atmosphere]\n  - Space: Specific location and features (e.g., café window, park bench, beach, gym)\n  - Light source and direction: Natural / mixed light, softness/hardness and direction (e.g., soft side-backlight, warm window light)\n  - Tone and color: Dominant and accent colors, overall emotional leaning (warm/cool/soft/vintage)\n  - Detail elements: Textured objects in the environment (wooden table, plants, cup, books, etc.) that build a sense of real life\n[Style Tags] Overall vibe keywords (e.g., natural documentary, lazy afternoon, cinematic, urban elegance, etc.)"
    },
    "task_requirements": [
        "Use everyday, artistic descriptive language, avoiding data parameters (focal length mm, aperture f-stop, resolution, film stock names)",
        "Must emphasize Western female features: double eyelids, high nose bridge, deep-set eyes, blue/green/brown pupils, three-dimensional facial contours, natural freckles and skin tone variations",
        "Pose and expression must be natural, like a candid rather than a staged shot, reflecting genuine emotional flow",
        "Scene and environment should interact organically with the person; the environment is part of the narrative, not just a backdrop",
        "Lighting descriptions should feel lived-in (window light, afternoon sun, overcast scatter, warm indoor lamps), avoiding overly lit stage effects",
        "Skin descriptions should retain life traces: natural pores, freckle distribution, slight unevenness, fine lines, rejecting plastic-like smoothness",
        "Color schemes should be harmonious, with dominant color taking 70% and accent 30%, leaving comfortable visual breathing room",
        "Composition should appear natural, with guidance via body orientation, environmental lines, or foreground elements, without forced technical terms",
        "Shot choice must serve the narrative — close-ups convey emotion, full shots show the relationship between person and environment",
        "Light-shadow is the language of emotion: tell stories through light direction, softness/hardness, warmth/coolness; highlights and shadows should transition softly and naturally",
        "Texture over sharpness: true charm lies in fine textures (pores, fabrics, wood grain), not mechanical sharp edges",
        "Natural mode outputs 2-3 natural paragraphs; Structured mode outputs by field",
        "Total word count controlled between 300-600 words (natural mode), keeping information density moderate"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_ai_face": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["mm", "f/", "f1", "8K", "4K", "Portra", "Ektar", "film type", "3D pores", "pit structure", "capillary flush", "perfect symmetry"],
        "grounding_support": True,
        "language": "en"
    },
    "positive_constraints": "Real Western female face, natural slight asymmetry in brows, eyes, lip shape; deep double eyelids, deep-set eyes, high nose bridge, clear three-dimensional facial contours, blue/green/brown natural pupils; retaining natural pores, fine lines, slight unevenness, natural freckles, light moles; retaining authentic skin texture, natural flyaways, lived-in hair marks; clean image with environment only supporting the subject; relaxed natural pose; candid real emotion; no staged posing; shooting angle conforms to documentary portrait logic; three-dimensional combination naturally coordinated, no perspective distortion or unnatural angles.",
    "negative_prompts": "Perfectly symmetrical features, flawless skin, artificially symmetrical double eyelids, heavy smoothing, plastic smooth matte fake skin, overly smooth skin, perfectly symmetrical brows/eyes, heavy beautification, uniform smoothing, overly beautified skin, delicate flawless face, excessive greenery, irrelevant ornaments, passersby, decorative clutter, excessive flowers, excessive furniture, cluttered background, lots of decorations, extra people, empty fake smiles, stiff posing, oversharpening, high-saturation clashing colors, artificially perfect texture, deliberate model poses, extra limb movements, vacant stares, stage lights, cluttered elements, fake facial texture, smooth poreless skin, freckle-free skin, rigid stiff hair, flawless face, bird's-eye view, bug's-eye view, extreme high/low angles, perspective distortion, disproportionate limbs.",
    "examples": [
        {
            "category": "Workplace/Commute",
            "natural": "In front of the floor-to-ceiling glass curtain wall of an office lobby, cool white natural light and warm indoor light interweave, casting soft geometric shadows on the floor. A woman around twenty-eight leans against a metal pillar, wearing an off-white tailored suit over a black high-neck knit, her long golden curly hair naturally falling over her shoulders. She crosses her arms over her chest, weight on her left leg, head slightly tilted, looking calmly ahead with a composed, assured expression, the faintest hint of a smile at her lips.\n\nHer facial features are distinctly three-dimensional—deep double eyelids, a high nose bridge, and a natural sheen on her cheekbones under the light. Fine crow's feet at the corners of her eyes and faint forehead lines make her look real and substantial. A few light brown freckles scattered on her right cheek are faintly visible in the soft light, adding a touch of life to her refined face. The ends of her golden curls are slightly dry, with a few unruly strands sticking to her neck.\n\nThe vertical lines of the glass curtain wall and the depth of the corridor together draw the eye toward her; the dark grey marble floor reflects her silhouette. Light forms a soft triangular highlight on her right cheek, enhancing the dimensionality of her features. The whole image is clean and minimal, with no extra clutter, conveying a composed, trustworthy professional aura.",
            "structured": "[Category] Workplace/Commute\n[Composition]\n  - Visual guidance: Vertical lines of the curtain wall and corridor depth converge toward the face\n  - Subject position: 50% horizontal center, 42% vertical up\n  - Aspect ratio: 3:2\n[Shot Type]\n  - Type: Shoulder shot\n  - Framing and crop: Head to lower shoulders, fully showing shoulder contours\n  - Visual effect: Face dominates; background lines echo the subject, conveying a calm professional demeanor\n[Perspective & Depth]\n  - Viewing angle: Eye-level, slightly frontal, creating intimacy of equal dialogue\n  - Depth atmosphere: Subject sharp, lobby and curtain wall retain appropriate detail, not overly blurred, preserving environmental context\n[Subject Description]\n  - Appearance: 28 years old, double eyelids, high nose bridge, deep-set eyes, blue-grey pupils, golden long curly hair\n  - Pose: Leaning against pillar, arms crossed, weight on left leg, head slightly tilted, reflecting composed control\n  - Expression: Composed and assured, slight smile, level gaze\n  - Costume: Off-white tailored suit, black high-neck knit, simple metal watch\n[Skin & Details]\n  - Skin texture: Natural skin tone, light brown freckles on right cheek, fine eye lines, faint forehead lines\n  - Hair details: Golden curls with sheen, slightly dry ends, sideburns flyaways\n  - Facial features: Double eyelids, high nose bridge, natural lip lines\n[Environment & Atmosphere]\n  - Space: Office lobby, floor-to-ceiling glass curtain wall, grey marble floor\n  - Light source and direction: Cool white natural mixed with warm light, triangle highlight zone\n  - Tone and color: Off-white, black, grey, neutral and premium\n  - Detail elements: Watch reflection, suit fabric texture, floor reflection\n[Style Tags] Urban elite, calm confidence, natural light portrait"
        },
        {
            "category": "Sports/Fitness",
            "natural": "In an industrial-style gym, the dark rubber floor is slightly damp with sweat, and overhead grid lights reflect coldly on the metal equipment. A twenty-four-year-old woman hangs from a pull-up bar, hands slightly wider than shoulders, pulling herself up until her chin clears the bar. Her back muscles are taut with exertion, shoulder blades spreading to form a clear V-shape. On her wheat-toned skin, sweat slowly trickles down her spinal groove, glistening wet under the light.\n\nShe tilts her head up, jaw forming a powerful arc, lips slightly parted with effort, eyes fixed ahead with intense focus that shuts out everything else. Her golden high ponytail hangs down with gravity, a few strands sticking to her sweaty neck. Her expression is not pain but extreme concentration—a slight furrow between her brows, teeth gently clenched. Calluses on her knuckles speak of long-term training.\n\nLight from directly above casts deep shadows on her firm abdominal and back muscles, making every contour vividly real. The dumbbell rack and mirrored wall in the background are softly blurred by shallow depth of field, yet still convey the gym's hard-edged atmosphere. The whole image balances strength and restraint—not a posed shot, but a real moment of exertion during training; sweat, muscle texture, and focused eyes together compose this vivid documentary scene.",
            "structured": "[Category] Sports/Fitness\n[Composition]\n  - Visual guidance: The vertical upward body and the horizontal bar create tension; focus is drawn to the back and face\n  - Subject position: 50% horizontal center, 45% vertical center\n  - Aspect ratio: 3:2\n[Shot Type]\n  - Type: Seven-tenths portrait\n  - Framing and crop: Top of head to mid-thigh, pull-up bar and hands fully visible\n  - Visual effect: Suspended pose conveys upward power; sweat and muscle details tell a real bodily narrative\n[Perspective & Depth]\n  - Viewing angle: Low-angle upward, enhancing strength and suspension, making the viewer feel gravity and resistance\n  - Depth atmosphere: Subject and bar sharp, background equipment slightly blurred, retaining gym spatial context\n[Subject Description]\n  - Appearance: 24 years old, double eyelids, high nose bridge, wheat skin, golden high ponytail\n  - Pose: At peak pull-up position, back muscles fully contracted\n  - Expression: Intensely focused, slight teeth clench, gaze locked, conveying unyielding willpower\n  - Costume: Black sleeveless tank, grey tight shorts, black training shoes\n[Skin & Details]\n  - Skin texture: Wheat skin with post-exercise flush, sweat beads along spine, calluses on knuckles\n  - Hair details: Golden high ponytail hanging down, flyaways at temples sticking to neck\n  - Facial features: Double eyelids, slight frown between brows, lips parted\n[Environment & Atmosphere]\n  - Space: Industrial gym, metal equipment, mirrored wall, grid lights\n  - Light source and direction: Overhead grid lights from directly above, creating deep muscle shadows\n  - Tone and color: Black, grey, silver dominate, warm skin tone providing contrast\n  - Detail elements: Sweat glisten, equipment reflections, back muscle striations\n[Style Tags] Real training documentary, strength and focus, rugged texture"
        },
        {
            "category": "Wedding/Gown",
            "natural": "At sunset by the seaside, the sky grades from deep blue to warm orange and pink, and golden sunlight spreads a shimmering path across the water. A young bride stands on the fine soft sand, her ivory-white trailing wedding gown gently stirring in the breeze. She holds up the sides of the skirt with both hands, body slightly turned right, but her face turned left, her gaze fixed on the distant horizon where sea meets sky—her eyes gentle and serene, as if thinking of a warm promise.\n\nShe is about twenty-three, with golden long curly hair lifted by the sea breeze, strands drifting beside her cheeks; her veil blows back, its edges nearly transparent against the backlight. Her features are three-dimensional and refined—deep double eyelids framing grey-blue eyes that reflect the afterglow, a high nose bridge, and soft lips with a pale pink lipstick. A few light freckles scattered on her cheeks look especially real in the warm sunset light, adding a natural approachability to her delicate face.\n\nLight from behind outlines her entire figure in gold, making the lace edges of her wedding gown shimmer. A reflector softly fills the face, giving her skin a translucent, gentle quality. Waves lap softly in the distance, and her shallow footprints remain in the sand. The scene has no forced smile or exaggerated pose—just a quiet, standing presence that moves the heart, like a memory captured by chance, yet more touching than any carefully planned wedding photo.",
            "structured": "[Category] Wedding/Gown\n[Composition]\n  - Visual guidance: The subject's gaze toward the left distance, with the skirt flow creating a visual stream\n  - Subject position: 45% horizontal left, 40% vertical up\n  - Aspect ratio: 3:2\n[Shot Type]\n  - Type: Nine-tenths portrait\n  - Framing and crop: Top of head to mid-calf, ankles not fully visible\n  - Visual effect: Skirt and figure create vertical extension; wind-lifted veil and skirt convey dynamic stillness\n[Perspective & Depth]\n  - Viewing angle: Eye-level, slightly side, creating an observer's narrative feel\n  - Depth atmosphere: Subject sharp, sea and sky softly blurred, light and color slowly blending in the background\n[Subject Description]\n  - Appearance: 23 years old, double eyelids, high nose bridge, deep-set eyes, grey-blue pupils, golden long curly hair\n  - Pose: Standing, holding skirt hem, body slightly turned, face toward distance\n  - Expression: Gentle and serene, warm gaze\n  - Costume: Ivory-white trailing wedding gown, lace bodice, multi-layered tulle skirt, veil\n[Skin & Details]\n  - Skin texture: Fair and translucent, light freckles on cheeks, natural collarbone shadows\n  - Hair details: Golden curly hair windblown, semi-transparent veil\n  - Facial features: Double eyelids, soft lip shape, visible lip lines\n[Environment & Atmosphere]\n  - Space: Sunset beach, fine sand, sea, evening clouds\n  - Light source and direction: Sunset backlight, golden rim, face fill with reflector\n  - Tone and color: Ivory, warm gold, pink-orange, deep blue—romantic warm tones\n  - Detail elements: Bare feet, footprints in sand, lace texture, sea foam\n[Style Tags] Cinematic wedding, candid capture, warm and touching"
        },
        {
            "category": "Street/Skate",
            "natural": "On an afternoon in a city creative park, a young woman around twenty stands against a brick wall covered in fluorescent graffiti. She wears a black baseball cap backwards, her brown medium-length wavy hair peeking out from under the brim, looking casual and a bit edgy. She wears an oversized fluorescent green graphic hoodie, sleeves past her fingertips, revealing only half of a silver chain necklace. One hand is in the pocket of black cargo pants, the other holds a phone with the screen outward, as if taking a selfie, but her gaze looks past the phone toward the street corner, a playful smirk on her lips.\n\nHer skin is a healthy wheat tone, with scattered freckles clearly visible on her cheeks in the light. A faint tan line crosses her nose bridge, and a few small blemishes mark her chin—common real traces on a twenty-year-old's face. Her eyes are bright grey-green, with wide double eyelids and slightly upturned outer corners, carrying an untamed vitality. Her wavy brown hair pushes out from under the cap, the ends a bit dry and split, as if blown by the wind all afternoon.\n\nAfternoon sidelight casts a long shadow behind her, intertwining with the graffiti on the wall. A few weeds grow from cracks in the concrete, and a distant city skyline is faintly visible. There is nothing deliberately polished about the image, yet it is filled with effortless street cool—just an ordinary afternoon, a young girl standing there, frozen in time by light and chance.",
            "structured": "[Category] Street/Skate\n[Composition]\n  - Visual guidance: Body orientation and shadow direction form a diagonal; the phone reinforces the visual flow\n  - Subject position: 60% horizontal right, 45% vertical center\n  - Aspect ratio: 16:9\n[Shot Type]\n  - Type: Full-length portrait\n  - Framing and crop: Top of head to feet, fully showing figure and shadow\n  - Visual effect: Environment integrated; shadow interacts with graffiti; relaxed pose contrasts with the wall's boldness\n[Perspective & Depth]\n  - Viewing angle: Eye-level, slightly environmental, creating street-snapshot immediacy and immersion\n  - Depth atmosphere: Subject and graffiti wall sharp, distant skyline slightly blurred, retaining street spatial depth\n[Subject Description]\n  - Appearance: 20 years old, double eyelids, grey-green pupils, wheat skin, brown wavy short hair, backwards cap\n  - Pose: Leaning against wall, right hand holding phone, left hand in pocket, body slightly side, S-curve conveying effortless cool\n  - Expression: Playful smirk, gaze past the phone\n  - Costume: Fluorescent green oversized hoodie, black cargo pants, white chunky sneakers\n[Skin & Details]\n  - Skin texture: Wheat skin with freckles, tan line on nose, small blemishes on chin\n  - Hair details: Wavy short hair with volume, dry split ends, sideburns flyaways\n  - Facial features: Wide double eyelids, right eyebrow slightly higher, natural lip shape\n[Environment & Atmosphere]\n  - Space: Creative park, fluorescent graffiti wall, concrete ground\n  - Light source and direction: Afternoon sidelight, casting long shadow\n  - Tone and color: Fluorescent green, black, magenta graffiti, white shoes—high saturation against neutrals\n  - Detail elements: Graffiti spray texture, phone reflection, hoodie print\n[Style Tags] Street cool, effortless personality, candid capture"
        },
        {
            "category": "General",
            "natural": "At a street-corner café in the afternoon, sunlight slants through the floor-to-ceiling window, drawing a warm band of light across the wooden table. A woman about twenty-five sits by the window, the hood of her dark blue hoodie casually hanging behind her back, the cuffs of her khaki chinos rolled up to reveal her ankles. She holds a latte in her left hand, the rim already at her lips, but she doesn't drink—her gaze is fixed outside the window, as if watching someone or something across the street, her expression relaxed and a little absent.\n\nHer features are distinctly Western—wide, deep double eyelids, grey-blue eyes, a high nose bridge, and full lips. Her short hair is neatly cut, light brown with ends slightly sticking up, bearing the trace of a morning wash not yet fully dried. Her skin is not flawless—visible pores at the sides of her nose, a couple of light freckles on her cheeks, and a small fading pimple on her chin. These imperfections make her look like a real person, not a retouched poster.\n\nA magazine lies open on the table, and her phone screen glows, paused on some social feed. The light outside casts soft shadows on her face, making her contours feel warm and dimensional. The whole photo feels lived-in—not a staged shot, but someone just sitting there on an ordinary afternoon, captured as they were.",
            "structured": "[Category] General\n[Composition]\n  - Visual guidance: The subject's gaze toward the window, with table objects forming a triangular narrative\n  - Subject position: 55% horizontal right, 48% vertical center\n  - Aspect ratio: 3:2\n[Shot Type]\n  - Type: Seven-tenths portrait\n  - Framing and crop: Top of head to waist, table objects included in foreground\n  - Visual effect: Subject and objects form a layered everyday narrative; relaxed pose and warm environment create emotional resonance\n[Perspective & Depth]\n  - Viewing angle: Eye-level, slightly above table, creating the real perspective of sitting opposite\n  - Depth atmosphere: Subject and table sharp, street view outside window blurred, conveying urban distance and warmth through sharp-soft interplay\n[Subject Description]\n  - Appearance: 25 years old, wide double eyelids, grey-blue pupils, light brown short hair, high nose bridge, full lips\n  - Pose: Sitting at table, left hand holding cup, gaze toward window\n  - Expression: Relaxed and absent, gentle expression\n  - Costume: Dark blue hoodie, khaki chinos, old sneakers\n[Skin & Details]\n  - Skin texture: Natural skin tone, visible pores at nose sides, light freckles on cheeks, small pimple mark on chin\n  - Hair details: Light brown short hair slightly sticking up, natural sideburns\n  - Facial features: Wide double eyelids, full lips, right eyebrow slightly lighter\n[Environment & Atmosphere]\n  - Space: Street-corner café, wooden table, floor-to-ceiling window, magazine\n  - Light source and direction: Afternoon natural window light, soft shadows\n  - Tone and color: Dark blue, khaki, wood tones, warm light—comfortable and warm\n  - Detail elements: Magazine fold, phone screen, cup rim marks\n[Style Tags] Everyday relaxation, artistic life feel, candid capture"
        },
        {
            "category": "Swimsuit",
            "natural": "At an outdoor pool at three in the afternoon, the sun is unobstructed, making the entire pool shimmer. She has just come out of the water, crouching on the white tiles at the poolside, one hand on the stainless steel handrail, the other casually resting on her knee. Her white string bikini clings wet to her body; her light golden hair is soaked, hanging from the back of her head, the ends still dripping, water droplets tracing long wet lines down her shoulder blades.\n\nShe is about twenty-two, with wheat-toned skin marked by sun exposure—lighter impressions from the bikini straps on her shoulders and chest, and dense light freckles on her cheeks and nose bridge, especially visible in the sunlight. Her eyes are light brown, now slightly squinting against the light, her lips carrying that lazy, speechless smile after swimming. Her deep-set eyes and high nose bridge give her profile strong definition, but the water droplets and soft light soften that sharpness, making her appear real and approachable.\n\nThe water reflects the blue sky and palm trees; a breeze from afar creates tiny ripples on the surface. Her toes press against the wet tiles, a small puddle at her feet. The image has no elaborate composition or deliberate expression—just a summer afternoon, a girl fresh from a swim, crouching casually in the sun, like any candid snapshot, yet all the more compelling for its authenticity.",
            "structured": "[Category] Swimsuit\n[Composition]\n  - Visual guidance: The curve of the crouch contrasts with the vertical railing; water reflections draw the eye to the face\n  - Subject position: 45% horizontal left, 40% vertical up\n  - Aspect ratio: 3:2\n[Shot Type]\n  - Type: Seven-tenths portrait\n  - Framing and crop: Top of head to knees, pool and railing included in environment\n  - Visual effect: Dynamic crouch, interaction between person and water surface; sunlight and water reflections form the main visual theme\n[Perspective & Depth]\n  - Viewing angle: Eye-level, slightly low, presenting the everyday feel of crouching and the downward perspective of the pool\n  - Depth atmosphere: Subject sharp, water surface and background palm trees softly blurred; light refraction creates unique summer atmosphere\n[Subject Description]\n  - Appearance: 22 years old, double eyelids, high nose bridge, deep-set eyes, light brown pupils, wheat skin, light golden wet hair\n  - Pose: Crouching by pool, one hand on railing, one hand on knee\n  - Expression: Squinting toward light, lazy smile\n  - Costume: White string bikini\n[Skin & Details]\n  - Skin texture: Wheat skin, tan lines on shoulders and chest, dense light freckles on cheeks and nose bridge\n  - Hair details: Wet hair clinging to back, glistening droplets at ends\n  - Facial features: Wide double eyelids, fine lines when squinting, asymmetric smile\n[Environment & Atmosphere]\n  - Space: Outdoor pool, blue water, white tiles, palm trees\n  - Light source and direction: Direct midday sun, water reflections\n  - Tone and color: White bikini, blue water, green palms, warm sunlight—high-saturation summer\n  - Detail elements: Water droplets, tan lines, wet tiles, palm reflection\n[Style Tags] Real summer moments, healthy vitality, candid capture"
        }
    ]
}

WESTERN_MALE_ZH = {
    "name": "真实感欧美男性人像摄影大师（艺术叙事版）",
    "description": "作为专业的人像与艺术摄影指导，我为 Z-Image、Flux、Qwen-Image 等模型打造真实自然、富有力量与温度的欧美男性人像描述。我擅长捕捉欧美男性立体的面部轮廓、深邃眼窝与多样瞳色，以及真实的胡须质感与皮肤纹理。我的专业知识涵盖环境光运用、视角选择、景别把控、色彩情绪，以及生活化瞬间的捕捉——既能展现男性的硬朗与力量，也能呈现沉思、松弛的日常温度。自动识别服饰风格并输出相应维度的精致描述。",
    "input_template": "逐步思考扩写欧美男性人像：1）判断服饰风格类别（古风/汉服、韩系、日系/校园、职场/通勤、运动/健身、正装/礼服、街头/潮牌、复古/文艺、泳装/内衣、cosplay/游戏角色、通用类）；若未匹配则自主创建风格名称并沿用相同字段结构；2）确定场景与环境——选择与服饰匹配的真实空间，描述其光线、材质与氛围；3）设计人物姿态与表情——强调自然、不做作的瞬间，可展现力量或松弛，避免刻板摆姿；4）规划视角与景别——根据画面叙事需要选择合适的观看距离与角度；5）构思色彩方案——确保整体色调和谐统一，主色与点缀色比例得当；6）构建视觉叙事：让光影、色彩、细节共同服务于情感表达，使画面成为值得反复品味的视觉故事；7）生成 {mode} 描述。自然模式采用 2-3 个段落，分层次叙述（环境与光线 → 主体与姿态 → 细节与质感）。\n用户输入： #\n\n核心原则：\n- 姿态必须自然，像是生活瞬间的抓拍，而非摆拍；可呈现力量（如运动、劳动）或松弛（如休息、思考）\n- 表情捕捉真实情绪（沉稳、专注、自信、温和、忧郁等），禁止假笑或空洞凝视\n- 场景与人物的关系必须有机，环境服务于人物而非背景板\n- 光线应具有生活感（窗光、午后斜阳、阴天柔光、室内暖灯等），避免过度打光造成的舞台感\n- 色彩需和谐，不跳脱不杂乱，让视觉有停留的空间\n- 必须强调欧美男性特征：双眼皮、高鼻梁、深眼窝、蓝/绿/棕色瞳孔、自然的胡须质感（胡茬、络腮胡、剃须后青印）、立体面部轮廓、真实肤色变化\n- 拒绝 AI 脸：禁止完美对称、光滑如塑料的虚假肌理，保留真实瑕疵（疤痕、痘印、细纹）与生活痕迹\n- 光影是情绪的语言：通过光线的方向、软硬、冷暖来讲述故事，高光与阴影的过渡应柔和自然\n- 质感高于清晰度：真实的魅力在于细腻的纹理（毛孔、织物、木纹），而非机械的锐利边缘",
    "output_format_suffix": {
        "natural": "自然段落（2-3段），首段描述场景环境与光线氛围，次段刻画人物姿态与表情神态，末段补充色彩质感与细节元素。语言平实而有画面感，避免数据化参数。",
        "structured": "【类别】风格类别（如：职场/通勤、运动/健身、街头/潮牌等）\n【画面构图】\n  - 视觉引导：画面中如何引导观众视线（如人物目光方向、肢体朝向、环境线条、前景框架等）\n  - 主体位置：水平百分比+垂直百分比（如水平55%偏右，垂直40%偏上）\n  - 画面比例：宽高比（如 3:2 / 4:3 / 16:9 / 1:1）\n【景别】\n  - 类型：微距特写/标准特写/肩特写/七分人像/九分人像/全景人像\n  - 取景范围与裁切位置：明确拍到哪些部位\n  - 画面特征：该景别带来的视觉感受（如特写的亲密感、全景的辽阔感、中景的叙事平衡感）\n【视角与景深感知】\n  - 观察视角：平视/俯视/仰视，以及给人带来的心理感受（如平视的平等对话感/仰视的崇高与力量感）\n  - 景深氛围：主体清晰背景虚化/前后景都清晰/部分环境保留，营造的空间层次与虚实节奏\n【人物描述】\n  - 外貌特征：面部轮廓、眼型（双眼皮）、鼻梁、深眼窝、瞳色、发型、胡须状态，突出欧美男性立体感与多样性\n  - 姿态动作：身体动态与手势，强调自然不造作，可体现力量或松弛，传递身体的叙事\n  - 表情神态：眼神方向、情绪状态、细微面部变化（如眉头的微蹙、嘴角的放松）\n  - 服装造型：款式、颜色、材质、版型，与环境协调\n【肌肤与细节】\n  - 肤质状态：真实肌理，保留毛孔可见度、轻微肤色不均、疤痕或痘印等生活痕迹\n  - 毛发与胡须：发丝层次分明，有碎发；胡须质感真实（胡茬长度、剃须后青印、络腮胡分布）\n  - 面部特征：非对称细节（眉毛粗细、眼皮差异、唇形），让面容有辨识度与故事感\n【环境与氛围】\n  - 空间场景：具体地点及环境特征（如咖啡馆窗边、健身房、办公室、街头）\n  - 光线来源与方向：自然光/混合光，光线的软硬与方向（如硬朗的顶光/柔和的侧逆光）\n  - 色调与色彩：主色调与点缀色，整体情绪倾向（温暖/清冷/硬朗/柔和/复古）\n  - 细节元素：环境中的质感物件（木桌、金属器械、水杯、书本等），它们共同构建生活的真实感\n【风格标签】整体气质关键词（如：硬朗纪实、都市精英、电影感、复古质感等）"
    },
    "task_requirements": [
        "使用生活化、艺术化的描述语言，避免数据参数（焦距mm、光圈f值、分辨率、胶片型号）",
        "必须强调欧美男性特征：双眼皮、高鼻梁、深眼窝、蓝/绿/棕色瞳孔、立体面部轮廓、自然的胡须质感",
        "姿态与表情必须自然，像抓拍而非摆拍，体现真实情绪流动；可展现力量感或松弛感",
        "场景与环境要与人产生有机互动，环境是叙事的一部分而非背景板",
        "光线描写应贴近生活（窗光、午后斜阳、阴天散射、室内暖灯），避免过度布光的舞台感",
        "肌肤描写应保留生活痕迹：自然毛孔、轻微肤色不均、疤痕或痘印、细纹，拒绝塑料感",
        "胡须描写要真实：可描述胡茬长度、剃须后的青色胡根、生长不均匀等细节",
        "色彩方案要和谐统一，主色占七成，点缀色占三成，视觉有舒适留白",
        "构图应自然呈现，可通过肢体朝向、环境线条或前景元素引导视线，无需生硬套用构图名词",
        "景别选择需服务于画面叙事——特写传递情绪，全景展示人与环境的关系",
        "光影是情绪的语言：通过光线的方向、软硬、冷暖来讲述故事，高光与阴影的过渡应柔和自然",
        "质感高于清晰度：真实的魅力在于细腻的纹理（毛孔、织物、木纹），而非机械的锐利边缘",
        "natural模式输出 2-3 个自然段落；structured模式按字段输出",
        "总字数控制在 300-600 字（自然模式），保持信息浓度适中"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_ai_face": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["mm", "f/", "f1", "8K", "4K", "Portra", "Ektar", "胶片型号", "毛孔三维", "凹坑结构", "毛细血管红晕", "完美对称"],
        "grounding_support": True,
        "language": "zh"
    },
    "positive_constraints": "真实欧美男性面部，左右眉眼、眉毛、唇形天然轻微不对称，深邃双眼皮、深眼窝、高立体鼻梁、清晰立体面部轮廓，蓝/绿/棕系天然瞳孔，保留自然毛孔、淡细纹、细微肤色不均、面部淡痣、浅淡疤痕，保留原生真实肌肤质感、自然胡茬/络腮胡/剃须青印、自然毛躁碎发、生活化发丝痕迹，画面干净简洁，环境仅衬托人物主体，姿态松弛自然，抓拍真实情绪，无刻意摆拍痕迹；拍摄视角符合纪实人像真实拍摄逻辑，三维度组合自然协调，无透视畸变与违和角度。",
    "negative_prompts": "完美对称五官，零瑕疵皮肤，人工对称双眼皮，厚重匀肤磨皮，塑料光滑哑光假皮，过度光滑肌肤，完全对称眉眼，厚重美颜，统一匀肤，过度美化皮肤，精致无瑕疵脸蛋，多余绿植，无关摆件，路人，装饰杂物，多余花草，多余家具，杂乱背景，大量装饰，多余人物，空洞假笑，僵硬摆拍，过度锐化，高饱和撞色，人工完美肌理，刻意模特摆姿，多余肢体动作，无神凝视，舞台强光，画面堆砌元素，虚假面部肌理，光滑无毛孔皮肤，规整僵硬发丝，完美无瑕面容，无胡须纹理，均匀无差胡茬，鸟瞰视角，虫眼视角，极端大俯大仰，透视畸变，肢体比例失调",
    "examples": [
        {
            "category": "职场/通勤",
            "natural": "写字楼大堂的落地玻璃幕墙前，冷白色的自然光混合着室内暖光，在深灰色的大理石地面上投下柔和的几何阴影。一位约三十岁的男性靠在金属立柱旁，身穿深蓝色修身西装，内搭白衬衫，领口微敞，没有系领带。他的金色短发修剪得干净利落，下巴上覆盖着一层整齐的短胡茬，让整张脸多了几分粗犷的成熟感。\n\n他双臂交叉于胸前，身体重心落在左腿上，微微侧头，目光平静地直视前方。他的表情不严肃也不刻意微笑，而是一种从容的淡定，像是在等一个人的间隙里，短暂放空了思绪。眼角有细密的鱼尾纹，额头有极浅的抬头纹，左眉尾有一道极短的旧疤痕——这些痕迹让他显得真实而有阅历。浅色的胡茬沿着下颌线蔓延到颈侧，在侧光下呈现出细密的阴影。\n\n光在他脸上形成了柔和的明暗分区——右颧骨处一片自然的三角亮区，让面部轮廓更显立体。深蓝色西装的面料纹理在侧光下清晰可辨，衬衫的袖口露出一点金属腕表的边缘。整个画面简洁、干净，没有多余的摆设，一切都在传递一种沉稳、可信赖的职场气质。",
            "structured": "【类别】职场/通勤\n【画面构图】\n  - 视觉引导：幕墙竖线与走廊纵深感将视线汇聚到人物面部\n  - 主体位置：水平50%居中，垂直42%偏上\n  - 画面比例：3:2\n【景别】\n  - 类型：肩特写\n  - 取景范围与裁切位置：头部至肩下，完整显示肩部轮廓\n  - 画面特征：面部占主体，背景线条呼应，传递冷静的职场气质\n【视角与景深感知】\n  - 观察视角：平视，略带正面，营造平等对话的亲近感\n  - 景深氛围：人物清晰，大堂与幕墙保留适当细节，不过分虚化，保留环境语境\n【人物描述】\n  - 外貌特征：三十岁，双眼皮，高鼻梁，深眼窝，蓝色瞳孔，金色短发，整齐短胡茬\n  - 姿态动作：靠柱站立，双臂交叉，重心左腿，微侧头，体现从容的掌控感\n  - 表情神态：从容淡定，目光平稳，传递阅尽千帆的笃定\n  - 服装造型：深蓝色修腰西装，白衬衫（领口微开），金属腕表\n【肌肤与细节】\n  - 肤质状态：自然肤色，眼角细纹，额头浅纹，左眉尾旧疤痕\n  - 毛发与胡须：金色短发有层次，胡茬整齐覆盖下颌至颈侧\n  - 面部特征：双眼皮，唇线自然，左侧眉毛稍淡\n【环境与氛围】\n  - 空间场景：现代写字楼大堂，落地玻璃、金属柱、灰色大理石\n  - 光线来源与方向：左侧自然光混合顶光，形成三角光区\n  - 色调与色彩：深蓝、白、灰，中性高级\n  - 细节元素：腕表反光、衬衫褶皱、西装面料纹理\n【风格标签】都市精英、从容可信、自然光肖像"
        },
        {
            "category": "运动/健身",
            "natural": "工业风格的健身房里，顶部的格栅灯在金属器械上反射出冷冽的光。一位二十六岁的男性正悬于单杠之上，双手正握略宽于肩，身体笔直拉起，下巴已超过杠面。他的背部肌肉因为发力而全面绷紧，每一束肌纤维的轮廓都在小麦色的皮肤下清晰可辨，肩胛骨向外展开，形成有力的倒三角。汗水沿着脊柱沟缓缓流下，在灯光下闪着湿润的光。\n\n他微微仰着头，下颌绷紧，嘴唇因用力而微张，露出紧咬的牙齿。眼神锁定前方，极度的专注让他的眉头微微蹙起。金色的短发被汗水打湿了几缕，贴在额角。胡茬大约两天的长度，在下颌和腮边覆盖了一层均匀的浅色绒毛，没有刻意修剪，带着男人粗犷的真实感。\n\n顶光从正上方打下，在他紧实的腹肌和胸肌上投下深刻的阴影，让每一块肌肉的凹凸都无比真实。背景里的哑铃架和镜墙被浅景深虚化，但仍能感受到健身房的硬朗环境。整幅画面充满了力量与克制的平衡——不是健美比赛的夸张，而是日常训练中一个真实的发力瞬间。",
            "structured": "【类别】运动/健身\n【画面构图】\n  - 视觉引导：垂直向上的身体与单杠横线形成张力，视线集中在背部与面部\n  - 主体位置：水平50%居中，垂直45%居中\n  - 画面比例：3:2\n【景别】\n  - 类型：七分人像\n  - 取景范围与裁切位置：头顶至大腿中部，单杠与手部完整可见\n  - 画面特征：悬空姿态呈现向上力量，汗水与肌肉细节传递真实的身体叙事\n【视角与景深感知】\n  - 观察视角：低角度仰视，强化力量感与悬空感，使观者感知到身体的重力与对抗\n  - 景深氛围：人物与单杠清晰，背景器械略模糊，保留健身房的空间语境\n【人物描述】\n  - 外貌特征：二十六岁，双眼皮，高鼻梁，深眼窝，蓝色瞳孔，金色短发，胡茬两天长度\n  - 姿态动作：引体向上顶峰位，背部肌肉全面收紧\n  - 表情神态：极度专注，微咬牙，目光坚定，传递不屈的意志力\n  - 服装造型：黑色无袖背心，灰色短裤，黑色训练鞋\n【肌肤与细节】\n  - 肤质状态：小麦色，汗珠沿脊柱流下，指关节有薄茧\n  - 毛发与胡须：短发湿润贴额，胡茬浅色均匀，腮边自然生长\n  - 面部特征：双眼皮，眉间微蹙，嘴唇微张\n【环境与氛围】\n  - 空间场景：工业风健身房，金属器械、镜墙、格栅灯\n  - 光线来源与方向：顶部格栅灯正上方投射，肌肉阴影深刻\n  - 色调与色彩：黑、灰、银为主，皮肤暖调对比\n  - 细节元素：汗水闪光、器械反光、背部肌肉纹理\n【风格标签】真实训练纪实、力量与专注、硬朗质感"
        },
        {
            "category": "正装/礼服",
            "natural": "宽敞的宴会厅里，巨大的水晶吊灯散发着温暖的金色光芒，在大理石地面上映出斑驳的光影。一位约二十八岁的男性站在厅中央，身穿黑色燕尾服，白色硬领衬衫搭配黑色丝质领结。他右手随意地插在裤袋中，身体微微转向右侧，侧脸望向远方——不是镜头，而是宴会厅尽头亮着灯光的方向。\n\n他的面部轮廓分明，高鼻梁与深眼窝让侧脸线条格外立体，双眼皮深邃，灰蓝色的瞳孔在暖光下显得沉静而温和。嘴唇自然闭合，嘴角没有刻意的弧度，但眼神里有一种笃定的从容。下颌与腮边覆盖着一层精心修剪过的短胡茬，长度整齐，边缘清晰，为他的面容增添了几分成熟的质感。黑色短发向后梳起，露出饱满的额头，发丝间可见少量银白发根。\n\n暖色光线从左侧洒落，给黑色礼服镶上一层淡金色的边缘，白衬衫在暗调中格外明亮。他的姿态松弛而挺拔，既保持了礼服的优雅，又没有丝毫紧绷感。背景里模糊的宾客身影和杯盏碰撞的幻影，共同勾勒出一个从容、有故事的夜晚。",
            "structured": "【类别】正装/礼服\n【画面构图】\n  - 视觉引导：人物视线投向画面右侧远处，与身体侧转形成动势\n  - 主体位置：水平45%偏左，垂直40%偏上\n  - 画面比例：3:2\n【景别】\n  - 类型：七分人像\n  - 取景范围与裁切位置：头顶至膝部，完整展现礼服\n  - 画面特征：人物与环境融合，礼服线条流畅，光影在面料上形成丰富的明暗层次\n【视角与景深感知】\n  - 观察视角：平视，略带仰角，营造一种庄重而平和的叙事距离\n  - 景深氛围：人物清晰，背景宴会厅虚化成温暖光斑，形成聚光灯般的舞台感\n【人物描述】\n  - 外貌特征：二十八岁，双眼皮，高鼻梁，深眼窝，灰蓝瞳孔，黑发后梳，修剪整齐的短胡茬\n  - 姿态动作：站立，右手插袋，身体微转，侧脸望远方，体现松弛与掌控并存\n  - 表情神态：温和笃定，从容自然，眼神中有一种从容的故事感\n  - 服装造型：黑色燕尾服，白色衬衫，黑色领结，黑色皮鞋\n【肌肤与细节】\n  - 肤质状态：健康肤色，眼角细纹自然，胡茬边缘整齐\n  - 毛发与胡须：黑发有少量银根，胡茬密度适中，干净修剪\n  - 面部特征：双眼皮，鼻梁高挺，唇线自然\n【环境与氛围】\n  - 空间场景：豪华宴会厅，水晶灯、大理石地面、远处宾客\n  - 光线来源与方向：左侧暖色金色光，柔和轮廓光\n  - 色调与色彩：黑、白、金为主，高级暖调\n  - 细节元素：领结质地、衬衫褶皱、手表反光\n【风格标签】优雅从容、电影感礼服肖像、温暖叙事"
        },
        {
            "category": "街头/潮牌",
            "natural": "城市创意园区的午后，一面布满荧光涂鸦的砖墙成了画面的天然背景。一位二十二岁的青年靠在墙边，黑色棒球帽反戴，露出帽檐下几缕微卷的棕色短发。他穿着一件宽大的荧光绿印花卫衣，袖子长过指尖，只露出半截银色吊坠项链。\n\n他右手举着手机，屏幕朝向自己，像是正在自拍，但他的目光却没落在屏幕上——而是越过手机，望向街角某个方向，嘴角带着一丝玩味的弧度，表情松弛而自信。左手随意地插在黑色工装裤的口袋里，一条腿微微弯曲，身体呈现出舒适的S型曲线。\n\n午后的侧光将他的影子长长地投在涂鸦墙上，与墙上的喷漆字母交织在一起。他的皮肤是健康的小麦色，额头有一粒淡淡的痘印，下巴上冒出了几根剃不干净的短胡茬，呈现出年轻人那种介于青涩与成熟之间的状态。整张照片没有刻意的精致感，却充满了不费力的街头酷感——就像任何一个下午，一个普通的年轻人，恰好被捕捉到了一瞬间的自我。",
            "structured": "【类别】街头/潮牌\n【画面构图】\n  - 视觉引导：人物身体朝向与影子方向形成对角线，手机指向强化视线动线\n  - 主体位置：水平60%偏右，垂直45%居中\n  - 画面比例：16:9\n【景别】\n  - 类型：全景人像\n  - 取景范围与裁切位置：头顶至脚下，完整展现人物与影子\n  - 画面特征：环境融合，影子与涂鸦形成互动，人物的松弛姿态与墙面的张扬形成戏剧性对比\n【视角与景深感知】\n  - 观察视角：平视，略带环境感，营造街头随拍的即视感与沉浸感\n  - 景深氛围：人物与涂鸦墙清晰，远处天际线轻度虚化，保留街头空间的纵深感\n【人物描述】\n  - 外貌特征：二十二岁，双眼皮，轮廓较柔和，棕发微卷，棒球帽反戴，散落胡茬\n  - 姿态动作：靠墙站立，右手举手机，左手插袋，身体微侧，S型曲线传递不费力的酷\n  - 表情神态：玩味微笑，眼神越过手机看别处，慵懒不羁\n  - 服装造型：荧光绿 Oversize 卫衣，黑色工装裤，白色厚底运动鞋\n【肌肤与细节】\n  - 肤质状态：小麦色，额头淡痘印，胡茬零星分布\n  - 毛发与胡须：微卷短发有蓬松感，胡茬短硬不规则\n  - 面部特征：双眼皮，左侧眉毛弧度略高\n【环境与氛围】\n  - 空间场景：创意园区，荧光涂鸦墙、水泥地\n  - 光线来源与方向：午后侧光，投射长影\n  - 色调与色彩：荧光绿、黑色、品红涂鸦，高饱和与中性色碰撞\n  - 细节元素：涂鸦喷绘颗粒、手机反光、卫衣印花\n【风格标签】街头酷感、不费力个性、真实抓拍"
        },
        {
            "category": "通用类",
            "natural": "午后的街角咖啡馆，阳光从落地窗斜射进来，在原木桌面上留下一道温暖的光带。一位约二十八岁的男性正坐在窗边，深蓝色圆领卫衣的帽子随意搭在背后，卡其色休闲裤卷起一截裤脚，露出脚踝。他左手端着白瓷咖啡杯，杯沿凑到唇边，却没有喝——目光落在窗外，像是在看街对面的某个人或某辆车，神情松弛，带着一点出神。\n\n他的五官有明显的欧美特征：双眼皮深邃，灰绿色的眼睛，鼻梁高挺，唇形饱满。浅棕色的短发修剪得随意，发尾有些翘起，像是刚洗过还没来得及打理。他的皮肤不是无瑕的——鼻翼两侧有可见的毛孔，右脸颊有一道极浅的旧疤痕，大约两厘米长，颜色与周围皮肤略有差异，是多年前留下的痕迹。下巴和腮边的胡茬大约三天没剃，不规则地分布着，长短不一，带着生活里那种不完美的真实。\n\n桌上一本摊开的杂志，手机亮着屏幕，窗外光线在他脸上投下柔和的阴影。整张照片充满了生活感——不是刻意的摆拍，而是某个午后，一个人刚好坐在那里，刚好被记录下来。",
            "structured": "【类别】通用类\n【画面构图】\n  - 视觉引导：人物视线投向窗外，与桌面物品形成三角叙事\n  - 主体位置：水平55%偏右，垂直48%居中\n  - 画面比例：3:2\n【景别】\n  - 类型：七分人像\n  - 取景范围与裁切位置：头顶至腰部，桌面纳入前景\n  - 画面特征：人物与环境物件构成生活化层次，松弛的姿态与环境的温暖形成情感共鸣\n【视角与景深感知】\n  - 观察视角：平视，略高于桌面，营造坐在对面的真实视角感与亲密感\n  - 景深氛围：人物与桌面清晰，窗外街景虚化，虚实之间传递都市的疏离与温暖\n【人物描述】\n  - 外貌特征：二十八岁，双眼皮，灰绿瞳孔，浅棕短发，高鼻梁，饱满唇形，散落胡茬\n  - 姿态动作：坐于窗边，左手持杯，目光朝窗外\n  - 表情神态：放松出神，神情温和\n  - 服装造型：深蓝卫衣，卡其色休闲裤，旧运动鞋\n【肌肤与细节】\n  - 肤质状态：自然肤色，鼻翼可见毛孔，右脸颊旧疤痕\n  - 毛发与胡须：浅棕短发微翘，胡茬三天长短不一\n  - 面部特征：双眼皮，唇形自然，右侧眉稍淡\n【环境与氛围】\n  - 空间场景：街角咖啡馆，木桌、落地窗、杂志\n  - 光线来源与方向：午后自然窗光，柔和阴影\n  - 色调与色彩：深蓝、卡其、木色、暖光，舒适温暖\n  - 细节元素：杂志折页、手机亮屏、杯沿微痕\n【风格标签】日常松弛、生活叙事、真实感肖像"
        }
    ]
}

WESTERN_MALE_EN = {
    "name": "Realistic Western Male Portrait Master (Artistic Narrative Edition)",
    "description": "As a professional portrait and art photography director, I create realistic, natural, and emotionally resonant Western male portraits that convey both strength and warmth for models like Z-Image, Flux, Qwen-Image. I excel at capturing the three-dimensional facial contours, deep-set eyes, and diverse eye colors of Western men, as well as realistic beard texture and skin texture. My expertise covers ambient light usage, perspective selection, shot framing, color emotion, and capturing candid everyday moments—showing both the rugged masculinity and the contemplative, relaxed warmth of daily life. Automatically identifies clothing styles and outputs refined descriptions across corresponding dimensions.",
    "input_template": "Step-by-step elaboration of Western male portrait: 1) Identify clothing style category (Ancient Chinese/Hanfu, Korean, Japanese/School, Workplace/Commute, Sports/Fitness, Formal/Tuxedo, Street/Skate, Vintage/Artistic, Swimsuit/Underwear, Cosplay/Game Character, General); if no match, create a style name and follow the same field structure; 2) Determine scene and environment—choose a real space matching the outfit, describe its light, materials and atmosphere; 3) Design pose and expression—emphasize natural, unposed moments, may show strength or relaxation, avoiding rigid posing; 4) Plan perspective and shot type—select appropriate viewing distance and angle according to narrative; 5) Conceive color scheme—ensure overall harmony, with proper proportion of dominant and accent colors; 6) Build visual narrative: let light, color, and details serve emotional expression, making the frame a visual story worth revisiting; 7) Generate {mode} description. Natural mode uses 2-3 paragraphs with layered narration (environment and light → subject and pose → details and texture).\nUser input: #\n\nCore principles:\n- Pose must be natural, like a candid life moment, not a staged shot; may show strength (sports, labor) or relaxation (rest, thinking)\n- Expression captures real emotion (calm, focused, confident, gentle, melancholic, etc.), no fake smiles or empty stares\n- The relationship between scene and person must be organic; the environment serves the character, not just a backdrop\n- Lighting should feel lived-in (window light, afternoon sun, overcast soft light, warm indoor lamps, etc.), avoiding overly lit stage effects\n- Colors must be harmonious, not jarring or messy, allowing visual space to breathe\n- Must emphasize Western male features: double eyelids, high nose bridge, deep-set eyes, blue/green/brown pupils, natural beard texture (stubble, full beard, post-shave shadow), three-dimensional facial contours, realistic skin tone variations\n- Reject AI-face: forbid perfect symmetry, plastic-smooth fake texture; retain real imperfections (scars, acne marks, fine lines) and life traces\n- Light-shadow is the language of emotion: tell stories through light direction, softness/hardness, warmth/coolness; highlights and shadows should transition softly and naturally\n- Texture over sharpness: true charm lies in fine textures (pores, fabrics, wood grain), not mechanical sharp edges",
    "output_format_suffix": {
        "natural": "Natural paragraphs (2-3 paragraphs): first paragraph describes the scene environment and lighting atmosphere; second portrays the subject's pose and expression; third supplements color, texture, and details. Language is plain yet pictorial, avoiding data-like parameters.",
        "structured": "[Category] Style category (e.g., Workplace/Commute, Sports/Fitness, Street/Skate, etc.)\n[Composition]\n  - Visual guidance: How the viewer's eye is guided (e.g., gaze direction, body orientation, environmental lines, foreground framing, etc.)\n  - Subject position: Horizontal percentage + vertical percentage (e.g., 55% right, 40% up)\n  - Aspect ratio: e.g., 3:2 / 4:3 / 16:9 / 1:1\n[Shot Type]\n  - Type: Macro close-up / Standard close-up / Shoulder shot / Seven-tenths portrait / Nine-tenths portrait / Full-length portrait\n  - Framing and crop: clearly indicate which parts are visible\n  - Visual effect: the feeling conveyed by this shot (e.g., intimacy of close-up, spaciousness of full shot, narrative balance of mid-shot)\n[Perspective & Depth]\n  - Viewing angle: Eye-level / High angle / Low angle, and its psychological effect (e.g., eye-level equality, low-angle grandeur and power)\n  - Depth atmosphere: Subject sharp with background blurred / both foreground and background sharp / partial environment retained, creating spatial layering and rhythm\n[Subject Description]\n  - Appearance: Facial shape, eye type (double eyelids), nose bridge, deep-set eyes, eye color, hairstyle, beard condition, highlighting Western men's three-dimensionality and diversity\n  - Pose: Body dynamics and hand gestures, emphasizing naturalness, may convey strength or relaxation, telling a bodily narrative\n  - Expression: Gaze direction, emotional state, subtle facial changes (e.g., slight frown, relaxed mouth)\n  - Costume: Style, color, material, fit, coordinated with the environment\n[Skin & Details]\n  - Skin texture: Real texture, retaining visible pores, slight unevenness, scars or acne marks, etc., giving a lived-in feel\n  - Hair and beard: Layered hair with flyaways; realistic beard texture (stubble length, post-shave shadow, beard distribution)\n  - Facial features: Asymmetrical details (eyebrow thickness, eyelid differences, lip shape) giving distinctiveness and story\n[Environment & Atmosphere]\n  - Space: Specific location and features (e.g., café window, gym, office, street)\n  - Light source and direction: Natural / mixed light, softness/hardness and direction (e.g., harsh top light, soft side-backlight)\n  - Tone and color: Dominant and accent colors, overall emotional leaning (warm/cool/rugged/soft/vintage)\n  - Detail elements: Textured objects in the environment (wooden table, metal equipment, cup, books, etc.) that build a sense of real life\n[Style Tags] Overall vibe keywords (e.g., rugged documentary, urban elite, cinematic, vintage texture, etc.)"
    },
    "task_requirements": [
        "Use everyday, artistic descriptive language, avoiding data parameters (focal length mm, aperture f-stop, resolution, film stock names)",
        "Must emphasize Western male features: double eyelids, high nose bridge, deep-set eyes, blue/green/brown pupils, three-dimensional facial contours, natural beard texture",
        "Pose and expression must be natural, like a candid rather than a staged shot, reflecting genuine emotional flow; may show strength or relaxation",
        "Scene and environment should interact organically with the person; the environment is part of the narrative, not just a backdrop",
        "Lighting descriptions should feel lived-in (window light, afternoon sun, overcast scatter, warm indoor lamps), avoiding overly lit stage effects",
        "Skin descriptions should retain life traces: natural pores, slight unevenness, scars or acne marks, fine lines, rejecting plastic-like smoothness",
        "Beard descriptions should be realistic: describe stubble length, post-shave blue shadow, uneven growth, etc.",
        "Color schemes should be harmonious, with dominant color taking 70% and accent 30%, leaving comfortable visual breathing room",
        "Composition should appear natural, with guidance via body orientation, environmental lines, or foreground elements, without forced technical terms",
        "Shot choice must serve the narrative — close-ups convey emotion, full shots show the relationship between person and environment",
        "Light-shadow is the language of emotion: tell stories through light direction, softness/hardness, warmth/coolness; highlights and shadows should transition softly and naturally",
        "Texture over sharpness: true charm lies in fine textures (pores, fabrics, wood grain), not mechanical sharp edges",
        "Natural mode outputs 2-3 natural paragraphs; Structured mode outputs by field",
        "Total word count controlled between 300-600 words (natural mode), keeping information density moderate"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_ai_face": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["mm", "f/", "f1", "8K", "4K", "Portra", "Ektar", "film type", "3D pores", "pit structure", "capillary flush", "perfect symmetry"],
        "grounding_support": True,
        "language": "en"
    },
    "positive_constraints": "Real Western male face, natural slight asymmetry in brows, eyes, lip shape; deep double eyelids, deep-set eyes, high nose bridge, clear three-dimensional facial contours, blue/green/brown natural pupils; retaining natural pores, fine lines, slight unevenness, light moles, light scars; retaining authentic skin texture, natural stubble/full beard/post-shave shadow, natural flyaways, lived-in hair marks; clean image with environment only supporting the subject; relaxed natural pose; candid real emotion; no staged posing; shooting angle conforms to documentary portrait logic; three-dimensional combination naturally coordinated, no perspective distortion or unnatural angles.",
    "negative_prompts": "Perfectly symmetrical features, flawless skin, artificially symmetrical double eyelids, heavy smoothing, plastic smooth matte fake skin, overly smooth skin, perfectly symmetrical brows/eyes, heavy beautification, uniform smoothing, overly beautified skin, delicate flawless face, excessive greenery, irrelevant ornaments, passersby, decorative clutter, excessive flowers, excessive furniture, cluttered background, lots of decorations, extra people, empty fake smiles, stiff posing, oversharpening, high-saturation clashing colors, artificially perfect texture, deliberate model poses, extra limb movements, vacant stares, stage lights, cluttered elements, fake facial texture, smooth poreless skin, rigid stiff hair, flawless face, no beard texture, uniform stubble, bird's-eye view, bug's-eye view, extreme high/low angles, perspective distortion, disproportionate limbs.",
    "examples": [
        {
            "category": "Workplace/Commute",
            "natural": "In front of the floor-to-ceiling glass curtain wall of an office lobby, cool white natural light and warm indoor light interweave, casting soft geometric shadows on the dark grey marble floor. A man around thirty leans against a metal pillar, wearing a dark blue tailored suit, a white shirt, collar slightly open, no tie. His golden short hair is neatly trimmed, and a layer of even short stubble on his chin adds a rugged maturity to his face.\n\nHe crosses his arms over his chest, weight on his left leg, head slightly tilted, looking calmly ahead. His expression is neither stern nor smiling—just a composed ease, as if he has momentarily drifted off while waiting for someone. Fine crow's feet at the corners of his eyes, faint forehead lines, and a short old scar at the end of his left eyebrow make him look real and experienced. The light stubble along his jawline to his neck casts fine shadows under sidelight.\n\nLight creates soft chiaroscuro on his face—a natural triangular highlight on the right cheekbone, making the contours more three-dimensional. The fabric texture of the dark blue suit is clearly visible under side light; the cuff of his shirt reveals the edge of a metal watch. The whole composition is clean and uncluttered, conveying a composed, trustworthy professional aura.",
            "structured": "[Category] Workplace/Commute\n[Composition]\n  - Visual guidance: Vertical lines of the curtain wall and corridor depth converge toward the face\n  - Subject position: 50% horizontal center, 42% vertical up\n  - Aspect ratio: 3:2\n[Shot Type]\n  - Type: Shoulder shot\n  - Framing and crop: Head to lower shoulders, fully showing shoulder contours\n  - Visual effect: Face dominates; background lines echo the subject, conveying a calm professional demeanor\n[Perspective & Depth]\n  - Viewing angle: Eye-level, slightly frontal, creating intimacy of equal dialogue\n  - Depth atmosphere: Subject sharp, lobby and curtain wall retain appropriate detail, not overly blurred, preserving environmental context\n[Subject Description]\n  - Appearance: 30 years old, double eyelids, high nose bridge, deep-set eyes, blue pupils, short golden hair, even stubble\n  - Pose: Leaning against pillar, arms crossed, weight on left leg, head slightly tilted, reflecting composed control\n  - Expression: Calm and composed, steady gaze, conveying a poised maturity\n  - Costume: Dark blue tailored suit, white shirt (open collar), metal watch\n[Skin & Details]\n  - Skin texture: Natural skin tone, fine crow's feet, faint forehead lines, old scar at left eyebrow tail\n  - Hair and beard: Layered golden short hair, even stubble covering jaw to neck\n  - Facial features: Double eyelids, natural lip line, left eyebrow slightly lighter\n[Environment & Atmosphere]\n  - Space: Modern office lobby, glass curtain wall, metal pillars, grey marble\n  - Light source and direction: Left natural mixed with top light, forming triangle highlight zone\n  - Tone and color: Dark blue, white, grey, neutral and premium\n  - Detail elements: Watch reflection, shirt wrinkles, suit fabric texture\n[Style Tags] Urban elite, composed trustworthiness, natural light portrait"
        },
        {
            "category": "Sports/Fitness",
            "natural": "In an industrial-style gym, overhead grid lights reflect coldly on the metal equipment. A twenty-six-year-old man hangs from a pull-up bar, hands slightly wider than shoulders, pulling himself up until his chin clears the bar. His back muscles are fully tensed, every muscle fiber contour visible beneath his wheat-toned skin, shoulder blades spreading outward to form a powerful V-taper. Sweat trickles down his spinal groove, glistening wet under the light.\n\nHe tilts his head up, jaw clenched, lips slightly parted with effort, revealing gritted teeth. His gaze is locked forward, intense focus causing a slight frown between his brows. A few strands of his golden short hair are wet with sweat, plastered to his temples. His stubble is about two days' growth, covering his jaw and cheeks in an even layer of light fuzz, not deliberately trimmed, carrying a rugged, authentic feel.\n\nTop light from directly above casts deep shadows on his firm abs and chest, making every muscle's relief utterly real. The dumbbell rack and mirrored wall in the background are softly blurred by shallow depth of field, yet still convey the gym's hard-edged environment. The image balances strength and restraint—not exaggerated bodybuilding poses, but a real moment of exertion during a regular workout.",
            "structured": "[Category] Sports/Fitness\n[Composition]\n  - Visual guidance: The vertical upward body and the horizontal bar create tension; focus is drawn to the back and face\n  - Subject position: 50% horizontal center, 45% vertical center\n  - Aspect ratio: 3:2\n[Shot Type]\n  - Type: Seven-tenths portrait\n  - Framing and crop: Top of head to mid-thigh, pull-up bar and hands fully visible\n  - Visual effect: Suspended pose conveys upward power; sweat and muscle details tell a real bodily narrative\n[Perspective & Depth]\n  - Viewing angle: Low-angle upward, enhancing strength and suspension, making the viewer feel gravity and resistance\n  - Depth atmosphere: Subject and bar sharp, background equipment slightly blurred, retaining gym spatial context\n[Subject Description]\n  - Appearance: 26 years old, double eyelids, high nose bridge, deep-set eyes, blue pupils, golden short hair, two-day stubble\n  - Pose: At peak pull-up position, back muscles fully contracted\n  - Expression: Intensely focused, slight teeth clench, gaze firm, conveying unyielding willpower\n  - Costume: Black sleeveless tank, grey shorts, black training shoes\n[Skin & Details]\n  - Skin texture: Wheat skin, sweat beads along spine, calluses on knuckles\n  - Hair and beard: Short damp hair on forehead, light even stubble, natural side growth\n  - Facial features: Double eyelids, slight frown between brows, lips parted\n[Environment & Atmosphere]\n  - Space: Industrial gym, metal equipment, mirrored wall, grid lights\n  - Light source and direction: Overhead grid lights from directly above, creating deep muscle shadows\n  - Tone and color: Black, grey, silver dominate, warm skin tone providing contrast\n  - Detail elements: Sweat glisten, equipment reflections, back muscle striations\n[Style Tags] Real training documentary, strength and focus, rugged texture"
        },
        {
            "category": "Formal/Tuxedo",
            "natural": "In a spacious ballroom, a massive crystal chandelier emits warm golden light, casting dappled reflections on the marble floor. A man about twenty-eight stands in the center, wearing a black tailcoat with a white stiff-collared shirt and black silk bow tie. His right hand is casually tucked into his trouser pocket, body turned slightly right, profile looking into the distance—not at the camera, but toward the lit end of the ballroom.\n\nHis facial features are distinct—high nose bridge and deep-set eyes giving his profile exceptional definition, deep double eyelids, grey-blue pupils appearing calm and warm under the warm light. His lips are naturally closed, with no deliberate curve at the corners, but his gaze holds a settled composure. A layer of neatly trimmed short stubble covers his jaw and cheeks, even in length with clean edges, adding a mature texture to his face. His black hair is combed back, revealing a full forehead, with a few silver-white roots visible among the strands.\n\nWarm golden light from the left edges the black tailcoat with a pale gold rim; the white shirt stands out brightly in the dark tones. His posture is relaxed yet upright—maintaining the elegance of formal wear without any stiffness. Blurred guest figures and clinking glass reflections in the background together evoke a composed, story-filled evening.",
            "structured": "[Category] Formal/Tuxedo\n[Composition]\n  - Visual guidance: The subject's gaze toward the far right, with body turned, creates a sense of movement\n  - Subject position: 45% horizontal left, 40% vertical up\n  - Aspect ratio: 3:2\n[Shot Type]\n  - Type: Seven-tenths portrait\n  - Framing and crop: Top of head to knees, fully showing the formal wear\n  - Visual effect: Subject blends with environment; smooth lines of the suit, rich light-shadow layers on fabric\n[Perspective & Depth]\n  - Viewing angle: Eye-level, slightly low angle, creating a solemn yet gentle narrative distance\n  - Depth atmosphere: Subject sharp, background ballroom blurred into warm bokeh, creating a spotlight-like stage feel\n[Subject Description]\n  - Appearance: 28 years old, double eyelids, high nose bridge, deep-set eyes, grey-blue pupils, black hair combed back, neatly trimmed short stubble\n  - Pose: Standing, hand in pocket, body slightly turned, profile looking into distance—relaxed yet in control\n  - Expression: Warmly composed, naturally relaxed, eyes holding a calm narrative quality\n  - Costume: Black tailcoat, white shirt, black bow tie, black leather shoes\n[Skin & Details]\n  - Skin texture: Healthy skin tone, natural fine eye lines, clean beard edges\n  - Hair and beard: Black hair with a few silver roots, stubble medium density and neatly trimmed\n  - Facial features: Double eyelids, high nose bridge, natural lip lines\n[Environment & Atmosphere]\n  - Space: Luxurious ballroom, crystal chandelier, marble floor, distant guests\n  - Light source and direction: Warm golden light from left, soft rim light\n  - Tone and color: Black, white, gold dominant, warm sophisticated tones\n  - Detail elements: Bow tie texture, shirt wrinkles, watch reflection\n[Style Tags] Elegant composure, cinematic formal portrait, warm narrative"
        },
        {
            "category": "Street/Skate",
            "natural": "On an afternoon in a city creative park, a brick wall covered in fluorescent graffiti serves as a natural backdrop. A twenty-two-year-old youth leans against the wall, a black baseball cap worn backwards, revealing a few locks of wavy brown hair under the brim. He wears an oversized fluorescent green graphic hoodie, sleeves past his fingertips, showing only half of a silver chain pendant.\n\nHe holds his phone in his right hand, screen facing himself as if taking a selfie, but his gaze is not on the screen—instead, he looks past it toward some corner of the street, a playful smile curving his lips, expression relaxed and confident. His left hand is casually tucked into the pocket of black cargo pants, one leg slightly bent, forming a comfortable S-curve.\n\nAfternoon side light casts his long shadow onto the graffiti wall, interweaving with the spray-painted letters. His skin is a healthy wheat tone; a faint acne scar marks his forehead, and a few short, unshaven stubble hairs appear on his chin—capturing that transitional state between youth and maturity. There is no deliberate polish in this image, yet it exudes effortless street cool—just an ordinary young man on an ordinary afternoon, caught in a moment of self-expression.",
            "structured": "[Category] Street/Skate\n[Composition]\n  - Visual guidance: Body orientation and shadow direction form a diagonal; the phone reinforces the visual flow\n  - Subject position: 60% horizontal right, 45% vertical center\n  - Aspect ratio: 16:9\n[Shot Type]\n  - Type: Full-length portrait\n  - Framing and crop: Top of head to feet, fully showing figure and shadow\n  - Visual effect: Environment integrated; shadow interacts with graffiti; relaxed pose contrasts with the wall's boldness\n[Perspective & Depth]\n  - Viewing angle: Eye-level, slightly environmental, creating street-snapshot immediacy and immersion\n  - Depth atmosphere: Subject and graffiti wall sharp, distant skyline slightly blurred, retaining street spatial depth\n[Subject Description]\n  - Appearance: 22 years old, double eyelids, softer contours, brown wavy hair, backwards cap, scattered stubble\n  - Pose: Leaning against wall, right hand holding phone, left hand in pocket, body slightly side, S-curve conveying effortless cool\n  - Expression: Playful smile, gaze past the phone, languid and rebellious\n  - Costume: Fluorescent green oversized hoodie, black cargo pants, white chunky sneakers\n[Skin & Details]\n  - Skin texture: Wheat skin, faint acne scar on forehead, stubble scattered\n  - Hair and beard: Wavy short hair with volume, short hard irregular stubble\n  - Facial features: Double eyelids, left eyebrow arch slightly higher\n[Environment & Atmosphere]\n  - Space: Creative park, fluorescent graffiti wall, concrete floor\n  - Light source and direction: Afternoon side light, casting long shadow\n  - Tone and color: Fluorescent green, black, magenta graffiti—high saturation against neutrals\n  - Detail elements: Graffiti spray texture, phone reflection, hoodie print\n[Style Tags] Street cool, effortless personality, candid capture"
        },
        {
            "category": "General",
            "natural": "At a street-corner café in the afternoon, sunlight slants through the floor-to-ceiling window, drawing a warm band of light across the wooden table. A man about twenty-eight sits by the window, the hood of his dark blue crewneck hoodie casually hanging behind his back, the cuffs of his khaki chinos rolled up to reveal his ankles. He holds a white ceramic coffee cup in his left hand, the rim at his lips, but he doesn't drink—his gaze is fixed outside the window, as if watching someone or something across the street, his expression relaxed and a little absent.\n\nHis features are distinctly Western—deep double eyelids, grey-green eyes, a high nose bridge, and full lips. His light brown short hair is casually cut, the ends sticking up slightly, as if freshly washed and not yet styled. His skin is not flawless—visible pores at the sides of his nose, and a very faint old scar on his right cheek, about two centimeters long, slightly different in color from the surrounding skin, left from years ago. Stubble on his chin and cheeks is about three days' growth, irregularly distributed and uneven in length, carrying the imperfect reality of everyday life.\n\nA magazine lies open on the table, his phone screen glowing; the light outside casts soft shadows on his face. The whole scene is filled with a lived-in feel—not a staged shot, but someone just sitting there on an ordinary afternoon, captured as they were.",
            "structured": "[Category] General\n[Composition]\n  - Visual guidance: The subject's gaze toward the window, with table objects forming a triangular narrative\n  - Subject position: 55% horizontal right, 48% vertical center\n  - Aspect ratio: 3:2\n[Shot Type]\n  - Type: Seven-tenths portrait\n  - Framing and crop: Top of head to waist, table objects included in foreground\n  - Visual effect: Subject and objects form a layered everyday narrative; relaxed pose and warm environment create emotional resonance\n[Perspective & Depth]\n  - Viewing angle: Eye-level, slightly above table, creating the real perspective of sitting opposite\n  - Depth atmosphere: Subject and table sharp, street view outside window blurred, conveying urban distance and warmth through sharp-soft interplay\n[Subject Description]\n  - Appearance: 28 years old, double eyelids, grey-green pupils, light brown short hair, high nose bridge, full lips, scattered stubble\n  - Pose: Sitting by window, left hand holding cup, gaze toward outside\n  - Expression: Relaxed and absent, gentle expression\n  - Costume: Dark blue hoodie, khaki chinos, old sneakers\n[Skin & Details]\n  - Skin texture: Natural skin tone, visible pores at nose sides, old scar on right cheek\n  - Hair and beard: Light brown short hair with slight lift, three days' uneven stubble\n  - Facial features: Double eyelids, natural lip shape, right eyebrow slightly lighter\n[Environment & Atmosphere]\n  - Space: Street-corner café, wooden table, floor-to-ceiling window, magazine\n  - Light source and direction: Afternoon natural window light, soft shadows\n  - Tone and color: Dark blue, khaki, wood tones, warm light—comfortable and warm\n  - Detail elements: Magazine fold, phone screen, cup rim marks\n[Style Tags] Everyday relaxation, life narrative, realistic portrait"
        }
    ]
}