# -*- coding: utf-8 -*-
"""
图像反推类预设模块

Author: 亲卿于情 (@Qo-qiao)
GitHub: https://github.com/Qo-qiao
License: See LICENSE file for details
"""

IMAGE_REVERSE_TAGS_ZH = {
    "name": "图像标签反推生成器",
    "description": "作为专业的SDXL标签化模型提示词工程师，我将自动识别图像类别并生成精确的中文标签列表。我的专业知识涵盖摄影术语、艺术风格、色彩理论、构图学、镜头光学、人体姿态、材质质感、SDXL权重语法、负面提示词工程等领域，可精准还原原图构图、主体位置、姿态动作、色彩光影、镜头虚实、空间层次。",
    "input_template": "逐步思考：1）分析图像内容，识别主导视觉元素，标注主体位置、构图布局、前后景层级；2）从以下类别中选择最合适的：风景类、摄影类、人像类、插画类、IP类、cosplay类、游戏角色类、产品类、建筑室内类、动物类、美食类、UI界面类、时尚穿搭类、通用类；3）如未匹配，根据图像内容创建合适的类别名称；4）区分主体/次要物体，使用SDXL权重语法区分标签优先级，按照类别特定字段结构生成{mode}标签列表；5）验证：30-60个标签，无重复无同义冗余，包含强制质量标签、构图标签、镜头标签，同步生成配套负面标签。\n\n用户输入：#\n\n规则：1.仅输出JSON，无额外文字；2.标签总数30-60，无重复、无同义语义重复；3.必须包含质量标签（杰作、最佳质量、高分辨率、超精细、8K）；4.强制加入构图布局、主体位置、画面层级标签；5.主体标签添加(xxx:1.1~1.3)权重强化，次要杂物使用[xxx:0.6~0.8]弱化；6.同步输出配套负面标签字符串；7.严格按照下方字段结构输出。",
    "output_format_suffix": {
        "natural": "逗号分隔带SDXL权重的标签字符串，末尾拼接分号+逗号分隔负面标签字符串。",
        "structured": "【类别】类别名称\n【质量标签】杰作，最佳质量，高分辨率，超精细，8K\n【构图布局】构图类型，主体画面占比，主体位置，画面留白，画幅比例\n【核心要素】\n  - 场景类型：场景描述内容\n  - 时间光线：时间与光线描述内容，阴影硬度，光斑形态，轮廓光强度\n  - 色彩氛围：主色调，辅色调，白平衡，色彩对比度，饱和度梯度，环境反光色\n【画面层级】前景元素，中景主体，远景背景\n【人物/物体特征】（按类别自动适配，人像/动物/产品专属）\n【姿态动作】头部转向，视线方向，肢体扭转，手部动作\n【景别】景别描述内容（微距特写/标准特写/肩特写/七分人像/九分人像/全景人像），主体画面占比数值\n【细节元素】细节元素描述内容，材质肌理，粗糙度，反光属性\n【画质修正】暗角，胶片颗粒，锐化强度，镜头畸变，色散控制\n【技术参数】镜头与视角描述内容，光圈数值，虚化强度，焦平面位置\n【负面标签】逗号分隔规避画面崩坏、色差、畸变、多余杂物的负面提示词"
    },
    "task_requirements": [
        "先识别图像类别，再按对应字段输出标签",
        "必须包含杰作、最佳质量、高分辨率、超精细、8K等质量标签",
        "标签简洁，每个字段内逗号分隔，总标签数30-60，自动合并同义标签避免冗余",
        "各类别字段顺序可调整，但字段名必须完全一致，新增字段不可删除",
        "natural模式：输出带SDXL权重逗号分隔标签字符串，末尾追加分号分隔负面标签；structured模式：输出完整结构化提示词（含构图、层级、画质、负面标签模块）",
        "景别判断规则：\n  - 微距特写（Macro Close-up）：只截取人体极小局部，无完整面部，填满画面，极致细节（单只眼睛/嘴唇/指尖/皮肤肌理/发丝等），主体画面占比90%~100%\n  - 标准特写（Close-up）：头顶至下巴，完整脸部不含肩膀，画面主体全是人脸，主体画面占比70%~90%\n  - 肩特写（Close-up with shoulder）：头部+一点点肩线，只露出肩头一小截，主体画面占比60%~80%\n  - 七分人像（Medium Shot）：头顶到腰腹/腰线，截断于腰部肚脐附近，含完整头部肩膀胸口腰，主体画面占比40%~65%\n  - 九分人像（Medium Full Shot）：头顶到小腿膝盖下方/脚踝上方，裁切在脚踝/小腿中段，不完整露出双脚，主体画面占比30%~50%\n  - 全景人像（Full Body Shot）：完整从头到脚全身入镜，四肢双脚全部包含无裁切，主体画面占比20%~40%",
        "构图强制要求：每张图必须标注构图（三分构图/黄金分割/居中构图/左偏移构图/右偏移构图/对称构图）、主体画面占比、画面留白多少、画幅比例（16:9/4:3/1:1/9:16/2.35:1）",
        "权重规则：核心主体(标签:1.2)，次要装饰物体[标签:0.7]，环境基础描述无权重",
        "负面标签强制生成：畸形，五官扭曲，色差，严重畸变，多余肢体，模糊，低分辨率，水印，文字，杂乱杂物，过曝，死黑阴影"
    ],
    "constraints": {
        "max_tags": 60,
        "min_tags": 30,
        "no_duplicates": True,
        "exclude_abstract": True,
        "no_semantic_repeat": True,
        "must_include_composition_tags": True,
        "must_include_depth_layer_tags": True,
        "must_attach_negative_tags": True
    },
    "examples": [
        {
            "category": "风景类",
            "natural": "(杰作:1.3),(最佳质量:1.2),(高分辨率:1.2),(8K:1.2),(超精细:1.2),风景照,(雪山:1.3),云海,峡谷,日出,(金色时刻:1.1),硬光,侧逆光,冷色调,蓝白灰,宁静,空旷感,航拍视角,远景,长焦镜头,16:9宽幅,三分构图,主体占比35%,画面底部留白,松树,[薄雾:0.7],层峦叠嶂,阴影对比,蓝天白云,天空渐变,大气透视,近深远淡,空气湿度,能见度极高,晨雾缭绕,晨曦穿透,层次分明,透视感强,氛围感强,低胶片颗粒,无暗角;畸形,模糊,低清,水印,文字,多余山峰,过曝天空,死黑阴影",
            "structured": "【类别】风景类\n【质量标签】杰作，最佳质量，高分辨率，超精细，8K\n【构图布局】三分构图，主体画面占比35%，主体居中偏上，底部大量留白，16:9宽幅\n【核心要素】\n  - 场景类型：山景，雪山，云海，峡谷\n  - 时间光线：日出，金色时刻，硬光，侧逆光，中度阴影硬度，圆形光斑，弱轮廓光\n  - 色彩氛围：主色调冷蓝，辅色调灰白，标准白平衡，低色彩对比度，低饱和度，天空淡金色环境反光\n【画面层级】前景低矮松树，中景层叠山峦，远景云海天际线\n【姿态动作】无\n【景别】全景远景，主体画面占比35%\n【细节元素】松树，薄雾，层峦叠嶂，明暗阴影对比，岩石哑光肌理\n【画质修正】低胶片颗粒，无暗角，零镜头畸变，轻度锐化\n【技术参数】航拍视角，远景，长焦镜头，f/8，弱虚化，焦平面锁定雪山主峰\n【负面标签】畸形，模糊，低分辨率，水印，文字，多余山峰，天空过曝，死黑阴影，色彩断层"
        },
        {
            "category": "人像类",
            "natural": "(杰作:1.3),(最佳质量:1.2),(高分辨率:1.2),(8K:1.2),(超精细:1.2),人像摄影,(亚洲女性:1.3),25岁,(黑色长发披肩:1.2),杏仁眼,(温柔微笑:1.2),自然细腻肤色,(浅米色针织衫:1.1),袖口蕾丝,[咖啡馆窗边:0.8],午后阳光,柔和侧光,低饱和度,温暖色调,居中构图,主体占比60%,左右小幅留白,平视视角,中景,35mm定焦,f/1.8,浅景深,温馨氛围,(安静阅读:1.2),书籍,[咖啡杯:0.7],木质桌面,[薄纱窗帘:0.7],轻微暗角,低颗粒;五官扭曲,畸形手,模糊,色差,水印,多余人物,过曝脸部,死黑阴影" ,
            "structured": "【类别】人像类\n【质量标签】杰作，最佳质量，高分辨率，超精细，8K\n【构图布局】居中构图，主体画面占比60%，左右小幅留白，4:3画幅\n【核心要素】\n  - 场景类型：咖啡馆室内\n  - 时间光线：午后自然光，柔和侧光，软阴影，长条窗光光斑，弱轮廓光\n  - 色彩氛围：主色调暖米，辅色调浅棕，暖白平衡，低色彩对比度，中低饱和度，窗帘柔光反光\n【画面层级】前景咖啡杯，中景人物主体，远景窗外虚化绿植\n【人物特征】\n  - 外貌：亚洲女性，25岁，黑色长发披肩，杏仁眼，温柔微笑，细腻自然皮肤\n  - 服装：浅米色针织衫，袖口蕾丝装饰，哑光织物肌理\n  - 姿态：安静阅读，右手翻书，头部轻微左偏，视线向下看向书页\n【姿态动作】头部左偏15°，视线向下，右手抬起翻页，躯干轻微前倾\n【景别】七分人像（Medium Shot）：头顶到腰部，完整头部肩膀胸口腰，截断于腰部肚脐附近，主体画面占比60%\n【细节元素】纸质书籍，陶瓷咖啡杯，原木纹理桌面，半透薄纱窗帘，漂浮窗光尘埃\n【画质修正】轻微暗角，低胶片颗粒，无镜头畸变，中度锐化皮肤\n【技术参数】平视视角，中景，35mm定焦，f/1.8，强浅景深，焦平面锁定人物面部\n【负面标签】五官扭曲，畸形手部，模糊，色彩色差，水印，多余人物，脸部过曝，死黑阴影，肢体残缺"
        },
        {
            "category": "动物类",
            "natural": "(杰作:1.3),(最佳质量:1.2),(高分辨率:1.2),(8K:1.2),(超精细:1.2),动物摄影,(橙色虎斑猫:1.3),(绿色眼睛:1.2),坐姿,(蓬松毛发:1.2),室内窗台,阳光洒落,温暖光影,柔和光线,高对比度,左偏移构图,主体占比70%,右侧留白,特写镜头,50mm微距,浅景深,毛绒质感,(胡须清晰:1.1),眼神灵动,[窗台绿植:0.7],木质纹理,自然光,温馨氛围,(可爱警觉表情:1.2),低颗粒;畸形五官,扭曲猫爪,模糊,色差,多余杂物,过曝毛发,死黑阴影",
            "structured": "【类别】动物类\n【质量标签】杰作，最佳质量，高分辨率，超精细，8K\n【构图布局】左偏移构图，主体画面占比70%，右侧大面积留白，1:1方形画幅\n【核心要素】\n  - 场景类型：室内窗台\n  - 时间光线：自然窗光，柔和侧光，软阴影，圆形阳光光斑，中度轮廓光\n  - 色彩氛围：主色调暖橙，辅色调原木棕，暖白平衡，高色彩对比度，中饱和度，绿植淡绿反光\n【画面层级】前景猫爪毛发，中景猫咪主体，远景虚化窗台绿植\n【动物特征】\n  - 物种：橙色虎斑猫\n  - 外貌：绿色通透眼睛，蓬松双层毛发，根根清晰胡须，短绒毛肌理\n  - 姿态：端正坐姿，警觉向前，眼神直视镜头\n【姿态动作】头部正对镜头，视线平视前方，前爪收拢于胸前，身体挺直\n【景别】肩特写，主体画面占比70%\n【细节元素】窗台小型绿植，原木窗台纹理，阳光圆形光斑，绒毛反光高光\n【画质修正】低胶片颗粒，无暗角，零畸变，高锐化毛发细节\n【技术参数】特写镜头，50mm微距，f/2.0，强浅景深，焦平面锁定猫咪面部\n【负面标签】畸形五官，扭曲猫爪，画面模糊，色彩色差，多余杂物，毛发过曝，死黑阴影，多只猫咪"
        },
        {
            "category": "美食类",
            "natural": "(杰作:1.3),(最佳质量:1.2),(高分辨率:1.2),(8K:1.2),(超精细:1.2),美食摄影,(草莓蛋糕:1.3),奶油装饰,(新鲜草莓:1.2),木质托盘,白色餐盘,午后阳光,柔和逆光,暖色调,高饱和度,45度俯视对称构图,主体占比65%,四周均匀留白,浅景深,焦外虚化,蛋糕纹理,(奶油细腻:1.1),(草莓水珠:1.1),温馨氛围,诱人食欲,烘焙质感,甜点,下午茶,[咖啡搭配:0.7],桌面纹理,无暗角;融化糊掉奶油,腐烂草莓,模糊,色差,多余餐具,过曝蛋糕表面",
            "structured": "【类别】美食类\n【质量标签】杰作，最佳质量，高分辨率，超精细，8K\n【构图布局】45度俯视对称构图，主体画面占比65%，四周均匀留白，4:3画幅\n【核心要素】\n  - 场景类型：餐桌静物\n  - 时间光线：午后阳光，柔和逆光，软阴影，长条光斑，强轮廓光勾勒食物边缘\n  - 色彩氛围：主色调暖粉白，辅色调鲜红，暖白平衡，高对比度，高饱和度，木质暖棕反光\n【画面层级】前景草莓水珠，中景蛋糕主体，远景虚化咖啡杯桌面\n【美食特征】\n  - 主体：草莓奶油蛋糕，裱花奶油装饰，带水珠新鲜草莓果肉\n  - 质感：海绵蛋糕多孔纹理，丝滑哑光奶油，透亮草莓表皮水珠\n【姿态动作】无\n【景别】静物标准特写，主体画面占比65%\n【细节元素】原木托盘，纯白陶瓷餐盘，玻璃咖啡杯，实木桌面纹理，奶油裱花纹路\n【画质修正】无暗角，极低胶片颗粒，无畸变，中度锐化食物细节\n【技术参数】45度俯视，50mm定焦，f/2.2，浅景深，焦平面锁定蛋糕顶部草莓\n【负面标签】融化糊掉奶油，腐烂发黑草莓，画面模糊，色彩色差，多余餐具，蛋糕表面过曝，杂乱桌面杂物"
        },
        {
            "category": "建筑室内类",
            "natural": "(杰作:1.3),(最佳质量:1.2),(高分辨率:1.2),(8K:1.2),(超精细:1.2),室内设计,现代简约,(客厅:1.3),落地窗,自然光,白色墙面,原木家具,(灰色沙发:1.2),绿植装饰,开放式布局,空间通透,光影层次,柔和光线,冷色调,简洁干净,对称居中构图,主体占比40%,上下留白,广角镜头,透视感强,北欧风格,舒适氛围,几何线条,[室内植物:0.7],装饰品,轻微暗角;墙体扭曲,家具变形,模糊,色差,多余杂物,过曝落地窗,死黑角落阴影",
            "structured": "【类别】建筑室内类\n【质量标签】杰作，最佳质量，高分辨率，超精细，8K\n【构图布局】对称居中构图，主体画面占比40%，上下大面积留白，16:9宽幅\n【核心要素】\n  - 场景类型：现代简约北欧客厅\n  - 时间光线：全天均匀自然窗光，极软阴影，大面积漫反射光斑，弱轮廓光\n  - 色彩氛围：主色调冷白，辅色调原木灰，冷白平衡，低对比度，低饱和度，绿植淡绿反光\n【画面层级】前景茶几摆件，中景沙发家具主体，远景落地窗户外虚化景色\n【空间特征】\n  - 布局：开放式通透布局，横向延伸空间\n  - 材质：哑光白色墙面，原木哑光家具，布艺灰色沙发，玻璃通透落地窗\n  - 装饰：落地绿植，简约金属桌面装饰品\n【姿态动作】无\n【景别】全景空间全景，主体画面占比40%\n【细节元素】直线几何装饰线条，室内光影明暗层次，大型落地观叶绿植，金属摆件反光\n【画质修正】轻微四角暗角，无胶片颗粒，广角轻微桶形畸变，低锐化柔和空间质感\n【技术参数】广角镜头，平视正面，f/4.0，深景深全画面清晰，焦平面锁定沙发区域\n【负面标签】墙体扭曲变形，家具比例失调，画面模糊，色彩色差，多余杂物，落地窗强光过曝，角落死黑阴影"
        },
        {
            "category": "产品类",
            "natural": "(杰作:1.3),(最佳质量:1.2),(高分辨率:1.2),(8K:1.2),(超精细:1.2),产品摄影,(无线降噪耳机:1.3),黑色磨砂,金属质感,悬浮摆放,镜面反射,深蓝色背景,三点布光,主光左前,补光右侧,背光轮廓,45度俯视左偏移构图,主体占比68%,右侧留白,高对比度,科技感,(精致耳罩纹理:1.1),海绵透气孔,质感细腻,专业灯光,高端质感,无暗角;耳机变形,划痕杂乱,模糊,色差,多余线材,反光杂斑,过曝金属边缘",
            "structured": "【类别】产品类\n【质量标签】杰作，最佳质量，高分辨率，超精细，8K\n【构图布局】45度俯视左偏移构图，主体画面占比68%，右侧留白，1:1方形商业画幅\n【核心要素】\n  - 场景类型：专业商业摄影棚纯色背景\n  - 光线方案：三点布光，主光左前，柔光补光右侧，强背光轮廓光，硬小面积阴影，圆形高光光斑\n  - 色彩氛围：主色调深空蓝，辅色调哑光黑，冷白平衡，极高色彩对比度，中饱和度，金属银色高光反光\n【画面层级】前景镜面倒影，中景耳机产品主体，远景纯深蓝虚化背景\n【产品特征】\n  - 主体：无线降噪头戴耳机\n  - 材质：哑光黑色磨砂塑料，拉丝金属头梁，透气海绵耳罩\n  - 细节：细密耳罩纹理，圆形海绵透气孔，金属拉丝反光线条\n【姿态动作】耳机悬浮平放，耳罩微微向内倾斜\n【景别】产品标准特写，主体画面占比68%\n【细节元素】镜面地面清晰倒影，无多余杂物，金属边缘高光，塑料磨砂细腻肌理\n【画质修正】无暗角，零胶片颗粒，无镜头畸变，超高锐化产品细节\n【技术参数】45度俯视，标准定焦镜头，f/3.2，中等景深，焦平面锁定耳机耳罩区域\n【负面标签】耳机造型扭曲变形，表面杂乱划痕，画面模糊，色彩色差，多余线材，大面积杂斑反光，金属边缘强光过曝"
        }
    ]
}

IMAGE_REVERSE_TAGS_EN = {
    "name": "Image Tag Reverse Generator",
    "description": "As a professional SDXL tagging model prompt engineer, I automatically recognize image categories and generate precise English tag lists. My expertise covers photography terminology, art styles, color theory, composition, lens optics, human poses, material textures, SDXL weight syntax, and negative prompt engineering, enabling precise reproduction of original image composition, subject position, pose, color, lighting, lens blur, and spatial layers.",
    "input_template": "Step-by-step thinking: 1) Analyze image content, identify dominant visual elements, mark subject position, composition layout, foreground/midground/background hierarchy; 2) Choose the most appropriate category from: Landscape, Photography, Portrait, Illustration, IP, Cosplay, Game Character, Product, Architecture/Interior, Animal, Food, UI Interface, Fashion/Style, General; 3) If no match, create a suitable category name based on image content; 4) Distinguish primary/secondary objects, use SDXL weight syntax to differentiate tag priorities, generate {mode} tag list according to category-specific field structure; 5) Verify: 30-60 tags, no duplicates, no semantic redundancy, include mandatory quality tags, composition tags, lens tags, and generate matching negative tag strings.\n\nUser input: #\n\nRules: 1. Output only JSON, no extra text; 2. Total tags 30-60, no duplicates, no semantic redundancy; 3. Must include quality tags (masterpiece, best quality, high resolution, ultra-detailed, 8K); 4. Mandatory composition layout, subject position, and frame hierarchy tags; 5. Primary subject tags add (xxx:1.1~1.3) weight enhancement, secondary objects use [xxx:0.6~0.8] weakening; 6. Output matching negative tag strings simultaneously; 7. Strictly follow the field structure below.",
    "output_format_suffix": {
        "natural": "Comma-separated tag string with SDXL weights, ending with semicolon + comma-separated negative tag string.",
        "structured": "【Category】Category Name\n【Quality Tags】masterpiece, best quality, high resolution, ultra-detailed, 8K\n【Composition Layout】composition type, subject frame percentage, subject position, frame negative space, aspect ratio\n【Core Elements】\n  - Scene Type: scene description content\n  - Time/Lighting: time and lighting description content, shadow hardness, light spot shape, rim light intensity\n  - Color/Mood: dominant color, secondary color, white balance, color contrast, saturation gradient, ambient reflection color\n【Frame Hierarchy】foreground elements, midground subject, background\n【Character/Object Features】(auto-adapt by category, portrait/animal/product exclusive)\n【Pose/Movement】head turn direction, gaze direction, body twist, hand movements\n【Shot Type】shot type description (macro close-up/standard close-up/close-up with shoulder/medium shot/medium full shot/full body shot), subject frame percentage\n【Detail Elements】detail element description, material texture, roughness, reflection properties\n【Image Quality Correction】vignette, film grain, sharpening intensity, lens distortion, chromatic aberration control\n【Technical Parameters】lens and perspective description, aperture value, blur intensity, focal plane position\n【Negative Tags】comma-separated negative prompts to avoid frame defects, color shift, distortion, and unwanted objects"
    },
    "task_requirements": [
        "First identify image category, then output tags according to corresponding field group",
        "Must include masterpiece, best quality, high resolution, ultra-detailed, 8K and other quality tags",
        "Tags concise, comma separated within each field, total 30-60, automatically merge synonymous tags to avoid redundancy",
        "Field order can be adjusted, but field names must be exactly consistent, new fields cannot be deleted",
        "natural mode: output comma-separated tag string with SDXL weights, append semicolon-separated negative tags at the end; structured mode: output complete structured prompt (including composition, hierarchy, image quality, negative tag modules)",
        "Shot type judgment rules:\n  - Macro Close-up: captures only a tiny human body part, no complete face, fills the frame, extreme detail (single eye/lips/fingertips/skin texture/hair strands etc.), subject frame percentage 90%~100%\n  - Close-up: top of head to chin, complete face without shoulders, subject frame percentage 70%~90%\n  - Close-up with Shoulder: head + a small portion of shoulders, only a hint of shoulder line, subject frame percentage 60%~80%\n  - Medium Shot: top of head to waist/abdomen, cut off at waist/navel area, includes complete head shoulders chest waist, subject frame percentage 40%~65%\n  - Medium Full Shot: top of head to below knee/above ankle, cut off at ankle/calf mid-section, feet not fully visible, subject frame percentage 30%~50%\n  - Full Body Shot: complete head to toe full body, all limbs and feet included without cropping, subject frame percentage 20%~40%",
        "Composition mandatory requirements: Each image must be tagged with composition (rule of thirds/golden ratio/centered/left offset/right offset/symmetrical), subject frame percentage, frame negative space amount, aspect ratio (16:9/4:3/1:1/9:16/2.35:1)",
        "Weight rules: core subject (tag:1.2), secondary decorative objects [tag:0.7], environmental basic descriptions no weight",
        "Negative tags mandatory generation: deformed, facial distortion, color shift, severe distortion, extra limbs, blurry, low resolution, watermark, text, clutter, overexposed, dead black shadows"
    ],
    "constraints": {
        "max_tags": 60,
        "min_tags": 30,
        "no_duplicates": True,
        "exclude_abstract": True,
        "no_semantic_repeat": True,
        "must_include_composition_tags": True,
        "must_include_depth_layer_tags": True,
        "must_attach_negative_tags": True
    },
    "examples": [
        {
            "category": "Landscape",
            "natural": "(masterpiece:1.3),(best quality:1.2),(high resolution:1.2),(8K:1.2),(ultra-detailed:1.2),landscape photography,(snow-capped mountains:1.3),sea of clouds,canyon,sunrise,(golden hour:1.1),hard light,side backlight,cool tone,blue-white-gray palette,tranquil atmosphere,vast openness,aerial view,wide angle,telephoto lens,16:9 aspect ratio,rule of thirds,subject frame 35%,bottom negative space,pine trees,[morning mist:0.7],layered mountain peaks,shadow contrast,blue sky with white clouds,sky gradient,atmospheric perspective,foreground sharp background soft,moderate humidity,high visibility,morning fog,dawn light breaking through clouds,distinct layering,strong sense of depth,cinematic atmosphere,low film grain,no vignette;deformed,blurry,low resolution,watermark,text,extra mountains,overexposed sky,dead black shadows",
            "structured": "【Category】Landscape\n【Quality Tags】masterpiece, best quality, high resolution, ultra-detailed, 8K\n【Composition Layout】rule of thirds, subject frame percentage 35%, subject center-top, large bottom negative space, 16:9 wide aspect ratio\n【Core Elements】\n  - Scene Type: mountain scenery, snow-capped mountains, sea of clouds, canyon\n  - Time/Lighting: sunrise, golden hour, hard light, side backlight, moderate shadow hardness, circular light spots, weak rim light\n  - Color/Mood: dominant color cool blue, secondary color white-gray, standard white balance, low color contrast, low saturation, sky pale gold ambient reflection\n【Frame Hierarchy】foreground: low pine trees, midground: layered mountains, background: cloud sea skyline\n【Pose/Movement】none\n【Shot Type】panorama long shot, subject frame percentage 35%\n【Detail Elements】pine trees, morning mist, layered mountain peaks, light and shadow contrast, rock matte texture\n【Image Quality Correction】low film grain, no vignette, zero lens distortion, light sharpening\n【Technical Parameters】aerial view, wide angle, telephoto lens, f/8, weak blur, focal plane locked on snow-capped main peak\n【Negative Tags】deformed, blurry, low resolution, watermark, text, extra mountains, overexposed sky, dead black shadows, color banding"
        },
        {
            "category": "Portrait",
            "natural": "(masterpiece:1.3),(best quality:1.2),(high resolution:1.2),(8K:1.2),(ultra-detailed:1.2),portrait photography,(Asian female:1.3),age 25,(long black hair:1.2),almond-shaped eyes,(gentle smile:1.2),natural skin tone,(light beige knit sweater:1.1),lace-trimmed cuffs,[cafe window seat:0.8],afternoon sunlight,soft side lighting,low saturation,warm tone,centered composition,subject frame 60%,left-right small negative space,eye-level perspective,medium shot,35mm prime,f/1.8,shallow depth of field,cozy atmosphere,(quietly reading:1.2),book,[coffee cup:0.7],wooden table surface,[sheer curtain:0.7],slight vignette,low film grain;facial distortion,deformed hands,blurry,color shift,watermark,extra people,overexposed face,dead black shadows",
            "structured": "【Category】Portrait\n【Quality Tags】masterpiece, best quality, high resolution, ultra-detailed, 8K\n【Composition Layout】centered composition, subject frame percentage 60%, left-right small negative space, 4:3 aspect ratio\n【Core Elements】\n  - Scene Type: cafe interior\n  - Time/Lighting: afternoon natural light, soft side lighting, soft shadows, long window light spots, weak rim light\n  - Color/Mood: dominant color warm beige, secondary color light brown, warm white balance, low color contrast, medium-low saturation, curtain soft light reflection\n【Frame Hierarchy】foreground: coffee cup, midground: person subject, background: blurred outdoor greenery behind window\n【Character/Object Features】\n  - Appearance: Asian female, age 25, long black hair, almond-shaped eyes, gentle smile, natural skin texture\n  - Clothing: light beige knit sweater, lace-trimmed cuffs, matte fabric texture\n  - Pose: quietly reading, right hand turning pages, head slightly left tilted, gaze downward toward book\n【Pose/Movement】head left tilted 15°, gaze downward, right hand raised turning pages, torso slightly forward leaning\n【Shot Type】Medium Shot: top of head to waist, complete head shoulders chest waist, cut off at waist/navel area, subject frame percentage 60%\n【Detail Elements】paper book, ceramic coffee cup, wood grain table surface, semi-transparent sheer curtain, floating dust particles in window light\n【Image Quality Correction】slight vignette, low film grain, no lens distortion, medium skin sharpening\n【Technical Parameters】eye-level perspective, medium shot, 35mm prime, f/1.8, strong shallow depth of field, focal plane locked on person's face\n【Negative Tags】facial distortion, deformed hands, blurry, color shift, watermark, extra people, overexposed face, dead black shadows, missing limbs"
        },
        {
            "category": "Animal",
            "natural": "(masterpiece:1.3),(best quality:1.2),(high resolution:1.2),(8K:1.2),(ultra-detailed:1.2),animal photography,(orange tabby cat:1.3),(emerald green eyes:1.2),sitting pose,(fluffy fur:1.2),indoor windowsill,natural sunlight,warm lighting,soft diffused light,high contrast,left offset composition,subject frame 70%,right negative space,close-up shot,50mm macro,shallow depth of field,detailed fur texture,(sharp whiskers:1.1),expressive eyes,[windowsill potted plant:0.7],wooden texture,natural light source,cozy atmosphere,(cute alert expression:1.2),low film grain;deformed facial features,twisted paws,blurry,color shift,extra clutter,overexposed fur,dead black shadows",
            "structured": "【Category】Animal\n【Quality Tags】masterpiece, best quality, high resolution, ultra-detailed, 8K\n【Composition Layout】left offset composition, subject frame percentage 70%, large right negative space, 1:1 square aspect ratio\n【Core Elements】\n  - Scene Type: indoor windowsill\n  - Time/Lighting: natural window light, soft side lighting, soft shadows, circular sunlight spots, medium rim light\n  - Color/Mood: dominant color warm orange, secondary color wood brown, warm white balance, high color contrast, medium saturation, green plant light reflection\n【Frame Hierarchy】foreground: cat paw fur, midground: cat subject, background: blurred windowsill plants\n【Character/Object Features】\n  - Species: orange tabby cat\n  - Appearance: emerald green eyes, fluffy double-layer fur, individual whiskers visible, short fur texture\n  - Pose: upright sitting, alert forward, gaze directly at camera\n【Pose/Movement】head facing camera, gaze level forward, front paws tucked to chest, body straight\n【Shot Type】Close-up with Shoulder, subject frame percentage 70%\n【Detail Elements】windowsill small potted plant, wood windowsill texture, circular sunlight spots, fur highlight reflections\n【Image Quality Correction】low film grain, no vignette, zero distortion, high fur sharpening detail\n【Technical Parameters】close-up shot, 50mm macro, f/2.0, strong shallow depth of field, focal plane locked on cat's face\n【Negative Tags】deformed facial features, twisted paws, blurry, color shift, extra clutter, overexposed fur, dead black shadows, multiple cats"
        },
        {
            "category": "Food",
            "natural": "(masterpiece:1.3),(best quality:1.2),(high resolution:1.2),(8K:1.2),(ultra-detailed:1.2),food photography,(strawberry cake:1.3),cream decoration,(fresh strawberries:1.2),wooden serving tray,white ceramic plate,afternoon sunlight,soft backlighting,warm tone,high saturation,45-degree overhead symmetrical composition,subject frame 65%,even negative space,shallow depth of field,beautiful bokeh,cake crumb texture,(smooth cream:1.1),(strawberry water droplets:1.1),warm inviting atmosphere,appetizing presentation,baked texture,dessert,afternoon tea,[coffee pairing:0.7],wooden table texture,no vignette;melting cream,rotten strawberries,blurry,color shift,extra tableware,overexposed cake surface",
            "structured": "【Category】Food\n【Quality Tags】masterpiece, best quality, high resolution, ultra-detailed, 8K\n【Composition Layout】45-degree overhead symmetrical composition, subject frame percentage 65%, even negative space around, 4:3 aspect ratio\n【Core Elements】\n  - Scene Type: table still life\n  - Time/Lighting: afternoon sunlight, soft backlighting, soft shadows, long light spots, strong rim light outlining food edges\n  - Color/Mood: dominant color warm pink-white, secondary color bright red, warm white balance, high contrast, high saturation, wood warm brown reflection\n【Frame Hierarchy】foreground: strawberry water droplets, midground: cake subject, background: blurred coffee cup table surface\n【Character/Object Features】\n  - Subject: strawberry cream cake, piped cream decoration, water droplets on fresh strawberry flesh\n  - Texture: sponge cake porous texture, smooth matte cream, translucent strawberry skin droplets\n【Pose/Movement】none\n【Shot Type】Still life standard close-up, subject frame percentage 65%\n【Detail Elements】wood serving tray, white ceramic plate, glass coffee cup, wood table texture, cream piping patterns\n【Image Quality Correction】no vignette, extremely low film grain, no distortion, medium food detail sharpening\n【Technical Parameters】45-degree overhead, 50mm prime, f/2.2, shallow depth of field, focal plane locked on top strawberry\n【Negative Tags】melting cream, rotten black strawberries, blurry, color shift, extra tableware, overexposed cake surface, messy table clutter"
        },
        {
            "category": "Architecture/Interior",
            "natural": "(masterpiece:1.3),(best quality:1.2),(high resolution:1.2),(8K:1.2),(ultra-detailed:1.2),interior design photography,modern minimalist,(living room:1.3),floor-to-ceiling windows,natural light,white walls,wooden furniture,(gray sofa:1.2),green plant decoration,open layout,spacious room,light and shadow play,soft diffused lighting,cool tone,clean aesthetic,symmetrical centered composition,subject frame 40%,top-bottom negative space,wide-angle lens,strong perspective,Nordic design style,cozy atmosphere,geometric lines,[indoor plants:0.7],decorative ornaments,slight vignette;warped walls,deformed furniture,blurry,color shift,extra clutter,overexposed windows,dead black corner shadows",
            "structured": "【Category】Architecture/Interior\n【Quality Tags】masterpiece, best quality, high resolution, ultra-detailed, 8K\n【Composition Layout】symmetrical centered composition, subject frame percentage 40%, large top-bottom negative space, 16:9 wide aspect ratio\n【Core Elements】\n  - Scene Type: modern minimalist Nordic living room\n  - Time/Lighting: all-day even natural window light, extremely soft shadows, large area diffuse reflection spots, weak rim light\n  - Color/Mood: dominant color cool white, secondary color wood gray, cool white balance, low contrast, low saturation, green plant light reflection\n【Frame Hierarchy】foreground: coffee table decorations, midground: sofa furniture subject, background: floor-to-ceiling window blurred outdoor view\n【Character/Object Features】\n  - Layout: open spacious layout, horizontally extended space\n  - Materials: matte white walls, wood matte furniture, fabric gray sofa, glass transparent floor-to-ceiling windows\n  - Decor: floor plants, minimalist metal table decorations\n【Pose/Movement】none\n【Shot Type】panorama space view, subject frame percentage 40%\n【Detail Elements】straight geometric lines, interior light and shadow layers, large floor plants, metal ornament reflections\n【Image Quality Correction】slight corner vignette, no film grain, wide-angle slight barrel distortion, low sharpening soft space texture\n【Technical Parameters】wide-angle lens, front eye-level, f/4.0, deep depth of field full frame sharp, focal plane locked on sofa area\n【Negative Tags】warped walls, deformed furniture proportions, blurry, color shift, extra clutter, overexposed window light, dead black corner shadows"
        },
        {
            "category": "Product",
            "natural": "(masterpiece:1.3),(best quality:1.2),(high resolution:1.2),(8K:1.2),(ultra-detailed:1.2),product photography,(wireless noise-canceling headphones:1.3),black matte finish,brushed metal texture,floating display,mirror surface reflection,deep blue background,three-point lighting,key light front-left,fill light right,back rim light,45-degree overhead left offset composition,subject frame 68%,right negative space,high contrast,modern tech feel,(intricate earcup texture:1.1),foam cushion vents,detailed texture,professional studio lighting,premium quality,no vignette;deformed headphones,scratch marks,blurry,color shift,extra cables,glare spots,overexposed metal edges",
            "structured": "【Category】Product\n【Quality Tags】masterpiece, best quality, high resolution, ultra-detailed, 8K\n【Composition Layout】45-degree overhead left offset composition, subject frame percentage 68%, right negative space, 1:1 square commercial aspect ratio\n【Core Elements】\n  - Scene Type: professional commercial studio solid color background\n  - Lighting Scheme: three-point lighting, key light front-left, soft fill light right, strong back rim light, hard small area shadows, circular highlight spots\n  - Color/Mood: dominant color deep space blue, secondary color matte black, cool white balance, extremely high color contrast, medium saturation, metal silver highlight reflection\n【Frame Hierarchy】foreground: mirror reflection, midground: headphone product subject, background: pure deep blue blurred background\n【Character/Object Features】\n  - Subject: wireless noise-canceling over-ear headphones\n  - Material: matte black plastic, brushed metal headband, breathable foam ear cushions\n  - Details: intricate earcup texture, circular foam vents, metal brushed reflection lines\n【Pose/Movement】headphones floating flat, earcups slightly inward tilted\n【Shot Type】product standard close-up, subject frame percentage 68%\n【Detail Elements】mirror floor clear reflection, no extra clutter, metal edge highlights, plastic matte fine texture\n【Image Quality Correction】no vignette, zero film grain, no lens distortion, ultra-high product detail sharpening\n【Technical Parameters】45-degree overhead, standard prime lens, f/3.2, medium depth of field, focal plane locked on headphone earcup area\n【Negative Tags】deformed headphones, messy surface scratches, blurry, color shift, extra cables, large glare spots, overexposed metal edges"
        }
    ]
}

IMAGE_REVERSE_DESCRIBE_ZH = {
    "name": "图像反推描述器",
    "description": "作为专业的图像分析专家，我将自动识别图像类别并生成专业、流畅的自然语言描述，适用于Flux、Z-Image、Qwen-Image、Krea等主流自然语言图像生成模型。我的专业知识涵盖摄影术语、艺术风格、灯光设计、色彩理论、画面构图分析、主体位置识别、肢体姿态拆解、物体遮挡层级、镜头光学画质、画面瑕疵识别和视觉视角推断，精准复刻原图构图、动作、色彩、镜头质感，控制生成与输入图高度一致。",
    "input_template": "逐步思考：1）分析图像内容，识别关键视觉元素、肢体动作、物体遮挡关系、镜头光学质感与艺术风格；2）从以下类别中选择最合适的：风景类、摄影类、人像类、插画类、IP类、cosplay类、游戏角色类、产品类、建筑室内类、动物类、美食类、UI界面类、时尚穿搭类、通用类；3）分析画面构图（三分法/对称/对角线/框架/中心/三角形等）、主体坐标（水平+垂直百分比）、画面上下左右留白、边缘裁切物体；4）拆解主体肢体姿态：头部偏转角度、视线方向、手部/四肢动作、躯干扭转角度；5）推断视角类型（广角/标准/长焦/超长焦）、景深效果（浅/中/深）、镜头光学细节（暗角、胶片颗粒、畸变、锐化）；6）梳理前中远景物体互相遮挡、重叠区域；7）区分主辅色彩、白平衡、高光阴影状态，记录画面瑕疵（水印、文字、多余杂物）；8）如未匹配，创建合适的类别名称；9）按类别字段生成{mode}描述，确保所有视觉元素以自然语言连贯表达，规避原图不存在的畸形、多余物体，符合物理逻辑；10）验证描述专业细致，覆盖构图、姿态、光影、遮挡、画质五大维度，只聚焦可视觉化细节，不包含抽象情感或故事。\n\n用户输入：#\n\n描述要点：根据类别输出对应字段，必须包含构图方式、主体位置、留白裁切、视角类型、景深效果、肢体姿态、物体遮挡、光线色彩、镜头光学细节和材质质感，用语流畅，避免数据化参数。natural模式强制分多段落分层描述（主体姿态、构图与遮挡、光线与色彩、画质细节、氛围质感），增强可读性，完整覆盖全部画面维度。",
    "output_format_suffix": {
        "natural": "多段式自然段落，分层覆盖主体肢体姿态、构图留白与物体遮挡、光线色彩层次、镜头光学画质、氛围材质细节，包含构图方式、主体坐标、留白裁切、视角类型、景深、肢体动作、物体遮挡关系、白平衡、暗角/颗粒/畸变等光学特征，语言流畅专业。固定分段逻辑：第一段主体与肢体动作；第二段构图、留白、物体遮挡；第三段光线、白平衡、色彩调性；第四段镜头画质与材质细节；第五段整体氛围。",
        "structured": "【类别】类别名称\n【画面构图】\n  - 构图方式：构图类型（三分法/对称/对角线/框架/中心/三角形等）\n  - 主体位置：水平位置+垂直位置（百分比表示，如水平50%居中，垂直40%偏上）\n  - 画面比例：画面宽高比（16:9/9:16/4:3等）\n  - 留白与裁切：上下左右留白占比、画面边缘裁切物体\n【景别】\n  - 景别类型：微距特写/标准特写/肩特写/七分人像/九分人像/全景人像（无人物时可省略）\n  - 取景范围：描述取景范围\n  - 拍到部位：描述拍到部位（如头顶至胸部）\n  - 画面特征：描述画面构图特征\n【视觉参数】\n  - 视角类型：广角（透视夸张）/标准（平实视角）/长焦（空间压缩）/超长焦（强烈压缩）\n  - 视角效果：描述视角带来的视觉感受\n  - 景深效果：浅景深（背景虚化）/中景深（部分清晰）/深景深（全景清晰）\n  - 光学画质细节：暗角强弱、胶片颗粒浓度、镜头畸变类型、画面锐化程度、色散状态\n【场景描述】\n  - 地理地貌：场景类型和地貌特征\n  - 天气光线：天气状况与光线方向、软硬、高光/阴影状态、轮廓光强弱、光斑形态\n  - 色彩调性：主辅色彩占比、冷暖倾向、白平衡、饱和度、有无色彩断层、环境反光色\n  - 空间层次：前景/中景/背景的内容与互相遮挡重叠关系\n  - 风格流派：（可选）艺术风格或设计流派（如北欧风、赛博朋克、印象派等）\n【肢体姿态】（无人物/动物可标注无）\n  - 头部状态：头部偏转角度、视线朝向\n  - 躯干四肢：躯干扭转、手臂/爪子摆放、手部动作细节\n  - 整体体态：站姿/坐姿/趴卧等基础体态\n【氛围意境】氛围与意境关键词（简洁）\n【细节质感】突出材质、纹理、表面特征等细节\n【画面瑕疵】原图无水印、无文字、无多余杂物、无畸形扭曲物体（记录原图存在的瑕疵，不存在则标注无）"
    },
    "task_requirements": [
        "先识别图像类别，再按对应字段输出描述",
        "描述专业细致，聚焦视觉可呈现元素，不使用抽象情感或故事叙述",
        "必须分析构图方式并写出具体类型",
        "必须给出主体位置（水平+垂直百分比）、画面留白与边缘裁切内容",
        "必须拆解完整肢体姿态：头部偏转、视线、四肢手部动作",
        "必须梳理前中远景物体遮挡、重叠关系",
        "必须推断视角类型（广角/标准/长焦/超长焦，不写具体焦距）",
        "必须描述景深效果（浅/中/深，不写光圈值）",
        "必须记录镜头光学画质细节：暗角、胶片颗粒、畸变、锐化",
        "必须判断景别类型（无人物时可省略相关人物字段）",
        "人物与物品互动需符合现实物理逻辑，规避原图不存在的畸形肢体、多余物体",
        "natural模式：强制分5段分层描述，完整覆盖姿态、构图遮挡、光影色彩、画质、质感氛围；structured模式：输出完整结构化全部字段",
        "总字数控制在300~600字之间（自然模式），上限不超过800字"
    ],
    "constraints": {
        "max_length": 800,
        "must_record_occlusion": True,
        "must_record_body_pose": True,
        "must_record_optical_detail": True
    },
    "examples": [
        {
            "category": "风景类",
            "natural": "采用航拍广角视角，无镜头畸变，低胶片颗粒，无暗角，深景深画面全程清晰。主体为连绵雪山主峰，山体完整无裁切，山谷云海铺展，无人物、动物肢体。\n\n画面采用三分法构图，主峰落在右上方三分交点；主体坐标水平70%偏右、垂直60%偏上，画面顶部少量留白，底部大面积留白，前景松树剪影遮挡山脚山体，中景云海完全覆盖峡谷，远景天际线无遮挡。16:9宽幅画面，边缘无裁切物体。\n\n日出金色时刻硬光从左侧斜射，高光集中在主峰顶端无溢色，山谷阴影呈冷蓝色无死黑区域，弱金色轮廓光包裹山体边缘，光斑呈长条放射状；白平衡偏暖，主色调白、冷蓝、暖金，白色雪峰占画面60%，饱和度中等，无色彩断层，山体反射淡金色环境反光。大气透视拉开空间层次，能见度极高。\n\n镜头无暗角，极低胶片颗粒，画面中度锐化，无色散；雪峰岩石纹理清晰，松树剪影轮廓锐利，云海拥有细腻丝绒质感。\n\n整体氛围宁静壮丽，充满雪山旷野的神圣辽阔感，原图无水印、无多余杂物、无畸形扭曲元素。",
            "structured": "【类别】风景类\n【画面构图】\n  - 构图方式：三分法，主峰位于右上方交点，前景松树剪影作为平衡遮挡元素\n  - 主体位置：水平70%偏右，垂直60%偏上\n  - 画面比例：16:9\n  - 留白与裁切：顶部少量留白，底部大面积留白，画面边缘无裁切物体\n【景别】\n  - 景别类型：远景（无人物）\n  - 取景范围：涵盖前景、中景、远景，层次丰富\n  - 拍到部位：无人物\n  - 画面特征：宽广场景，纵深强烈，前景松树遮挡山脚山体\n【视觉参数】\n  - 视角类型：广角（透视夸张）\n  - 视角效果：增强山体雄伟感，拉伸空间纵深\n  - 景深效果：深景深，从前到后全部清晰\n  - 光学画质细节：无暗角，低胶片颗粒，无镜头畸变，中度锐化，无色散\n【场景描述】\n  - 地理地貌：连绵雪山群峰，峡谷间铺展云海\n  - 天气光线：日出金色时刻，硬光左侧斜射，高光无溢色，山谷柔和阴影无死黑，弱轮廓光，长条放射光斑\n  - 色彩调性：主色白、冷蓝、暖金，雪峰占画面60%，白平衡偏暖，饱和度中等，无色彩断层，山体反射淡金色环境反光\n  - 空间层次：前景：松树暗部（遮挡山脚）；中景：云海（完全覆盖峡谷）；远景：雪山主峰与淡紫天空（无遮挡）\n  - 风格流派：写实风光摄影\n【肢体姿态】无\n【氛围意境】宁静、壮丽、神圣、辽阔\n【细节质感】雪峰表面岩石纹理清晰，松树剪影轮廓分明，云海呈现丝绒细腻质感\n【画面瑕疵】无水印、无文字、无多余杂物、无畸形扭曲物体"
        },
        {
            "category": "人像类",
            "natural": "标准平视视角，轻微四角暗角，低胶片颗粒，中度锐化，浅景深虚化背景。25岁亚洲女性为画面主体，头部轻微向左偏转15°，视线向下落在手中书页；坐姿，躯干微微前倾，右手抬起翻书，左手托住书本底部，完整呈现上半身肢体动作。\n\n中心对称构图，人物主体坐标水平50%居中、垂直50%居中，画面左右小幅留白，上下均衡留白；前景咖啡杯局部遮挡书本右下角，人物无遮挡，背景薄纱窗帘完整在人物后方无重叠。3:2画幅，画面无裁切人体部位。\n\n午后右前方柔和侧光，无生硬阴影，高光落在脸颊无溢色，无死黑阴影，微弱轮廓光勾勒发丝，光斑为长条窗纹状；暖调白平衡，主色米色、原木棕，肤色占画面40%，低饱和度，无色彩断层，窗帘柔光反射浅米环境色。空间层次清晰，前景咖啡杯、中景人物、背景虚化街道。\n\n镜头轻微暗角，低胶片颗粒，无镜头畸变，皮肤中度锐化保留肌理；针织毛衣纹理、泛黄书页粗糙质感、陶瓷咖啡杯细腻釉面、原木桌面年轮纹路完整呈现。\n\n整体氛围安静温馨，充满松弛的下午茶生活感，原图无水印、无多余人物、无畸形五官与扭曲手部。",
            "structured": "【类别】人像类\n【画面构图】\n  - 构图方式：中心构图，主体居中，书本与咖啡杯构成三角稳定布局，咖啡杯局部遮挡书本\n  - 主体位置：水平50%居中，垂直50%居中\n  - 画面比例：3:2\n  - 留白与裁切：左右小幅留白，上下均衡留白，无裁切人体部位\n【景别】\n  - 景别类型：七分人像（头顶至腰部）\n  - 取景范围：从头顶到腰部，完整头部、肩膀、胸部及腰线\n  - 拍到部位：头部、肩颈、腰腹、双手\n  - 画面特征：上半身为核心主体，咖啡馆环境作为虚化背景\n【视觉参数】\n  - 视角类型：标准视角（平实自然）\n  - 视角效果：符合人眼视觉，无夸张透视畸变\n  - 景深效果：浅景深，背景完全虚化，人物主体清晰锐利\n  - 光学画质细节：轻微四角暗角，低胶片颗粒，无镜头畸变，中度锐化，无色散\n【场景描述】\n  - 地理地貌：咖啡馆室内窗边\n  - 天气光线：午后自然光，柔和侧光从右前方洒落，无高光溢色、无死黑阴影，弱发丝轮廓光，长条窗纹光斑\n  - 色彩调性：主色调暖米、原木棕，肤色占画面40%，暖白平衡，低饱和度，无色彩断层，窗帘浅米柔光反光\n  - 空间层次：前景：桌面咖啡杯（遮挡书本右下角）；中景：人物主体（无遮挡）；背景：薄纱窗帘与窗外虚化街道（无重叠遮挡）\n  - 风格流派：生活纪实自然光摄影\n【肢体姿态】\n  - 头部状态：头部左偏15°，视线向下看向书页\n  - 躯干四肢：躯干微微前倾，右手抬起翻页，左手托住书本底部\n  - 整体体态：端正坐姿\n【氛围意境】安静、温馨、松弛、惬意\n【细节质感】毛衣针织纹理清晰，书页泛黄粗糙，咖啡杯陶瓷细腻釉面，原木桌面年轮纹理完整\n【画面瑕疵】无水印、无文字、无多余人物、无畸形五官、无扭曲手部肢体"
        },
        {
            "category": "动物类",
            "natural": "标准平视特写视角，无暗角，低胶片颗粒，高锐化突出毛发，浅景深虚化背景绿植。橙色虎斑猫端坐窗台，头部正对镜头无偏转，视线平视前方；前爪收拢于胸前，身体挺直，胡须、耳毛完整舒展，肢体无遮挡。\n\n三分法构图，猫眼落在横纵三分交点；主体坐标水平50%居中、垂直40%偏下，画面右侧大面积留白，上下小幅留白，背景窗台绿植完全在猫咪后方无重叠遮挡。4:3方形画幅，无裁切猫身部位。\n\n左侧窗户柔和自然光，圆形光斑落在猫背，高光柔和无溢色，身体左侧浅淡阴影无死黑，中度轮廓光勾勒毛发边缘；暖调白平衡，主色暖橙、原木棕、草绿，猫身毛发占画面70%，饱和度适中，无色彩断层，绿植反射淡绿色环境反光。\n\n镜头无暗角，低胶片颗粒，无畸变，毛发高锐化；虎斑条纹层次分明，单根毛发丝缕可见，胡须纤细通透，绿植叶片油亮光滑。\n\n整体氛围温馨治愈，猫咪神态灵动警觉，原图无水印、无多余杂物、无畸形五官扭曲猫爪。",
            "structured": "【类别】动物类\n【画面构图】\n  - 构图方式：中心偏下构图，猫眼位于三分法交点，绿植后置无遮挡主体\n  - 主体位置：水平50%居中，垂直40%偏下\n  - 画面比例：4:3\n  - 留白与裁切：右侧大面积留白，上下小幅留白，无裁切猫身部位\n【景别】\n  - 景别类型：标准特写（头部至前胸）\n  - 取景范围：猫头部及前胸完整躯体\n  - 拍到部位：头部、双耳、前胸、收拢前爪\n  - 画面特征：猫面部为视觉核心，窗台绿植作为虚化背景\n【视觉参数】\n  - 视角类型：标准视角\n  - 视角效果：无透视畸变，真实还原猫咪体态比例\n  - 景深效果：浅景深，背景绿植完全虚化，猫身毛发极致清晰\n  - 光学画质细节：无暗角，低胶片颗粒，无镜头畸变，毛发高锐化，无色散\n【场景描述】\n  - 地理地貌：居家室内木质窗台\n  - 天气光线：左侧自然窗光，圆形阳光光斑，柔和高光无溢色，浅淡软阴影，中度毛发轮廓光\n  - 色彩调性：主色调暖橙、原木棕、草绿，猫身占画面70%，暖白平衡，饱和度适中，无色彩断层，绿植淡绿色反光\n  - 空间层次：前景：猫咪主体（无遮挡）；背景：窗台多肉绿植（后置无重叠遮挡）\n  - 风格流派：自然光宠物写实摄影\n【肢体姿态】\n  - 头部状态：头部无偏转，视线平视镜头正前方\n  - 躯干四肢：躯干挺直，双前爪收拢贴于胸前，四肢无交叉遮挡\n  - 整体体态：端正警觉坐姿\n【氛围意境】温馨、治愈、灵动、柔和\n【细节质感】虎斑条纹层次清晰，单根毛发丝缕分明，胡须纤细通透，绿植叶片油亮光滑\n【画面瑕疵】无水印、无文字、无多余杂物、无畸形五官、无扭曲猫爪"
        },
        {
            "category": "美食类",
            "natural": "45度俯视标准视角，无暗角，极低胶片颗粒，中度锐化，浅景深虚化桌面边缘。草莓奶油蛋糕为核心主体，静物无肢体动作，完整放置于白色餐盘内，无物体遮挡蛋糕主体。\n\n对角线构图，蛋糕主体坐标水平60%偏右、垂直50%居中，画面四周均匀留白，餐盘完整入镜无裁切；前景蛋糕水珠无遮挡奶油表层，背景咖啡杯后置虚化无重叠。1:1方形画幅。\n\n右上方午后柔和逆光，长条轮廓光勾勒蛋糕边缘，草莓表面高光透亮无溢色，阴影柔和无死黑；暖白平衡，主色奶白、鲜红、原木棕，蛋糕占画面65%，高饱和度，无色彩断层，木质托盘反射暖棕反光。\n\n镜头无暗角，几乎无胶片颗粒，无畸变，食物细节中度锐化；海绵蛋糕多孔纹理、丝滑哑光奶油、草莓表面晶莹水珠、实木托盘质朴木纹清晰可见。\n\n整体氛围香甜治愈，充满下午茶舒适氛围感，原图无水印、无腐烂水果、无多余杂乱餐具。",
            "structured": "【类别】美食类\n【画面构图】\n  - 构图方式：对角线构图，蛋糕主体置于中心偏右，草莓形成对角线视觉引导，无物体遮挡蛋糕本体\n  - 主体位置：水平60%偏右，垂直50%居中\n  - 画面比例：1:1\n  - 留白与裁切：画面四周均匀留白，餐盘完整入镜无裁切边缘\n【景别】\n  - 景别类型：微距静物特写\n  - 取景范围：餐盘内蛋糕及周边装饰点缀\n  - 拍到部位：完整蛋糕、餐盘、局部托盘\n  - 画面特征：俯视平面展示，食物细节完整暴露\n【视觉参数】\n  - 视角类型：标准俯视视角\n  - 视角效果：平坦展示桌面静物，无透视变形\n  - 景深效果：浅景深，桌面边缘背景虚化，蛋糕主体清晰锐利\n  - 光学画质细节：无暗角，极低胶片颗粒，无镜头畸变，中度锐化，无色散\n【场景描述】\n  - 地理地貌：居家餐桌静物场景\n  - 天气光线：午后柔和逆光，长条轮廓光勾勒食物边缘，草莓透亮高光无溢色，柔和软阴影无死黑\n  - 色彩调性：主色调奶白、鲜红、原木棕，蛋糕占画面65%，暖白平衡，高饱和度，无色彩断层，托盘暖棕色环境反光\n  - 空间层次：前景：蛋糕、草莓水珠（无遮挡）；背景：虚化咖啡杯、米白桌布（后置无重叠）\n  - 风格流派：明亮清新商业美食摄影\n【肢体姿态】无\n【氛围意境】香甜、治愈、闲适、下午茶氛围感\n【细节质感】海绵蛋糕多孔细密纹理，哑光丝滑奶油，草莓表皮晶莹水珠，实木托盘质朴粗糙木纹\n【画面瑕疵】无水印、无文字、无腐烂草莓、无多余杂乱餐具、无融化变形奶油"
        },
        {
            "category": "建筑室内类",
            "natural": "广角正面平视视角，轻微桶形畸变，无暗角，零胶片颗粒，低锐化柔和空间质感，深景深全屋清晰。现代简约客厅，无人物动物肢体，灰色布艺沙发为画面核心主体，茶几、绿植完整摆放于沙发前方，无互相遮挡。\n\n对称居中构图，沙发主体坐标水平50%居中、垂直50%居中，画面上下大面积留白，左右均衡留白；前景茶几完整在沙发前方，背景落地窗无物体遮挡，16:10宽幅，无裁切家具边缘。\n\n全屋均匀柔和漫射自然光，无强烈高光与死黑阴影，弱漫反射轮廓光；冷调白平衡，主色哑光白、浅灰、原木色，沙发布艺占画面40%，低饱和度，无色彩断层，绿植反射淡绿色柔光。空间纵深层次分明，前后物体无穿插遮挡。\n\n广角轻微桶形畸变，无暗角，无胶片颗粒，空间低锐化柔和质感；哑光墙面细腻涂料、布艺沙发柔软肌理、木地板清晰年轮、绿植斑驳光影完整呈现。\n\n整体氛围宁静通透，北欧简约松弛感，原图无水印、无变形墙体、无多余杂乱摆件。",
            "structured": "【类别】建筑室内类\n【画面构图】\n  - 构图方式：对称居中构图，沙发与茶几居中，两侧落地窗装饰平衡画面，物体无互相遮挡\n  - 主体位置：水平50%居中，垂直50%居中\n  - 画面比例：16:10\n  - 留白与裁切：上下大面积留白，左右均衡留白，家具完整无裁切边缘\n【景别】\n  - 景别类型：室内全景（无人物）\n  - 取景范围：完整客厅全屋空间\n  - 拍到部位：全屋家具、落地窗、墙面装饰、落地绿植\n  - 画面特征：横向开阔空间，广角拉伸纵深透视感\n【视觉参数】\n  - 视角类型：广角（透视夸张）\n  - 视角效果：拉伸横向空间，放大客厅开阔感，轻微桶形畸变\n  - 景深效果：深景深，全屋前景至背景全部清晰可见\n  - 光学画质细节：无暗角，零胶片颗粒，轻微桶形广角畸变，空间低锐化，无色散\n【场景描述】\n  - 地理地貌：现代北欧简约居家客厅\n  - 天气光线：全天均匀漫射自然光，无硬高光、无死黑角落阴影，弱漫反射轮廓光铺满全屋\n  - 色彩调性：主色调哑光冷白、浅灰、原木色，布艺沙发占画面40%，冷白平衡，低饱和度，无色彩断层，绿植淡绿色环境反光\n  - 空间层次：前景：灰色布艺沙发；中景：茶几、落地绿植（无遮挡沙发）；背景：落地窗、白色墙面（无遮挡）\n  - 风格流派：北欧极简室内设计摄影\n【肢体姿态】无\n【氛围意境】宁静、通透、舒适、松弛简约\n【细节质感】墙面哑光细腻涂料，沙发柔软布艺肌理，木地板清晰年轮纹理，绿植斑驳透光叶片\n【画面瑕疵】无水印、无文字、无扭曲变形墙体、无多余杂乱摆件、无过曝落地窗光斑"
        },
        {
            "category": "产品类",
            "natural": "45度俯视标准视角，无暗角，零胶片颗粒，超高锐化突出产品细节，浅景深虚化深蓝背景。无线降噪头戴耳机悬浮摆放，无肢体动作，镜面倒影完整位于耳机下方，无物体遮挡耳机主体。\n\n中心对称构图，耳机主体坐标水平50%居中、垂直50%居中，画面右侧小幅留白，上下均衡留白，1:1方形商业画幅，产品完整无裁切。\n\n专业影棚三点布光，左前方主光打出金属高光无溢色，右侧柔光补光消除硬阴影，强背光勾勒耳机轮廓，圆形高光光斑落在金属头梁；冷调白平衡，主色深空深蓝、哑光炭黑、金属银，耳机占画面68%，高对比度，中等饱和度，无色彩断层，镜面反射深蓝环境反光。\n\n镜头无暗角，零胶片颗粒，无畸变，产品超高锐化；磨砂塑料细腻颗粒、海绵透气孔洞、金属拉丝细密纹路、镜面锐利倒影完整呈现。\n\n整体氛围高端冷静，充满科技极简商业质感，原图无水印、无杂乱划痕、无多余线材、无变形耳机结构。",
            "structured": "【类别】产品类\n【画面构图】\n  - 构图方式：中心对称构图，耳机完整居中，下方镜面倒影辅助平衡画面，无物体遮挡耳机本体\n  - 主体位置：水平50%居中，垂直50%居中\n  - 画面比例：1:1\n  - 留白与裁切：右侧小幅留白，上下均衡留白，耳机完整无裁切边缘\n【景别】\n  - 景别类型：产品全身特写\n  - 取景范围：完整耳机机身+底部局部镜面倒影\n  - 拍到部位：头梁、耳罩、海绵耳垫、完整机身轮廓、镜面倒影\n  - 画面特征：45度俯视立体展示产品全部外观细节\n【视觉参数】\n  - 视角类型：标准45度俯视视角\n  - 视角效果：立体展示产品三维形态，无透视变形扭曲\n  - 景深效果：浅景深，深蓝色背景完全虚化，耳机产品极致锐利清晰\n  - 光学画质细节：无暗角，零胶片颗粒，无镜头畸变，产品超高锐化，无色散\n【场景描述】\n  - 地理地貌：纯色渐变商业摄影棚台面\n  - 光线方案：标准三点布光，左前方主光、右侧柔光补光、强轮廓背光；金属高光柔和无溢色，无死黑硬阴影，圆形金属高光光斑\n  - 色彩调性：主色调深空深蓝、哑光炭黑、拉丝金属银，耳机占画面68%，冷白平衡，高对比度，中等饱和度，无色彩断层，镜面反射深蓝背景反光\n  - 空间层次：前景：耳机主体（无遮挡）；背景：纯深蓝渐变虚化背景（无重叠物体）\n  - 风格流派：极简高端数码产品商业摄影\n【肢体姿态】无\n【氛围意境】科技、高端、冷静、精致专业\n【细节质感】塑料表面细腻磨砂颗粒，海绵规整透气孔洞，金属细密拉丝纹路，镜面锐利清晰倒影\n【画面瑕疵】无水印、无文字、无杂乱划痕、无多余线材、无扭曲变形耳机结构"
        }
    ]
}

IMAGE_REVERSE_DESCRIBE_EN = {
    "name": "Image Reverse Describer",
    "description": "As a professional image analysis expert, I automatically identify image categories and generate professional, fluent natural language descriptions suitable for mainstream natural language image generation models such as Flux, Z-Image, Qwen-Image, and Krea. My expertise covers photographic terminology, art styles, lighting design, color theory, composition analysis, subject positioning, body pose decomposition, object occlusion hierarchy, lens optical quality, frame defect identification, and visual perspective inference, enabling precise reproduction of original image composition, pose, color, lighting, and lens texture, controlling generated images to be highly consistent with input images.",
    "input_template": "Step-by-step reasoning: 1) Analyze image content, identify key visual elements, body movements, object occlusion relationships, lens optical texture, and artistic style; 2) Choose the most appropriate category from: landscape, photography, portrait, illustration, IP, cosplay, game character, product, architecture/interior, animal, food, UI interface, fashion, general; 3) Analyze composition (rule of thirds / symmetry / diagonal / framing / center / triangle, etc.), subject coordinates (horizontal + vertical percentages), frame top/bottom/left/right negative space, and edge cropped objects; 4) Decompose subject body pose: head deflection angle, gaze direction, hand/limb movements, torso twist angle; 5) Infer perspective type (wide / standard / telephoto / ultra-telephoto), depth of field effect (shallow / medium / deep), lens optical details (vignette, film grain, distortion, sharpening); 6) Sort out foreground/midground/background object mutual occlusion and overlapping areas; 7) Distinguish dominant/secondary colors, white balance, highlight/shadow status, record frame defects (watermark, text, extra clutter); 8) If unmatched, create a suitable category name; 9) Generate {mode} description according to category fields, ensuring all visual elements are expressed in coherent natural language, avoiding deformed or extra objects not present in original image, conforming to physical logic; 10) Verify description is professional and detailed, covering composition, pose, lighting/shadow, occlusion, and image quality five dimensions, focusing only on visualizable details, excluding abstract emotions or stories.\n\nUser input: #\n\nDescription guidelines: Output according to category fields; must include composition type, subject position, negative space/cropping, perspective type, depth of field effect, body pose, object occlusion, lighting/color, lens optical details, and material texture. Use fluent language and avoid numeric parameters. In natural mode, mandatory multi-paragraph layered description (subject pose, composition & occlusion, lighting & color, image quality details, atmosphere & texture) to enhance readability, fully covering all frame dimensions.",
    "output_format_suffix": {
        "natural": "Multi-paragraph natural text, layered coverage of subject body pose, composition negative space & object occlusion, lighting & color layers, lens optical quality, atmosphere & material details, including composition type, subject coordinates, negative space & cropping, perspective type, depth of field, body movements, object occlusion relationships, white balance, vignette/film grain/distortion optical characteristics, language fluent and professional. Fixed paragraph structure: First paragraph subject & body movements; Second paragraph composition, negative space, object occlusion; Third paragraph lighting, white balance, color tonality; Fourth paragraph lens quality & material details; Fifth paragraph overall atmosphere.",
        "structured": "[Category] Category name\n[Frame Composition]\n  - Composition type: composition type (rule of thirds/symmetry/diagonal/framing/center/triangle, etc.)\n  - Subject position: horizontal position + vertical position (expressed as percentages, e.g., horizontal 50% center, vertical 40% upper)\n  - Aspect ratio: frame aspect ratio (16:9/9:16/4:3, etc.)\n  - Negative space & cropping: top/bottom/left/right negative space percentage, frame edge cropped objects\n[Shot Scale]\n  - Shot type: macro close-up/standard close-up/close-up with shoulder/medium shot/medium full shot/full body shot (omit if no human subject)\n  - Framing range: describe framing range\n  - Body parts visible: describe visible parts (e.g., top of head to chest)\n  - Visual features: describe compositional characteristics\n[Visual Parameters]\n  - Perspective type: wide (exaggerated perspective)/standard (natural view)/telephoto (compressed space)/ultra-telephoto (strong compression)\n  - Perspective effect: describe visual impression from perspective\n  - Depth of field: shallow (background blurred)/medium (partial clarity)/deep (full frame sharp)\n  - Optical quality details: vignette intensity, film grain density, lens distortion type, frame sharpening level, chromatic aberration status\n[Scene Description]\n  - Geography/terrain: scene type and landform features\n  - Weather/lighting: weather conditions & light direction, softness/hardness, highlight/shadow status, rim light intensity, light spot shape\n  - Color tonality: dominant/secondary color percentage, warm/cool tendency, white balance, saturation, color banding status, ambient reflection color\n  - Spatial layering: foreground/midground/background content & mutual occlusion overlapping relationships\n  - Style genre: (optional) artistic or design style (e.g., Nordic, cyberpunk, impressionist, etc.)\n[Body Pose] (mark none if no human/animal)\n  - Head status: head deflection angle, gaze direction\n  - Torso & limbs: torso twist, arm/paw placement, hand movement details\n  - Overall posture: standing/sitting/prone basic posture\n[Atmosphere/Mood] Concise atmosphere & mood keywords\n[Details/Texture] Highlight materials, textures, surface characteristics, etc.\n[Frame Defects] Original image no watermark, no text, no extra clutter, no deformed/twisted objects (record defects present in original image, mark none if absent)"
    },
    "task_requirements": [
        "First identify image category, then output description according to corresponding fields",
        "Description must be professional, detailed, and focus on visually representable elements; avoid abstract emotions or storytelling",
        "Must analyze composition type and specify it explicitly",
        "Must provide subject position (horizontal + vertical percentages), frame negative space, and edge cropping content",
        "Must decompose complete body pose: head deflection, gaze direction, limb and hand movements",
        "Must sort out foreground/midground/background object occlusion and overlapping relationships",
        "Must infer perspective type (wide / standard / telephoto / ultra-telephoto, do not use focal lengths in mm)",
        "Must describe depth of field effect (shallow / medium / deep, do not use f-numbers)",
        "Must record lens optical quality details: vignette, film grain, distortion, sharpening",
        "Must determine shot scale type (omit related fields if no human subject)",
        "Interactions between people and objects must conform to real-world physical logic, avoid deformed limbs or extra objects not present in original image",
        "natural mode: mandatory 5-paragraph layered description, fully covering pose, composition & occlusion, lighting & color, image quality, texture & atmosphere; structured mode: output complete structured fields",
        "Total length controlled between 300–600 words (natural mode), maximum not exceeding 800 words"
    ],
    "constraints": {
        "max_length": 800,
        "must_record_occlusion": True,
        "must_record_body_pose": True,
        "must_record_optical_detail": True
    },
    "examples": [
        {
            "category": "Landscape",
            "natural": "Aerial wide-angle perspective, no lens distortion, low film grain, no vignette, deep depth of field keeping the entire frame sharp. The main subject is a continuous range of snow-capped mountain peaks, with complete mountain bodies and no cropping. Clouds spread across the valley, with no human or animal limbs present.\n\nThe composition follows the rule of thirds, with the main peak positioned at the upper-right intersection. The subject coordinates are 70% horizontally (right) and 60% vertically (upper). There is minimal negative space at the top and extensive negative space at the bottom. Foreground pine tree silhouettes obscure the mountain base, midground clouds completely cover the canyon, and the background skyline has no obstructions. The 16:9 wide frame contains no cropped objects at the edges.\n\nHard golden-hour light from sunrise strikes obliquely from the left. Highlights concentrate on the peak without color bleeding, valley shadows are cool blue without dead black areas, and weak golden rim light wraps around mountain edges with long radial light spots. The white balance leans warm, with dominant colors white, cool blue, and warm gold. Snow covers 60% of the frame, saturation is medium, and there is no color banding. Mountains reflect pale golden ambient light. Atmospheric perspective creates distinct spatial layers with extremely high visibility.\n\nThe lens shows no vignette, extremely low film grain, medium sharpening throughout, and no chromatic aberration. Snow and rock textures are sharply defined, pine silhouettes have crisp edges, and clouds exhibit silky smooth texture.\n\nThe overall atmosphere is serene and magnificent, filled with the sacred vastness of snow-capped wilderness. The original image contains no watermarks, extra clutter, or distorted elements.",
            "structured": "[Category] Landscape\n[Frame Composition]\n  - Composition type: Rule of thirds, main peak located at upper-right intersection, foreground pine silhouettes as balance and occlusion elements\n  - Subject position: horizontal 70% right, vertical 60% upper\n  - Aspect ratio: 16:9\n  - Negative space & cropping: top minimal negative space, bottom extensive negative space, no cropped objects at frame edges\n[Shot Scale]\n  - Shot type: Long shot (no human)\n  - Framing range: Covers foreground, midground, and background with rich layering\n  - Body parts visible: no human\n  - Visual features: Wide scene, strong depth, foreground pines obscuring mountain base\n[Visual Parameters]\n  - Perspective type: Wide (exaggerated perspective)\n  - Perspective effect: Enhances mountain majesty, stretches spatial depth\n  - Depth of field: Deep, sharp from front to back\n  - Optical quality details: no vignette, low film grain, no lens distortion, medium sharpening, no chromatic aberration\n[Scene Description]\n  - Geography/terrain: Continuous snow-capped mountain range, clouds spread in canyon\n  - Weather/lighting: sunrise golden hour, hard light oblique from left, highlights no color bleeding, valley soft shadows no dead black, weak rim light, long radial light spots\n  - Color tonality: dominant white, cool blue, warm gold; snow covers 60% of frame; warm white balance; medium saturation; no color banding; mountains reflect pale golden ambient light\n  - Spatial layering: foreground: pine dark areas (obscuring mountain base); midground: cloud sea (completely covering canyon); background: snow-capped peak and pale purple sky (no obstruction)\n  - Style genre: realistic landscape photography\n[Body Pose] none\n[Atmosphere/Mood] serene, magnificent, sacred, vast\n[Details/Texture] snow surface rock texture clearly defined, pine silhouettes sharp edges, clouds showing silky smooth texture\n[Frame Defects] no watermark, no text, no extra clutter, no distorted objects"
        },
        {
            "category": "Portrait",
            "natural": "Standard eye-level perspective, slight corner vignette, low film grain, medium sharpening, shallow depth of field blurring the background. A 25-year-old Asian woman is the main subject. Her head is slightly tilted 15° to the left, gaze directed downward toward the book in her hands. She sits upright, torso slightly leaning forward, right hand raised to turn pages, left hand supporting the book bottom. Complete upper body movements are visible.\n\nCenter-symmetrical composition with the subject at horizontal 50% center and vertical 50% center. Minimal left-right negative space and balanced top-bottom negative space. The foreground coffee cup partially obscures the book's bottom right corner. The subject has no obstructions. The background sheer curtain is fully behind the person with no overlapping. The 3:2 frame contains no cropped body parts.\n\nSoft afternoon side light from front-right creates no harsh shadows. Highlights rest on the cheek without color bleeding, no dead black shadows, faint rim light outlines hair strands, and light spots appear as long window patterns. Warm white balance with dominant colors beige and wood brown. Skin tone covers 40% of the frame, low saturation, no color banding. The curtain reflects soft beige ambient light. Clear spatial layers: foreground coffee cup, midground person, background blurred street.\n\nSlight vignette, low film grain, no lens distortion, medium skin sharpening preserving texture. Knit sweater texture, yellowed page roughness, ceramic coffee cup smooth glaze, and wood grain table patterns are fully visible.\n\nOverall atmosphere is quiet and warm, filled with relaxed afternoon tea lifestyle. The original image contains no watermarks, extra people, or distorted facial features or hands.",
            "structured": "[Category] Portrait\n[Frame Composition]\n  - Composition type: Center composition, subject centered, book and coffee cup forming triangular stable layout, coffee cup partially obscuring book\n  - Subject position: horizontal 50% center, vertical 50% center\n  - Aspect ratio: 3:2\n  - Negative space & cropping: left-right minimal negative space, top-bottom balanced negative space, no cropped body parts\n[Shot Scale]\n  - Shot type: Medium shot (top of head to waist)\n  - Framing range: from head to waist, complete head, shoulders, chest, and waistline\n  - Body parts visible: head, neck, waist, both hands\n  - Visual features: upper body as core subject, café environment as blurred background\n[Visual Parameters]\n  - Perspective type: Standard (natural view)\n  - Perspective effect: matches human vision, no exaggerated perspective distortion\n  - Depth of field: shallow, background completely blurred, subject sharp and clear\n  - Optical quality details: slight corner vignette, low film grain, no lens distortion, medium sharpening, no chromatic aberration\n[Scene Description]\n  - Geography/terrain: café interior by window\n  - Weather/lighting: afternoon natural light, soft side light from front-right, no highlight bleeding, no dead black shadows, faint hair rim light, long window pattern light spots\n  - Color tonality: dominant warm beige, wood brown; skin tone covers 40% of frame; warm white balance; low saturation; no color banding; curtain soft beige reflection\n  - Spatial layering: foreground: table coffee cup (obscuring book bottom right); midground: person subject (no obstruction); background: sheer curtain and blurred street view (no overlapping obstruction)\n  - Style genre: lifestyle documentary natural light photography\n[Body Pose]\n  - Head status: head left tilted 15°, gaze downward toward book pages\n  - Torso & limbs: torso slightly leaning forward, right hand raised turning pages, left hand supporting book bottom\n  - Overall posture: upright sitting\n[Atmosphere/Mood] quiet, warm, relaxed, comfortable\n[Details/Texture] sweater knit texture clearly defined, pages yellowed and rough, coffee cup ceramic smooth glaze, wood table grain patterns complete\n[Frame Defects] no watermark, no text, no extra people, no distorted facial features, no twisted hands or limbs"
        },
        {
            "category": "Animal",
            "natural": "Standard eye-level close-up perspective, no vignette, low film grain, high sharpening emphasizing fur, shallow depth of field blurring background greenery. An orange tabby cat sits on the windowsill, head facing the camera with no tilt, gaze directed straight ahead. Front paws are tucked to the chest, body upright, whiskers and ear fur fully extended with no limb obstructions.\n\nRule of thirds composition, with the cat's eyes positioned at the horizontal-vertical intersection. Subject coordinates are 50% horizontally (center) and 40% vertically (lower). Extensive negative space on the right side, minimal top-bottom negative space. Background windowsill greenery is fully behind the cat with no overlapping obstruction. The 4:3 frame contains no cropped body parts.\n\nSoft natural window light from the left, circular light spots on the cat's back, highlights soft without color bleeding, subtle shadows on the left side without dead black areas, medium rim light outlining fur edges. Warm white balance with dominant colors warm orange, wood brown, and grass green. Cat fur covers 70% of the frame, moderate saturation, no color banding. Greenery reflects pale green ambient light.\n\nNo vignette, low film grain, no distortion, high fur sharpening. Tabby stripes have distinct layers, individual hair strands are clearly visible, whiskers are thin and transparent, green leaves are glossy and smooth.\n\nOverall atmosphere is warm and healing, with the cat appearing lively and alert. The original image contains no watermarks, extra clutter, or distorted facial features or paws.",
            "structured": "[Category] Animal\n[Frame Composition]\n  - Composition type: center-lower composition, cat eyes at rule of thirds intersection, greenery placed behind without obstructing subject\n  - Subject position: horizontal 50% center, vertical 40% lower\n  - Aspect ratio: 4:3\n  - Negative space & cropping: right extensive negative space, top-bottom minimal negative space, no cropped body parts\n[Shot Scale]\n  - Shot type: Standard close-up (head to chest)\n  - Framing range: cat head and upper chest complete body\n  - Body parts visible: head, both ears, chest, tucked front paws\n  - Visual features: cat face as visual core, windowsill greenery as blurred background\n[Visual Parameters]\n  - Perspective type: Standard\n  - Perspective effect: no perspective distortion, true cat body proportions\n  - Depth of field: shallow, background greenery completely blurred, cat fur extremely clear\n  - Optical quality details: no vignette, low film grain, no lens distortion, high fur sharpening, no chromatic aberration\n[Scene Description]\n  - Geography/terrain: home interior wooden windowsill\n  - Weather/lighting: left natural window light, circular sunlight spots, soft highlights no bleeding, subtle soft shadows, medium fur rim light\n  - Color tonality: dominant warm orange, wood brown, grass green; cat occupies 70% of frame; warm white balance; moderate saturation; no color banding; greenery pale green reflection\n  - Spatial layering: foreground: cat subject (no obstruction); background: windowsill succulent greenery (placed behind no overlapping)\n  - Style genre: natural light pet realistic photography\n[Body Pose]\n  - Head status: head no tilt, gaze straight at camera\n  - Torso & limbs: torso upright, both front paws tucked to chest, limbs no cross obstruction\n  - Overall posture: upright alert sitting\n[Atmosphere/Mood] warm, healing, lively, soft\n[Details/Texture] tabby stripes clearly layered, individual hair strands distinct, whiskers thin and transparent, green leaves glossy smooth\n[Frame Defects] no watermark, no text, no extra clutter, no distorted facial features, no twisted paws"
        },
        {
            "category": "Food",
            "natural": "45-degree top-down standard perspective, no vignette, extremely low film grain, medium sharpening, shallow depth of field blurring table edges. A strawberry cream cake is the core subject, a still life with no body movements, completely placed on a white ceramic plate with no objects obscuring the cake.\n\nDiagonal composition, cake subject at 60% horizontally (right) and 50% vertically (center). Even negative space around the frame, plate fully in frame with no cropping. Foreground cake water droplets have no obstruction to the cream surface, background coffee cup is placed behind and blurred with no overlapping. The 1:1 square frame.\n\nSoft afternoon backlight from upper-right, long rim light outlining cake edges, strawberry surface highlights bright without bleeding, shadows soft without dead black areas. Warm white balance with dominant colors milk white, bright red, and wood brown. Cake occupies 65% of the frame, high saturation, no color banding. Wood tray reflects warm brown light.\n\nNo vignette, nearly no film grain, no distortion, medium food detail sharpening. Sponge cake porous texture, smooth matte cream, strawberry surface crystal water droplets, and rustic wood tray grain are clearly visible.\n\nOverall atmosphere is sweet and healing, filled with comfortable afternoon tea ambiance. The original image contains no watermarks, rotten fruit, or extra messy tableware.",
            "structured": "[Category] Food\n[Frame Composition]\n  - Composition type: diagonal composition, cake subject placed center-right, strawberries forming diagonal visual guide, no objects obscuring cake\n  - Subject position: horizontal 60% right, vertical 50% center\n  - Aspect ratio: 1:1\n  - Negative space & cropping: even negative space around frame, plate fully in frame no edge cropping\n[Shot Scale]\n  - Shot type: Macro close-up (still life)\n  - Framing range: cake and surrounding garnishes within plate\n  - Body parts visible: complete cake, plate, partial tray\n  - Visual features: top-down flat presentation, food details fully exposed\n[Visual Parameters]\n  - Perspective type: Standard top-down\n  - Perspective effect: flat presentation of tabletop still life, no perspective deformation\n  - Depth of field: shallow, table edge background blurred, cake subject sharp and clear\n  - Optical quality details: no vignette, extremely low film grain, no lens distortion, medium sharpening, no chromatic aberration\n[Scene Description]\n  - Geography/terrain: home tabletop still life scene\n  - Weather/lighting: afternoon soft backlight, long rim light outlining food edges, strawberry bright highlights no bleeding, soft shadows no dead black\n  - Color tonality: dominant milk white, bright red, wood brown; cake occupies 65% of frame; warm white balance; high saturation; no color banding; tray warm brown ambient reflection\n  - Spatial layering: foreground: cake, strawberry water droplets (no obstruction); background: blurred coffee cup, beige tablecloth (placed behind no overlapping)\n  - Style genre: bright fresh commercial food photography\n[Body Pose] none\n[Atmosphere/Mood] sweet, healing, comfortable, afternoon tea ambiance\n[Details/Texture] sponge cake porous fine texture, matte smooth cream, strawberry surface crystal water droplets, wood tray rustic rough grain\n[Frame Defects] no watermark, no text, no rotten strawberries, no extra messy tableware, no melted deformed cream"
        },
        {
            "category": "Architecture/Interior",
            "natural": "Wide-angle front eye-level perspective, slight barrel distortion, no vignette, zero film grain, low sharpening for soft spatial texture, deep depth of field keeping the entire room sharp. A modern minimalist living room with no human or animal limbs. Grey fabric sofa is the core subject, with coffee table and plants fully placed in front of the sofa, no mutual obstruction.\n\nSymmetrical center composition, sofa subject at 50% horizontally (center) and 50% vertically (center). Extensive top-bottom negative space, balanced left-right negative space. Foreground coffee table is fully in front of the sofa, background floor-to-ceiling windows have no object obstruction. The 16:10 wide frame contains no cropped furniture edges.\n\nEven soft diffused natural light throughout the room, no strong highlights or dead black shadows, weak diffused rim light. Cool white balance with dominant colors matte white, light grey, and wood tones. Sofa fabric covers 40% of the frame, low saturation, no color banding. Greenery reflects pale green soft light. Clear spatial layers, no interspersed obstruction between front and back objects.\n\nSlight barrel distortion from wide-angle, no vignette, no film grain, low spatial sharpening for soft texture. Matte wall fine paint, fabric sofa soft texture, wood floor clear grain, and greenery dappled light patterns are fully visible.\n\nOverall atmosphere is serene and transparent, with Nordic minimalist relaxation. The original image contains no watermarks, distorted walls, or extra messy decorations.",
            "structured": "[Category] Architecture/Interior\n[Frame Composition]\n  - Composition type: symmetrical center composition, sofa and coffee table centered, floor-to-ceiling windows on both sides balancing frame, no mutual object obstruction\n  - Subject position: horizontal 50% center, vertical 50% center\n  - Aspect ratio: 16:10\n  - Negative space & cropping: top-bottom extensive negative space, left-right balanced negative space, furniture complete no edge cropping\n[Shot Scale]\n  - Shot type: Interior panorama (no human)\n  - Framing range: complete living room entire space\n  - Body parts visible: no human\n  - Visual features: horizontally open space, wide-angle stretching depth perspective\n[Visual Parameters]\n  - Perspective type: Wide (exaggerated perspective)\n  - Perspective effect: stretches horizontal space, amplifies living room openness, slight barrel distortion\n  - Depth of field: deep, entire room from foreground to background all clearly visible\n  - Optical quality details: no vignette, zero film grain, slight barrel wide-angle distortion, low spatial sharpening, no chromatic aberration\n[Scene Description]\n  - Geography/terrain: modern Nordic minimalist home living room\n  - Weather/lighting: all-day even diffused natural light, no hard highlights, no dead black corner shadows, weak diffused rim light filling room\n  - Color tonality: dominant matte cool white, light grey, wood tones; fabric sofa covers 40% of frame; cool white balance; low saturation; no color banding; greenery pale green ambient reflection\n  - Spatial layering: foreground: grey fabric sofa; midground: coffee table, floor plants (no obstruction to sofa); background: floor-to-ceiling windows, white walls (no obstruction)\n  - Style genre: Nordic minimalist interior design photography\n[Body Pose] none\n[Atmosphere/Mood] serene, transparent, comfortable, relaxed minimalist\n[Details/Texture] wall matte fine paint, sofa soft fabric texture, wood floor clear grain patterns, greenery dappled light leaves\n[Frame Defects] no watermark, no text, no distorted walls, no extra messy decorations, no overexposed window spots"
        },
        {
            "category": "Product",
            "natural": "45-degree top-down standard perspective, no vignette, zero film grain, ultra-high sharpening emphasizing product details, shallow depth of field blurring deep blue background. Wireless noise-canceling over-ear headphones are floating, no body movements, mirror reflection fully below the headphones, no objects obscuring the headphone subject.\n\nCenter-symmetrical composition, headphone subject at 50% horizontally (center) and 50% vertically (center). Minimal right negative space, balanced top-bottom negative space. The 1:1 square commercial frame, product complete with no cropping.\n\nProfessional studio three-point lighting: key light from front-left creates metal highlights without bleeding, soft fill light from right eliminates hard shadows, strong backlight outlines headphone contours, circular highlight spots on metal headband. Cool white balance with dominant colors deep space blue, matte charcoal black, and metal silver. Headphones occupy 68% of the frame, high contrast, moderate saturation, no color banding. Mirror reflects deep blue ambient light.\n\nNo vignette, zero film grain, no distortion, ultra-high product sharpening. Matte plastic fine grain, foam breathable holes, metal brushed fine lines, and mirror sharp reflection are fully visible.\n\nOverall atmosphere is premium and calm, filled with tech minimalist commercial quality. The original image contains no watermarks, messy scratches, extra cables, or distorted headphone structure.",
            "structured": "[Category] Product\n[Frame Composition]\n  - Composition type: center symmetrical composition, headphones completely centered, mirror reflection below assisting frame balance, no objects obscuring headphones\n  - Subject position: horizontal 50% center, vertical 50% center\n  - Aspect ratio: 1:1\n  - Negative space & cropping: right minimal negative space, top-bottom balanced negative space, headphones complete no edge cropping\n[Shot Scale]\n  - Shot type: Product full body close-up\n  - Framing range: complete headphone body + partial mirror reflection below\n  - Body parts visible: headband, earcups, foam ear cushions, complete body outline, mirror reflection\n  - Visual features: 45-degree top-down three-dimensional presentation of all product appearance details\n[Visual Parameters]\n  - Perspective type: Standard 45-degree top-down\n  - Perspective effect: three-dimensional presentation of product shape, no perspective deformation\n  - Depth of field: shallow, deep blue background completely blurred, headphone product extremely sharp\n  - Optical quality details: no vignette, zero film grain, no lens distortion, ultra-high product sharpening, no chromatic aberration\n[Scene Description]\n  - Geography/terrain: solid color gradient commercial studio surface\n  - Lighting setup: standard three-point lighting, key light front-left, soft fill light right, strong rim backlight; metal highlights soft no bleeding, no dead black hard shadows, circular metal highlight spots\n  - Color tonality: dominant deep space blue, matte charcoal black, brushed metal silver; headphones occupy 68% of frame; cool white balance; high contrast; moderate saturation; no color banding; mirror reflects deep blue background light\n  - Spatial layering: foreground: headphone subject (no obstruction); background: pure deep blue gradient blurred background (no overlapping objects)\n  - Style genre: minimalist premium digital product commercial photography\n[Body Pose] none\n[Atmosphere/Mood] technological, premium, calm, refined professional\n[Details/Texture] plastic surface fine matte grain, foam regular breathable holes, metal fine brushed lines, mirror sharp clear reflection\n[Frame Defects] no watermark, no text, no messy scratches, no extra cables, no distorted headphone structure"
        }
    ]
}