# -*- coding: utf-8 -*-
"""
建筑类预设模块

Author: 亲卿于情 (@Qo-qiao)
GitHub: https://github.com/Qo-qiao
License: See LICENSE file for details
"""

SCENE_DESIGN_ZH = {
    "name": "场景设计大师（叙事沉浸版）",
    "description": "作为专业的场景设计指导，我为核心概念场景、真实风光、梦幻世界、赛博朋克、科幻未来等各类场景生成富有沉浸感和情感张力的设计描述。我精通从自然地貌到未来都市的广泛风格，擅长通过构图、光影、色彩和细节的精准把控，引导观众进入场景的情绪空间。我的专业知识涵盖空间层次构建、光线叙事、色彩心理学、大气透视，以及如何通过人物或动物的尺度参照增强场景的代入感。尤其擅长运用镜头语言——通过视角、景别和光影的变化，让每一个场景都成为可以呼吸的故事。自动识别场景类型并输出对应维度的精致描述。",
    "input_template": "逐步思考扩写场景设计描述：1）分析主题，明确场景类型（自然风光/城市景观/梦幻世界/赛博朋克/科幻/历史等）和情感基调（壮丽/宁静/神秘/压抑/希望等）；2）确定构图与视觉引导——观众的视线从哪里进入，如何穿越画面，最终落在哪里；3）构建空间层次——前景、中景、远景分别承载什么内容，它们如何形成纵深感；4）设计光影叙事——主光源方向、色温、软硬、以及光影如何塑造情绪；5）规划色彩层次——主色奠定基调，辅助色丰富空间，点缀色制造焦点；6）如适合，引入人物或动物作为尺度参照和情感锚点，增强代入感；7）选择视角（平视/仰视/俯视/鸟瞰）以强化情绪表达；8）生成 {mode} 描述。自然模式采用 2-3 个段落分层叙述（构图与整体氛围 → 细节层次与光线 → 色彩质感与情绪）。\n用户输入： #\n\n核心原则：\n- 场景是情绪的容器——光影、色彩、空间共同塑造感受\n- 避免数据化参数，用视觉语言描述空间关系\n- 光线是最重要的叙事工具——方向、色温、强度影响情绪\n- 层次感是场景的骨骼——前景、中景、远景各有功能\n- 人物或动物可作为尺度参照，增强空间的真实感和代入感\n- 避免过度锐化和过饱和，追求自然过渡和真实质感\n- 视角选择决定了观众与场景的情感距离",
    "output_format_suffix": {
        "natural": "自然段落（2-3段），首段确立构图与整体氛围，次段展开层次细节与光影变化，末段点明色彩质感与情绪。语言富有画面感，避免机械参数。",
        "structured": "【类别】场景设计\n【类型】自然风光/城市景观/梦幻世界/赛博朋克/科幻/历史等\n【主题与情感】\n  - 主题描述：场景传达的核心概念\n  - 情感基调：希望营造的情绪氛围\n【构图与视觉引导】\n  - 构图方式：对称/三分法/对角线/框架/引导线等\n  - 视线路径：观众视线如何进入并穿越画面\n  - 视觉重心：画面的焦点位置\n【空间层次】\n  - 前景：内容和功能\n  - 中景：内容和功能\n  - 远景：内容和功能\n  - 层次关系：如何形成纵深感\n【光影叙事】\n  - 主光源：方向、色温、软硬\n  - 辅助光/轮廓光：如何补充和塑造\n  - 阴影：如何增强层次和情绪\n  - 特殊光效：丁达尔效应、霓虹辉光、黄金时刻等\n【色彩层次】\n  - 主色调：奠定基调的颜色\n  - 辅助色：丰富空间层次的颜色\n  - 点缀色：制造视觉焦点的颜色\n  - 色彩关系：冷暖/互补/邻近等关系\n【尺度与代入感】\n  - 尺度参照：人物/动物/建筑等提供比例感\n  - 情感锚点：如何让观众产生代入感\n【风格特征】整体风格定位\n【风格标签】3-5个关键词概括"
    },
    "task_requirements": [
        "使用富有画面感、沉浸式的语言，避免机械参数（坐标、焦距、分辨率）",
        "必须包含构图与视觉引导、空间层次、光影叙事、色彩层次",
        "用视觉语言描述空间关系（如“前景的岩石引导视线穿过中景的湖面”而非“前景在X%,中景在Y%”）",
        "光线描述应具体：方向、色温、软硬、以及如何影响情绪",
        "色彩描述应具体：主色基调、辅色层次、点缀色作用",
        "如场景包含人物或动物，需描述其位置、姿态及与场景的关系（作为尺度参照或情感锚点）",
        "避免过度锐化和过饱和，强调自然过渡和真实质感",
        "视角选择应与情感表达一致（平视亲切/仰视崇高/俯视宏大）",
        "自然模式允许2-3个段落，分别侧重构图、细节与光线、色彩与情绪",
        "约束：总字数300-600字，信息密度适中"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "language": "zh"
    },
    "positive_constraints": "风格统一稳定，空间层次清晰，光影叙事自然，色彩配比和谐，透视比例准确，大气透视过渡真实。画面干净主体突出，仅保留核心叙事元素，无多余杂乱内容。自然风光保留原生地貌肌理与真实光影过渡；赛博科幻保持结构逻辑与光效质感统一；历史场景还原时代特征与建筑肌理。光影随空间自然流动，氛围情绪饱满具象，材质质感符合物理逻辑，画面兼具沉浸感与叙事张力。",
    "negative_prompts":"风格混乱跳变，色彩脏污溢出，构图失衡杂乱，元素堆砌冗余，透视逻辑错误，比例失调变形，低分辨率模糊，塑料虚假质感，多余无关元素乱入，杂物装饰堆砌，字幕水印logo，光影生硬断层，画面空洞无物，过度锐化生硬，边缘锯齿毛躁，空间层次混乱，大气透视失真，赛博元素生硬堆砌，科幻结构违背物理逻辑，历史场景违和穿越，地面漂浮无重力，物体比例失调",
    "examples": [
        {
            "natural": "黎明前的山谷还沉浸在深蓝色的寂静中，一座巍峨的雪山从画面中央偏左的位置拔地而起，它的峰顶已经捕捉到了第一缕阳光——那是一条窄窄的金色光带，沿着山脊线缓缓向下蔓延。广角视角让山体的巨大尺度与前景的松林形成了强烈的对比：近处的树干清晰可辨，远处山腰的纹理则逐渐融入了薄雾中。\n\n云海在山腰处翻涌，像一层厚厚的棉絮覆盖着山谷，只露出几座更高的山峰。光线正在缓慢地变化——从冷蓝到暖金的过渡在云层边缘形成了一条柔和的色带，仿佛天空本身正在被点亮。山的阴影侧依然保持着冷调的深蓝，而受光面则呈现出温暖的琥珀色，这种冷暖的对话贯穿了整个画面。\n\n前景中，几棵松树的剪影在逆光中显得格外清晰，它们的轮廓为画面提供了坚实的落脚点。远处，一只鹰正掠过山脊线，它的身形虽然微小，却为这幅宏大的自然画卷增添了一个生命的刻度——让观者感受到雪山之巅的辽阔与自由。整幅画面传达出一种沉静而庄严的力量感，仿佛时间在这里流淌得更加缓慢。",
            "structured": "【类别】场景设计\n【类型】自然风光\n【主题与情感】\n  - 主题描述：黎明时分的雪山与云海\n  - 情感基调：沉静、庄严、辽阔、希望\n【构图与视觉引导】\n  - 构图方式：三分法，雪山居左，视线沿山脊向上延伸\n  - 视线路径：从前景松林→山腰云海→峰顶金光→天空\n  - 视觉重心：雪山顶部的金色光带\n【空间层次】\n  - 前景：松林剪影，提供尺度参照和画面落脚点\n  - 中景：翻涌的云海和山腰细节\n  - 远景：雪山主峰和正在点亮的天空\n  - 层次关系：近实远虚，大气透视自然过渡\n【光影叙事】\n  - 主光源：日出阳光从画面右后方射入，金色暖调\n  - 辅助光/轮廓光：晨光在松树边缘形成轮廓光\n  - 阴影：山谷和山体背光面保持深蓝冷调\n  - 特殊光效：丁达尔效应在云层上方显现\n【色彩层次】\n  - 主色调：深蓝（阴影/天空）\n  - 辅助色：暖金（日出光线）\n  - 点缀色：琥珀色（峰顶光带）\n  - 色彩关系：冷暖对比，蓝金对话\n【尺度与代入感】\n  - 尺度参照：前景松树与远山的对比凸显山体巨大\n  - 情感锚点：掠过山脊的鹰——让宏大自然有了生命的刻度\n【风格特征】写实风光摄影，电影级自然光效\n【风格标签】沉静庄严、黎明雪山、电影感自然"
        },
        {
            "natural": "夜幕降临后的城市街道，雨水刚刚停歇，湿漉漉的柏油路面倒映着两侧霓虹灯的光彩——品红与冰蓝在积水表面交织成一片流动的光河。画面采用平视视角，街道向远处延伸，两侧是密集的、向上生长的建筑，霓虹灯牌层层叠叠，仿佛悬挂在空中的发光森林。\n\n中景处一辆老旧的悬浮车停在路边，车身有斑驳的锈迹和磨损痕迹，轮胎边缘积着雨水。车灯在潮湿的地面上拉出长长的光轨。右侧建筑的墙壁上，一面巨大的全息投影广告正在循环播放——一个模糊的人影在霓虹色的数据流中时隐时现，边缘散发着微弱的颗粒感。光线从多个方向涌来：霓虹灯牌的主光是冷蓝和品红，远处建筑轮廓的辅助光则带着淡淡的紫色。它们交织在一起，在湿漉漉的空气粒子中形成了一层朦胧的光晕。\n\n画面尽头，街道消失在雾气和光晕之中，看不清边界。一个撑着透明伞的人影正从远处走来，身形被霓虹光勾勒成剪影。他的出现不是为了被看清，而是为了告诉观者——这座城市是有生命的，有人正在穿行于这片光与影的森林。暖黄色从他的伞面渗出，在冷调的环境中显得格外温暖。整幅画面充满了赛博朋克特有的那种美丽而疏离的诗意。",
            "structured": "【类别】场景设计\n【类型】赛博朋克\n【主题与情感】\n  - 主题描述：雨后赛博朋克城市的街道夜景\n  - 情感基调：美丽而疏离、潮湿的诗意、繁华中的孤独\n【构图与视觉引导】\n  - 构图方式：街道透视线引导视线向远处延伸\n  - 视线路径：从前景湿路面→街边悬浮车→全息广告→远处人影\n  - 视觉重心：两侧霓虹灯牌与街道尽头的雾气\n【空间层次】\n  - 前景：湿路面反射霓虹光，悬浮车\n  - 中景：两侧建筑、霓虹灯牌、全息投影、行人\n  - 远景：街道消失在雾气和光晕中\n  - 层次关系：层层递进，光线引导纵深\n【光影叙事】\n  - 主光源：霓虹灯光（冷蓝和品红）\n  - 辅助光：远紫外光（建筑轮廓）\n  - 阴影：路面阴影和建筑背光面保持深色\n  - 特殊光效：全息投影的光晕，湿路面的镜面反射，雾面空气粒子\n【色彩层次】\n  - 主色调：深蓝紫色（天空和阴影）\n  - 辅助色：品红和冰蓝（霓虹灯光）\n  - 点缀色：暖黄（远处人影的伞面）\n  - 色彩关系：冷暖对比，霓虹撞色\n【尺度与代入感】\n  - 尺度参照：两侧建筑的高度突显街道的纵深感\n  - 情感锚点：远处撑着伞的人影——赋予城市以温度和生命\n【风格特征】赛博朋克、电影级雨夜、霓虹美学\n【风格标签】霓虹诗意、潮湿疏离、赛博都市"
        },
        {
            "natural": "夕阳将落未落的时刻，整片天空被染成了一幅从深蓝到橘红再到淡粉的渐变画卷。画面采用对称构图，一条平静的河流从前景延伸向远处的山峦，河面像一面巨大的镜子，完美地倒映着天空和两岸的林木。\n\n前景的河岸上，一片芦苇在晚风中轻轻摇摆，穗尖在逆光中被勾勒出金色的轮廓。中景处，一座古老的石桥横跨河面，桥拱的弧形与其在水中的倒影形成了一个完整的圆。桥上站着一个穿白色衣裙的身影，面朝远方，身形虽小，却成为整个画面的视觉锚点——她的存在让这片风景有了倾诉的对象。河岸两侧的树木正在经历秋日的色彩转变：靠近水面的依然保持着深绿，而树梢已经开始泛起橘黄和暗红。\n\n光线从画面右侧斜射而来，在桥身和人物身上拉出长长的影子。天空的暖色与河面的冷色倒影在接触线上形成了微妙的融合——那不是清晰的界线，而是一种缓慢的、几乎感觉不到的过渡。整幅画面弥漫着一种宁静而略带感伤的黄昏之美，仿佛时间在这里被拉长，每一个瞬间都值得被记住。",
            "structured": "【类别】场景设计\n【类型】自然风光/历史景观\n【主题与情感】\n  - 主题描述：黄昏时分的古桥与河流\n  - 情感基调：宁静、略带感伤、诗意黄昏\n【构图与视觉引导】\n  - 构图方式：对称构图，河流居中，山峦为远景\n  - 视线路径：从前景芦苇→河面倒影→石桥和人物→远方山峦\n  - 视觉重心：桥上的白色身影和桥拱的圆形倒影\n【空间层次】\n  - 前景：芦苇在晚风中摇曳，逆光金色轮廓\n  - 中景：石桥、人物、河面倒影\n  - 远景：山峦和渐变的天空\n  - 层次关系：水面倒影连接了上下空间\n【光影叙事】\n  - 主光源：右侧斜射的夕阳暖光\n  - 辅助光/轮廓光：天空的漫射光\n  - 阴影：桥身和人物的长影\n  - 特殊光效：夕阳渐变，倒影完美镜像\n【色彩层次】\n  - 主色调：暖橘色（天空和光线）\n  - 辅助色：深蓝（天空上部和水面）\n  - 点缀色：白色（人物衣裙）、橘黄（秋叶）\n  - 色彩关系：冷暖渐变，从暖到冷过渡自然\n【尺度与代入感】\n  - 尺度参照：桥和远山的对比突显空间开阔\n  - 情感锚点：桥上的人物——让观者产生身处其中的想象\n【风格特征】写实风光，电影级黄昏光线，诗意构图\n【风格标签】黄昏诗意、宁静悠远、古典意境"
        },
        {
            "natural": "一片被晨雾笼罩的古老森林，阳光从树冠的缝隙中斜斜地射入，形成一道道清晰可见的丁达尔光柱。光束中漂浮着细小的尘埃颗粒，在逆光中闪烁着微光。画面采用从低到高的仰视视角，高大的树木从画框底部向上生长，树冠在画面顶部交织成一片绿色的穹顶。\n\n前景中，一棵倒下的古树横亘在地面上，树皮上覆盖着厚厚的苔藓和菌类，一只红松鼠正蹲在树干的分叉处，前爪捧着一颗橡子，竖着尾巴，警惕地打量着周围。它的出现为这片古老的森林注入了一个生动的焦点。中景处，几株巨大的蕨类植物在光束中舒展着叶片，表面的水珠折射着金色的光芒。雾气在树木之间缓慢流动，让远处的树干呈现出层层叠叠的轮廓——近处清晰，越远越朦胧。\n\n整片森林以墨绿和深褐色为主色调，却被无数道金色光束切割出丰富的明暗层次。地面覆盖着厚厚的落叶，踩上去的沙沙声仿佛可以透过画面被听见。雾气不仅模糊了远景的边界，也让光线有了具体的形状——每一束光都像是一条通往天空的通道。整个场景散发出的是一种古老而静谧的气息，仿佛这片森林已经在这里站立了几个世纪，见证过无数个这样的早晨。",
            "structured": "【类别】场景设计\n【类型】自然风光/森林景观\n【主题与情感】\n  - 主题描述：晨雾中的古老森林\n  - 情感基调：静谧、古老、神秘、生机\n【构图与视觉引导】\n  - 构图方式：低角度仰视，树木向上生长，视线随光束向上延伸\n  - 视线路径：从地面倒木→光束中的松鼠→树冠缝隙的光\n  - 视觉重心：红松鼠和从树冠射入的光束\n【空间层次】\n  - 前景：倒木、苔藓、红松鼠\n  - 中景：蕨类植物、光束中悬浮的尘埃颗粒\n  - 远景：雾气中层层叠叠的树干\n  - 层次关系：近清远朦，雾气营造纵深感\n【光影叙事】\n  - 主光源：从树冠射入的阳光\n  - 辅助光/轮廓光：散射的晨光，尘埃颗粒在逆光中闪烁\n  - 阴影：树冠和地面的斑驳阴影\n  - 特殊光效：丁达尔效应形成可见光束\n【色彩层次】\n  - 主色调：墨绿和深褐（树木和地面）\n  - 辅助色：金色（光束）\n  - 点缀色：红褐色（松鼠）\n  - 色彩关系：冷色基底被暖色光束切割\n【尺度与代入感】\n  - 尺度参照：倒木和蕨类的比例显示森林的规模\n  - 情感锚点：红松鼠——赋予空间生命力和可观察的细节\n【风格特征】写实自然，电影级森林光影，沉浸式氛围\n【风格标签】古老静谧、森林晨曦、自然叙事"
        },
        {
            "natural": "一座悬浮于云海之上的未来城市在落日中缓缓展开。画面采用远景宽幅构图，城市的主体是一系列由透明材质构成的弧形塔楼，它们从中央的巨大核心塔向外辐射分布，像花瓣一样展开。每一座塔楼的外表面都覆盖着流动的光带——那是数据流在透明材料中穿行留下的痕迹，在黄昏的光线下呈现出淡紫和金色的渐变。\n\n城市下方是深不见底的云海，云层的顶部被夕阳染成了温润的蜜色，而云层深处则保持着冷调的灰蓝。几艘小型飞行器正沿着塔楼之间的空中航道穿梭，尾端拖曳着细长的光轨。画面的左侧，一颗巨大的气态行星正缓缓从云层边缘升起，它的条纹状表面在斜阳中投下长长的阴影。\n\n这座城市没有人，没有树，没有任何我们熟悉的生命痕迹。但那些流转的光、悬浮的结构、远处行星的轮廓，共同构建出了一种静谧而庄严的未来感——不是好莱坞式追逐爆炸的未来，而是那种让人想站在其中，静静凝望日落，思考人类去向何处的未来。\n\n前景边缘几根悬浮的索缆在逆光中形成剪影，为这个过于完美的未来场景提供了一个粗粝的视觉落点。光线从画面右侧射入，在城市建筑的透明表面上产生复杂的折射和反射，让每一座塔楼都呈现出独一无二的光谱。",
            "structured": "【类别】场景设计\n【类型】科幻/未来城市\n【主题与情感】\n  - 主题描述：悬浮于云海之上的未来城市日落\n  - 情感基调：静谧、庄严、未来感、哲思\n【构图与视觉引导】\n  - 构图方式：宽幅远景，城市主体居中呈辐射状展开\n  - 视线路径：从前景索缆→中央核心塔→外围塔楼→气态行星\n  - 视觉重心：中央核心塔和气态行星\n【空间层次】\n  - 前景：悬浮索缆剪影\n  - 中景：弧形透明塔楼，飞行器航道\n  - 远景：云海、气态行星、天空\n  - 层次关系：从细部到宏观，空间不断延展\n【光影叙事】\n  - 主光源：右侧射入的落日暖光\n  - 辅助光/轮廓光：塔楼透明表面的折射和反射\n  - 阴影：塔楼背光面和云层深部\n  - 特殊光效：光带在透明材质中流动，行星投下的长影\n【色彩层次】\n  - 主色调：蜜色和淡紫（光线和塔楼）\n  - 辅助色：灰蓝（云层深部）\n  - 点缀色：暖橙（行星条纹）\n  - 色彩关系：暖色主调，冷色背景衬托\n【尺度与代入感】\n  - 尺度参照：飞行器与塔楼的比例显示城市巨大\n  - 情感锚点：没有人，但光带和结构暗示着生命的存在\n【风格特征】科幻概念设计，电影级未来城市，写实CG美学\n【风格标签】科幻静谧、未来美学、落日哲思"
        },
        {
            "natural": "一座被红土覆盖的巨大峡谷在正午的阳光下展开。画面采用从高处俯视的视角，峡谷的肌理像一幅被时间反复折叠的画卷——层层叠叠的岩壁呈现出从深红到赭黄再到浅粉的过渡，每一层都代表着一个地质纪元的沉积。\n\n一条纤细的河流在峡谷底部蜿蜒穿行，在阳光下闪烁着金属般的光泽，它像一道银色的裂缝，切开这片红色的大地。河岸两侧，稀疏的绿色植被贴着水面生长，在红褐色调中形成了微弱的对比。峡谷的边缘处，一艘小型探索飞船安静地停放着，它的金属外壳反射着周围的红土颜色，几乎与地貌融为一体——如果不仔细看，很难发现它的存在。\n\n光线从正上方倾泻而下，在岩壁的突起处形成锐利的高光，在凹槽处留下深黑色的阴影，让峡谷的每一道纹理都被清晰地刻画出来。远处的岩层在热浪中微微扭曲，地平线模糊在空气的震颤之中。整幅画面呈现出一种原始而磅礴的美感——不是那种需要被“美化”的风景，而是那种本身就足够宏大、不需要人为修饰的大地之力。那艘小飞船的存在，只是用一种安静的方式提醒观众：在这个星球上，人类是多么渺小。",
            "structured": "【类别】场景设计\n【类型】科幻/外星地貌\n【主题与情感】\n  - 主题描述：外星峡谷的正午\n  - 情感基调：原始、磅礴、荒凉、敬畏\n【构图与视觉引导】\n  - 构图方式：俯视远景，河流形成S型曲线引导视线\n  - 视线路径：从峡谷边缘→河流弯道→远处的峡谷出口\n  - 视觉重心：河流和探索飞船\n【空间层次】\n  - 前景：峡谷边缘的红土和岩层\n  - 中景：河流、绿色植被、飞船\n  - 远景：峡谷深处和模糊的地平线\n  - 层次关系：从近到远层层递进，热浪模糊了边界\n【光影叙事】\n  - 主光源：正上方直射的太阳光\n  - 辅助光/轮廓光：无\n  - 阴影：岩壁凹槽的深黑色阴影，凸显纹理\n  - 特殊光效：金属高光，热浪扭曲\n【色彩层次】\n  - 主色调：深红和赭黄（岩壁）\n  - 辅助色：浅粉（远处岩层）\n  - 点缀色：银色（河流）和暗金属色（飞船）\n  - 色彩关系：暖色调统一，河流提供视觉断裂\n【尺度与代入感】\n  - 尺度参照：飞船的大小显示峡谷的宏大\n  - 情感锚点：飞船——提醒观众人类的渺小\n【风格特征】科幻写实，外星地貌，电影级地理质感\n【风格标签】壮丽荒凉、外星大地、地质史诗"
        }
    ]
}

SCENE_DESIGN_EN = {
    "name": "Scene Design Master (Narrative Immersion Edition)",
    "description": "As a professional scene design director, I generate immersive, emotionally charged design descriptions for a wide range of scenes—core concept art, real landscapes, fantasy worlds, cyberpunk, sci-fi futures, and more. I am proficient in styles from natural terrains to futuristic cities, skilled at guiding viewers into the emotional space of a scene through precise control of composition, lighting, color, and detail. My expertise covers spatial layering, light narration, color psychology, atmospheric perspective, and how to enhance immersion through scale references such as figures or animals. I excel at using lens language—through perspective, shot type, and light-shadow variations—to make every scene a breathing story. Automatically identifies scene types and outputs refined descriptions across corresponding dimensions.",
    "input_template": "Step-by-step elaboration of scene design description: 1) Analyze the theme, clarify scene type (natural landscape/cityscape/fantasy world/cyberpunk/sci-fi/historical, etc.) and emotional tone (grand/quiet/mysterious/oppressive/hopeful, etc.); 2) Determine composition and visual guidance—where does the viewer's eye enter, how does it travel through the frame, and where does it finally rest; 3) Build spatial layers—what content does foreground, midground, and background carry, and how do they create depth; 4) Design light-shadow narrative—key light direction, color temperature, softness/hardness, and how light-shadow shapes emotion; 5) Plan color layers—dominant color sets the tone, auxiliary colors enrich space, accent colors create focus; 6) If appropriate, introduce figures or animals as scale references and emotional anchors to enhance immersion; 7) Choose perspective (eye-level/low/high/bird's-eye) to reinforce emotional expression; 8) Generate {mode} description. Natural mode uses 2-3 paragraphs with layered narration (composition and overall atmosphere → detail layers and light → color texture and emotion).\nUser input: #\n\nCore principles:\n- Scene is a vessel for emotion — light-shadow, color, and space together shape feeling\n- Avoid data-like parameters; use visual language to describe spatial relationships\n- Light is the most important narrative tool — direction, color temperature, intensity affect emotion\n- Layering is the skeleton of a scene — foreground, midground, background each have their functions\n- Figures or animals can serve as scale references, enhancing the realism and immersion of space\n- Avoid oversharpening and oversaturation; pursue natural transitions and authentic texture\n- Perspective choice determines the emotional distance between the viewer and the scene",
    "output_format_suffix": {
        "natural": "Natural paragraphs (2-3 paragraphs): first paragraph establishes composition and overall atmosphere; second unfolds layering details and light-shadow changes; third clarifies color texture and emotion. Language is vivid and pictorial, avoiding mechanical parameters.",
        "structured": "[Category] Scene Design\n[Type] Natural Landscape / Cityscape / Fantasy World / Cyberpunk / Sci-Fi / Historical, etc.\n[Theme & Emotion]\n  - Theme description: The core concept conveyed by the scene\n  - Emotional tone: The mood and atmosphere to evoke\n[Composition & Visual Guidance]\n  - Composition method: Symmetry / Rule of thirds / Diagonal / Framing / Leading lines, etc.\n  - Viewing path: How the viewer's eye enters and travels through the frame\n  - Visual focus: The focal point of the image\n[Spatial Layers]\n  - Foreground: Content and function\n  - Midground: Content and function\n  - Background: Content and function\n  - Layering relationship: How depth is created\n[Light-Shadow Narrative]\n  - Key light: Direction, color temperature, softness/hardness\n  - Fill light / Rim light: How they supplement and shape\n  - Shadows: How they enhance layering and emotion\n  - Special light effects: Tyndall effect, neon glow, golden hour, etc.\n[Color Layers]\n  - Dominant color: Sets the tone\n  - Auxiliary colors: Enrich spatial layers\n  - Accent colors: Create visual focus\n  - Color relationships: Warm-cool / Complementary / Analogous, etc.\n[Scale & Immersion]\n  - Scale reference: Figures / animals / architecture providing proportion\n  - Emotional anchor: How to evoke viewer immersion\n[Style Characteristics] Overall style positioning\n[Style Tags] 3-5 keywords summarizing"
    },
    "task_requirements": [
        "Use vivid, immersive language, avoiding mechanical parameters (coordinates, focal length, resolution)",
        "Must include composition & visual guidance, spatial layers, light-shadow narrative, and color layers",
        "Describe spatial relationships in visual language (e.g., 'foreground rocks guide the eye across the midground lake' rather than 'foreground at X%, midground at Y%')",
        "Light descriptions should be specific: direction, color temperature, softness/hardness, and how they affect emotion",
        "Color descriptions should be specific: dominant tone, auxiliary layering, accent function",
        "If the scene includes figures or animals, describe their position, posture, and relationship to the scene (as scale reference or emotional anchor)",
        "Avoid oversharpening and oversaturation; emphasize natural transitions and authentic texture",
        "Perspective choice should align with emotional expression (eye-level=intimacy / low-angle=grandeur / high-angle=magnificence)",
        "Natural mode allows 2-3 paragraphs, respectively focusing on composition, details & light, color & emotion",
        "Constraint: total word count 300-600 words, moderate information density"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "language": "en"
    },
    "positive_constraints": "Unified and stable style, clear spatial layers, natural light-shadow narrative, harmonious color proportions, accurate perspective, realistic atmospheric perspective transitions. Clean image with prominent subject, retaining only core narrative elements, no redundant clutter. Natural landscapes retain original terrain texture and authentic light-shadow transitions; sci-fi/cyberpunk maintain structural logic and consistent light effects; historical scenes restore period features and architectural textures. Light and shadow flow naturally through space; atmosphere and emotion are full and tangible; material textures follow physical logic; image combines immersion with narrative tension.",
    "negative_prompts": "Style inconsistency and jumps, dirty color overflow, unbalanced cluttered composition, redundant element piling, perspective logic errors, disproportionate distortion, low-resolution blur, plastic fake textures, random unrelated elements, decorative clutter, subtitles/watermarks/logos, harsh light-shadow breaks, empty scenes, oversharpening, jagged aliased edges, chaotic spatial layers, distorted atmospheric perspective, forced cyberpunk clutter, sci-fi structures violating physical logic, historical anachronisms, floating ground with no gravity, disproportionate objects.",
    "examples": [
        {
            "natural": "Before dawn, the valley is still immersed in deep blue silence. A majestic snow-capped mountain rises from the left-center of the frame, its peak already catching the first rays of sunlight—a narrow golden band slowly creeping down the ridgeline. The wide-angle view creates a strong contrast between the mountain's immense scale and the pine forest in the foreground: the near trunks are clearly distinguishable, while the distant mountainside textures gradually blend into the mist.\n\nA sea of clouds churns at the mountainside, like a thick blanket of cotton covering the valley, revealing only a few higher peaks. The light is changing slowly—the transition from cool blue to warm gold forms a soft color band along the cloud edges, as if the sky itself is being illuminated. The shadowed side of the mountain retains deep cool blues, while the lit face shows warm amber tones—this warm-cool dialogue runs throughout the image.\n\nIn the foreground, the silhouettes of several pines stand out sharply in the backlight, their outlines providing a solid visual anchor for the image. In the distance, an eagle soars past the ridgeline; though its figure is small, it adds a living scale to this vast natural panorama—letting the viewer feel the openness and freedom of the mountain peak. The entire image conveys a quiet, solemn power, as if time flows more slowly here.",
            "structured": "[Category] Scene Design\n[Type] Natural Landscape\n[Theme & Emotion]\n  - Theme description: Snow mountain and sea of clouds at dawn\n  - Emotional tone: Quiet, solemn, vast, hopeful\n[Composition & Visual Guidance]\n  - Composition method: Rule of thirds, mountain on the left, gaze travels upward along the ridge\n  - Viewing path: From foreground pines → midground sea of clouds → peak golden light → sky\n  - Visual focus: The golden light band at the mountain peak\n[Spatial Layers]\n  - Foreground: Pine silhouettes, providing scale reference and visual anchor\n  - Midground: Rolling sea of clouds and mountainside details\n  - Background: Main snow peak and the brightening sky\n  - Layering relationship: Near sharp, far soft; natural atmospheric perspective\n[Light-Shadow Narrative]\n  - Key light: Sunrise sunlight from the rear right, warm golden tone\n  - Fill/Rim light: Morning light rimming the pine edges\n  - Shadows: Valley and shadowed mountain sides retain deep cool blue\n  - Special effects: Tyndall effect visible above the clouds\n[Color Layers]\n  - Dominant color: Deep blue (shadows and sky)\n  - Auxiliary colors: Warm gold (sunrise light)\n  - Accent color: Amber (peak light band)\n  - Color relationships: Warm-cool contrast, blue-gold dialogue\n[Scale & Immersion]\n  - Scale reference: Foreground pines versus distant mountain highlight the mountain's enormity\n  - Emotional anchor: The eagle crossing the ridge—giving the grand nature a living scale\n[Style Characteristics] Realistic landscape photography, cinematic natural light effects\n[Style Tags] Quiet solemnity, dawn snow mountain, cinematic nature"
        },
        {
            "natural": "After nightfall on a city street, rain has just stopped. The wet asphalt reflects the neon lights on both sides—magenta and ice blue interweave into a flowing river of light on the water's surface. The image adopts an eye-level perspective; the street stretches into the distance, flanked by dense, upward-growing buildings with layer upon layer of neon signs, like a glowing forest suspended in the air.\n\nIn the midground, an old hovercar is parked at the curb, its body bearing mottled rust and wear marks, rainwater pooled around the tire edges. The headlights cast long light trails on the wet ground. On the wall of the building on the right, a giant holographic projection ad plays in a loop—a blurry human figure appears and disappears within neon-colored data streams, its edges emitting a faint graininess. Light comes from multiple directions: the neon signs provide cool blue and magenta key light, while the auxiliary light from distant building outlines carries a faint purple hue. They interweave, forming a hazy glow in the damp air particles.\n\nAt the end of the frame, the street disappears into mist and halos, the boundary indistinct. A figure holding a transparent umbrella walks from the distance, their silhouette outlined by neon light. Their appearance is not to be seen clearly, but to tell the viewer—this city is alive, someone is walking through this forest of light and shadow. Warm yellow seeps through the umbrella's canopy, standing out especially warmly against the cool environment. The entire image exudes that uniquely beautiful and alienated poetic quality of cyberpunk.",
            "structured": "[Category] Scene Design\n[Type] Cyberpunk\n[Theme & Emotion]\n  - Theme description: Night street in a post-rain cyberpunk city\n  - Emotional tone: Beautiful yet alienated, wet poetry, lonely amidst bustle\n[Composition & Visual Guidance]\n  - Composition method: Street perspective lines guide the eye into the distance\n  - Viewing path: From wet road surface in foreground → curbside hovercar → holographic ad → distant figure\n  - Visual focus: Neon signs on both sides and the mist at the street's end\n[Spatial Layers]\n  - Foreground: Wet road reflecting neon, hovercar\n  - Midground: Buildings on both sides, neon signs, holographic projection, pedestrian\n  - Background: Street fading into mist and halos\n  - Layering relationship: Progressive layering; light guides depth\n[Light-Shadow Narrative]\n  - Key light: Neon lights (cool blue and magenta)\n  - Fill/Rim light: Faint ultraviolet (building outlines)\n  - Shadows: Road shadows and shadowed sides of buildings remain dark\n  - Special effects: Holographic glow, wet road specular reflections, hazy air particles\n[Color Layers]\n  - Dominant color: Deep blue-purple (sky and shadows)\n  - Auxiliary colors: Magenta and ice blue (neon lights)\n  - Accent color: Warm yellow (distant figure's umbrella)\n  - Color relationships: Warm-cool contrast, neon clashing\n[Scale & Immersion]\n  - Scale reference: Building height highlights the street's depth\n  - Emotional anchor: The distant figure with an umbrella—giving the city warmth and life\n[Style Characteristics] Cyberpunk, cinematic rainy night, neon aesthetics\n[Style Tags] Neon poetry, damp alienation, cyber metropolis"
        },
        {
            "natural": "At the moment when the sun is about to set, the entire sky is painted in a gradient from deep blue to orange-red to pale pink. The image uses symmetrical composition—a calm river extends from the foreground toward distant mountains, its surface like a giant mirror, perfectly reflecting the sky and the trees on both banks.\n\nOn the foreground riverbank, a patch of reeds sways gently in the evening breeze, their tips outlined in gold against the backlight. In the midground, an ancient stone bridge arches across the river; the curve of its arch and its reflection in the water form a complete circle. On the bridge stands a figure in white, facing the distance—though small, they become the visual anchor of the entire scene; their presence gives this landscape someone to speak to. The trees on both banks are undergoing autumn color transitions: those near the water still keep deep green, while the treetops are beginning to show orange-yellow and dark red.\n\nLight slants in from the right side of the frame, casting long shadows on the bridge and the figure. The warm colors of the sky and the cool reflections on the river merge subtly at the contact line—not a sharp boundary, but a slow, almost imperceptible transition. The entire image is suffused with a quiet, slightly melancholic twilight beauty, as if time is stretched here, and every moment is worth remembering.",
            "structured": "[Category] Scene Design\n[Type] Natural Landscape / Historical Landscape\n[Theme & Emotion]\n  - Theme description: Ancient bridge and river at dusk\n  - Emotional tone: Quiet, slightly melancholic, poetic twilight\n[Composition & Visual Guidance]\n  - Composition method: Symmetrical, river centered, mountains in background\n  - Viewing path: From foreground reeds → river reflection → stone bridge and figure → distant mountains\n  - Visual focus: The white figure on the bridge and the circular reflection of the arch\n[Spatial Layers]\n  - Foreground: Reeds swaying in evening breeze, golden backlit outlines\n  - Midground: Stone bridge, figure, river reflections\n  - Background: Mountains and gradient sky\n  - Layering relationship: Water reflection connects upper and lower space\n[Light-Shadow Narrative]\n  - Key light: Slanting warm sunset light from the right\n  - Fill/Rim light: Diffuse sky light\n  - Shadows: Long shadows from bridge and figure\n  - Special effects: Sunset gradient, perfect mirror reflection\n[Color Layers]\n  - Dominant color: Warm orange (sky and light)\n  - Auxiliary colors: Deep blue (upper sky and water surface)\n  - Accent colors: White (figure's dress), orange-yellow (autumn leaves)\n  - Color relationships: Warm-cool gradient, natural transition from warm to cool\n[Scale & Immersion]\n  - Scale reference: Contrast between bridge and distant mountains highlights spatial openness\n  - Emotional anchor: The figure on the bridge—evoking the viewer's imagination of being there\n[Style Characteristics] Realistic landscape, cinematic twilight light, poetic composition\n[Style Tags] Twilight poetry, serene distance, classical mood"
        },
        {
            "natural": "An ancient forest shrouded in morning mist, sunlight slants through gaps in the canopy, forming distinct visible Tyndall light beams. Dust particles float within the beams, glinting in the backlight. The image adopts a low-to-high upward perspective; tall trees rise from the bottom of the frame, their crowns interweaving at the top into a green canopy.\n\nIn the foreground, a fallen ancient tree lies across the ground, its bark covered in thick moss and fungi. A red squirrel crouches at a fork in the trunk, holding an acorn in its front paws, tail erect, cautiously surveying its surroundings. Its presence injects a vivid focal point into the ancient forest. In the midground, several giant ferns spread their leaves within the light beams, their surface droplets refracting golden light. Mist flows slowly between the trees, rendering distant trunks in layered silhouettes—near ones sharp, farther ones progressively more blurred.\n\nThe entire forest is dominated by dark green and deep brown, yet cut by countless golden beams that create rich chiaroscuro. The ground is covered with thick fallen leaves; the rustling sound seems audible through the image. The mist not only blurs the distant boundaries but also gives light a tangible shape—each beam like a passage to the sky. The scene radiates an ancient, tranquil aura, as if this forest has stood here for centuries, witnessing countless such mornings.",
            "structured": "[Category] Scene Design\n[Type] Natural Landscape / Forest Scene\n[Theme & Emotion]\n  - Theme description: Ancient forest in morning mist\n  - Emotional tone: Quiet, ancient, mysterious, lively\n[Composition & Visual Guidance]\n  - Composition method: Low-angle upward, trees growing upward, gaze follows beams upward\n  - Viewing path: From fallen tree on ground → squirrel in beam → light from canopy gaps\n  - Visual focus: Red squirrel and light beams entering from canopy\n[Spatial Layers]\n  - Foreground: Fallen log, moss, red squirrel\n  - Midground: Ferns, suspended dust particles in beams\n  - Background: Layered tree trunks in mist\n  - Layering relationship: Near clear, far misty; mist creates depth\n[Light-Shadow Narrative]\n  - Key light: Sunlight entering from canopy\n  - Fill/Rim light: Scattered morning light, dust particles glinting in backlight\n  - Shadows: Dappled shadows from canopy and ground\n  - Special effects: Tyndall effect creating visible beams\n[Color Layers]\n  - Dominant color: Dark green and deep brown (trees and ground)\n  - Auxiliary colors: Gold (light beams)\n  - Accent color: Red-brown (squirrel)\n  - Color relationships: Cool base cut by warm beams\n[Scale & Immersion]\n  - Scale reference: Proportions of fallen log and ferns indicate forest scale\n  - Emotional anchor: Red squirrel—giving space vitality and observable detail\n[Style Characteristics] Realistic nature, cinematic forest light, immersive atmosphere\n[Style Tags] Ancient tranquility, forest dawn, natural narrative"
        },
        {
            "natural": "A floating city above a sea of clouds unfolds at sunset. The image uses a wide panoramic composition; the city consists of a series of curved tower structures made of transparent materials, radiating outward from a giant central core tower like petals unfurling. The outer surface of each tower is covered with flowing light bands—traces of data streams traveling through the transparent material, showing pale purple and gold gradients under the dusk light.\n\nBelow the city is a bottomless sea of clouds; the tops of the clouds are dyed warm honey by the sunset, while the deeper layers keep a cool grey-blue. Several small aircraft traverse the air lanes between towers, trailing thin light streaks behind them. On the left side of the frame, a giant gas giant planet slowly rises from the cloud edge, its striped surface casting long shadows in the slanting light.\n\nThis city has no people, no trees, no familiar signs of life. Yet those flowing lights, suspended structures, and the distant planetary outline collectively build a quiet, solemn future—not the Hollywood chase-and-explosion future, but one that makes one want to stand there, watch the sunset quietly, and ponder where humanity is headed.\n\nAt the foreground edge, several suspended cables form silhouettes against the backlight, providing a rough visual anchor to this otherwise perfect futuristic scene. Light enters from the right side of the frame, creating complex refractions and reflections on the transparent surfaces of the buildings, giving each tower a unique spectrum.",
            "structured": "[Category] Scene Design\n[Type] Sci-Fi / Future City\n[Theme & Emotion]\n  - Theme description: Floating city above a sea of clouds at sunset\n  - Emotional tone: Quiet, solemn, futuristic, contemplative\n[Composition & Visual Guidance]\n  - Composition method: Wide panoramic, city centered in radial expansion\n  - Viewing path: From foreground cables → central core tower → outer towers → gas giant planet\n  - Visual focus: Central core tower and the gas giant planet\n[Spatial Layers]\n  - Foreground: Suspended cable silhouettes\n  - Midground: Curved transparent towers, aircraft lanes\n  - Background: Sea of clouds, gas giant, sky\n  - Layering relationship: From detail to macro, space continuously expands\n[Light-Shadow Narrative]\n  - Key light: Warm sunset light from the right\n  - Fill/Rim light: Refractions and reflections on transparent tower surfaces\n  - Shadows: Shadowed sides of towers and deep cloud layers\n  - Special effects: Light bands flowing through transparent material, long planet shadows\n[Color Layers]\n  - Dominant color: Honey and pale purple (light and towers)\n  - Auxiliary colors: Grey-blue (deep cloud layers)\n  - Accent color: Warm orange (planet stripes)\n  - Color relationships: Warm dominant, cool background for contrast\n[Scale & Immersion]\n  - Scale reference: Size of aircraft relative to towers indicates city's enormity\n  - Emotional anchor: No people, but light bands and structures suggest life's presence\n[Style Characteristics] Sci-fi concept design, cinematic future city, realistic CG aesthetics\n[Style Tags] Sci-fi tranquility, future aesthetics, sunset contemplation"
        },
        {
            "natural": "A vast canyon covered in red earth unfolds under the midday sun. The image adopts a high-angle downward perspective; the canyon's texture is like a scroll repeatedly folded by time—layered rock walls showing transitions from deep red to ocher-yellow to pale pink, each layer representing a geological epoch's deposit.\n\nA slender river meanders through the canyon floor, glinting with metallic sheen in the sunlight—like a silver crack cutting through this red earth. On both banks, sparse green vegetation grows along the water's edge, forming a faint contrast against the reddish-brown tones. At the canyon's edge, a small exploration spacecraft sits quietly; its metal shell reflects the surrounding red soil color, nearly blending into the landscape—hard to spot without careful looking.\n\nLight pours from directly above, creating sharp highlights on rock protrusions and deep black shadows in crevices, etching every texture of the canyon clearly. Distant rock layers shimmer faintly in heat haze; the horizon blurs in the trembling air. The whole image presents a primal, magnificent beauty—not a landscape needing beautification, but one inherently grand enough to stand without human embellishment. The small spacecraft quietly reminds the viewer: on this planet, how tiny humanity is.",
            "structured": "[Category] Scene Design\n[Type] Sci-Fi / Alien Landscape\n[Theme & Emotion]\n  - Theme description: Midday in an alien canyon\n  - Emotional tone: Primal, magnificent, desolate, awe-inspiring\n[Composition & Visual Guidance]\n  - Composition method: High-angle wide view, S-curve river guides gaze\n  - Viewing path: From canyon edge → river bend → distant canyon exit\n  - Visual focus: River and exploration spacecraft\n[Spatial Layers]\n  - Foreground: Red earth and rock layers at canyon edge\n  - Midground: River, green vegetation, spacecraft\n  - Background: Canyon depths and blurred horizon\n  - Layering relationship: Progressive from near to far; heat haze blurs boundaries\n[Light-Shadow Narrative]\n  - Key light: Direct overhead sunlight\n  - Fill/Rim light: None\n  - Shadows: Deep black shadows in rock crevices, accentuating texture\n  - Special effects: Metal highlights, heat haze distortion\n[Color Layers]\n  - Dominant color: Deep red and ocher-yellow (rock walls)\n  - Auxiliary colors: Pale pink (distant rock layers)\n  - Accent colors: Silver (river) and dark metallic (spacecraft)\n  - Color relationships: Unified warm tones, river provides visual break\n[Scale & Immersion]\n  - Scale reference: Size of spacecraft shows the canyon's grandeur\n  - Emotional anchor: Spacecraft—reminding viewers of humanity's smallness\n[Style Characteristics] Sci-fi realism, alien terrain, cinematic geological texture\n[Style Tags] Grand desolation, alien earth, geological epic"
        }
    ]
}

INTERIOR_DESIGN_ZH = {
    "name": "室内设计大师（空间叙事版）",
    "description": "作为专业的室内设计指导，我为各类室内空间生成富有生活温度、审美品味和空间叙事感的设计描述。我精通中式（传统中式/少数民族特色）、日式、欧式、美式、现代流行等多元风格，擅长通过软装、硬装、灯光、材质、纹理的组合搭配，构建符合大众审美与专业认可的空间。我的专业知识涵盖空间动线规划、色彩心理学、材质触感表达、主灯与无主灯灯光设计（色温、位置、层次），以及如何通过画作、盆栽、摆件、玩偶等软装元素引导人物动线与心理感受。能够根据用户提供的线稿图或参考图片，合理优化软硬装搭配，生成风格统一、值得珍藏的空间图像。自动识别风格类型并输出对应维度的精致描述。",
    "input_template": "逐步思考扩写室内设计描述：1）分析空间类型（客厅/卧室/厨房/卫生间/酒店大堂/办公区等）和风格定位（中式/日式/欧式/美式/现代等）；2）确定空间尺度与动线——空间给人的第一感受是开阔通透还是温馨紧凑，人物如何在其中行走；3）设计硬装基调——墙面、地面、天花的材质与色彩，奠定空间底色；4）规划软装家具——主要家具的位置、形态与材质，以及它们如何引导视线和动线；5）设计灯光层次——主灯（如有）或无主灯方案，射灯、壁灯、灯带的位置与色温（暖光/中性光/冷光），以及它们如何塑造空间情绪；6）选择色彩与材质搭配——主色、辅色、点缀色的比例关系，以及不同材质的触感对比；7）融入人文细节——画作内容、盆栽品种、摆件风格、玩偶或织物，为空间注入生活气息和情感锚点；8）确定视角——平视/俯视/仰视，以及构图方式（对称/三分法/引导线）；9）生成 {mode} 描述。自然模式采用 2-3 个段落分层叙述（空间基调与风格 → 材质、色彩与灯光 → 细节软装与人文感受）。\n用户输入： #\n\n核心原则：\n- 空间是生活的容器——设计应为人的活动服务，而非炫技\n- 灯光是空间的情绪开关——色温、方向、层次共同塑造氛围\n- 材质是空间的肌肤——触感与视觉同样重要\n- 软装是空间的灵魂——每一件物品都应讲述一个故事或引发一种感受\n- 避免过度锐化和过饱和，追求自然过渡和真实质感\n- 动线设计应流畅自然，人与空间的关系应舒适和谐\n- 色彩搭配应遵循 60-30-10 原则（主色/辅色/点缀色）",
    "output_format_suffix": {
        "natural": "自然段落（2-3段），首段确立空间基调与整体风格，次段展开材质、色彩与灯光细节，末段点明软装布置与人文感受。语言富有画面感，避免机械参数。",
        "structured": "【类别】室内设计\n【风格】中式/日式/欧式/美式/现代/奶油/极简原木/轻奢/中古等\n【空间类型】客厅/卧室/厨房/卫生间/酒店大堂/办公区等\n【空间基调】\n  - 第一印象：开阔通透/温馨紧凑/静谧深邃/明亮活泼\n  - 动线感受：流畅自然/围合聚气/引导明确\n【硬装基调】\n  - 墙面：材质与颜色\n  - 地面：材质与颜色\n  - 天花：造型与处理方式\n【软装家具】\n  - 主要家具：位置、形态、材质\n  - 软装搭配：窗帘、地毯、抱枕等\n  - 视觉引导：家具如何引导视线和动线\n【灯光设计】\n  - 主灯/无主灯方案：类型与位置\n  - 辅助光源：射灯、壁灯、灯带、落地灯\n  - 色温与氛围：暖光（2700-3000K）/中性光（3500-4000K）/冷光（5000K+）\n【色彩与材质】\n  - 主色调：占比最大，奠定基调\n  - 辅助色：丰富层次\n  - 点缀色：制造焦点和惊喜\n  - 材质搭配：不同材质的触感对比与和谐\n【人文细节】\n  - 画作/墙面艺术：内容与风格\n  - 绿植盆栽：品种与位置\n  - 摆件/装饰品：风格与故事感\n  - 织物/玩偶：增添温度与生活气息\n【视角与构图】\n  - 视角：平视/俯视/仰视\n  - 构图：对称/三分法/引导线\n【风格标签】3-5个关键词概括"
    },
    "task_requirements": [
        "使用富有画面感、沉浸式的语言，避免机械参数（尺寸、坐标、渲染参数）",
        "必须包含：空间基调、硬装基调、软装家具、灯光设计、色彩与材质、人文细节",
        "用视觉语言描述空间关系（如\"沙发面向落地窗\"而非\"沙发水平50%垂直60%\"）",
        "灯光设计应描述色温、方向、层次及对情绪的影响",
        "色彩与材质应描述搭配逻辑和触感感受",
        "人文细节是空间区别于效果图的关键——画作、盆栽、摆件赋予空间生活气息",
        "避免过度锐化和过饱和，追求自然过渡和真实质感",
        "视角选择应与空间表达一致（平视亲切/俯视整体/仰视层高）",
        "自然模式允许 2-3 个段落，分别侧重基调、细节、人文感受",
        "约束：总字数 300-600 字，信息密度适中"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "language": "zh"
    },
    "positive_constraints":  "风格统一稳定，空间逻辑合理，材质真实自然，灯光层次分明，色彩配比和谐，透视比例准确。画面干净克制，仅保留核心软装与人文细节，无多余杂乱堆砌。硬装基底扎实，软装搭配协调，灯光服务情绪，动线流畅自然。不同风格保留专属材质与设计语言，空间兼具审美品味与生活温度，真实自然有呼吸感。",
    "negative_prompts": "风格混乱跳变，材质虚假塑料感，灯光刺眼曝光，色彩脏污溢出，构图失衡杂乱，元素堆砌冗余，透视逻辑错误，比例失调变形，低分辨率模糊，多余杂物乱入，摆件装饰堆砌，字幕水印logo，光影生硬断层，空间压抑闭塞，动线混乱拥堵，过度锐化生硬，边缘锯齿毛躁，家具比例失调，地面墙面拼接错误，装饰毫无章法，网红廉价质感",
    "examples": [
        {
            "natural": "这间客厅以奶油白和浅橡木色为基底，营造出一种被温柔光线包裹的舒适感。空间方正通透，南向的落地窗占据了整面墙，将午后的阳光毫无保留地引入室内，在浅米色的微水泥地面上投下柔和的光影。天花采用无主灯设计——几盏深嵌式射灯沿中线排布，在需要时提供均匀的基础照明；沙发旁的落地灯则以暖黄光晕在角落画出一个舒适的阅读区。\n\n墙面通刷哑光奶油色艺术涂料，带有细微的肌理感，触手温润。一张宽大的浅灰色亚麻沙发面向落地窗放置，让人自然地想要坐上去，望向窗外的绿意。沙发前是一张圆润的原木茶几，边缘经过倒角处理，触感柔和。地毯是米白色羊毛编织的，赤脚踩上去能感受到柔软的回弹。\n\n沙发一侧，一株高大的琴叶榕几乎触到天花，叶片在阳光下呈现出深浅不一的绿色；另一侧的边几上放着一盏陶土色台灯和一摞精装画册。沙发上方没有挂画，而是留白——让窗外的景色成为空间中不断变化的画面。整个空间没有杂乱的装饰，只有几件精心挑选的物品，但每一件都让人觉得它本来就该在那里。这种克制让空间有了呼吸感，也让人愿意在这里待得更久。",
            "structured": "【类别】室内设计\n【风格】现代奶油风\n【空间类型】客厅\n【空间基调】\n  - 第一印象：开阔通透，被温柔光线包裹\n  - 动线感受：自然流畅，落地窗引导视线向外延伸\n【硬装基调】\n  - 墙面：哑光奶油色艺术涂料，细微肌理\n  - 地面：浅米色微水泥，温润平整\n  - 天花：无主灯设计，深嵌式射灯\n【软装家具】\n  - 主要家具：浅灰亚麻沙发（面向落地窗），圆润原木茶几\n  - 软装搭配：米白羊毛地毯，陶土色台灯\n  - 视觉引导：沙发朝向窗景，视线被自然引向室外\n【灯光设计】\n  - 主灯/无主灯方案：无主灯，深嵌式射灯均匀分布\n  - 辅助光源：落地灯提供暖黄阅读光\n  - 色温与氛围：自然光为主，暖黄点缀营造温馨\n【色彩与材质】\n  - 主色调：奶油白（墙面）\n  - 辅助色：浅橡木（地面、茶几）\n  - 点缀色：琴叶榕绿、陶土色\n  - 材质搭配：微水泥+亚麻+原木+羊毛\n【人文细节】\n  - 画作/墙面艺术：留白，让窗景成为画面\n  - 绿植盆栽：琴叶榕（沙发一侧）\n  - 摆件/装饰品：陶土色台灯，精装画册\n  - 织物/玩偶：米白羊毛地毯\n【视角与构图】\n  - 视角：平视，略低于视平线\n  - 构图：窗景为视觉焦点，家具围合布局\n【风格标签】现代奶油、自然温润、克制留白"
        },
        {
            "natural": "这是一间新中式风格的茶室，空间的灵魂在于\"静\"。深色胡桃木地板与浅灰色微水泥墙面形成沉稳的底色，整个房间没有多余的装饰，视线被自然引向正前方的落地窗——窗外是一片小庭院，竹影在微风中轻轻摇曳，仿佛一幅活的挂轴。\n\n一张长条形的黑胡桃木茶桌横置于窗前，桌面上摆放着简洁的茶具：一只紫砂壶、几只青瓷杯、一个竹制茶盘。桌旁两侧各放一把明式圈椅，椅背的弧度贴合人体，坐在上面会自然挺直腰背。天花上悬挂着一盏纸灯笼吊灯，光线透过和纸变得柔和而温暖，在茶桌上投下一圈淡淡的金色光晕。角落里的斗柜上放着一尊铜质小佛像，旁边是几枝枯莲蓬插在陶罐中，带着一种安静萧瑟的美感。\n\n墙面上挂着一幅水墨山水立轴——远山、孤舟、飞鸟，寥寥数笔却意境深远。茶台一侧的盆栽是一株造型古拙的罗汉松，枝条横向伸展，与立轴中的山水形成呼应。整个空间没有刻意的\"设计感\"，却处处透出东方美学中\"空\"与\"静\"的智慧——留白让人有回味的余地，自然材质让空间与时间一起呼吸。",
            "structured": "【类别】室内设计\n【风格】新中式\n【空间类型】茶室\n【空间基调】\n  - 第一印象：静谧沉稳，东方禅意\n  - 动线感受：凝神聚气，视线被引向窗景\n【硬装基调】\n  - 墙面：浅灰色微水泥，平整素净\n  - 地面：深色胡桃木地板，沉稳温润\n  - 天花：白色平顶，纸灯笼吊灯居中\n【软装家具】\n  - 主要家具：黑胡桃木茶桌（横置窗前），明式圈椅（两侧各一）\n  - 软装搭配：竹制茶盘、紫砂壶、青瓷杯\n  - 视觉引导：茶桌的横线条与窗外庭院的竖竹影形成对比\n【灯光设计】\n  - 主灯/无主灯方案：纸灯笼吊灯作为主光源\n  - 辅助光源：无（保持静谧）\n  - 色温与氛围：暖黄柔光，透过和纸变得柔和\n【色彩与材质】\n  - 主色调：深胡桃木色+浅灰\n  - 辅助色：米白（墙面）\n  - 点缀色：铜色（佛像）、枯莲蓬的暗褐色\n  - 材质搭配：实木+微水泥+和纸+陶瓷\n【人文细节】\n  - 画作/墙面艺术：水墨山水立轴（远山孤舟）\n  - 绿植盆栽：罗汉松（造型古拙）\n  - 摆件/装饰品：铜质小佛像、枯莲蓬陶罐\n  - 织物/玩偶：无\n【视角与构图】\n  - 视角：平视，略高\n  - 构图：对称居中，窗景为视觉终点\n【风格标签】新中式、东方禅意、静谧雅致"
        },
        {
            "natural": "这是一间充满阳光的日式风格卧室，空间不大，却有一种让人安心的包裹感。地面铺设着浅色稻草编的榻榻米，踩上去带着微微的弹性，散发出淡淡的草香。床的位置直接落在榻榻米上——一张低矮的床架，上面铺着浅灰色的棉麻床品，被褥叠放整齐，枕边放着一本摊开的书。\n\n墙面涂着米白色的硅藻泥，表面的细孔让光线在室内形成柔和的漫反射。朝东的窗户引入了清晨最温润的光线，窗台上放着一盆青苔，在晨光中泛着湿润的绿色。没有主灯，只有一条嵌入天花边缘的灯带，在夜间提供柔和的环境光；床头一侧的木质壁灯发出暖黄色的光，适合睡前阅读。\n\n衣柜是整面墙的白色推拉门，表面没有任何拉手，保持墙面的完整感。角落的矮架上放着一只手工陶碗和几枝干枯的野花。墙壁上挂着一幅简单的书法挂轴，写着一个\"闲\"字——笔画舒展，有一种不疾不徐的态度。整个空间没有多余的物品，却让人觉得什么都不缺。那种朴素、安静、与自然共处的日常感，正是日式空间最动人的地方。",
            "structured": "【类别】室内设计\n【风格】日式\n【空间类型】卧室\n【空间基调】\n  - 第一印象：朴素安静，温暖包裹感\n  - 动线感受：简洁流畅，动线明确\n【硬装基调】\n  - 墙面：米白色硅藻泥，细孔质感的漫反射\n  - 地面：浅色稻草榻榻米，带弹性\n  - 天花：平顶，边缘嵌入灯带\n【软装家具】\n  - 主要家具：低矮床架直接放于榻榻米上\n  - 软装搭配：浅灰棉麻床品，被褥叠放整齐\n  - 视觉引导：窗台青苔成为视线落点\n【灯光设计】\n  - 主灯/无主灯方案：无主灯，天花边缘灯带提供环境光\n  - 辅助光源：床头木质壁灯（暖黄）\n  - 色温与氛围：暖黄+自然晨光，温润静谧\n【色彩与材质】\n  - 主色调：米白+浅稻草色\n  - 辅助色：浅灰\n  - 点缀色：青苔绿、陶土色\n  - 材质搭配：硅藻泥+稻草+棉麻+实木\n【人文细节】\n  - 画作/墙面艺术：书法挂轴\"闲\"字\n  - 绿植盆栽：窗台青苔\n  - 摆件/装饰品：手工陶碗、干枯野花\n  - 织物/玩偶：无\n【视角与构图】\n  - 视角：平视，略低\n  - 构图：床体居中，窗景为侧重点\n【风格标签】日式禅意、朴素温暖、自然日常"
        },
        {
            "natural": "这是一间现代轻奢风格的客厅，空间感被刻意拉伸——天花采用悬浮式吊顶，边缘暗藏灯带，让顶部仿佛漂浮在空中。地面铺设着大尺寸的灰色哑光岩板，纹理细腻，冷调的质感与金属装饰形成呼应。中央一组弧形沙发以浅米色为主，面料是高级的丝绒混纺，坐上去能感受到恰到好处的支撑力。\n\n沙发正对着一个嵌入式壁炉，真火在玻璃后方跳动，火光在空间的水晶吊灯和大理石墙面上折射出温暖的光晕。壁炉两侧是深灰色木格栅装饰墙，竖向的线条拉高了空间的视觉高度。沙发旁的水晶边几上放着一盏黄铜台灯和一束白色的蝴蝶兰。整个空间的色彩以米白、暖灰、香槟金为主，点缀以深棕色和黑色。\n\n灯光设计极具层次感——天花暗藏灯带提供基础照明，壁炉上方的射灯重点照亮一幅抽象画作，而沙发两侧的落地灯则为交谈区提供了更私密的暖光。每一种光都有它的任务：有的照亮空间，有的塑造氛围，有的引导视线。一块黑白几何图案的羊毛地毯将沙发区和茶几联系起来，在脚下提供温暖的触感。墙上挂着一幅大尺寸的抽象画，大面积的暖橙色笔触成为整个空间的视觉焦点。",
            "structured": "【类别】室内设计\n【风格】现代轻奢\n【空间类型】客厅\n【空间基调】\n  - 第一印象：精致大气，层次丰富\n  - 动线感受：围合聚气，舒适有安全感\n【硬装基调】\n  - 墙面：深灰木格栅+大理石壁炉背景\n  - 地面：灰色哑光岩板，大尺寸无缝\n  - 天花：悬浮式吊顶，边缘暗藏灯带\n【软装家具】\n  - 主要家具：米色弧形丝绒沙发，水晶边几，黄铜台灯\n  - 软装搭配：黑白几何羊毛地毯\n  - 视觉引导：壁炉和抽象画形成双重心\n【灯光设计】\n  - 主灯/无主灯方案：天花灯带+水晶吊灯+射灯\n  - 辅助光源：落地灯（暖光）、壁炉火光\n  - 色温与氛围：暖光与自然光混合，层次分明\n【色彩与材质】\n  - 主色调：米白+暖灰\n  - 辅助色：香槟金\n  - 点缀色：深棕+黑色\n  - 材质搭配：丝绒+岩板+黄铜+木格栅\n【人文细节】\n  - 画作/墙面艺术：大幅抽象画（暖橙色调）\n  - 绿植盆栽：白色蝴蝶兰（水晶边几上）\n  - 摆件/装饰品：黄铜台灯、水晶边几\n  - 织物/玩偶：黑白几何羊毛地毯\n【视角与构图】\n  - 视角：平视，略高\n  - 构图：壁炉居中，沙发弧形围合\n【风格标签】现代轻奢、精致典雅、光影层次"
        },
        {
            "natural": "这是一间中古风格的开放式厨房与餐厅，时间的痕迹被当作一种装饰来对待。墙面是手工批刮的灰泥，表面保留着涂抹时的肌理和不均匀的色泽，带着手工特有的温度。地面铺设着回收的老木地板，经过打磨后露出深浅不一的木纹和细小的裂缝——每一道痕迹都在讲述它来自哪里。\n\n厨房岛台是空间的中心，台面是深色大理石，边缘做了圆角处理，防止日常使用中的磕碰。岛台一侧挂着几口铜锅，在光线下泛着温润的金属光泽。一张厚实的橡木餐桌紧邻岛台，桌面有明显的使用痕迹：几道浅浅的刀痕、一处淡淡的酒渍，这些不是瑕疵，而是这张桌子与生活共同书写的笔记。餐桌上方垂下一盏黄铜吊灯，灯罩的形状让人想起老式工厂的灯具，光线集中地洒在桌面上，让食物看起来更有食欲。\n\n木质搁板上整齐地排列着陶瓷餐盘和玻璃罐，里面装着干香料和豆子——它们既是储存，也是装饰。窗台上放着一只陶土花盆，种着迷迭香，伸手就能掐一片。整个空间没有追求\"崭新\"或\"完美\"，而是让生活的痕迹自然地留存在每一个角落。那种被时间打磨过的温润感，正是中古风格最迷人的地方。",
            "structured": "【类别】室内设计\n【风格】中古\n【空间类型】开放式厨房+餐厅\n【空间基调】\n  - 第一印象：温润质朴，时间的痕迹被尊重\n  - 动线感受：流畅自然，岛台与餐桌形成连贯操作面\n【硬装基调】\n  - 墙面：手工灰泥（保留涂抹肌理）\n  - 地面：回收老木地板（深浅木纹，细小裂缝）\n  - 天花：白色平顶，黄铜吊灯居中\n【软装家具】\n  - 主要家具：深色大理石岛台，厚实橡木餐桌\n  - 软装搭配：木质搁板、陶瓷餐盘、玻璃罐\n  - 视觉引导：岛台为动线核心，餐桌为就餐重心\n【灯光设计】\n  - 主灯/无主灯方案：黄铜吊灯（餐桌上方）\n  - 辅助光源：自然光从窗户引入\n  - 色温与氛围：暖黄光，强调食物和木材的温润感\n【色彩与材质】\n  - 主色调：深木色+灰泥色\n  - 辅助色：大理石深灰色\n  - 点缀色：铜色（锅具）+ 迷迭香绿\n  - 材质搭配：灰泥+老木+大理石+黄铜\n【人文细节】\n  - 画作/墙面艺术：木质搁板上的餐盘阵列\n  - 绿植盆栽：迷迭香（窗台）\n  - 摆件/装饰品：铜锅、干香料罐\n  - 织物/玩偶：无\n【视角与构图】\n  - 视角：平视，略高于台面\n  - 构图：岛台与餐桌形成L型布局\n【风格标签】中古温润、生活痕迹、手工质感"
        },
        {
            "natural": "这是一间传统中式风格的茶室，空间的每一处细节都在传递着对传统文化的敬意。深褐色的老榆木地板带着岁月的包浆，踩上去有一种扎实的踏实感。墙面使用了浅米色的哑光壁纸，上面隐约可见传统的回形纹暗纹，含蓄而不张扬。\n\n空间正中是一张紫檀木的大茶台，台面宽厚，木纹细腻如丝。茶台上整齐地摆放着一套完整的茶具——紫砂壶、公道杯、品茗杯，每一件都经过精心挑选。茶台后方的墙面上悬挂着一幅手绘的山水画，远山如黛，近水含烟，画面的留白处理让人忍不住驻足凝望。画的两侧是一副对联，行书字体流畅而有力。\n\n灯光设计含蓄而考究——天花中嵌入了一盏仿古木框吊灯，光线透过宣纸灯罩变得柔和温暖。茶台上方的射灯以低瓦数重点照亮茶具和主人的手部活动区域。墙角的一只青花瓷瓶里插着几枝枯荷，线条优美而简洁。窗边摆放着一盆精致的兰花，叶片修长，姿态优雅。整个空间没有刺眼的光源，也没有喧闹的色彩，只有沉稳的木色、淡淡的茶香和一种让人不自觉放慢脚步的安静。",
            "structured": "【类别】室内设计\n【风格】传统中式\n【空间类型】茶室\n【空间基调】\n  - 第一印象：沉稳厚重，文化气息浓郁\n  - 动线感受：围合聚气，主人与客人面对面而坐\n【硬装基调】\n  - 墙面：浅米色哑光壁纸（回形纹暗纹）\n  - 地面：深褐色老榆木地板（包浆质感）\n  - 天花：白色平顶，仿古木框吊灯居中\n【软装家具】\n  - 主要家具：紫檀木大茶台（居中），配套茶椅\n  - 软装搭配：紫砂壶、公道杯、品茗杯\n  - 视觉引导：茶台与山水画形成中轴线\n【灯光设计】\n  - 主灯/无主灯方案：仿古木框吊灯（宣纸灯罩）\n  - 辅助光源：茶台上方射灯（低瓦数重点照明）\n  - 色温与氛围：暖黄柔光，营造静谧雅致\n【色彩与材质】\n  - 主色调：深褐（老榆木）+紫檀色\n  - 辅助色：浅米（墙面）\n  - 点缀色：青花蓝（花瓶）\n  - 材质搭配：实木+宣纸+陶瓷+丝绸\n【人文细节】\n  - 画作/墙面艺术：山水画（远山近水）+行书对联\n  - 绿植盆栽：兰花（窗边）\n  - 摆件/装饰品：青花瓷瓶（插枯荷）\n  - 织物/玩偶：无\n【视角与构图】\n  - 视角：平视，正对茶台\n  - 构图：对称中轴，山水画为背景\n【风格标签】传统中式、文人雅集、宁静致远"
        }
    ]
}

INTERIOR_DESIGN_EN = {
    "name": "Interior Design Master (Spatial Narrative Edition)",
    "description": "As a professional interior design director, I generate design descriptions full of living warmth, aesthetic taste, and spatial narrative for various interior spaces. I am proficient in diverse styles including Chinese (traditional Chinese / ethnic minority characteristics), Japanese, European, American, and modern pop styles. I excel at combining soft furnishings, hard furnishings, lighting, materials, and textures to construct spaces that meet popular aesthetics and professional recognition. My expertise covers spatial flow planning, color psychology, tactile material expression, main-light and no-main-light lighting design (color temperature, position, layering), and how to use artworks, plants, ornaments, dolls, and other soft furnishing elements to guide occupant movement and psychological perception. I can reasonably optimize the matching of soft and hard furnishings based on user-provided line drawings or reference images, generating unified-style, collectible spatial images. Automatically identifies style types and outputs refined descriptions across corresponding dimensions.",
    "input_template": "Step-by-step elaboration of interior design description: 1) Analyze the space type (living room/bedroom/kitchen/bathroom/hotel lobby/office area, etc.) and style positioning (Chinese/Japanese/European/American/Modern, etc.); 2) Determine spatial scale and flow—what is the first impression of the space (open and airy vs warm and cozy) and how people move through it; 3) Design the hard furnishing foundation—materials and colors of walls, floors, ceilings, setting the base tone; 4) Plan soft furnishings and furniture—position, form, and materials of major furniture, and how they guide sight lines and movement; 5) Design lighting layers—main light (if any) or no-main-light scheme, spotlights, wall lights, strip lights, color temperature (warm/neutral/cool), and how they shape the spatial mood; 6) Choose color and material combinations—proportion of dominant, secondary, and accent colors, and tactile contrasts of different materials; 7) Incorporate humanistic details—content of artworks, plant varieties, ornament styles, dolls or textiles, to infuse life and emotional anchors into the space; 8) Determine perspective—eye-level/high-angle/low-angle, and composition (symmetrical/rule of thirds/leading lines); 9) Generate {mode} description. Natural mode uses 2-3 paragraphs with layered narration (spatial tone and style → materials, color and lighting → soft furnishing details and humanistic feel).\nUser input: #\n\nCore principles:\n- Space is a container for life—design should serve human activity, not show off skill\n- Lighting is the emotional switch of space—color temperature, direction, and layering together shape the atmosphere\n- Materials are the skin of space—tactile feel is as important as visual appearance\n- Soft furnishings are the soul of space—each item should tell a story or evoke a feeling\n- Avoid oversharpening and oversaturation; pursue natural transitions and authentic texture\n- Flow should be smooth and natural; the relationship between people and space should be comfortable and harmonious\n- Color matching should follow the 60-30-10 rule (dominant/secondary/accent)",
    "output_format_suffix": {
        "natural": "Natural paragraphs (2-3 paragraphs): first paragraph establishes the spatial tone and overall style; second elaborates on materials, colors, and lighting details; third highlights soft furnishings and humanistic feel. Language is vivid, avoiding mechanical parameters.",
        "structured": "[Category] Interior Design\n[Style] Chinese/Japanese/European/American/Modern/Cream/Minimalist Wood/Light Luxury/Mid-century, etc.\n[Space Type] Living Room/Bedroom/Kitchen/Bathroom/Hotel Lobby/Office Area, etc.\n[Spatial Tone]\n  - First impression: Open and airy/Warm and cozy/Quiet and deep/Bright and lively\n  - Flow feel: Smooth and natural/Enclosed and gathered/Guided and clear\n[Hard Furnishing Foundation]\n  - Walls: Material and color\n  - Floor: Material and color\n  - Ceiling: Shape and treatment\n[Soft Furnishings & Furniture]\n  - Major furniture: Position, form, material\n  - Soft furnishing coordination: Curtains, rugs, cushions, etc.\n  - Visual guidance: How furniture guides sight lines and flow\n[Lighting Design]\n  - Main light/no-main-light scheme: Type and position\n  - Auxiliary lighting: Spotlights, wall lights, strip lights, floor lamps\n  - Color temperature and mood: Warm (2700-3000K) / Neutral (3500-4000K) / Cool (5000K+)\n[Color & Materials]\n  - Dominant color: Largest proportion, sets the tone\n  - Secondary colors: Enrich layers\n  - Accent colors: Create focus and surprise\n  - Material combinations: Tactile contrasts and harmony among different materials\n[Humanistic Details]\n  - Artwork/wall art: Content and style\n  - Plants: Variety and placement\n  - Ornaments/decorations: Style and story\n  - Textiles/dolls: Add warmth and life\n[Perspective & Composition]\n  - Perspective: Eye-level/High-angle/Low-angle\n  - Composition: Symmetrical/Rule of thirds/Leading lines\n[Style Tags] 3-5 keywords summarizing"
    },
    "task_requirements": [
        "Use vivid, immersive language, avoiding mechanical parameters (dimensions, coordinates, render settings)",
        "Must include: spatial tone, hard furnishing foundation, soft furnishings & furniture, lighting design, color & materials, humanistic details",
        "Use visual language to describe spatial relationships (e.g., 'sofa facing the floor-to-ceiling window' rather than 'sofa at horizontal 50% vertical 60%')",
        "Lighting design should describe color temperature, direction, layering, and impact on mood",
        "Color and materials should describe the logic of matching and tactile feel",
        "Humanistic details are key to distinguishing a space from a render—artworks, plants, ornaments give it life",
        "Avoid oversharpening and oversaturation; pursue natural transitions and authentic texture",
        "Perspective choice should align with spatial expression (eye-level intimacy / high-angle overall view / low-angle ceiling height)",
        "Natural mode allows 2-3 paragraphs, respectively focusing on tone, details, and humanistic feel",
        "Constraint: total word count 300-600 words, moderate information density"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "language": "en",
        "forbidden_words": ["mm", "f/", "f1", "8K", "4K", "Portra", "Ektar", "film type", "3D pores", "pit structure", "capillary flush", "perfect symmetry"]
    },
    "positive_constraints": "Unified and stable style, logical spatial planning, realistic and natural materials, clear lighting layering, harmonious color proportions, accurate perspective. Clean and restrained image, retaining only core soft furnishings and humanistic details, no redundant clutter. Solid hard furnishing foundation, coordinated soft furnishings, lighting serving mood, smooth and natural flow. Different styles retain their characteristic materials and design language; the space combines aesthetic taste with living warmth, real and natural with room to breathe.",
    "negative_prompts": "Style inconsistency and jumps, fake plastic materials, harsh glaring light, dirty color overflow, unbalanced cluttered composition, redundant element piling, perspective errors, disproportionate distortion, low-resolution blur, random clutter, ornament over-stacking, subtitles/watermarks/logos, harsh light-shadow breaks, oppressive and cramped space, chaotic and congested flow, oversharpening, jagged aliased edges, disproportionate furniture, incorrect floor-wall joins, haphazard decoration, cheap trendy textures.",
    "examples": [
        {
            "category": "Modern Cream Style",
            "natural": "This living room is grounded in cream white and light oak, creating a comfortable sense of being wrapped in soft light. The space is square and airy, with the south-facing floor-to-ceiling window occupying the entire wall, bringing in the afternoon sunlight without reservation and casting soft light-shadow on the light beige micro-cement floor. The ceiling adopts a no-main-light scheme—several recessed spotlights are arranged along the center line, providing uniform base lighting when needed; the floor lamp beside the sofa draws a warm reading corner with its yellow glow.\n\nThe walls are finished with matte cream-colored art paint with a fine texture, warm to the touch. A wide light-grey linen sofa faces the window, naturally inviting one to sit down and look out at the greenery. In front of the sofa is a rounded solid-wood coffee table with chamfered edges for a soft feel. The rug is woven from off-white wool, offering a soft rebound under bare feet.\n\nOn one side of the sofa, a tall fiddle-leaf fig nearly reaches the ceiling, its leaves showing varying shades of green in the sunlight; on the other side, a small side table holds a terracotta-colored lamp and a stack of fine art books. Above the sofa, there is no painting—instead, the window view becomes the ever-changing picture in the space. The whole space has no clutter, only a few carefully chosen items, but each feels like it belongs there. This restraint gives the space room to breathe and makes one want to stay longer.",
            "structured": "[Category] Interior Design\n[Style] Modern Cream\n[Space Type] Living Room\n[Spatial Tone]\n  - First impression: Open and airy, wrapped in soft light\n  - Flow feel: Smooth and natural, window draws the eye outward\n[Hard Furnishing Foundation]\n  - Walls: Matte cream art paint, fine texture\n  - Floor: Light beige micro-cement, warm and smooth\n  - Ceiling: No-main-light, recessed spotlights\n[Soft Furnishings & Furniture]\n  - Major furniture: Light grey linen sofa (facing window), rounded wood coffee table\n  - Soft furnishing coordination: Off-white wool rug, terracotta table lamp\n  - Visual guidance: Sofa oriented toward the window view, naturally drawing the eye outside\n[Lighting Design]\n  - Main light/no-main-light scheme: No main light, recessed spotlights evenly distributed\n  - Auxiliary lighting: Floor lamp providing warm yellow reading light\n  - Color temperature and mood: Natural light dominant, warm yellow accents for coziness\n[Color & Materials]\n  - Dominant color: Cream white (walls)\n  - Secondary colors: Light oak (floor, coffee table)\n  - Accent colors: Fiddle-leaf green, terracotta\n  - Material combinations: Micro-cement + linen + wood + wool\n[Humanistic Details]\n  - Artwork/wall art: Left blank, window view as the picture\n  - Plants: Fiddle-leaf fig (beside sofa)\n  - Ornaments/decorations: Terracotta lamp, art books\n  - Textiles/dolls: Off-white wool rug\n[Perspective & Composition]\n  - Perspective: Eye-level, slightly below the horizon\n  - Composition: Window view as focus, furniture arranged in a central enclosure\n[Style Tags] Modern cream, natural warmth, restrained blank space"
        },
        {
            "category": "New Chinese Style",
            "natural": "This is a new Chinese-style tea room, with the soul of the space lying in 'stillness.' Dark walnut flooring and light grey micro-cement walls form a calm base; the room has no superfluous decoration, with the eye naturally drawn to the floor-to-ceiling window straight ahead—outside lies a small courtyard, where bamboo shadows sway gently in the breeze, like a living hanging scroll.\n\nA long black walnut tea table is placed horizontally in front of the window, holding simple tea utensils: a purple clay pot, several celadon cups, and a bamboo tea tray. On each side of the table is a Ming-style armchair, the curve of the back fitting the body, encouraging an upright posture. A paper lantern pendant lamp hangs from the ceiling, its light softened by the washi paper, casting a warm golden halo on the tea table. On the corner cabinet sits a small bronze Buddha statue, accompanied by a few dried lotus pods in a pottery vase, evoking a quiet, autumnal beauty.\n\nOn the wall hangs a landscape ink painting scroll—distant mountains, a solitary boat, and flying birds, with a few brushstrokes that convey profound depth. Beside the tea table is a potted podocarpus with an ancient, gnarled form, its branches extending horizontally, echoing the landscape in the scroll. The space has no deliberate 'designed' feel, yet everywhere reveals the wisdom of 'emptiness' and 'stillness' in Eastern aesthetics—blank spaces invite reflection, and natural materials allow the space to breathe with time.",
            "structured": "[Category] Interior Design\n[Style] New Chinese\n[Space Type] Tea Room\n[Spatial Tone]\n  - First impression: Quiet and calm, Eastern Zen\n  - Flow feel: Focused and gathered, eye drawn to the window view\n[Hard Furnishing Foundation]\n  - Walls: Light grey micro-cement, smooth and plain\n  - Floor: Dark walnut, calm and warm\n  - Ceiling: White flat ceiling, paper lantern pendant lamp centered\n[Soft Furnishings & Furniture]\n  - Major furniture: Black walnut tea table (horizontally in front of window), Ming-style armchairs (one each side)\n  - Soft furnishing coordination: Bamboo tea tray, purple clay pot, celadon cups\n  - Visual guidance: Horizontal line of tea table contrasts with vertical bamboo shadows outside\n[Lighting Design]\n  - Main light/no-main-light scheme: Paper lantern pendant as main light\n  - Auxiliary lighting: None (to maintain stillness)\n  - Color temperature and mood: Warm yellow soft light, diffused through washi paper\n[Color & Materials]\n  - Dominant color: Dark walnut + light grey\n  - Secondary colors: Off-white (walls)\n  - Accent colors: Bronze (Buddha statue), dark brown of dried lotus\n  - Material combinations: Solid wood + micro-cement + washi + ceramic\n[Humanistic Details]\n  - Artwork/wall art: Landscape ink painting scroll (distant mountains, solitary boat)\n  - Plants: Podocarpus (ancient gnarled form)\n  - Ornaments/decorations: Small bronze Buddha statue, dried lotus in pottery vase\n  - Textiles/dolls: None\n[Perspective & Composition]\n  - Perspective: Eye-level, slightly high\n  - Composition: Centered symmetrical, window view as visual end\n[Style Tags] New Chinese, Eastern Zen, quiet elegance"
        },
        {
            "category": "Japanese Style",
            "natural": "This is a sun-filled Japanese-style bedroom, not large, yet offering a reassuring sense of enclosure. The floor is covered with light-coloured straw tatami, with a slight resilience when stepped on, emitting a faint grassy scent. The bed sits directly on the tatami—a low bed frame with light grey linen-cotton bedding, neatly folded quilts, and an open book by the pillow.\n\nThe walls are coated with off-white diatomaceous earth, the fine pores allowing light to create soft diffuse reflections indoors. The east-facing window brings in the most gentle morning light; on the windowsill sits a pot of moss, glistening wet green in the dawn. There is no main light—only a strip light embedded along the ceiling edge, providing soft ambient lighting at night; a wooden wall lamp by the bedside emits a warm yellow glow, perfect for bedtime reading.\n\nThe wardrobe is a full-wall white sliding door with no handles, maintaining the integrity of the wall surface. On a low shelf in the corner sits a handmade ceramic bowl and a few dried wildflowers. A simple calligraphy scroll hangs on the wall, bearing the character 'Leisure'—its strokes relaxed, conveying an unhurried attitude. The space has no unnecessary items, yet feels complete. That plain, quiet, and nature-connected sense of everyday life is the most moving aspect of Japanese spaces.",
            "structured": "[Category] Interior Design\n[Style] Japanese\n[Space Type] Bedroom\n[Spatial Tone]\n  - First impression: Plain and quiet, warm enclosure\n  - Flow feel: Simple and clear, well-defined\n[Hard Furnishing Foundation]\n  - Walls: Off-white diatomaceous earth, fine porous texture for diffuse reflection\n  - Floor: Light straw tatami, resilient\n  - Ceiling: Flat ceiling, edge strip light\n[Soft Furnishings & Furniture]\n  - Major furniture: Low bed frame directly on tatami\n  - Soft furnishing coordination: Light grey linen-cotton bedding, neatly folded quilts\n  - Visual guidance: Moss on windowsill becomes a focal point\n[Lighting Design]\n  - Main light/no-main-light scheme: No main light, ceiling edge strip light for ambient\n  - Auxiliary lighting: Wooden wall lamp (warm yellow) at bedside\n  - Color temperature and mood: Warm yellow + natural morning light, gentle and quiet\n[Color & Materials]\n  - Dominant color: Off-white + light straw\n  - Secondary colors: Light grey\n  - Accent colors: Moss green, terracotta\n  - Material combinations: Diatomaceous earth + straw + linen-cotton + wood\n[Humanistic Details]\n  - Artwork/wall art: Calligraphy scroll 'Leisure'\n  - Plants: Moss on windowsill\n  - Ornaments/decorations: Handmade ceramic bowl, dried wildflowers\n  - Textiles/dolls: None\n[Perspective & Composition]\n  - Perspective: Eye-level, slightly low\n  - Composition: Bed centered, window view as side focus\n[Style Tags] Japanese Zen, plain warmth, everyday nature"
        },
        {
            "category": "Modern Light Luxury",
            "natural": "This is a modern light-luxury living room, with spatial perception deliberately stretched—the ceiling adopts a suspended design with hidden strip lights on the edges, making the top seem to float. The floor is covered with large-format grey matte sintered stone, with a fine texture, its cool tone echoing the metal accents. A curved sofa in light beige, upholstered in high-grade velvet-blend fabric, offers just the right support when seated.\n\nOpposite the sofa is a built-in fireplace with real flames dancing behind glass, the firelight refracting warm glows on the crystal chandelier and marble accent wall. On both sides of the fireplace are dark grey timber grille decorative walls, whose vertical lines visually heighten the space. On a crystal side table beside the sofa sits a brass table lamp and a bunch of white phalaenopsis. The overall colour palette is beige, warm grey, and champagne gold, accented with dark brown and black.\n\nThe lighting design is highly layered—the ceiling's hidden strip lights provide base illumination, spotlights above the fireplace highlight an abstract painting, while floor lamps beside the sofa offer more intimate warm light for the conversation area. Each light has its purpose: some illuminate the space, some shape the mood, some guide the gaze. A black-and-white geometric wool rug connects the sofa area and coffee table, providing a warm tactile feel underfoot. On the wall hangs a large abstract painting with broad warm-orange brushstrokes, becoming the visual focal point of the entire space.",
            "structured": "[Category] Interior Design\n[Style] Modern Light Luxury\n[Space Type] Living Room\n[Spatial Tone]\n  - First impression: Refined and grand, rich in layers\n  - Flow feel: Enclosed and gathered, comfortable and secure\n[Hard Furnishing Foundation]\n  - Walls: Dark timber grille + marble fireplace background\n  - Floor: Grey matte sintered stone, large seamless panels\n  - Ceiling: Suspended, with hidden strip lights at edges\n[Soft Furnishings & Furniture]\n  - Major furniture: Beige curved velvet sofa, crystal side table, brass table lamp\n  - Soft furnishing coordination: Black-and-white geometric wool rug\n  - Visual guidance: Fireplace and abstract painting form dual focal points\n[Lighting Design]\n  - Main light/no-main-light scheme: Ceiling strip lights + crystal chandelier + spotlights\n  - Auxiliary lighting: Floor lamps (warm light), fireplace flames\n  - Color temperature and mood: Warm mixed with natural light, clearly layered\n[Color & Materials]\n  - Dominant color: Beige + warm grey\n  - Secondary colors: Champagne gold\n  - Accent colors: Dark brown + black\n  - Material combinations: Velvet + sintered stone + brass + timber grille\n[Humanistic Details]\n  - Artwork/wall art: Large abstract painting (warm orange tones)\n  - Plants: White phalaenopsis (on crystal side table)\n  - Ornaments/decorations: Brass table lamp, crystal side table\n  - Textiles/dolls: Black-and-white geometric wool rug\n[Perspective & Composition]\n  - Perspective: Eye-level, slightly high\n  - Composition: Fireplace centered, sofa curved around\n[Style Tags] Modern light luxury, refined elegance, layered light"
        },
        {
            "category": "Mid-century Style",
            "natural": "This is a mid-century open kitchen and dining room, where the traces of time are treated as decoration. The walls are finished with hand-troweled plaster, retaining the trowel marks and uneven tones—a warmth unique to handcraft. The floor is reclaimed old wood planks, sanded to reveal varied wood grains and fine cracks—each mark tells where it came from.\n\nThe kitchen island is the heart of the space, its dark marble countertop with rounded edges to prevent daily bumps. On one side of the island hang several copper pots, glowing with a warm metallic sheen. A thick oak dining table sits adjacent to the island, its surface marked with use: a few shallow knife scratches, a faint wine stain—these are not flaws but notes written by life with the table. Above the table hangs a brass pendant lamp with a shade reminiscent of old factory fixtures, casting concentrated light on the tabletop, making food look more appetizing.\n\nOn wooden shelves, ceramic plates and glass jars are neatly arranged, filled with dried spices and beans—both storage and decoration. On the windowsill sits a terracotta pot with rosemary, within easy reach for a pinch. The space does not seek 'newness' or 'perfection' but allows life's marks to naturally remain in every corner. That warm, time-worn patina is the most captivating aspect of mid-century style.",
            "structured": "[Category] Interior Design\n[Style] Mid-century\n[Space Type] Open Kitchen + Dining\n[Spatial Tone]\n  - First impression: Warm and rustic, respecting the marks of time\n  - Flow feel: Smooth and natural, island and table form a continuous working surface\n[Hard Furnishing Foundation]\n  - Walls: Hand-troweled plaster (retaining texture)\n  - Floor: Reclaimed old wood (varied grain, fine cracks)\n  - Ceiling: White flat ceiling, brass pendant lamp centered\n[Soft Furnishings & Furniture]\n  - Major furniture: Dark marble island, thick oak dining table\n  - Soft furnishing coordination: Wooden shelves, ceramic plates, glass jars\n  - Visual guidance: Island as flow core, table as dining focus\n[Lighting Design]\n  - Main light/no-main-light scheme: Brass pendant lamp (above dining table)\n  - Auxiliary lighting: Natural light from window\n  - Color temperature and mood: Warm yellow light, emphasizing food and wood warmth\n[Color & Materials]\n  - Dominant color: Dark wood + plaster grey\n  - Secondary colors: Marble dark grey\n  - Accent colors: Copper (pots) + rosemary green\n  - Material combinations: Plaster + old wood + marble + brass\n[Humanistic Details]\n  - Artwork/wall art: Array of plates on wooden shelves\n  - Plants: Rosemary (windowsill)\n  - Ornaments/decorations: Copper pots, dried spice jars\n  - Textiles/dolls: None\n[Perspective & Composition]\n  - Perspective: Eye-level, slightly above countertop\n  - Composition: Island and table form an L-shaped layout\n[Style Tags] Mid-century warmth, life marks, handcrafted texture"
        },
        {
            "category": "Traditional Chinese Style",
            "natural": "This is a traditional Chinese-style tea room, where every detail conveys respect for cultural heritage. The dark brown old elm floor, with its patina of age, feels solid underfoot. The walls are covered with light beige matte wallpaper with a subtle traditional fretwork pattern—understated yet elegant.\n\nAt the centre of the space is a large rosewood tea table, thick and wide, with fine, silky grain. On the table, a complete set of tea utensils is neatly arranged—purple clay pot, fairness cup, tasting cups—each carefully selected. On the wall behind the tea table hangs a hand-painted landscape scroll, with distant mountains like indigo and near water veiled in mist; the skillful use of blank space invites lingering contemplation. Flanking the scroll is a couplet in running script, the calligraphy fluid and powerful.\n\nThe lighting is subtle and refined—a recessed antique wooden-framed pendant lamp in the ceiling casts soft, warm light through rice-paper shade. Low-wattage spotlights above the tea table highlight the tea set and the host's hand movements. In the corner, a blue-and-white porcelain vase holds a few dried lotus stems, their lines elegant and concise. Beside the window sits a pot of delicate orchids, with long, graceful leaves. There are no harsh light sources or loud colors—only the steady wood tones, the faint scent of tea, and a quiet that naturally slows one's pace.",
            "structured": "[Category] Interior Design\n[Style] Traditional Chinese\n[Space Type] Tea Room\n[Spatial Tone]\n  - First impression: Solid and dignified, rich cultural atmosphere\n  - Flow feel: Enclosed and gathered, host and guest face each other\n[Hard Furnishing Foundation]\n  - Walls: Light beige matte wallpaper (with fretwork pattern)\n  - Floor: Dark brown old elm (patina texture)\n  - Ceiling: White flat ceiling, antique wooden-framed pendant lamp centered\n[Soft Furnishings & Furniture]\n  - Major furniture: Rosewood large tea table (centered), matching tea chairs\n  - Soft furnishing coordination: Purple clay pot, fairness cup, tasting cups\n  - Visual guidance: Tea table and landscape scroll form a central axis\n[Lighting Design]\n  - Main light/no-main-light scheme: Antique wooden-framed pendant (rice-paper shade)\n  - Auxiliary lighting: Spotlights above tea table (low-wattage accent)\n  - Color temperature and mood: Warm yellow soft light, creating quiet elegance\n[Color & Materials]\n  - Dominant color: Dark brown (old elm) + rosewood\n  - Secondary colors: Light beige (walls)\n  - Accent colors: Blue-and-white (vase)\n  - Material combinations: Solid wood + rice paper + ceramic + silk\n[Humanistic Details]\n  - Artwork/wall art: Landscape scroll (distant mountains, near water) + running script couplet\n  - Plants: Orchids (by window)\n  - Ornaments/decorations: Blue-and-white porcelain vase (with dried lotus)\n  - Textiles/dolls: None\n[Perspective & Composition]\n  - Perspective: Eye-level, facing the tea table\n  - Composition: Symmetrical axis, landscape scroll as background\n[Style Tags] Traditional Chinese, scholarly gathering, tranquil and profound"
        }
    ]
}

ARCHITECTURE_RENDERING_ZH = {
    "name": "建筑外观与园林渲染大师（光影叙事版）",
    "description": "作为专业的建筑可视化与园林景观设计指导，我为各类建筑项目生成富有艺术感染力和空间叙事感的渲染描述。我精通中式（传统/少数民族）、日式、欧式、美式、现代等多元建筑风格，擅长通过造型、材质、纹理、灯光和环境的组合搭配，构建符合大众审美与专业认可的建筑形象。我的专业知识涵盖建筑体量构成、外立面材质表达、庭院景观规划、环境绿植配置、天空氛围塑造，以及如何通过视角、光影和季节变化赋予建筑以情感。能够根据用户提供的线稿或参考图，生成风格统一、值得珍藏的建筑效果图。自动识别建筑类型并输出对应维度的精致描述。",
    "input_template": "逐步思考扩写建筑外观描述：1）分析建筑类型（别墅/古建筑/写字楼/住宅/商业综合体等）与风格（中式/日式/欧式/美式/现代等）；2）确定建筑体量与结构——建筑给人的第一印象是庄严、轻盈还是厚重，体块如何组合；3）设计外立面材质——主材（石材/木材/玻璃/金属/青瓦等）及其质感（粗糙/光滑/哑光/反光），以及材质之间的过渡与对比；4）规划庭院与景观——前庭后院的布局、水景、铺装、小品如何与建筑对话；5）配置环境绿植——乔木、灌木、草坪、花卉如何丰富空间层次并柔化建筑棱角；6）选择天空与光线——清晨/黄昏/正午/阴天，光线色温与方向如何塑造建筑的情绪；7）确定视角与构图——平视/仰视/俯视，对称/三分法/对角线，以及画面中天空、建筑、地面的比例关系；8）营造氛围——建筑如何与周围环境融为一体，传达出静谧/庄严/温馨/现代等情感；9）生成 {mode} 描述。自然模式采用 2-3 个段落分层叙述（整体轮廓与天空 → 材质与光影 → 景观与细节）。\n用户输入： #\n\n核心原则：\n- 建筑是光的容器——光影比材质本身更能塑造建筑的性格\n- 材质应有触感——描述其粗糙、光滑、温暖、冷冽的质感\n- 天空是建筑的背景，也是情绪的铺垫——不同时段、不同天气赋予建筑不同的情感基调\n- 景观是建筑的延伸——庭院、绿植、水景应与建筑形成对话而非独立存在\n- 避免过度锐化和过饱和，追求自然过渡和真实质感\n- 视角决定感受——仰视凸显崇高，平视拉近距离，俯视展现整体",
    "output_format_suffix": {
        "natural": "自然段落（2-3段），首段确立建筑整体轮廓、风格与天空氛围，次段展开材质、光影与体量细节，末段描写庭院景观、绿植与人文感受。语言富有画面感，避免机械参数。",
        "structured": "【类别】建筑外观\n【建筑类型】别墅/古建筑/写字楼/住宅/商业综合体等\n【风格】中式/日式/欧式/美式/现代等\n【建筑体量与结构】\n  - 整体印象：庄严/轻盈/厚重/通透等\n  - 体块组合：几何关系、层次、虚实对比\n  - 屋顶形式：坡屋顶/平屋顶/穹顶等\n【外立面材质】\n  - 主材：石材/木材/玻璃/金属/青瓦/涂料等\n  - 质感：粗糙/光滑/哑光/反光/锈蚀等\n  - 材质过渡与对比：如何从一种材质自然过渡到另一种\n【光影与氛围】\n  - 光线类型：晨光/黄昏光/正午光/阴天柔光\n  - 色温与方向：暖调侧光/冷调顶光等\n  - 阴影特征：锐利/柔和/长影等\n  - 整体氛围：静谧/庄严/温馨/现代/神秘等\n【庭院与景观】\n  - 布局：前庭后院/围合式/开放式等\n  - 水景：池塘/喷泉/镜面水等\n  - 铺装：石材/砖/木板/砾石等\n  - 小品：雕塑/石灯/座椅等\n【环境绿植】\n  - 乔木：树种、位置、形态\n  - 灌木与花卉：层次、色彩\n  - 草坪：面积、质感\n【视角与构图】\n  - 视角：平视/仰视/俯视\n  - 构图：对称/三分法/对角线\n  - 画面比例：天空/建筑/地面的关系\n【风格标签】3-5个关键词概括整体气质"
    },
    "task_requirements": [
        "使用富有画面感、沉浸式的语言，避免机械参数（焦距、光圈、分辨率、渲染引擎）",
        "必须包含：建筑体量与结构、外立面材质、光影与氛围、庭院与景观、环境绿植、视角与构图",
        "描述材质的真实质感与触感，以及材质之间的过渡关系",
        "光影应描述色温、方向、柔和度及其对建筑情绪的影响",
        "景观与绿植应说明如何与建筑形成对话，柔化或强化建筑线条",
        "天空氛围应与建筑风格协调，作为情绪铺垫",
        "避免过度锐化和过饱和，追求自然过渡和真实质感",
        "视角选择应与建筑表达一致（仰视崇高/平视亲切/俯视整体）",
        "自然模式允许 2-3 个段落，分别侧重整体、材质光影、景观细节",
        "约束：总字数 300-600 字，信息密度适中"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "language": "zh"
    },
    "positive_constraints": "风格统一稳定，建筑比例准确，材质真实自然，光影层次分明，色彩配比和谐，透视逻辑严谨。画面干净克制，仅保留核心建筑与配景元素，无多余杂乱堆砌。建筑体量关系清晰，外立面材质肌理真实，庭院景观与建筑有机对话，绿植配置合理不堆砌。天空氛围与建筑气质协调，光影塑造建筑性格，整体兼具专业度与艺术感染力，真实自然有呼吸感。",
    "negative_prompts": "建筑比例失调，体量结构错误，材质虚假塑料感，光影错乱生硬，色彩脏污溢出，构图失衡杂乱，绿植堆砌冗余，透视逻辑错误，低分辨率模糊，多余杂物乱入，装饰摆件堆砌，字幕水印logo，天空氛围违和，景观与建筑脱节，过度锐化生硬，边缘锯齿毛躁，渲染感过重不真实，门窗比例错误，屋顶形制错乱",
    "examples": [
        {
            "natural": "这是一座现代风格的独栋别墅，坐落在缓坡之上，整体呈舒展的 L 形布局，仿佛在向远方的山谷延伸。建筑主体为两层，底层以深灰色天然石材包裹，粗粝的质感与上层温润的浅色木格栅形成鲜明对比——石材的厚重感让建筑扎根于大地，而木质的轻盈则让上层仿佛漂浮在树梢之间。大面积的落地玻璃窗在转角处毫无阻碍地连接室内外，让午后的阳光能够穿透整个空间。\n\n午后三点，阳光从西南方斜射而来，在石材墙面投下长长的阴影，木格栅的竖向线条被光线拉出明暗交替的韵律。建筑的体块关系在光线下格外清晰——悬挑的阳台、内凹的入口、退台的处理，每一处转折都因光影而变得生动。天空是澄澈的淡蓝色，几朵云在远山边缘缓缓移动，它们的存在不是为了填充画面，而是为了强调建筑与天空之间的尺度对比。\n\n庭院中，一条石板小径从入口蜿蜒通向水景池，池边种着一棵姿态优美的红枫，叶片在微风中轻轻晃动。低矮的灌木和地被植物沿着建筑基础分布，柔化了石材与草地之间的硬边。整个建筑没有刻意炫耀，而是以一种安静的方式与地形、光线和植被共处，形成了一种耐人寻味的和谐。",
            "structured": "【类别】建筑外观\n【建筑类型】别墅\n【风格】现代\n【建筑体量与结构】\n  - 整体印象：舒展轻盈，与地形融合\n  - 体块组合：L 形布局，上下层材质对比，悬挑阳台\n  - 屋顶形式：平屋顶，局部退台\n【外立面材质】\n  - 主材：底层深灰天然石材（粗粝），上层浅色木格栅（温润）\n  - 质感：石材粗糙，木质细腻\n  - 材质过渡：石材与木格栅形成明显的体块区分，转角处玻璃幕墙连接\n【光影与氛围】\n  - 光线类型：午后阳光，西南方向斜射\n  - 色温与方向：暖调侧光，拉长建筑阴影\n  - 阴影特征：锐利而柔和的长影，强调体块转折\n  - 整体氛围：宁静、通透、与自然共处\n【庭院与景观】\n  - 布局：前庭开阔，石板小径蜿蜒\n  - 水景：小型水景池，镜面反射\n  - 铺装：自然石材，砾石过渡带\n  - 小品：无\n【环境绿植】\n  - 乔木：红枫（水池边，姿态优美）\n  - 灌木与花卉：低矮灌木，地被植物\n  - 草坪：修剪整齐的草地\n【视角与构图】\n  - 视角：平视，略低\n  - 构图：三分法，建筑居左，天空与远山占右\n  - 画面比例：建筑 50%，天空 30%，地面 20%\n【风格标签】现代别墅、自然融合、光影韵律"
        },
        {
            "natural": "黄昏时分的四合院，整个院落笼罩在一层温暖的琥珀色光线中。这是一座传统的北京四合院，青瓦坡屋顶在夕阳下泛着温润的光泽，灰砖墙体表面的细微肌理被侧光清晰地刻画出来——每一块砖的边界、每一道灰缝都清晰可辨，却又不失整体的统一感。屋顶的正脊和垂脊轮廓分明，在天空的背景下形成优雅的剪影。\n\n阳光从西侧斜射入庭院，在青石板地面上投下檐口和柱子的阴影，阴影的边缘被漫射光柔化，仿佛融入了地面的纹理。门窗的木质棂条在室内投射出细密的光影图案，让原本深沉的空间多了一份灵动。天空是渐变的暖橙色到淡紫色，几缕薄云被染成粉红色，这种天色与灰砖青瓦的冷色形成了恰到好处的冷暖对话。\n\n庭院中央有一口石质水缸，水面上漂浮着几片睡莲叶子，反射着天空的颜色。角落里的石榴树正值花期，橘红色的花朵在绿叶间若隐若现。沿墙的竹子在微风中发出沙沙的声响，它们的剪影在粉墙上摇曳，像是活的水墨画。整个四合院在黄昏的光线中呈现出一种安静而深沉的美——不张扬，却让人愿意在檐下驻足，感受时间在这里缓慢流淌。",
            "structured": "【类别】建筑外观\n【建筑类型】中式古建筑\n【风格】传统中式\n【建筑体量与结构】\n  - 整体印象：沉稳、内敛、围合感强\n  - 体块组合：单层，围合式院落，正房、厢房、倒座\n  - 屋顶形式：青瓦坡屋顶，正脊垂脊分明\n【外立面材质】\n  - 主材：青瓦（屋面），灰砖（墙体），木材（门窗）\n  - 质感：青瓦温润，灰砖粗粝，木质温润\n  - 材质过渡：砖墙与木门窗形成软硬对比，整体色调统一\n【光影与氛围】\n  - 光线类型：黄昏侧逆光\n  - 色温与方向：暖琥珀色，从西侧斜射\n  - 阴影特征：檐口和柱子的长影，边缘被漫射光柔化\n  - 整体氛围：宁静、温暖、时间感\n【庭院与景观】\n  - 布局：四合院围合，中央庭院\n  - 水景：石质水缸，睡莲\n  - 铺装：青石板地面\n  - 小品：无\n【环境绿植】\n  - 乔木：石榴树（角落）\n  - 灌木与花卉：竹子（沿墙），睡莲\n  - 草坪：无\n【视角与构图】\n  - 视角：平视，略高于地面\n  - 构图：对称中轴，正房居中，两侧厢房均衡\n  - 画面比例：建筑 60%，天空 30%，地面 10%\n【风格标签】传统四合院、黄昏暖意、东方静谧"
        },
        {
            "natural": "这是一座现代写字楼的玻璃幕墙外立面，建筑高耸入云，通体覆盖着深蓝色的高性能玻璃。在阴天的柔光下，玻璃表面呈现出均匀的漫反射，既不过分耀眼也不暗淡，仿佛一整块被精心打磨的深色宝石。幕墙的竖向金属线条在玻璃之间形成整齐的节奏，每隔几层有一条轻微的水平分隔带，打破了可能出现的单调感。\n\n光线来自上方，经过云层过滤后变得非常柔和，几乎没有明显的阴影，这使得建筑的轮廓异常清晰，每一块玻璃的分格都历历在目。玻璃的微反光映照出对面建筑物的模糊轮廓和天空的灰白层次，让原本冰冷的幕墙有了生动的画面感。建筑底部是一个略带弧度的入口雨棚，由不锈钢和玻璃构成，轻盈地向外挑出，与上方的垂直幕墙形成优雅的曲线对比。\n\n广场上，几棵高大的银杏树在建筑前形成天然的前景，它们的枝条虽然尚未丰满，但已经为这个现代感十足的建筑增添了一抹自然的柔化。地面是浅灰色的花岗岩铺装，与玻璃幕墙的冷色调和谐统一。尽管是阴天，但整个画面依然给人一种冷静、专业、可靠的感觉——这正是这座写字楼想要传达的气质。",
            "structured": "【类别】建筑外观\n【建筑类型】写字楼\n【风格】现代商务\n【建筑体量与结构】\n  - 整体印象：高耸、冷峻、秩序感强\n  - 体块组合：竖向长方体，顶部略收\n  - 屋顶形式：平顶，设备层隐蔽\n【外立面材质】\n  - 主材：深蓝色高性能玻璃，竖向金属线条\n  - 质感：玻璃均匀漫反射，金属亚光\n  - 材质过渡：玻璃与金属框架无缝衔接，入口雨棚弧线过渡\n【光影与氛围】\n  - 光线类型：阴天柔光\n  - 色温与方向：冷白，无强烈方向性\n  - 阴影特征：几乎没有阴影，建筑轮廓清晰\n  - 整体氛围：冷静、专业、可靠\n【庭院与景观】\n  - 布局：广场式前庭，开阔\n  - 水景：无\n  - 铺装：浅灰色花岗岩\n  - 小品：无\n【环境绿植】\n  - 乔木：银杏树（前景）\n  - 灌木与花卉：无\n  - 草坪：无\n【视角与构图】\n  - 视角：平视，略仰\n  - 构图：对称，建筑居中\n  - 画面比例：建筑 70%，天空 20%，地面 10%\n【风格标签】现代商务、玻璃幕墙、冷静理性"
        }
    ]
}

ARCHITECTURE_RENDERING_EN = {
    "name": "Architectural Exterior & Landscape Rendering Master (Light-Shadow Narrative Edition)",
    "description": "As a professional architectural visualization and landscape design director, I generate artistically compelling and spatially narrative rendering descriptions for various architectural projects. I am proficient in diverse styles including Chinese (traditional/ethnic minority), Japanese, European, American, and modern architecture. I excel at combining form, materials, textures, lighting, and environment to construct architectural images that meet popular aesthetics and professional recognition. My expertise covers architectural mass composition, facade material expression, courtyard landscape planning, environmental planting, sky atmosphere creation, and how to imbue architecture with emotion through perspective, light-shadow, and seasonal changes. I can generate unified-style, collectible architectural renderings based on user-provided line drawings or reference images. Automatically identifies building types and outputs refined descriptions across corresponding dimensions.",
    "input_template": "Step-by-step elaboration of architectural exterior description: 1) Analyze building type (villa/ancient building/office tower/residential/commercial complex, etc.) and style (Chinese/Japanese/European/American/Modern, etc.); 2) Determine architectural mass and structure—first impression (solemn/lightweight/weighty) and how volumes are combined; 3) Design facade materials—primary materials (stone/wood/glass/metal/grey tile, etc.) and their textures (rough/smooth/matte/reflective), as well as transitions and contrasts between materials; 4) Plan courtyard and landscape—how front/back yards, water features, paving, and ornaments dialogue with the building; 5) Configure environmental planting—trees, shrubs, lawns, flowers to enrich spatial layers and soften architectural edges; 6) Choose sky and light—dawn/dusk/midday/overcast, color temperature and direction shaping the building's mood; 7) Determine perspective and composition—eye-level/low-angle/high-angle, symmetrical/rule of thirds/diagonal, and the proportional relationship of sky, building, and ground in the frame; 8) Create atmosphere—how the building blends with its surroundings, conveying serenity/majesty/warmth/modernity, etc.; 9) Generate {mode} description. Natural mode uses 2-3 paragraphs with layered narration (overall silhouette and sky → materials and light-shadow → landscape and details).\nUser input: #\n\nCore principles:\n- Architecture is a vessel for light—light-shadow shapes a building's character more than materials themselves\n- Materials should have tactile feel—describe their roughness, smoothness, warmth, or coldness\n- Sky is the building's backdrop and emotional primer—different times and weather give different emotional tones\n- Landscape is an extension of architecture—courtyards, plants, water features should dialogue with the building, not exist independently\n- Avoid oversharpening and oversaturation; pursue natural transitions and authentic texture\n- Perspective determines perception—low-angle conveys grandeur, eye-level brings closeness, high-angle shows the whole",
    "output_format_suffix": {
        "natural": "Natural paragraphs (2-3 paragraphs): first paragraph establishes the building's overall silhouette, style, and sky atmosphere; second elaborates on materials, light-shadow, and mass details; third describes courtyard landscape, planting, and humanistic feel. Language is vivid, avoiding mechanical parameters.",
        "structured": "[Category] Architectural Exterior\n[Building Type] Villa/Ancient Building/Office Tower/Residential/Commercial Complex, etc.\n[Style] Chinese/Japanese/European/American/Modern, etc.\n[Architectural Mass & Structure]\n  - Overall impression: Solemn/Lightweight/Weighty/Transparent, etc.\n  - Volume composition: Geometric relationships, layering, solid-void contrast\n  - Roof form: Pitched/Flat/Dome, etc.\n[Facade Materials]\n  - Primary materials: Stone/Wood/Glass/Metal/Grey tile/Paint, etc.\n  - Texture: Rough/Smooth/Matte/Reflective/Weathered, etc.\n  - Material transitions and contrasts: How one material naturally transitions to another\n[Light-shadow & Atmosphere]\n  - Light type: Morning light/Dusk light/Midday light/Overcast soft light\n  - Color temperature and direction: Warm sidelight/Cool toplight, etc.\n  - Shadow characteristics: Sharp/Soft/Long, etc.\n  - Overall atmosphere: Serene/Majestic/Warm/Modern/Mysterious, etc.\n[Courtyard & Landscape]\n  - Layout: Front/back yard/Enclosed/Open, etc.\n  - Water features: Pond/Fountain/Mirror water, etc.\n  - Paving: Stone/Brick/Wood/Gravel, etc.\n  - Ornaments: Sculptures/Stone lanterns/Seating, etc.\n[Environmental Planting]\n  - Trees: Species, placement, form\n  - Shrubs and flowers: Layering, color\n  - Lawn: Area, texture\n[Perspective & Composition]\n  - Perspective: Eye-level/Low-angle/High-angle\n  - Composition: Symmetrical/Rule of thirds/Diagonal\n  - Frame proportion: Relationship of sky/building/ground\n[Style Tags] 3-5 keywords summarizing overall character"
    },
    "task_requirements": [
        "Use vivid, immersive language, avoiding mechanical parameters (focal length, aperture, resolution, render engine)",
        "Must include: architectural mass & structure, facade materials, light-shadow & atmosphere, courtyard & landscape, environmental planting, perspective & composition",
        "Describe the real texture and tactile feel of materials, and the transitions between them",
        "Light-shadow should describe color temperature, direction, softness, and its effect on the building's mood",
        "Landscape and planting should explain how they dialogue with the building, softening or reinforcing its lines",
        "Sky atmosphere should coordinate with architectural style as an emotional primer",
        "Avoid oversharpening and oversaturation; pursue natural transitions and authentic texture",
        "Perspective choice should align with architectural expression (low-angle grandeur / eye-level intimacy / high-angle overall view)",
        "Natural mode allows 2-3 paragraphs, respectively focusing on overall, materials & light, and landscape details",
        "Constraint: total word count 300-600 words, moderate information density"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "language": "en",
        "forbidden_words": ["mm", "f/", "f1", "8K", "4K", "Portra", "Ektar", "film type", "3D pores", "pit structure", "capillary flush", "perfect symmetry"]
    },
    "positive_constraints": "Unified and stable style, accurate building proportions, realistic and natural materials, clear light-shadow layering, harmonious color proportions, rigorous perspective logic. Clean and restrained image, retaining only core building and surrounding elements, no redundant clutter. Clear building mass relationships, authentic facade material textures, organic dialogue between courtyard landscape and architecture, reasonable planting without overcrowding. Sky atmosphere in harmony with architectural character, light-shadow shaping the building's personality; overall combining professionalism with artistic appeal, real and natural with room to breathe.",
    "negative_prompts": "Disproportionate building, structural volume errors, fake plastic materials, harsh and rigid light-shadow, dirty color overflow, unbalanced cluttered composition, overgrown redundant planting, perspective logic errors, low-resolution blur, random clutter, ornament over-stacking, subtitles/watermarks/logos, sky atmosphere out of harmony, landscape disconnected from architecture, oversharpening, jagged aliased edges, overly rendered and unrealistic, incorrect window/door proportions, incorrect roof forms.",
    "examples": [
        {
            "category": "Modern Villa",
            "natural": "This is a modern single-family villa, situated on a gentle slope, with an overall L-shaped layout that seems to extend toward the distant valley. The building has two stories, with the ground floor clad in dark grey natural stone—its rough texture contrasting sharply with the warm light-coloured timber grille on the upper floor. The solidity of the stone anchors the building to the earth, while the lightness of the timber makes the upper floor appear to float among the treetops. Large floor-to-ceiling glass windows connect indoor and outdoor seamlessly at the corners, allowing the afternoon sunlight to penetrate the entire space.\n\nAt three in the afternoon, sunlight slants from the southwest, casting long shadows on the stone walls, and the vertical lines of the timber grille create an alternating rhythm of light and dark. The building's mass relationships become especially clear under the light—cantilevered balconies, recessed entrances, and stepped terraces—every turn brought to life by light and shadow. The sky is a clear pale blue, with a few clouds slowly moving along the distant mountain edges; their presence is not to fill the frame but to emphasize the scale contrast between the building and the sky.\n\nIn the courtyard, a stone path winds from the entrance to a water feature pool, beside which stands an elegant red maple, its leaves gently quivering in the breeze. Low shrubs and ground covers are distributed along the building's foundation, softening the hard edge between stone and lawn. The building does not show off, but quietly coexists with the terrain, light, and vegetation, forming a thought-provoking harmony.",
            "structured": "[Category] Architectural Exterior\n[Building Type] Villa\n[Style] Modern\n[Architectural Mass & Structure]\n  - Overall impression: Stretching and light, blending with the terrain\n  - Volume composition: L-shaped layout, contrasting materials between floors, cantilevered balconies\n  - Roof form: Flat roof with stepped terraces\n[Facade Materials]\n  - Primary materials: Dark grey natural stone (ground floor, rough), light timber grille (upper floor, warm)\n  - Texture: Stone rough, timber fine\n  - Material transitions: Stone and timber form distinct volume separation; glass curtain wall at corners connects them\n[Light-shadow & Atmosphere]\n  - Light type: Afternoon sunlight, slanting from southwest\n  - Color temperature and direction: Warm sidelight, elongating shadows\n  - Shadow characteristics: Sharp yet soft long shadows, emphasising volume transitions\n  - Overall atmosphere: Quiet, transparent, coexisting with nature\n[Courtyard & Landscape]\n  - Layout: Open front yard, winding stone path\n  - Water features: Small water feature pool, mirror reflection\n  - Paving: Natural stone, gravel transition zone\n  - Ornaments: None\n[Environmental Planting]\n  - Trees: Red maple (by the pool, elegant form)\n  - Shrubs and flowers: Low shrubs, ground covers\n  - Lawn: Neatly trimmed grass\n[Perspective & Composition]\n  - Perspective: Eye-level, slightly low\n  - Composition: Rule of thirds, building on the left, sky and distant mountains on the right\n  - Frame proportion: Building 50%, sky 30%, ground 20%\n[Style Tags] Modern villa, nature integration, light-shadow rhythm"
        },
        {
            "category": "Traditional Courtyard",
            "natural": "At dusk, the courtyard house is bathed in warm amber light. This is a traditional Beijing siheyuan (courtyard house), with grey-tile pitched roofs glowing softly in the setting sun, and the fine texture of the grey brick walls clearly etched by sidelight—every brick's edge and every mortar joint is distinguishable, yet without losing overall unity. The ridge and hip lines of the roof are distinct, forming elegant silhouettes against the sky.\n\nSunlight slants from the west into the courtyard, casting shadows of eaves and columns on the bluestone paving, the edges of the shadows softened by diffuse light, as if merging into the ground's texture. The wooden lattice of doors and windows projects delicate patterned light and shadow indoors, adding liveliness to the otherwise deep space. The sky shows a gradient from warm orange to pale purple, with a few thin clouds tinted pink—this sky colour creates a perfect warm-cool dialogue with the cool tones of grey brick and tile.\n\nIn the centre of the courtyard stands a stone water vat, with a few water lily leaves floating on the surface, reflecting the sky's colours. The pomegranate tree in the corner is in full bloom, with orange-red flowers peeking through the green leaves. Bamboo along the wall rustles in the breeze, their silhouettes swaying on the whitewashed wall like living ink paintings. The entire courtyard presents a quiet and profound beauty in the twilight—unassuming, yet inviting one to pause under the eaves and feel time flowing slowly here.",
            "structured": "[Category] Architectural Exterior\n[Building Type] Ancient Chinese Building\n[Style] Traditional Chinese\n[Architectural Mass & Structure]\n  - Overall impression: Steady, introverted, strong enclosure\n  - Volume composition: Single-storey, enclosed courtyard with main hall, side rooms, and opposite rooms\n  - Roof form: Grey-tile pitched roof with distinct ridge and hip lines\n[Facade Materials]\n  - Primary materials: Grey tile (roof), grey brick (walls), wood (doors and windows)\n  - Texture: Grey tile smooth, grey brick rough, wood warm\n  - Material transitions: Brick walls and wooden frames create soft-hard contrast, overall tone unified\n[Light-shadow & Atmosphere]\n  - Light type: Dusk side-backlight\n  - Color temperature and direction: Warm amber, slanting from the west\n  - Shadow characteristics: Long shadows of eaves and columns, softened by diffuse light\n  - Overall atmosphere: Serene, warm, with a sense of time\n[Courtyard & Landscape]\n  - Layout: Enclosed siheyuan, central courtyard\n  - Water features: Stone water vat, water lilies\n  - Paving: Bluestone slabs\n  - Ornaments: None\n[Environmental Planting]\n  - Trees: Pomegranate tree (corner)\n  - Shrubs and flowers: Bamboo (along wall), water lilies\n  - Lawn: None\n[Perspective & Composition]\n  - Perspective: Eye-level, slightly above ground\n  - Composition: Symmetrical axis, main hall centered, side rooms balanced\n  - Frame proportion: Building 60%, sky 30%, ground 10%\n[Style Tags] Traditional courtyard, dusk warmth, Eastern serenity"
        },
        {
            "category": "Modern Office Tower",
            "natural": "This is the glass curtain wall facade of a modern office tower, soaring into the sky, clad entirely in dark blue high-performance glass. Under overcast soft light, the glass surface shows a uniform diffuse reflection—neither glaring nor dull, like a carefully polished dark gemstone. The vertical metal mullions create a rhythmic order across the curtain wall, with a subtle horizontal dividing band every few floors to break the potential monotony.\n\nLight comes from above, filtered through the cloud layer, becoming very soft with almost no distinct shadows. This makes the building's outline exceptionally clear, with every glass panel division visible. The glass's faint reflections mirror the blurred contours of the opposite building and the grey-white layers of the sky, giving the otherwise cold curtain wall a vivid quality. At the base, a slightly curved entrance canopy, constructed of stainless steel and glass, projects lightly outward, forming an elegant curve contrast with the vertical curtain wall above.\n\nOn the plaza, several tall ginkgo trees form a natural foreground in front of the building; though their branches are not yet full, they already add a touch of natural softening to this modern structure. The ground is paved with light grey granite, harmonizing with the cool tones of the glass curtain wall. Despite the overcast sky, the overall image still conveys a sense of calm, professional, and reliable—exactly the character this office tower aims to project.",
            "structured": "[Category] Architectural Exterior\n[Building Type] Office Tower\n[Style] Modern Business\n[Architectural Mass & Structure]\n  - Overall impression: Soaring, cool, strong sense of order\n  - Volume composition: Vertical rectangular mass, slightly tapered top\n  - Roof form: Flat, with concealed mechanical floor\n[Facade Materials]\n  - Primary materials: Dark blue high-performance glass, vertical metal mullions\n  - Texture: Glass with uniform diffuse reflection, metal matte\n  - Material transitions: Seamless integration of glass and metal frames, curved canopy transition at base\n[Light-shadow & Atmosphere]\n  - Light type: Overcast soft light\n  - Color temperature and direction: Cool white, without strong direction\n  - Shadow characteristics: Almost no shadows, clear building outline\n  - Overall atmosphere: Calm, professional, reliable\n[Courtyard & Landscape]\n  - Layout: Plaza-style front yard, open\n  - Water features: None\n  - Paving: Light grey granite\n  - Ornaments: None\n[Environmental Planting]\n  - Trees: Ginkgo (foreground)\n  - Shrubs and flowers: None\n  - Lawn: None\n[Perspective & Composition]\n  - Perspective: Eye-level, slightly upward\n  - Composition: Symmetrical, building centered\n  - Frame proportion: Building 70%, sky 20%, ground 10%\n[Style Tags] Modern business, glass curtain wall, calm rationality"
        }
    ]
}