# -*- coding: utf-8 -*-
"""
通用预设提示词库

Author: 亲卿于情 (@Qo-qiao)
GitHub: https://github.com/Qo-qiao
License: See LICENSE file for details
"""

PROMPT_EXPANDER_ZH = {
    "name": "提示词扩写器（自然语言美学版）",
    "description": "作为专业的AI图像生成提示词工程师，我将根据简短提示词生成富有艺术感染力、审美在线且层次分明的自然语言描述，完美适配Flux、Z-Image、Qwen-Image、Krea等主流模型。我精通摄影美学、光影叙事、色彩调和与视觉构图，擅长将抽象概念转化为生动的视觉语言。人像类支持两种风格：'真实'风格保留自然呼吸感（皮肤肌理、非对称特征）；'网红'风格强调精致滤镜美学（无瑕肤质、高级妆容）。",
    "input_template": "逐步思考扩写以下提示词：1）判断扩写类型（人像类、cosplay类、游戏角色类、产品类、场景类、动物类、美食类、通用类）；2）提取核心主体与关键动作，确保主题不偏离；3）设计和谐的配色方案（主色占比60%，辅色30%，点缀色10%），避免视觉杂乱；4）选择最适合的视角与景深氛围（广角震撼/标准平实/长焦压缩/微距极致）；5）构建视觉叙事：思考光线如何流动，色彩如何过渡，细节如何引导观众视线在画面中停留和回味，并营造出情绪和氛围；6）按类别生成{mode}描述，要求画面元素层次清晰、色彩统一、光影有叙事性。若未匹配类别则自主创建。\n用户输入：#\n\n【艺术创作核心准则】\n- 用视觉语言讲故事：让光影、色彩、质感共同服务于情感表达，使画面值得反复品味。\n- 拥抱自然过渡：拒绝生硬的边缘和突兀的对比，追求色彩、光影、景深之间的柔和渐变。\n- 质感高于清晰度：真实世界的魅力在于细腻的纹理（皮肤毛孔、织物肌理、锈蚀金属），而非机械的锐利。\n- 留白与呼吸感：给画面留出视觉休息区，避免元素堆砌，营造耐人寻味的意境。\n\n【人像类风格识别规则】\n- 若包含'网红'、'精致'、'完美'、'滤镜'、'美颜'等词 → 采用【网红风格】：强调陶瓷般无瑕的细腻肤质、精致立体的对称五官、柔焦梦幻光效、高级时尚感，整体呈现社交媒体精修大片的美学。\n- 若包含'真实'、'自然'、'写实'、'纪实'等词，或未指定 → 采用【真实风格】：强调富有呼吸感的自然皮肤肌理、保留细微非对称特征与日常瑕疵（淡斑、细纹），光影过渡自然，呈现真实摄影的叙事感。\n\n扩写要点：只扩写视觉可呈现的内容，不添加故事性旁白。确保色彩搭配和谐，避免无关元素堆砌。自然段落可分多层：主体描述、环境背景、光影氛围、细节质感。",
    "output_format_suffix": {
        "natural": "自然段落（允许多段分层），流畅融合主体特征、环境空间、光影色调与质感细节，无具体数值参数，语言富有画面感。无额外解释。",
        "structured": "【类别】类别名称（真实风格/网红风格）\n【画面构图】\n  - 构图方式：构图类型（三分法/对称/对角线/框架/中心/三角形/S形曲线等）\n  - 主体位置：水平位置+垂直位置（百分比表示，如水平50%居中，垂直40%偏上）\n  - 画面比例：宽高比（16:9/9:16/4:3/1:1等）\n【景别】\n  - 景别类型：微距特写/标准特写/肩特写/七分人像/九分人像/全景人像（无人物可省略）\n  - 取景范围：明确拍到部位与裁切位置\n  - 画面特征：突出视觉重心与构图张力\n【视觉视角与景深】\n  - 视角效果：广角透视感/标准平实视角/长焦空间压缩感/微距放大效果\n  - 景深氛围：浅景深柔焦虚化/中景深环境兼顾/深景深全景清晰\n【主体描述】\n  - 核心主体：外貌/物种/物体特征，突出最鲜明的视觉元素\n  - 动作姿态：动态或静态姿势，肢体语言与道具互动\n  - 服装造型：材质、颜色、款式及装饰细节\n【真实度细节】（真实风格专用，融入式描述）\n  - 肤质肌理：自然通透的皮肤质感，可见细腻毛孔与真实纹理，带有温和肤色不均与轻微日常瑕疵（如淡斑、眼下细纹），光影下呈现健康自然光泽\n  - 毛发特征：发丝柔顺自然，带有碎发与绒毛细节，睫毛眉毛根根分明\n  - 面部特征：保留非对称自然美，嘴唇有真实纹路，肤色由内而外自然过渡\n【精致度细节】（网红风格专用，融入式描述）\n  - 妆容肤质：精致无瑕的陶瓷肌，清透白皙或健康光泽，妆容立体高级（眼妆深邃、唇色饱满）\n  - 五官神态：比例完美的精致五官，眼神灵动迷人，表情管理极致\n  - 滤镜氛围：柔光梦幻滤镜，色彩统一高级，呈现社交媒体大片既视感\n【环境设置】\n  - 环境场景：具体空间与背景元素\n  - 光线效果：光源方向与质感（柔光/硬光/逆光/侧光），营造氛围\n  - 色彩搭配：主色调与点缀色，确保整体和谐有层次\n  - 细节刻画：环境中的质感元素（纹理、反光、阴影）\n【技术参数】整体风格标签（如：电影级质感、商业精修、自然纪实、赛博朋克等）"
    },
    "task_requirements": [
        "扩写内容生动专业，使用美学与摄影术语，但绝不使用具体焦距mm或光圈f值",
        "严格保持原意，不添加主体外的无关视觉元素",
        "人物与物品交互必须符合现实物理逻辑",
        "优先保证画面色彩和谐统一（主色/辅色/点缀色比例得当），避免杂乱无章",
        "构图可由肢体、环境、光影自然形成，无需生搬硬套固定模板",
        "必须明确主体位置（水平+垂直百分比），确保视觉重心突出",
        "必须描述视角带来的视觉效果（如：透视夸张、空间压缩）与景深氛围（虚化/清晰）",
        "必须正确判断景别类型，确保裁切位置描述准确",
        "人像类必须根据关键词判断风格：'网红/精致/完美'→网红风格；'真实/自然'或未指定→真实风格",
        "真实风格需突出自然肌理与瑕疵，网红风格需突出无瑕精致与滤镜感，均以流畅段落形式表现，禁止条目式罗列",
        "必须遵循【艺术创作核心准则】：用视觉语言讲故事、追求自然过渡、质感高于清晰度、留白与呼吸感",
        "natural模式输出一段或多段连贯描述，建议按[环境与光线]、[主体与姿态]、[细节与质感]分层；structured模式按字段输出",
        "文字总量控制在300~600字（自然模式），确保信息密度适中，不冗长"
    ],
    "constraints": {
        "max_length": 800,
        "keep_core_keywords": True,
        "avoid_numeric_parameters": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True
    },
    "positive_constraints": "主体突出明确，形态比例准确，质感真实细腻，光影层次分明有叙事性，色彩配比和谐统一，构图逻辑清晰有视觉引导。画面干净克制，仅保留核心叙事元素，无冗余杂物堆砌。人像类风格辨识度强：真实风格保留自然肌理与非对称特征，网红风格呈现精致无瑕的滤镜质感；其余品类均符合对应视觉语言，整体兼具审美性与生成稳定性，真实自然有呼吸感。",
    "negative_prompts":  "主体变形失真，质感虚假塑料感，光影杂乱过曝，色彩脏污溢出，元素堆砌冗余，构图失衡杂乱，透视比例错误，低分辨率模糊，多余杂物乱入，字幕水印logo，光影生硬断层，过度锐化生硬，边缘锯齿毛躁。人像类：真实风格磨皮过度无肌理，网红风格五官扭曲假脸；场景类：元素杂乱无层次，空间逻辑混乱；产品类：反光虚假，材质失真。",
    "examples": [
        {
            "category": "人像类（真实风格）",
            "natural": "午后阳光透过咖啡馆的落地窗洒进来，形成柔和的侧逆光，在空气中映出细微的尘埃轨迹。一位25岁左右的亚洲女性坐于窗边木桌前，身穿质感柔软的浅米色针织开衫，袖口有细腻的钩花蕾丝。她微垂眼眸，专注地翻阅着一本泛黄的精装书，左手轻轻按在书页边缘，右手食指正准备翻页。\n\n中景构图，平实的标准视角让画面极具代入感。她的黑色长发自然垂落，一缕发丝滑过额前，耳边的碎发在逆光中呈现柔和的透明感。午后的暖光将她的皮肤映衬得通透自然，脸颊上隐约可看到淡淡的雀斑和鼻翼两侧细微的毛孔肌理，眼下带有轻微的卧蚕与自然的暗沉，嘴唇呈现健康的淡粉色，唇纹若隐若现。\n\n色调以暖棕、米白与木色为主，低饱和度带来温馨舒缓的视觉感受。桌角放着一杯拉花精致的拿铁，杯壁倒映着窗外的街景，整体氛围安静而治愈，充满生活化的真实叙事感。光线在书页上形成柔和的渐层，阴影自然地软化在织物纹理中，整个画面像一帧被时光凝固的电影镜头，每一次凝视都能发现新的细节与温度。",
            "structured": "【类别】人像类（真实风格）\n【画面构图】\n  - 构图方式：三分法，人物居中偏右，书籍与咖啡杯形成三角形稳定结构\n  - 主体位置：水平55%偏右，垂直50%居中\n  - 画面比例：3:2\n【景别】\n  - 景别类型：七分人像\n  - 取景范围：头顶至腰部，完整展现头部、肩膀与手势动作\n  - 画面特征：上半身为主体，环境细节丰富但不抢镜\n【视觉视角与景深】\n  - 视角效果：标准平实视角，接近人眼所见，无透视畸变\n  - 景深氛围：浅景深柔焦，背景咖啡馆环境被轻柔虚化，人物主体突出\n【主体描述】\n  - 核心主体：25岁亚洲女性，黑色长发，柔和杏仁眼，专注阅读神态\n  - 动作姿态：静坐阅读，右手悬空准备翻页，身体微微前倾\n  - 服装造型：浅米色针织开衫，蕾丝钩花袖口，简约日常\n【真实度细节】\n  - 肤质肌理：皮肤通透自然，保留鼻翼细微毛孔与面颊淡淡雀斑，眼下有真实卧蚕与轻微暗沉，颧骨处有自然血晕\n  - 毛发特征：发丝垂顺带有碎发，逆光下边缘毛发呈现透明质感\n  - 面部特征：面部微非对称（左眼略高），嘴唇天然淡粉，唇纹真实可见\n【环境设置】\n  - 环境场景：温馨咖啡馆窗边，木质桌面，薄纱窗帘\n  - 光线效果：午后侧逆自然光，柔和漫射，形成轮廓光与暖调氛围\n  - 色彩搭配：暖棕、米白、原木色，饱和度低，视觉舒适\n  - 细节刻画：书页泛黄质感，咖啡拉花细腻，桌纹清晰，窗帘透光朦胧，光线在书页上形成柔和渐层\n【技术参数】自然纪实摄影风格，生活化叙事，写实质感"
        },
        {
            "category": "人像类（网红风格）",
            "natural": "精心布置的奶油色系网红咖啡厅内，暖色调的点光源与窗边柔光交织，营造出梦幻柔和的奶油肌氛围。一位20岁出头的时尚女性正对镜头，精致的韩式水光肌底妆让她整张脸显得毫无瑕疵，仿佛自带柔焦滤镜。\n\n镜头采用特写景别，85mm的中长焦视角带来平滑的空间压缩感，背景化为一片温暖的光斑。她微微侧头，乌黑亮丽的长卷发披散在肩头，发尾弧度优美。眼妆采用深邃的大地色系，睫毛浓密卷翘，唇部涂着流行的雾面豆沙色，整个五官立体而精致。\n\n她穿着一件米白色的羊绒短上衣，露出纤细的锁骨，耳畔的珍珠耳环在光线下散发温润光泽。整体画面呈现出低对比度、高明度的柔和质感，背景中的绿植与金属装饰被虚化成朦胧的色块，主体被衬托得极为突出。色彩在暖白与米色间细腻过渡，整个画面被一层柔和的光晕包裹，仿佛一个精心策划的梦境瞬间被永久定格。",
            "structured": "【类别】人像类（网红风格）\n【画面构图】\n  - 构图方式：中心构图，人物面部居中，视线正对镜头\n  - 主体位置：水平50%居中，垂直45%偏上\n  - 画面比例：3:2\n【景别】\n  - 景别类型：标准特写\n  - 取景范围：头顶至下巴，完全不含肩膀\n  - 画面特征：面部充斥整个画面，视觉冲击力强\n【视觉视角与景深】\n  - 视角效果：中长焦视角，空间压缩，面部立体感增强\n  - 景深氛围：浅景深极致柔焦，背景化为奶油般的光斑\n【主体描述】\n  - 核心主体：20出头年轻女性，精致立体五官，乌黑长卷发\n  - 动作姿态：微侧头部，直视镜头，表情自信从容\n  - 服装造型：米白色羊绒短上衣，珍珠耳环，简约高级\n【精致度细节】\n  - 妆容肤质：水光肌底妆，皮肤光滑如瓷无毛孔感，腮红自然提气色\n  - 五官神态：眉毛精细修整，眼妆深邃有神，雾面豆沙唇妆完美\n  - 滤镜氛围：低对比度、高明度柔焦滤镜，画面干净柔和\n【环境设置】\n  - 环境场景：网红咖啡厅，背景简洁有绿植与金属元素\n  - 光线效果：暖调柔光，结合窗边自然光，无生硬阴影\n  - 色彩搭配：奶油白、米色、香槟金，统一高级感色调\n  - 细节刻画：发丝光泽、珍珠耳环反光、毛衣绒毛质感，色彩在暖白与米色间细腻过渡\n【技术参数】高级网红风，社交媒体精修大片，商业人像质感"
        },
        {
            "category": "产品类",
            "natural": "深蓝色渐变背景前，一副旗舰级无线降噪耳机以悬浮姿态呈现在画面中央。45度俯拍视角下，产品轮廓利落分明，炭黑色磨砂质感的外壳在精心布置的三点布光下显得极具科技感。\n\n主光从左前方均匀铺开，细腻地勾勒出耳罩皮质纹理与金属头梁的拉丝光泽；右后方的辅助轮廓光将耳机的边缘与背景精准分离，赋予了产品轻盈的漂浮感。耳机底部投射出清晰锐利的镜面倒影，极大地增强了画面的高级商业质感。\n\n在高分辨率特写之下，记忆海绵耳垫的细微透气孔、头梁伸缩处精密的刻度标识均清晰可辨。整套布光消除了多余阴影，画面干净利落，冷冽的蓝色调与深灰、黑色交织，营造出极致的冷静与专业氛围。光线在金属与磨砂表面上的反射差异形成了丰富的灰度层次，让产品的质感从画面中无声地透出。",
            "structured": "【类别】产品类\n【画面构图】\n  - 构图方式：中心对称，耳机绝对居中\n  - 主体位置：水平50%居中，垂直50%居中\n  - 画面比例：1:1\n【景别】\n  - 景别类型：特写（静物）\n  - 取景范围：完整耳机主体及底部镜像倒影\n  - 画面特征：严谨对称，细节毕现\n【视觉视角与景深】\n  - 视角效果：标准45度俯视，立体展示产品三维形态\n  - 景深氛围：浅景深，产品主体锐利，背景均匀虚化\n【主体描述】\n  - 核心主体：旗舰级无线降噪耳机\n  - 动作姿态：悬浮静态展示\n  - 服装造型：炭黑色磨砂外壳，金属拉丝头梁，记忆海绵耳垫\n【环境设置】\n  - 环境场景：专业无影摄影棚\n  - 光线效果：三点布光（主光左前，辅光右侧，轮廓光右后）\n  - 色彩搭配：深蓝渐变背景，黑、灰、银冷色调\n  - 细节刻画：耳罩皮质纹理、海绵透气孔、金属拉丝纹路与刻度，光线在不同材质上形成丰富的灰度层次\n【技术参数】极简商业摄影，硬核科技质感"
        },
        {
            "category": "cosplay类",
            "natural": "破败的古堡废墟前，一位cosplayer化身动漫中的魔法少女，完美还原了角色的华丽战斗姿态。她手持镶嵌着紫水晶的魔法杖，银白长发在风中高高扬起，紫色的魔法长袍被气流撑起，裙摆的蕾丝与金色镶边在逆光中闪烁着神秘的光泽。\n\n标准视角配合中景构图，完整捕捉了从头部到膝盖的动态范围。她的面部妆容精致，眼尾一抹紫色渐变眼影与唇上的玫红色形成强烈对比，眼神坚定地凝视着前方，仿佛下一秒就要吟唱出高阶咒语。\n\n右侧主光源模拟了魔法爆发时的强烈光效，在人物身后拉出长长的影子，同时将法杖顶端的宝石映照得光芒四射。色调以梦幻的紫罗兰色与金色为主，背景暗部略带青灰，整体饱和度较高，充满了二次元特有的激情与华丽感。光影在蕾丝与镶金边缘上跳跃，与青灰色石墙的粗糙肌理形成质感对比，华丽中不失真实世界的厚重感。",
            "structured": "【类别】cosplay类\n【画面构图】\n  - 构图方式：动感对角线，人物身体略向右倾，法杖左指形成视觉引导\n  - 主体位置：水平45%偏左，垂直50%居中\n  - 画面比例：16:9\n【景别】\n  - 景别类型：九分人像\n  - 取景范围：头顶至膝盖下方，动态截断于小腿\n  - 画面特征：动作幅度大，服装飘动感强\n【视觉视角与景深】\n  - 视角效果：标准平视，略带仰角增强角色气势\n  - 景深氛围：中景深，人物清晰，背景废墟隐约可见但不过分抢眼\n【主体描述】\n  - 核心主体：魔法少女cosplayer，银白长发，手持水晶法杖\n  - 动作姿态：战斗施法姿态，衣袍飞起，眼神坚毅\n  - 服装造型：紫色魔法长袍，蕾丝与金色镶边，长筒靴\n【环境设置】\n  - 环境场景：古堡废墟，青灰色石墙与破碎拱门\n  - 光线效果：右侧强侧光，模拟魔法爆发，形成戏剧性阴影\n  - 色彩搭配：紫罗兰、金色为主，暗部青灰为辅\n  - 细节刻画：法杖宝石光晕、服装刺绣纹理、飘扬的发丝，光影在蕾丝与镶金边缘跳跃\n【技术参数】梦幻华丽风格，二次元还原度极高"
        },
        {
            "category": "游戏角色类",
            "natural": "霓虹灯牌在潮湿的夜空中不断闪烁，映照在积水的柏油路面上形成破碎的倒影。一位身着暗红色皮质风衣的机械改造人战士矗立于赛博朋克都市的天桥之上，银色的机械义肢在冷蓝色霓虹光下反射出锐利的金属光泽。\n\n采用广角透视的全景构图，将身后高耸入云的摩天大楼与全息广告尽数纳入画面，极大了增强了空间的纵深感与科幻压迫感。战士身体微弓，重心压低，右手紧握着巨型热能战斧，左臂的机械关节随着蓄力动作发出隐约的能量脉冲。风吹起他额前银白色的碎发，面部纵横的旧伤疤与发光的蓝色电子义眼形成了一种桀骜不羁的气质。\n\n色彩以深邃的午夜蓝与沉稳的黑为主，点缀以高饱和度的荧光粉和冷紫色霓虹，整体明暗对比强烈，画面虽然信息量极大，但通过统一的冷色调与光影引导，主体依然十分突出。霓虹光在雨后的路面上化作印象派的色块倒影，金属义肢的冷光与皮质风衣的哑光质感之间形成微妙平衡，让混乱中生出一种赛博都市特有的秩序感。",
            "structured": "【类别】游戏角色类\n【画面构图】\n  - 构图方式：对角线引导线与框架式构图，天桥栏杆形成前景框架\n  - 主体位置：水平30%偏左，垂直60%偏下\n  - 画面比例：16:9\n【景别】\n  - 景别类型：全景人像\n  - 取景范围：从头到脚完整全身，环境占据画面三分之二\n  - 画面特征：人物与环境深度互动，纵深感极强\n【视觉视角与景深】\n  - 视角效果：广角透视，强烈夸张前景与背景距离感\n  - 景深氛围：深景深，从前到后细节清晰，展现宏大世界观\n【主体描述】\n  - 核心主体：机械改造人战士，暗红风衣，银色机械义肢\n  - 动作姿态：蓄力战斗姿态，身体低伏，握紧战斧\n  - 服装造型：暗红皮质风衣，金属护甲，战术腰带\n【环境设置】\n  - 环境场景：赛博朋克天桥，霓虹都市，积水的路面\n  - 光线效果：冷蓝霓虹主光，粉紫色点缀光，路面反射光\n  - 色彩搭配：午夜蓝、黑为主，荧光粉、冷紫为点缀\n  - 细节刻画：义肢关节纹理、风衣磨损边角、全息投影颗粒感，霓虹倒影化作印象派色块\n【技术参数】赛博朋克风格，3A游戏CG级质感"
        },
        {
            "category": "场景类",
            "natural": "清晨的第一缕金色阳光斜斜地穿过古老密林高耸的树冠，形成一道道神圣的丁达尔光柱，照亮了空气中漂浮的微小水汽与尘埃。森林深处，一条被落叶覆盖的蜿蜒小径通向远方，两侧长满了厚厚的墨绿色苔藓，空气中弥漫着潮湿的泥土芬芳。\n\n广角全景构图将前景的粗糙树干、中景的石砌遗迹与远景的朦胧晨雾层叠展现，营造出极强的空间穿透感。画面左下方，一座爬满常青藤的巨石拱门静静伫立，门缝间透出的微光成为视觉的焦点。\n\n整体色调采用和谐的中低饱和度绿棕色系，阳光的金黄色与树荫的冷绿色形成自然的冷暖对比。雾气在林间自然流动，柔和了光影边界，使得整个场景宛如从史诗奇幻小说中截取的插画，宁静而深邃。光线穿过层层枝叶后在空气中形成的柔和光晕与阴影的冷调交织，让每一寸画面都充满了细腻的呼吸感。",
            "structured": "【类别】场景类\n【画面构图】\n  - 构图方式：垂直线条与汇聚线结合，小径将视线引向远方遗迹\n  - 主体位置：水平50%居中，垂直40%偏上（遗迹）\n  - 画面比例：16:9\n【景别】\n  - 景别类型：远景（大场景）\n  - 取景范围：涵盖前景树木、中景小径、远景遗迹与天空\n  - 画面特征：层次丰富，透视强烈\n【视觉视角与景深】\n  - 视角效果：广角平视，最大程度增强空间纵深感\n  - 景深氛围：深景深，从前景落叶到远景雾气全部清晰锐利\n【主体描述】\n  - 核心主体：古老密林、石砌遗迹\n  - 动作姿态：纯自然静态\n  - 服装造型：无\n【环境设置】\n  - 环境场景：原始森林深处，苔藓覆盖石阶，雾霭氤氲\n  - 光线效果：清晨丁达尔效应，斜射光柱，柔和散射\n  - 色彩搭配：墨绿、暖金、苔藓棕，低饱和度和谐过渡\n  - 细节刻画：树皮粗糙纹理、苔藓毛绒质感、落叶脉络、石柱风化痕迹，光晕与冷调阴影交织\n【技术参数】史诗奇幻场景，电影级自然光效"
        },
        {
            "category": "动物类",
            "natural": "温暖的午后阳光透过白色纱帘洒在柔软的米色羊毛毯上，一只通体雪白的波斯猫正慵懒地蜷卧其中。它的蓝宝石般的眼睛微微眯起，透着高贵的慵懒气息，蓬松的长毛在逆光下勾勒出一层金色的光晕边缘。\n\n标准特写镜头配合50mm等效视角，焦点精准地落在猫咪面部。镜头捕捉到了它粉嫩的鼻尖、修长且晶莹的白色胡须，以及厚实毛发的蓬松纹理。它的一只前爪自然伸展，露出粉色的肉垫，尾巴尖则随性地搭在毯子边缘。\n\n整张照片的色调温暖统一，以乳白、浅米与柔和的淡金色为主。左侧的侧逆光将猫咪的毛划分割出分明的明暗界线，却丝毫没有生硬之感，反而增强了立体毛绒质感。背景被虚化为一片柔和的暖色光斑，没有多余杂物，凸显了猫咪治愈而优雅的贵族气质。光线在绒毛尖端形成细腻的光晕，阴影在毛发的缝隙间柔化，让整张照片充满了触手可及的温暖与柔软。",
            "structured": "【类别】动物类\n【画面构图】\n  - 构图方式：中心偏下构图，猫咪面部处于上三分之一处\n  - 主体位置：水平50%居中，垂直35%偏上\n  - 画面比例：4:3\n【景别】\n  - 景别类型：标准特写\n  - 取景范围：头部及前胸，包含伸出的前爪\n  - 画面特征：眼神与毛发质感为重点\n【视觉视角与景深】\n  - 视角效果：平视标准视角，视角温馨亲切\n  - 景深氛围：浅景深，背景虚化为温暖光斑\n【主体描述】\n  - 核心主体：白色波斯猫\n  - 动作姿态：侧卧蜷缩，半眯眼，前爪微伸\n  - 服装造型：无（纯天然蓬松毛发）\n【环境设置】\n  - 环境场景：室内沙发，米色羊毛毯\n  - 光线效果：午后侧逆自然窗光，形成发光边缘\n  - 色彩搭配：乳白、浅米、淡金色，高度统一温馨\n  - 细节刻画：发丝根根分明、胡须通透、肉垫粉嫩、毯子针织纹理，光线在绒毛尖端形成细腻光晕\n【技术参数】治愈系宠物摄影，温暖柔焦风格"
        },
        {
            "category": "美食类",
            "natural": "深色实木餐桌上，一碗正宗的日式豚骨拉面正散发着氤氲的热气。45度俯拍视角完美展示了碗内的丰富内容：浓郁如牛奶般的乳白色汤底中，卷曲的极细直面呈现出金黄的色泽，表面整齐摆放着两片肥瘦相间的炙烤叉烧，边缘略带焦褐色。一颗对半切开的溏心蛋露出晶莹剔透的流心蛋黄，翠绿的葱花与鲜嫩的海苔片点缀其间。\n\n侧逆方向的主光在拉面汤的表面形成一层明亮的反光薄膜，凸显了汤底的厚重胶质感。筷子被精心架在碗沿，旁边的小碟中盛着粉红色的腌姜，增加了画面的生活气息。\n\n背景被柔和的浅景深虚化成温暖朦胧的木色与和风装饰剪影，完全避免了杂乱。整个画面的色彩令人食欲大开：奶白与金黄交织，点缀以翠绿、绯红与深褐，层次分明。光线在溏心蛋的晶莹表面与叉烧的焦褐边缘之间形成丰富的反射层次，热气在光影中升腾，让这道料理仿佛拥有了自己的生命与呼吸。",
            "structured": "【类别】美食类\n【画面构图】\n  - 构图方式：对角线构图，筷子与碗沿形成斜向引导线\n  - 主体位置：水平50%居中，垂直45%偏上\n  - 画面比例：1:1\n【景别】\n  - 景别类型：微距特写（静物）\n  - 取景范围：完整碗面及周边餐具\n  - 画面特征：俯视细节饱满，突出食材质感\n【视觉视角与景深】\n  - 视角效果：45度标准俯视，展示扁平化构图美感\n  - 景深氛围：浅景深，碗内主体清晰，四周点缀与背景虚化\n【主体描述】\n  - 核心主体：日式豚骨拉面\n  - 动作姿态：静态展示，热气蒸腾\n  - 服装造型：无\n【环境设置】\n  - 环境场景：深木纹餐桌，日式居酒屋风格\n  - 光线效果：侧逆窗光，汤面形成高光反膜，立体感强\n  - 色彩搭配：乳白、金黄叉烧、翠绿葱花、深褐木色\n  - 细节刻画：叉烧焦痕、溏心蛋流心、葱花颗粒、面条卷曲度，热气在光影中升腾\n【技术参数】温暖食欲风格，商业美食摄影质感"
        }
    ]
}

PROMPT_EXPANDER_EN = {
    "name": "Prompt Expander (Natural Language Aesthetics Edition)",
    "description": "As a professional AI image generation prompt engineer, I generate artistically compelling, aesthetically refined, and well-layered natural language descriptions from short prompts, perfectly suited for mainstream models such as Flux, Z-Image, Qwen-Image, and Krea. I am proficient in photographic aesthetics, lighting narrative, color harmony, and visual composition, skilled at transforming abstract concepts into vivid visual language. For portrait categories, two styles are supported: 'Realistic' style preserves natural breath (skin texture, asymmetric features); 'Influencer' style emphasizes refined filter aesthetics (flawless skin, high-end makeup).",
    "input_template": "Step-by-step thinking to expand the following prompt: 1) Determine the expansion type (portrait, cosplay, game character, product, scene, animal, food, general). 2) Extract the core subject and key action to ensure the theme does not deviate. 3) Design a harmonious color scheme (primary color 60%, secondary 30%, accent 10%) to avoid visual clutter. 4) Choose the most suitable perspective and depth-of-field atmosphere (wide-angle dramatic / standard flat / telephoto compression / macro extreme). 5) Construct a visual narrative: consider how light flows, how colors transition, how details guide the viewer's gaze to linger and reflect, and create mood and atmosphere. 6) Generate the {mode} description according to the category, ensuring clear visual hierarchy, unified color, and narrative lighting. If no category matches, create one autonomously.\nUser input: #\n\n[Core Artistic Principles]\n- Tell a story with visual language: let light, color, and texture together serve emotional expression, making the image worth revisiting.\n- Embrace natural transitions: reject harsh edges and abrupt contrasts, pursue soft gradients between color, light, and depth of field.\n- Texture above clarity: the charm of the real world lies in delicate textures (skin pores, fabric weaves, rusted metal), not mechanical sharpness.\n- Negative space and breath: leave visual resting areas in the frame, avoid element stacking, create a thought-provoking mood.\n\n[Portrait Style Identification Rules]\n- If containing words like 'influencer', 'refined', 'perfect', 'filter', 'beauty' → adopt [Influencer Style]: emphasizes porcelain-like flawless delicate skin, refined three-dimensional symmetrical features, soft dreamy light effects, high-end fashion sense, presenting the aesthetic of a social-media retouched masterpiece.\n- If containing words like 'realistic', 'natural', 'photorealistic', 'documentary', or if unspecified → adopt [Realistic Style]: emphasizes natural skin texture with breath, retains subtle asymmetric features and everyday imperfections (freckles, fine lines), natural lighting transitions, presenting a narrative sense of authentic photography.\n\nExpansion key points: only expand visually presentable content, do not add narrative voice-overs. Ensure harmonious color matching, avoid stacking irrelevant elements. Natural paragraphs can be multi-layered: subject description, environment and background, lighting and atmosphere, details and texture.",
    "output_format_suffix": {
        "natural": "Natural paragraphs (multiple paragraphs allowed), smoothly integrating subject features, environment space, lighting tones, and texture details, without specific numerical parameters, with rich visual language. No additional explanation.",
        "structured": "[Category] Category name (Realistic Style / Influencer Style)\n[Frame Composition]\n  - Composition type: composition type (rule of thirds / symmetry / diagonal / framing / center / triangle / S-curve, etc.)\n  - Subject position: horizontal position + vertical position (expressed as percentages, e.g., horizontal 50% centered, vertical 40% upper)\n  - Aspect ratio: aspect ratio (16:9 / 9:16 / 4:3 / 1:1, etc.)\n[Shot Scale]\n  - Shot type: macro close-up / standard close-up / shoulder shot / seven-eighths portrait / nine-tenths portrait / full-body portrait (omit if no person)\n  - Framing range: clearly indicate which parts are included and where cropped\n  - Frame characteristics: highlight visual weight and compositional tension\n[Visual Perspective and Depth of Field]\n  - Perspective effect: wide-angle perspective / standard flat view / telephoto spatial compression / macro magnification effect\n  - Depth of field atmosphere: shallow depth of field soft bokeh / medium depth with environment / deep depth with full clarity\n[Subject Description]\n  - Core subject: appearance/species/object features, highlight the most striking visual elements\n  - Action/posture: dynamic or static pose, body language and interaction with props\n  - Clothing and styling: material, color, style, and decorative details\n[Realistic Details] (for Realistic Style, integrated description)\n  - Skin texture: natural and translucent skin quality, visible fine pores and authentic texture, with gentle uneven skin tone and slight everyday imperfections (e.g., freckles, fine under-eye lines), presenting a healthy natural sheen under light\n  - Hair features: smooth and natural hair, with flyaways and fine hair details, eyelashes and eyebrows distinct\n  - Facial features: retaining asymmetric natural beauty, lips with realistic lines, skin tone naturally transitioning from within\n[Refined Details] (for Influencer Style, integrated description)\n  - Makeup and skin: refined flawless porcelain skin, clear fair or healthy glow, three-dimensional high-end makeup (deep eye makeup, full lip color)\n  - Facial features and expression: perfectly proportioned refined features, captivating expressive eyes, impeccable expression management\n  - Filter atmosphere: soft dreamy filter, unified high-end color palette, presenting a social-media blockbuster look\n[Environment Setting]\n  - Environment scene: specific space and background elements\n  - Lighting effect: light source direction and quality (soft/hard/backlight/side light), creating atmosphere\n  - Color palette: primary and accent colors, ensuring overall harmony and layering\n  - Detail depiction: textural elements in the environment (texture, reflections, shadows)\n[Technical Parameters] Overall style tags (e.g., cinematic quality, commercial retouching, natural documentary, cyberpunk, etc.)"
    },
    "task_requirements": [
        "Expanded content should be vivid and professional, using aesthetic and photographic terminology, but absolutely no specific focal length in mm or aperture f-number",
        "Strictly maintain the original meaning, do not add irrelevant visual elements beyond the subject",
        "Interactions between people and objects must conform to real-world physical logic",
        "Prioritize harmonious and unified color schemes (primary/secondary/accent proportions appropriate), avoid disorder",
        "Composition can be naturally formed by body, environment, and lighting, without rigidly adhering to fixed templates",
        "Must clearly specify subject position (horizontal + vertical percentages) to ensure visual weight stands out",
        "Must describe the visual effect of the perspective (e.g., exaggerated perspective, spatial compression) and depth-of-field atmosphere (bokeh/clarity)",
        "Must correctly determine the shot scale, ensuring accurate cropping position description",
        "Portrait categories must determine style based on keywords: 'influencer/refined/perfect' → Influencer Style; 'realistic/natural' or unspecified → Realistic Style",
        "Realistic Style should highlight natural texture and imperfections, Influencer Style should emphasize flawless refinement and filter feel; both expressed in fluent paragraph form, no bullet lists",
        "Must follow the [Core Artistic Principles]: tell a story with visual language, pursue natural transitions, texture above clarity, negative space and breath",
        "Natural mode outputs one or more coherent paragraphs, preferably layered by [environment and lighting], [subject and pose], [details and texture]; structured mode outputs by fields",
        "Total word count controlled between 300-600 words (natural mode), ensuring moderate information density, not verbose"
    ],
    "constraints": {
        "max_length": 800,
        "keep_core_keywords": True,
        "avoid_numeric_parameters": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True
    },
    "positive_constraints": "Subject is prominent and clear, forms and proportions accurate, texture realistic and delicate, lighting layered and narrative, color ratios harmonious and unified, composition logically clear with visual guidance. The frame is clean and restrained, retaining only core narrative elements, no redundant clutter. Portrait style recognizability is strong: Realistic Style retains natural texture and asymmetric features, Influencer Style presents flawless refined filter quality; other categories comply with their corresponding visual language, combining aesthetics and generation stability, authentic natural and breathable.",
    "negative_prompts": "Subject distortion or deformation, fake plastic texture, messy overexposed lighting, dirty color overflow, redundant element stacking, unbalanced chaotic composition, incorrect perspective and proportion, low-resolution blur, extraneous objects or passers-by, subtitles or watermarks, harsh lighting discontinuities, over-sharpening, jagged rough edges. Portrait: Realistic Style over-smoothing with no texture, Influencer Style distorted fake facial features; Scene: cluttered layers, chaotic spatial logic; Product: false reflections, distorted material.",
    "examples": [
        {
            "category": "Portrait (Realistic Style)",
            "natural": "Afternoon sunlight pours through the cafe's floor-to-ceiling windows, forming soft back-side lighting that reveals subtle dust motes in the air. An Asian woman in her mid-20s sits at a wooden table by the window, wearing a soft light-beige knitted cardigan with delicate crocheted lace at the cuffs. She lowers her gaze, absorbed in reading a yellowed hardcover book, her left hand gently resting on the page edge, her right index finger poised to turn the page.\n\nA mid-shot composition with a standard flat perspective creates a strong sense of immersion. Her long black hair falls naturally, a strand slipping across her forehead, and the stray hairs near her ears appear softly translucent against the backlight. The warm afternoon light makes her skin appear naturally luminous, with faint freckles visible on her cheeks and subtle pores around her nose, natural under-eye bags and slight shadows, lips a healthy light pink with faint lip lines.\n\nThe color palette is dominated by warm browns, off-whites, and wood tones, with low saturation bringing a warm and soothing visual feel. On the table corner sits a latte with delicate latte art, its cup reflecting the street view outside the window. The overall atmosphere is quiet and healing, full of lifelike narrative realism. Light forms soft gradients on the pages, shadows soften naturally into fabric textures; the entire frame feels like a cinematic moment frozen in time, revealing new details and warmth with each glance.",
            "structured": "[Category] Portrait (Realistic Style)\n[Frame Composition]\n  - Composition type: rule of thirds, subject slightly right of center, book and coffee cup forming a triangular stable structure\n  - Subject position: horizontal 55% right, vertical 50% centered\n  - Aspect ratio: 3:2\n[Shot Scale]\n  - Shot type: seven-eighths portrait\n  - Framing range: from top of head to waist, fully showing head, shoulders, and hand gestures\n  - Frame characteristics: upper body as main subject, environment rich but not distracting\n[Visual Perspective and Depth of Field]\n  - Perspective effect: standard flat view, close to human eye, no perspective distortion\n  - Depth of field atmosphere: shallow depth soft bokeh, cafe background gently blurred, subject stands out\n[Subject Description]\n  - Core subject: 25-year-old Asian woman, long black hair, soft almond eyes, focused reading expression\n  - Action/posture: seated reading, right hand hovering ready to turn page, body slightly leaning forward\n  - Clothing and styling: light beige knitted cardigan with crocheted lace cuffs, simple everyday wear\n[Realistic Details]\n  - Skin texture: natural translucent skin, retaining fine pores around nose and faint freckles on cheeks, natural under-eye bags and slight shadows, healthy flush on cheekbones\n  - Hair features: smooth hair with flyaways, edge hairs appearing translucent against backlight\n  - Facial features: slight asymmetry (left eye slightly higher), natural light pink lips with realistic lip lines\n[Environment Setting]\n  - Environment scene: cozy cafe by window, wooden table, sheer curtains\n  - Lighting effect: afternoon natural side-backlight, soft diffused, creating rim light and warm atmosphere\n  - Color palette: warm brown, off-white, natural wood, low saturation, visually comfortable\n  - Detail depiction: yellowed book pages, delicate latte art, clear wood grain, translucent curtains, soft light gradients on pages\n[Technical Parameters] Natural documentary photography style, lifelike narrative, realistic texture"
        },
        {
            "category": "Portrait (Influencer Style)",
            "natural": "In a carefully arranged cream-toned influencer cafe, warm point lights blend with soft window light, creating a dreamy and soft creamy-skin atmosphere. A fashionable woman in her early 20s faces the camera, her sophisticated Korean dewy glass-skin base makeup giving her face a flawless appearance, as if wrapped in a soft-focus filter.\n\nThe lens uses a close-up shot scale, with an 85mm equivalent medium-telephoto perspective providing smooth spatial compression, turning the background into a warm field of bokeh. She tilts her head slightly, her glossy black long wavy hair cascading over her shoulders with elegant curls. Her eye makeup uses deep earth tones, with thick curled lashes, and her lips are coated in the trendy matte mauve shade; her features are three-dimensional and refined.\n\nShe wears an off-white cashmere cropped top, revealing her delicate collarbones, with pearl earrings emitting a warm luster under the light. The overall image presents a low-contrast, high-key soft quality; the greenery and metallic decorations in the background are blurred into abstract color masses, making the subject exceptionally prominent. Colors transition finely between warm white and beige, and the entire frame is wrapped in a soft halo, as if a carefully curated dream moment has been permanently frozen.",
            "structured": "[Category] Portrait (Influencer Style)\n[Frame Composition]\n  - Composition type: center composition, face centered, gaze directly at lens\n  - Subject position: horizontal 50% centered, vertical 45% upper\n  - Aspect ratio: 3:2\n[Shot Scale]\n  - Shot type: standard close-up\n  - Framing range: from top of head to chin, shoulders completely excluded\n  - Frame characteristics: face fills the frame, strong visual impact\n[Visual Perspective and Depth of Field]\n  - Perspective effect: medium-telephoto view, spatial compression, enhanced facial three-dimensionality\n  - Depth of field atmosphere: shallow depth with extreme soft bokeh, background turned into creamy light spots\n[Subject Description]\n  - Core subject: young woman in early 20s, refined three-dimensional features, glossy black long wavy hair\n  - Action/posture: slightly tilted head, direct gaze, confident and composed expression\n  - Clothing and styling: off-white cashmere cropped top, pearl earrings, minimalist high-end\n[Refined Details]\n  - Makeup and skin: glass-skin foundation, porcelain-smooth with no visible pores, natural blush adding vitality\n  - Facial features and expression: finely shaped brows, deep expressive eye makeup, perfect matte mauve lip\n  - Filter atmosphere: low-contrast, high-key soft-focus filter, clean and soft visuals\n[Environment Setting]\n  - Environment scene: influencer cafe, simple background with greenery and metallic elements\n  - Lighting effect: warm soft light combined with window natural light, no harsh shadows\n  - Color palette: cream white, beige, champagne gold, unified high-end tones\n  - Detail depiction: hair shine, pearl earring reflections, sweater fuzz, colors transitioning finely between warm white and beige\n[Technical Parameters] High-end influencer style, social-media retouched blockbuster, commercial portrait quality"
        },
        {
            "category": "Product",
            "natural": "Against a dark blue gradient background, a flagship wireless noise-canceling headphone is suspended in the center of the frame. Shot from a 45-degree top-down angle, the product silhouette is clean and sharp, its charcoal-black matte-finished shell exuding a high-tech feel under carefully arranged three-point lighting.\n\nThe key light spreads evenly from the front-left, delicately outlining the leather ear-cup texture and the brushed metal headband's luster; the rear-right accent rim light precisely separates the headphone's edges from the background, giving the product a light floating sensation. A crisp mirror reflection on the bottom adds a premium commercial quality.\n\nUnder high-resolution close-up, the tiny ventilation pores of the memory foam ear pads and the precise scale markings on the adjustable headband are clearly visible. The lighting setup eliminates unwanted shadows, resulting in a clean, crisp image; cool blue tones interplay with dark gray and black, creating an ultimate sense of calm professionalism. The differential reflections on metal and matte surfaces form rich grayscale layers, silently conveying the product's material quality.",
            "structured": "[Category] Product\n[Frame Composition]\n  - Composition type: centered symmetry, headphone absolutely centered\n  - Subject position: horizontal 50% centered, vertical 50% centered\n  - Aspect ratio: 1:1\n[Shot Scale]\n  - Shot type: close-up (still life)\n  - Framing range: full headphone body and bottom mirror reflection\n  - Frame characteristics: rigorous symmetry, full detail visibility\n[Visual Perspective and Depth of Field]\n  - Perspective effect: standard 45-degree top-down, three-dimensionally showing product form\n  - Depth of field atmosphere: shallow depth, product sharp, background uniformly blurred\n[Subject Description]\n  - Core subject: flagship wireless noise-canceling headphone\n  - Action/posture: suspended static display\n  - Clothing and styling: charcoal-black matte shell, brushed metal headband, memory foam ear pads\n[Environment Setting]\n  - Environment scene: professional shadowless photography studio\n  - Lighting effect: three-point lighting (key front-left, fill right, rim right-rear)\n  - Color palette: dark blue gradient background, black, gray, silver cool tones\n  - Detail depiction: leather texture, sponge ventilation holes, brushed metal grain and markings, reflections creating rich grayscale layers on different materials\n[Technical Parameters] Minimalist commercial photography, hardcore tech texture"
        },
        {
            "category": "Cosplay",
            "natural": "In front of a ruined castle ruin, a cosplayer transforms into an anime magical girl, perfectly recreating the character's magnificent combat stance. She holds a magic wand embedded with amethyst, her silver-white hair flying high in the wind, her purple magical robe billowing, the lace and gold trim shimmering with mysterious luster against the backlight.\n\nA standard perspective combined with a mid-shot composition fully captures the dynamic range from head to knee. Her facial makeup is refined, with a touch of purple gradient eye shadow at the outer corners contrasting strongly with the rose-red lips; her gaze is firm, looking ahead as if about to chant a high-level spell.\n\nThe main light from the right simulates the intense light effect of a magical burst, casting a long shadow behind her while illuminating the wand's gemstone radiantly. The color palette features dreamy violet and gold, with dark areas slightly bluish-gray; overall saturation is high, full of the passion and magnificence characteristic of anime. Light dances on the lace and gold trim edges, contrasting with the rough texture of the bluish-gray stone walls—splendid yet retaining a sense of real-world weight.",
            "structured": "[Category] Cosplay\n[Frame Composition]\n  - Composition type: dynamic diagonal, body slightly leaning right, wand pointing left creating visual guidance\n  - Subject position: horizontal 45% left, vertical 50% centered\n  - Aspect ratio: 16:9\n[Shot Scale]\n  - Shot type: nine-tenths portrait\n  - Framing range: from top of head to below knees, dynamically cut at calves\n  - Frame characteristics: large motion amplitude, strong clothing fluttering\n[Visual Perspective and Depth of Field]\n  - Perspective effect: standard eye-level with slight upward angle to enhance character presence\n  - Depth of field atmosphere: medium depth, character sharp, ruins in background faintly visible but not distracting\n[Subject Description]\n  - Core subject: magical girl cosplayer, silver-white hair, crystal wand\n  - Action/posture: combat spell-casting stance, robe flying, determined gaze\n  - Clothing and styling: purple magical robe with lace and gold trim, thigh-high boots\n[Environment Setting]\n  - Environment scene: castle ruins, bluish-gray stone walls and broken arches\n  - Lighting effect: strong side light from right, simulating magical burst, creating dramatic shadows\n  - Color palette: violet, gold as primary, dark bluish-gray as secondary\n  - Detail depiction: wand gem glow, embroidery texture, flowing hair strands, light dancing on lace and gold edges\n[Technical Parameters] Dreamy magnificent style, high anime fidelity"
        },
        {
            "category": "Game Character",
            "natural": "Neon signs flicker in the humid night sky, their reflections shattered on the wet asphalt road. A cyborg warrior in a dark red leather trench coat stands on an overpass in a cyberpunk metropolis, his silver mechanical prosthetic limbs reflecting sharp metallic luster under cold blue neon light.\n\nA wide-angle perspective full-body composition incorporates the towering skyscrapers and holographic advertisements into the frame, greatly enhancing spatial depth and sci-fi intensity. The warrior crouches slightly, lowering his center of gravity, right hand gripping a massive thermal battle axe, his left arm's mechanical joints emitting faint energy pulses as he charges up. The wind blows his silver-white fringe, his face bearing old scars and a glowing blue cybernetic eye, exuding a defiant and unruly temperament.\n\nColors are dominated by deep midnight blue and solid black, accented with high-saturation fluorescent pink and cool purple neon. The overall contrast is strong; despite the high information density, the subject remains prominent through unified cool tones and lighting guidance. Neon lights reflect as impressionistic color blocks on the wet road, and the interplay between the cold gleam of metal prosthetics and the matte texture of the leather coat creates a delicate balance, bringing a distinct cyber-city order out of chaos.",
            "structured": "[Category] Game Character\n[Frame Composition]\n  - Composition type: diagonal leading lines and framing, overpass railing forms foreground frame\n  - Subject position: horizontal 30% left, vertical 60% lower\n  - Aspect ratio: 16:9\n[Shot Scale]\n  - Shot type: full-body portrait\n  - Framing range: full body from head to toe, environment occupies two-thirds of frame\n  - Frame characteristics: deep interaction between character and environment, strong depth\n[Visual Perspective and Depth of Field]\n  - Perspective effect: wide-angle perspective, strongly exaggerating foreground-background distance\n  - Depth of field atmosphere: deep depth, clear details from front to back, showcasing grand world-building\n[Subject Description]\n  - Core subject: cyborg warrior, dark red trench coat, silver mechanical prosthetics\n  - Action/posture: charging combat stance, body low, gripping battle axe\n  - Clothing and styling: dark red leather trench coat, metal armor, tactical belt\n[Environment Setting]\n  - Environment scene: cyberpunk overpass, neon city, wet road\n  - Lighting effect: cool blue neon as key, pink-purple accent lights, road reflections\n  - Color palette: midnight blue, black as primary, fluorescent pink, cool purple as accents\n  - Detail depiction: prosthetic joint textures, worn coat edges, holographic grain, neon reflections as impressionistic color blocks\n[Technical Parameters] Cyberpunk style, 3A game CG-level quality"
        },
        {
            "category": "Scene",
            "natural": "The first golden ray of morning sunlight diagonally pierces through the towering canopy of an ancient dense forest, forming sacred crepuscular rays that illuminate tiny water vapor and dust particles floating in the air. Deep in the forest, a winding path covered with fallen leaves leads into the distance, flanked by thick dark green moss, with a moist earthy scent permeating the air.\n\nA wide-angle panoramic composition layers the rough tree trunks in the foreground, stone ruins in the midground, and misty morning haze in the background, creating a strong sense of spatial penetration. In the lower-left of the frame, a massive stone archway covered in ivy stands quietly, with a faint glow emanating from its gaps becoming the focal point.\n\nThe overall color palette adopts a harmonious mid-to-low saturation green-brown scheme, with the golden sunlight and cool green of the shade forming a natural warm-cool contrast. Mist flows naturally through the trees, softening light boundaries, making the entire scene feel like an illustration taken from an epic fantasy novel—serene and profound. The interplay of soft halos formed by light passing through layered foliage and the cool tones of shadows fills every inch of the frame with delicate breath.",
            "structured": "[Category] Scene\n[Frame Composition]\n  - Composition type: combination of vertical lines and converging lines, path guides gaze toward distant ruins\n  - Subject position: horizontal 50% centered, vertical 40% upper (ruins)\n  - Aspect ratio: 16:9\n[Shot Scale]\n  - Shot type: long shot (grand scene)\n  - Framing range: covers foreground trees, midground path, background ruins and sky\n  - Frame characteristics: rich layering, strong perspective\n[Visual Perspective and Depth of Field]\n  - Perspective effect: wide-angle eye-level, maximizing spatial depth\n  - Depth of field atmosphere: deep depth, from foreground leaves to distant mist all sharp\n[Subject Description]\n  - Core subject: ancient dense forest, stone ruins\n  - Action/posture: purely natural static\n  - Clothing and styling: N/A\n[Environment Setting]\n  - Environment scene: deep primeval forest, moss-covered stone steps, misty haze\n  - Lighting effect: morning crepuscular rays, angled light beams, soft diffusion\n  - Color palette: dark green, warm gold, moss brown, low-saturation harmonious transitions\n  - Detail depiction: rough bark texture, fuzzy moss, leaf veins, weathered stone pillars, interplay of soft halos and cool shadows\n[Technical Parameters] Epic fantasy scene, cinematic natural lighting"
        },
        {
            "category": "Animal",
            "natural": "Warm afternoon sunlight filters through white sheer curtains onto a soft beige wool blanket, where a pure white Persian cat lounges lazily curled up. Its sapphire-like eyes are half-closed, exuding an air of noble languor, and its fluffy long fur is rimmed with a golden halo against the backlight.\n\nA standard close-up shot with a 50mm-equivalent perspective focuses precisely on the cat's face. The lens captures its pink nose, long translucent white whiskers, and the fluffy texture of its thick coat. One front paw is naturally extended, showing pink paw pads, while its tail tip casually rests on the edge of the blanket.\n\nThe overall tone is warm and unified, dominated by milky white, light beige, and soft pale gold. The side-backlight from the left creates distinct light and dark divisions in the cat's fur, yet without any harshness—instead enhancing the three-dimensional fluffy texture. The background is blurred into a soft warm bokeh, with no extraneous objects, highlighting the cat's healing and elegant aristocratic temperament. Light forms delicate halos on the fur tips, shadows soften between the fur strands, making the photo feel tangibly warm and soft.",
            "structured": "[Category] Animal\n[Frame Composition]\n  - Composition type: lower-center, cat's face in upper-third\n  - Subject position: horizontal 50% centered, vertical 35% upper\n  - Aspect ratio: 4:3\n[Shot Scale]\n  - Shot type: standard close-up\n  - Framing range: head and chest, including extended front paw\n  - Frame characteristics: focus on gaze and fur texture\n[Visual Perspective and Depth of Field]\n  - Perspective effect: eye-level standard, warm and intimate view\n  - Depth of field atmosphere: shallow depth, background blurred into warm bokeh\n[Subject Description]\n  - Core subject: white Persian cat\n  - Action/posture: side-lying curled, half-closed eyes, paw slightly extended\n  - Clothing and styling: N/A (purely natural fluffy fur)\n[Environment Setting]\n  - Environment scene: indoor sofa, beige wool blanket\n  - Lighting effect: afternoon natural side-backlight through window, creating rim light\n  - Color palette: milky white, light beige, pale gold, highly unified and warm\n  - Detail depiction: distinct fur strands, translucent whiskers, pink paw pads, blanket knit texture, delicate halos on fur tips\n[Technical Parameters] Healing pet photography, warm soft-focus style"
        },
        {
            "category": "Food",
            "natural": "On a dark solid wood dining table, a bowl of authentic Japanese tonkotsu ramen emits steaming hot vapors. A 45-degree top-down perspective perfectly displays the rich contents inside: the milky white broth is thick like milk, with curly thin noodles showing a golden hue, topped with two perfectly grilled slices of fatty chashu with slightly charred edges. A halved soft-boiled egg reveals its glistening runny yolk, garnished with vibrant green scallions and fresh nori seaweed.\n\nSide-backlight key lighting creates a bright reflective film on the surface of the broth, highlighting its rich gelatinous texture. Chopsticks are neatly placed on the bowl's rim, with a small dish of pink pickled ginger adding a touch of life to the composition.\n\nThe background is softly blurred with a shallow depth of field into warm, hazy wood tones and Japanese-style decorative silhouettes, avoiding any clutter. The overall color palette is incredibly appetizing: milky white and golden yellow interwoven, accented with emerald green, crimson, and deep brown, clear in layers. Light forms rich reflections on the glossy egg surface and the charred edges of the chashu, while steam rises through the light, giving the dish a life and breath of its own.",
            "structured": "[Category] Food\n[Frame Composition]\n  - Composition type: diagonal composition, chopsticks and bowl edge forming oblique leading lines\n  - Subject position: horizontal 50% centered, vertical 45% upper\n  - Aspect ratio: 1:1\n[Shot Scale]\n  - Shot type: macro close-up (still life)\n  - Framing range: full bowl and surrounding utensils\n  - Frame characteristics: top-down detail-rich, highlighting ingredient textures\n[Visual Perspective and Depth of Field]\n  - Perspective effect: standard 45-degree top-down, showcasing flattened composition aesthetics\n  - Depth of field atmosphere: shallow depth, bowl contents sharp, surrounding accents and background blurred\n[Subject Description]\n  - Core subject: Japanese tonkotsu ramen\n  - Action/posture: static display, steam rising\n  - Clothing and styling: N/A\n[Environment Setting]\n  - Environment scene: dark wood grain table, izakaya-style setting\n  - Lighting effect: side-back window light, broth surface with bright highlights, strong three-dimensionality\n  - Color palette: milky white, golden chashu, emerald scallions, deep brown wood\n  - Detail depiction: chashu char marks, runny egg yolk, scallion granules, noodle curliness, steam rising through light\n[Technical Parameters] Warm appetizing style, commercial food photography quality"
        }
    ]
}

EDIT_COMBINED_ZH = {
    "name": "Edit编辑提示增强器",
    "description": "生成精确、简洁的编辑提示词。支持添加、删除、替换、文本编辑、人物编辑、风格转换、材质替换、内容填充。编辑指令必须与原图逻辑、光影、透视保持一致。智能分析原图特征，确保编辑后的内容与原图完美融合。",
    "input_template": "逐步思考：1）分析原图特征（光源方向、光线类型、色彩基调、透视角度、材质质感、场景氛围）；2）识别用户编辑意图（添加/删除/替换/风格转换等）；3）匹配原图光影和透视规则；4）生成精确的编辑指令，确保视觉一致性。\n\n根据图片内容和用户提示，生成{mode}编辑提示。用户输入：#\n\n核心原则：编辑内容必须与原图的光源方向、光线类型、色彩基调、透视角度、材质质感保持一致。添加对象需考虑投影、反射、阴影与原图匹配。",
    "output_format_suffix": {
        "natural": "自然段落，精确描述编辑操作，包含原图特征分析和编辑指令。无解释。\n\n【原图分析模板】光源方向：[左/右/上/下/前/后]方；光线类型：[柔光/硬光/混合光/逆光]；色彩基调：[暖色调/冷色调/中性色调]；透视角度：[平视/俯视/仰视/倾斜]；材质质感：[金属/木质/布料/玻璃/皮革/皮肤]。\n\n【编辑操作公式】位置描述 + 对象特征 + 光影匹配（高光方向+阴影位置） + 材质反射 + 透视角度 + 色彩协调",
        "structured": "【原图分析】\n  - 光源方向：光源方向描述内容\n  - 光线类型：光线类型描述内容\n  - 色彩基调：色彩基调描述内容\n  - 透视角度：透视角度描述内容\n  - 材质质感：材质质感描述内容\n【任务信息】\n  - 任务类型：任务类型（添加物体/删除物体/替换物体/文本编辑/人物编辑/风格转换/材质替换/内容填充）\n  - 目标对象：目标对象描述内容\n【操作详情】\n  - 操作描述：详细操作描述内容\n  - 参数要求：参数要求描述内容（尺寸、位置、角度、光影）\n【视觉规范】\n  - 光影一致性：光影与原图光源匹配描述\n  - 透视一致性：透视角度与原图一致描述\n  - 色彩一致性：色彩与原图基调协调描述"
    },
    "general_principles": [
        "提示简洁全面具体",
        "指令矛盾时合理推断修正",
        "保持原始核心意图",
        "添加对象必须与原图逻辑、光影、透视、色彩平衡一致",
        "编辑前先分析原图特征：光源方向、光线类型、色彩基调、透视角度、材质质感",
        "光影匹配原则：高光位置与光源方向一致，阴影方向与光源相反，阴影强度与光线类型匹配",
        "材质反射原则：金属→高光锐利，布料→漫反射柔和，玻璃→折射与反射并存，皮肤→细腻漫反射"
    ],
    "task_rules": {
        "add_delete_replace": "指令清晰则保留，模糊则补充最少细节。替换任务明确用X替换Y。添加物体需描述位置、大小、材质、光影反射（高光方向+阴影位置）。删除物体需描述删除区域，保持背景纹理一致性。",
        "text_edit": "文本内容用英文双引号括起来。指定位置、颜色（与原图色彩基调协调）、字体风格（匹配场景氛围）。文字光影需与原图光源一致。",
        "person_edit": "保持人物核心视觉一致性（种族、性别、年龄、发型、表情、服装）。表情变化需自然细微，皮肤光影不变。发型修改需考虑发束走向和光泽感。服装修改需保持布料褶皱和质感。",
        "style_transfer": "指定风格则用关键特征描述（如'梵高星空风格'→漩涡状笔触、蓝黄高对比）。上色任务使用固定模板：修复并为照片上色，保持灰度层次，色彩与场景氛围协调。",
        "material_replace": "明确对象和材质。材质替换需保持光影反射特性（金属→高光锐利，布料→漫反射，玻璃→折射反射）。文本材质替换模板：将文本xxxx的材质改为激光风格（金属高光+霓虹边缘）。",
        "logo_pattern": "保留原始形状结构。迁移到新场景时保持形状一致，透视变形匹配。logo颜色需与场景色彩协调，边缘清晰。",
        "content_fill": "修复任务模板：对这张图像进行修复，消除指定瑕疵（划痕/污点），基于周围纹理智能填充，保持光影和色彩一致。扩展任务模板：通过图像扩展将图像延伸到其边界之外，保持内容逻辑、光影和风格一致。",
        "multi_image": "明确指定修改哪个图像的元素。风格化任务描述参考图像的风格，保留源图像视觉内容，仅迁移色彩/笔触/纹理。",
        "background_edit": "背景修改需保持景深层次，前景清晰背景虚化或反之。背景元素需与主体透视一致，色彩与主体协调。"
    },
    "constraints": {"max_length": 800},
    "task_requirements": [
        "提示简洁全面具体",
        "指令矛盾时合理推断修正",
        "保持原始核心意图",
        "添加对象必须与原图逻辑、光影、透视、色彩平衡一致",
        "必须先分析原图特征（光源方向、光线类型、色彩基调、透视角度、材质质感）",
        "光影匹配原则：高光位置与光源方向一致，阴影方向与光源相反",
        "材质反射原则：不同材质具有不同的反射特性",
        "natural模式：输出自然段落；structured模式：输出结构化提示词"
    ],
    "examples": [
        {
            "natural": "原图分析：光源方向为右前方柔光箱，光线类型为柔和侧光，色彩基调为暖色调，透视角度为平视，材质质感包含木质桌面和金属笔记本电脑。在笔记本电脑右侧的木质桌子上添加一只橙色虎斑猫，绿色眼睛，毛发质感真实，猫身体右侧应有高光（匹配右前方光源），左侧产生软阴影（边缘柔和），猫的体型、毛色与室内环境协调，透视角度与桌面一致。",
            "structured": "【原图分析】\n  - 光源方向：右前方\n  - 光线类型：柔和侧光（柔光箱）\n  - 色彩基调：暖色调\n  - 透视角度：平视\n  - 材质质感：木质桌面、金属笔记本电脑\n【任务信息】\n  - 任务类型：添加物体\n  - 目标对象：橙色虎斑猫\n【操作详情】\n  - 操作描述：在笔记本电脑右侧的木质桌子上添加一只橙色虎斑猫，绿色眼睛，毛发质感真实\n  - 参数要求：猫身体右侧有高光，左侧有软阴影，阴影边缘柔和\n【视觉规范】\n  - 光影一致性：高光位置与右前方光源一致，阴影方向与光源相反\n  - 透视一致性：透视角度与桌面一致\n  - 色彩一致性：猫的毛色与室内暖色调环境协调"
        },
        {
            "natural": "原图分析：光源方向为左侧暖光，光线类型为硬光，色彩基调为中性色调，透视角度为平视，材质质感包含陶瓷咖啡杯和人物手部皮肤。将人物手中的红色咖啡杯替换为蓝色星空图案的马克杯，杯身高光反射需与左侧暖光源一致（高光位于左侧），杯把方向不变，材质为陶瓷，漫反射高光，与咖啡杯原本的材质反射特性一致。",
            "structured": "【原图分析】\n  - 光源方向：左侧\n  - 光线类型：硬光（暖光）\n  - 色彩基调：中性色调\n  - 透视角度：平视\n  - 材质质感：陶瓷咖啡杯、皮肤\n【任务信息】\n  - 任务类型：替换物体\n  - 目标对象：红色咖啡杯\n【操作详情】\n  - 操作描述：用蓝色星空图案的马克杯替换红色咖啡杯，星空图案为深蓝底白色星点，杯把方向不变\n  - 参数要求：杯身高光位于左侧（匹配暖光源），保持与原图相同的尺寸和透视角度\n【视觉规范】\n  - 光影一致性：高光位置与左侧暖光源一致\n  - 透视一致性：保持与原图相同的透视角度\n  - 色彩一致性：深蓝星空图案与中性色调环境协调"
        },
        {
            "natural": "原图分析：光源方向为上方自然光，光线类型为柔光，色彩基调为暖色调，透视角度为俯视，材质质感包含木质地板和织物沙发。将沙发上的灰色抱枕替换为米色针织抱枕，抱枕表面有细腻的针织纹理，顶部有柔和高光（匹配上方光源），底部有轻微阴影，针织材质为漫反射，与周围环境协调。",
            "structured": "【原图分析】\n  - 光源方向：上方\n  - 光线类型：柔光（自然光）\n  - 色彩基调：暖色调\n  - 透视角度：俯视\n  - 材质质感：木质地板、织物沙发\n【任务信息】\n  - 任务类型：替换物体\n  - 目标对象：灰色抱枕\n【操作详情】\n  - 操作描述：用米色针织抱枕替换灰色抱枕，抱枕表面有细腻的针织纹理\n  - 参数要求：顶部有柔和高光，底部有轻微阴影\n【视觉规范】\n  - 光影一致性：高光位置与上方光源一致\n  - 透视一致性：保持俯视角度\n  - 色彩一致性：米色与暖色调环境协调，针织质感自然"
        },
        {
            "natural": "原图分析：光源方向为右侧冷光，光线类型为硬光，色彩基调为冷色调，透视角度为仰视，材质质感包含金属框架和玻璃。在窗户旁边添加一盆绿萝盆栽，白色陶瓷花盆，叶片翠绿有光泽，右侧叶片有明亮高光（匹配右侧冷光源），左侧叶片有明显阴影，花盆底部有投射阴影，透视角度与仰视一致。",
            "structured": "【原图分析】\n  - 光源方向：右侧\n  - 光线类型：硬光（冷光）\n  - 色彩基调：冷色调\n  - 透视角度：仰视\n  - 材质质感：金属框架、玻璃\n【任务信息】\n  - 任务类型：添加物体\n  - 目标对象：绿萝盆栽\n【操作详情】\n  - 操作描述：在窗户旁边添加一盆绿萝盆栽，白色陶瓷花盆，叶片翠绿有光泽\n  - 参数要求：右侧叶片有明亮高光，左侧叶片有明显阴影，花盆底部有投射阴影\n【视觉规范】\n  - 光影一致性：高光位置与右侧冷光源一致，阴影强烈（硬光特征）\n  - 透视一致性：保持仰视角度，盆栽底部略小\n  - 色彩一致性：翠绿叶片与冷色调环境形成对比但协调"
        }
    ]
}

EDIT_COMBINED_EN = {
    "name": "Edit Prompt Enhancer",
    "description": "Generates precise and concise edit prompts. Supports add, delete, replace, text editing, character editing, style transfer, material replacement, and content filling. Edit instructions must remain consistent with the original image's lighting, perspective, and logic. Intelligently analyzes original image features to ensure edited content blends perfectly with the original.",
    "input_template": "Step-by-step thinking: 1) Analyze the original image features (light source direction, light type, color tone, perspective angle, material texture, scene atmosphere); 2) Identify the user's editing intent (add/delete/replace/style transfer, etc.); 3) Match the original lighting and perspective rules; 4) Generate precise editing instructions to ensure visual consistency.\n\nBased on the image content and user prompt, generate {mode} edit prompt. User input: #\n\nCore principle: Edited content must remain consistent with the original image's light source direction, light type, color tone, perspective angle, and material texture. Added objects must consider projection, reflection, and shadow matching with the original.",
    "output_format_suffix": {
        "natural": "Natural paragraph, precisely describing the edit operation, including original image analysis and edit instructions. No explanation.\n\n[Original Image Analysis Template]Light source direction: [left/right/up/down/front/back]; Light type: [soft/hard/mixed/backlight]; Color tone: [warm/cool/neutral]; Perspective angle: [eye-level/top-down/low-angle/tilted]; Material texture: [metal/wood/fabric/glass/leather/skin].\n\n[Edit Operation Formula]Position description + Object features + Lighting matching (highlight direction + shadow position) + Material reflection + Perspective angle + Color coordination",
        "structured": "[Original Image Analysis]\n  - Light Source Direction: light source direction description\n  - Light Type: light type description\n  - Color Tone: color tone description\n  - Perspective Angle: perspective angle description\n  - Material Texture: material texture description\n[Task Information]\n  - Task Type: task type (add object / delete object / replace object / text edit / character edit / style transfer / material replace / content fill)\n  - Target Object: target object description\n[Operation Details]\n  - Operation Description: detailed operation description\n  - Parameter Requirements: parameter requirements (size, position, angle, lighting)\n[Visual Specifications]\n  - Lighting Consistency: lighting matching with original source description\n  - Perspective Consistency: perspective matching with original description\n  - Color Consistency: color coordination with original tone description"
    },
    "general_principles": [
        "Prompts should be concise, comprehensive, and specific",
        "When instructions conflict, make reasonable inferences and corrections",
        "Preserve the original core intent",
        "Added objects must be consistent with the original logic, lighting, perspective, and color balance",
        "Before editing, analyze original features: light source direction, light type, color tone, perspective angle, material texture",
        "Lighting matching principle: highlight position aligns with light source, shadow direction opposite to light source, shadow intensity matches light type",
        "Material reflection principle: metal → sharp highlights, fabric → soft diffuse reflection, glass → refraction and reflection coexisting, skin → fine diffuse reflection"
    ],
    "task_rules": {
        "add_delete_replace": "Keep if instruction is clear, supplement minimal details if vague. Replacement tasks: explicitly use X to replace Y. Add object: describe position, size, material, light reflection (highlight direction + shadow position). Delete object: describe deletion area, maintain background texture consistency.",
        "text_edit": "Wrap text content in English double quotes. Specify position, color (coordinating with original tone), font style (matching scene atmosphere). Text lighting must match original light source.",
        "person_edit": "Maintain character core visual consistency (ethnicity, gender, age, hairstyle, expression, clothing). Expression changes should be subtle and natural, skin lighting unchanged. Hairstyle modification must consider hair direction and gloss. Clothing modification must maintain fabric folds and texture.",
        "style_transfer": "If style specified, describe with key features (e.g., 'Van Gogh Starry Night style' → swirling brushstrokes, high-contrast blue-yellow). Coloring tasks use fixed template: restore and colorize the photo, maintain grayscale levels, colors coordinated with scene atmosphere.",
        "material_replace": "Specify object and material clearly. Material replacement must maintain light reflection properties (metal → sharp highlights, fabric → diffuse reflection, glass → refraction/reflection). Text material replacement template: change the material of text xxxx to laser style (metallic highlights + neon edges).",
        "logo_pattern": "Preserve original shape structure. When migrating to new scene, maintain shape consistency, perspective deformation matching. Logo color should coordinate with scene color, edges clear.",
        "content_fill": "Restoration task template: restore this image, eliminate specified imperfections (scratches/stains), intelligently fill based on surrounding texture, maintain lighting and color consistency. Extension task template: extend the image beyond its boundaries, maintain content logic, lighting, and style consistency.",
        "multi_image": "Clearly specify which image's elements to modify. Style transfer tasks: describe the reference image's style, preserve source image visual content, only migrate color/brushwork/texture.",
        "background_edit": "Background modification must maintain depth of field layers, foreground sharp background blurred or vice versa. Background elements must be consistent with subject perspective, colors coordinated with subject."
    },
    "constraints": {"max_length": 800},
    "task_requirements": [
        "Prompts concise, comprehensive, and specific",
        "When instructions conflict, make reasonable inferences and corrections",
        "Preserve the original core intent",
        "Added objects must be consistent with original logic, lighting, perspective, and color balance",
        "Must first analyze original features (light source direction, light type, color tone, perspective angle, material texture)",
        "Lighting matching principle: highlight position aligns with light source, shadow direction opposite to light source",
        "Material reflection principle: different materials have different reflection characteristics",
        "natural mode: output natural paragraph; structured mode: output structured prompt"
    ],
    "examples": [
        {
            "natural": "Original analysis: light source direction is front-right softbox, light type is soft side light, color tone is warm, perspective angle is eye-level, material textures include wooden table and metal laptop. Add an orange tabby cat on the wooden table to the right of the laptop, green eyes, realistic fur texture. The right side of the cat should have highlights (matching front-right source), left side soft shadows (soft edges). The cat's size and color should coordinate with the indoor environment, perspective matching the tabletop.",
            "structured": "[Original Image Analysis]\n  - Light Source Direction: front-right\n  - Light Type: soft side light (softbox)\n  - Color Tone: warm\n  - Perspective Angle: eye-level\n  - Material Texture: wooden table, metal laptop\n[Task Information]\n  - Task Type: add object\n  - Target Object: orange tabby cat\n[Operation Details]\n  - Operation Description: add an orange tabby cat on the wooden table to the right of the laptop, green eyes, realistic fur texture\n  - Parameter Requirements: highlights on the right side of the cat, soft shadows on the left, soft shadow edges\n[Visual Specifications]\n  - Lighting Consistency: highlights align with front-right source, shadows opposite\n  - Perspective Consistency: perspective matches tabletop\n  - Color Consistency: cat's fur coordinates with warm indoor environment"
        },
        {
            "natural": "Original analysis: light source direction is left warm light, light type is hard light, color tone is neutral, perspective angle is eye-level, material textures include ceramic coffee cup and human hand skin. Replace the red coffee cup in the person's hand with a blue starry-pattern mug. The cup's highlight reflection must match the left warm source (highlight on the left), handle direction unchanged, material ceramic with diffuse highlights, consistent with the original cup's reflection properties.",
            "structured": "[Original Image Analysis]\n  - Light Source Direction: left\n  - Light Type: hard light (warm)\n  - Color Tone: neutral\n  - Perspective Angle: eye-level\n  - Material Texture: ceramic coffee cup, skin\n[Task Information]\n  - Task Type: replace object\n  - Target Object: red coffee cup\n[Operation Details]\n  - Operation Description: replace the red coffee cup with a blue starry-pattern mug, dark blue base with white stars, handle direction unchanged\n  - Parameter Requirements: highlight on the left side of the mug (matching warm source), maintain same size and perspective as original\n[Visual Specifications]\n  - Lighting Consistency: highlight position aligns with left warm source\n  - Perspective Consistency: maintain same perspective as original\n  - Color Consistency: dark blue starry pattern coordinates with neutral environment"
        },
        {
            "natural": "Original analysis: light source direction is top natural light, light type is soft light, color tone is warm, perspective angle is top-down, material textures include wooden floor and fabric sofa. Replace the gray cushion on the sofa with a beige knitted cushion. The cushion surface should have fine knitted texture, soft highlights on top (matching top source), slight shadow at the bottom, knitted material with diffuse reflection, coordinating with the environment.",
            "structured": "[Original Image Analysis]\n  - Light Source Direction: top\n  - Light Type: soft light (natural)\n  - Color Tone: warm\n  - Perspective Angle: top-down\n  - Material Texture: wooden floor, fabric sofa\n[Task Information]\n  - Task Type: replace object\n  - Target Object: gray cushion\n[Operation Details]\n  - Operation Description: replace the gray cushion with a beige knitted cushion, fine knitted texture on the surface\n  - Parameter Requirements: soft highlight on top, slight shadow at bottom\n[Visual Specifications]\n  - Lighting Consistency: highlight aligns with top source\n  - Perspective Consistency: maintain top-down angle\n  - Color Consistency: beige coordinates with warm environment, natural knitted texture"
        },
        {
            "natural": "Original analysis: light source direction is right cool light, light type is hard light, color tone is cool, perspective angle is low-angle, material textures include metal frame and glass. Add a potted pothos plant next to the window, white ceramic pot, glossy green leaves. The right-side leaves should have bright highlights (matching right cool source), left leaves with distinct shadows, pot with cast shadow at the bottom, perspective matching the low-angle view.",
            "structured": "[Original Image Analysis]\n  - Light Source Direction: right\n  - Light Type: hard light (cool)\n  - Color Tone: cool\n  - Perspective Angle: low-angle\n  - Material Texture: metal frame, glass\n[Task Information]\n  - Task Type: add object\n  - Target Object: potted pothos\n[Operation Details]\n  - Operation Description: add a potted pothos plant next to the window, white ceramic pot, glossy green leaves\n  - Parameter Requirements: bright highlights on right leaves, distinct shadows on left leaves, cast shadow at pot bottom\n[Visual Specifications]\n  - Lighting Consistency: highlights align with right cool source, strong shadows (hard light characteristic)\n  - Perspective Consistency: maintain low-angle, pot slightly smaller at bottom\n  - Color Consistency: glossy green leaves contrast but coordinate with cool environment"
        }
    ]
}

IDEOGRAM4_ZH = {
    "name": "结构化提示词生成器（视觉叙事版）",
    "description": "作为专业的 Ideogram-4 结构化提示词工程师，我创建精确的 JSON 格式提示词，确保清晰的排版层次和可读性。我的专业知识涵盖视觉设计原则、排版、色彩理论和多文字场景优化。我擅长通过构图、光影、色彩和质感的协同来表达情绪，让画面成为值得反复品味的视觉故事。",
    "input_template": "根据用户输入，生成 {mode} Ideogram-4 结构化提示词。用户输入：#\n\n输出格式见下方。\n\n创作核心原则：\n- 光影是情绪的语言：通过光线的方向、软硬、冷暖来讲述故事，高光与阴影的过渡应柔和自然\n- 质感高于清晰度：真实的魅力在于细腻的纹理（毛孔、织物、木纹），而非机械的锐利边缘\n- 空间层次是画面深度：前景元素应部分遮挡中景或背景，营造纵深感\n- 文字既是信息也是设计元素——其位置、大小、颜色、字体风格服务于整体构图\n- 色彩是情感的调色板：主色调奠定基调，辅助色丰富层次，点缀色制造视觉惊喜",
    "output_format_suffix": {
        "natural": "自然段落（2-3段），首段确立整体场景与构图基调，次段展开主体与细节描绘，末段补充光影色彩与氛围。语言富有画面感和艺术感染力，避免数据化参数。",
        "structured": "{\n  \"high_level_description\": \"一两句话概括整个图像内容，突出视觉叙事核心。\",\n  \"style_description\": {\n    \"aesthetics\": \"美学关键词（如 cinematic, dreamy, warm, ethereal 等）。\",\n    \"lighting\": \"光线描述（如 warm golden hour glow, soft diffused window light, dramatic side lighting 等），需描述光线的方向、色温及其对情绪的影响。\",\n    \"medium\": \"媒介类型（photograph / painting / illustration / 3d_render / graphic_design）。\",\n    \"photo\": \"摄影风格描述（仅当 medium 为 photograph 时填写，如 'portrait photography with natural window light, shallow depth of field' 等，不使用具体焦距或光圈数值）。\",\n    \"art_style\": \"艺术风格（仅当 medium 非 photograph 时填写，如 'digital oil painting, visible brushstrokes, fantasy illustration' 等）。\",\n    \"color_palette\": [\"#RRGGBB\", \"#RRGGBB\"]\n  },\n  \"compositional_deconstruction\": {\n    \"background\": \"背景环境描述，包括远景元素、空间深度感。\",\n    \"elements\": [\n      {\n        \"type\": \"obj\",\n        \"bbox\": [y_min, x_min, y_max, x_max],\n        \"desc\": \"元素详细描述，需包含质感、光影、空间位置关系，以及它如何与周围元素互动。\",\n        \"color_palette\": [\"#RRGGBB\"]\n      },\n      {\n        \"type\": \"text\",\n        \"text\": \"要渲染的文字内容。\",\n        \"desc\": \"文字样式描述（字体风格、大小层级、对齐方式、视觉效果如阴影/发光/渐变，以及它在构图中的角色）。\",\n        \"bbox\": [y_min, x_min, y_max, x_max]\n      }\n    ]\n  }\n}"
    },
    "task_requirements": [
        "high_level_description 必填，一两句话概括整体，突出视觉叙事核心",
        "style_description 必填，必须包含 aesthetics、lighting、medium 字段",
        "medium 为 photograph 时填写 photo 字段（用自然语言描述摄影风格），art_style 留空；medium 非 photograph 时填写 art_style 字段，photo 留空",
        "compositional_deconstruction 必填，background 和 elements 都必填",
        "elements 至少一个元素，type 必填（obj 或 text）",
        "color_palette 颜色必须大写 #RRGGBB 格式，全局最多16色，元素级最多5色",
        "bbox 坐标归一化为 0-1000 整数，顺序为 [y_min, x_min, y_max, x_max]，注意 y_min<y_max 且 x_min<x_max",
        "必须明确区分前景、中景、背景的空间层次：\n  - 前景元素（bbox 的 y 值较小/靠近画面顶部，如 y_min 在 0-300 范围）：应部分裁切在画面边缘，遮挡中景元素，营造框架感和纵深感\n  - 中景元素（bbox 居中，如 y 在 200-700 范围）：通常是主体，应完整或大部分完整呈现\n  - 背景元素：在 background 字段描述其虚化/简化状态，营造空间深度",
        "摄影类照片应描述景深层次（前景/中景/背景的虚实关系）和自然光影过渡",
        "插画类作品应描述前景中景背景的遮挡关系和空间层次",
        "文字元素 desc 需包含：字体风格、字号层级（主/次/辅）、对齐方式、视觉效果（阴影/发光/渐变/纹理）",
        "海报/logo 等文字密集场景需明确主次标题层级关系和排版布局，文字颜色控制在3种以内",
        "自然模式输出 2-3 个自然段落；结构化模式输出 JSON"
    ],
    "constraints": {"max_length": 800},
    "positive_constraints": "主体突出明确，形态比例准确，质感真实细腻，光影层次分明有叙事性，色彩配比和谐统一，构图逻辑清晰有视觉引导。画面干净克制，仅保留核心叙事元素，无冗余杂物堆砌。人像类风格辨识度强：真实风格保留自然肌理与非对称特征，网红风格呈现精致无瑕的滤镜质感；其余品类均符合对应视觉语言，整体兼具审美性与生成稳定性，真实自然有呼吸感。",
    "negative_prompts":  "主体变形失真，质感虚假塑料感，光影杂乱过曝，色彩脏污溢出，元素堆砌冗余，构图失衡杂乱，透视比例错误，低分辨率模糊，多余杂物乱入，字幕水印logo，光影生硬断层，过度锐化生硬，边缘锯齿毛躁。人像类：真实风格磨皮过度无肌理，网红风格五官扭曲假脸；场景类：元素杂乱无层次，空间逻辑混乱；产品类：反光虚假，材质失真。",
    "examples": [
        {
            "category": "摄影",
            "natural": "一张电影感人像照，低角度仰拍，中长焦段营造平滑的空间压缩感，浅景深将背景虚化成梦幻的光斑。画面采用框架式构图——前景左下角，一块霓虹灯牌的局部边缘（红色与青色光管交错）被柔和地虚化，像一层温暖的薄纱半掩着镜头，引导视线穿过它，投向画面中央的亚洲女性。她站在湿润的城市街道上，正回眸望来，米色风衣的领口被微风轻轻掀起一角。她的长发被风拂起几缕，发丝在暖色路灯下泛着柔和的光。皮肤自然通透，颧骨处有淡而真实的晒斑，鼻翼两侧可见细腻的毛孔，眼下有轻微的细纹——这些细节没有经过修饰，却让这张脸显得真实而有故事。她的目光温柔而深邃，像在街角想起了某个久远的片段。背景是都市夜景——暖色的路灯在潮湿的地面上拉出长长的倒影，远处的建筑轮廓被雾气柔化，所有细节都融化在奶油般的焦外散景里。整张照片弥漫着一种温暖而略带感伤的都市氛围，像是电影里女主角转身前的那一帧。",
            "structured": "{\n  \"high_level_description\": \"一位亚洲女性站在霓虹闪烁的都市街道上回眸，前景霓虹灯牌虚化作为框架，背景散景如梦似幻。\",\n  \"style_description\": {\n    \"aesthetics\": \"cinematic, film grain, nostalgic, warm, intimate\",\n    \"lighting\": \"warm street lamp side light from upper right, gentle rim light on hair, soft bokeh background, natural shadow transitions\",\n    \"medium\": \"photograph\",\n    \"photo\": \"portrait photography with medium telephoto perspective, shallow depth of field, low angle eye-level shot, natural urban light\",\n    \"art_style\": \"\",\n    \"color_palette\": [\"#FFD700\", \"#FF6B6B\", \"#1A1A2E\", \"#F5F5F5\", \"#4A4A4A\"]\n  },\n  \"compositional_deconstruction\": {\n    \"background\": \"霓虹城市街道，远景建筑轮廓被雾气笼罩，暖色路灯形成奶油般散景（bokeh），潮湿地面反射霓虹倒影，整个背景做浅景深虚化处理，营造梦幻氛围。\",\n    \"elements\": [\n      {\n        \"type\": \"obj\",\n        \"bbox\": [0, 0, 300, 500],\n        \"desc\": \"前景霓虹灯牌，红色和青色光管组成的日文招牌局部，画面左下角部分裁切，高度虚化呈柔和光斑，仅露出边缘轮廓作为前景框架，营造空间纵深感。\",\n        \"color_palette\": [\"#FF6B6B\", \"#00CED1\"]\n      },\n      {\n        \"type\": \"obj\",\n        \"bbox\": [150, 250, 850, 750],\n        \"desc\": \"亚洲女性，中景主体，柔和侧光照明，鹅蛋脸，健康自然肤色，面颊有淡淡雀斑，鼻翼细腻毛孔可见，眼下轻微细纹，长发被微风吹起，发丝根根清晰，米色风衣领口微敞，回眸表情温柔深邃，眼神光温暖，唇色自然偏粉，唇纹细腻可见。\",\n        \"color_palette\": [\"#FFDAB9\", \"#F5F5DC\", \"#8B4513\"]\n      }\n    ]\n  }\n}"
        },
        {
            "category": "插画",
            "natural": "一幅梦幻森林精灵少女插画，低视角仰视，前景是巨型发光蘑菇的局部——菌盖半透明，内部荧光脉络如血管般清晰，从画面底部和左右两侧伸展进来，像一座发光的拱门，将视线引向画面中央。中景处，一位精灵少女坐在粗壮的树干上，银白色长发垂落至腰间，薄翼在光源下脉纹分明，她微微侧身，仿佛正要转过头来。背景是森林深处，薄雾笼罩着远方的树干和蕨类植物，隐约可见瀑布的水雾在蓝紫色的光晕中弥漫。整体以蓝紫与青绿为主调，厚涂笔触保留着画布的纹理。高分辨率下，能看到蘑菇菌盖上的荧光颗粒和空气中飘浮的细小鳞粉。",
            "structured": "{\n  \"high_level_description\": \"幻想风格的森林场景，低视角仰视，前景巨型发光蘑菇作为框架，中景精灵少女坐在树干上薄翼闪烁，背景薄雾笼罩的幻想森林。\",\n  \"style_description\": {\n    \"aesthetics\": \"fantasy, ethereal, dreamy, enchanting\",\n    \"lighting\": \"bioluminescent glow from mushrooms casting upward light, soft ambient fill, volumetric fog with rim light on wings, cool blue-purple atmosphere\",\n    \"medium\": \"painting\",\n    \"photo\": \"\",\n    \"art_style\": \"digital厚涂painting, visible brushstrokes, canvas texture, fantasy illustration, rich color layering\",\n    \"color_palette\": [\"#4B0082\", \"#00CED1\", \"#9370DB\", \"#98FB98\", \"#E6E6FA\"]\n  },\n  \"compositional_deconstruction\": {\n    \"background\": \"幻想森林深处，薄雾笼罩的粗壮树干和蕨类植物，远景瀑布水雾弥漫在蓝色雾气中，低饱和度蓝紫色调，远景元素做模糊和简化处理营造空间深度。\",\n    \"elements\": [\n      {\n        \"type\": \"obj\",\n        \"bbox\": [300, 0, 700, 450],\n        \"desc\": \"前景巨型发光蘑菇（右侧），菌盖直径占画面宽度的1/4，半透明可见内部荧光脉络，厚涂笔触纹理清晰，蘑菇伞沿部分遮挡中景精灵少女的右肩，营造前景框架效果。\",\n        \"color_palette\": [\"#00FF7F\", \"#7CFC00\", \"#ADFF2F\"]\n      },\n      {\n        \"type\": \"obj\",\n        \"bbox\": [200, 0, 500, 400],\n        \"desc\": \"前景巨型发光蘑菇（左侧），菌盖半透明荧光，从画面左边缘延伸进来，部分裁切在画面外，与右侧蘑菇形成框架式构图，中间留出中景精灵少女的空间。\",\n        \"color_palette\": [\"#00FF7F\", \"#7CFC00\"]\n      },\n      {\n        \"type\": \"obj\",\n        \"bbox\": [250, 250, 750, 800],\n        \"desc\": \"精灵少女，中景主体，坐在粗壮的树干上，身体朝向画面右侧但头部转向观众，精致五官，银色长发及腰带有微弱闪光，薄翼展开脉纹清晰可见，穿着轻盈半透明连衣裙，裙摆有鳞粉颗粒飘落。\",\n        \"color_palette\": [\"#C0C0C0\", \"#E6E6FA\", \"#DDA0DD\"]\n      }\n    ]\n  }\n}"
        },
        {
            "category": "海报",
            "natural": "一张咖啡品牌促销海报，以米黄色宣纸肌理为底，温暖的棕色系贯穿始终。主标题“COFFEE”以超大号手写体居画面上方，笔画粗犷流畅，边缘略带毛边，模拟钢笔书写的质感，深棕色的文字在暖色背景上形成强烈的视觉锚点。右上方，一个极简的咖啡杯剪影安静地缀在标题旁，像是设计师随手画上的注脚。标题下方，中号无衬线体“ARTISAN BREWS”以深棕色呈现，字距宽松，呼吸感十足。最底部，小号衬线体“EST. 2024”以浅棕色细体收尾，完成了从主到次、由粗到细、由深到浅的完美信息层级递进。整张海报没有多余的装饰，但每一处留白、每一根线条都在讲述一个关于时间与温度的故事。",
            "structured": "{\n  \"high_level_description\": \"一张温暖复古风格的咖啡品牌促销海报，手写体大字'COFFEE'居中作为视觉中心，下方层级递减的品牌名和日期，咖啡杯剪影点缀。\",\n  \"style_description\": {\n    \"aesthetics\": \"vintage, warm, cozy, minimalistic, handcrafted\",\n    \"lighting\": \"soft ambient lighting, warm brown tones, subtle shadow effects, organic paper texture\",\n    \"medium\": \"graphic_design\",\n    \"photo\": \"\",\n    \"art_style\": \"vintage poster design, hand lettering, organic textures, warm color palette\",\n    \"color_palette\": [\"#F5E6D3\", \"#8B4513\", \"#D2691E\", \"#F5DEB3\", \"#2F1810\"]\n  },\n  \"compositional_deconstruction\": {\n    \"background\": \"米黄色宣纸肌理背景，淡淡的咖啡渍纹理，温暖柔和，整体作为底层不抢文字主体。\",\n    \"elements\": [\n      {\n        \"type\": \"text\",\n        \"text\": \"COFFEE\",\n        \"desc\": \"超大号手写体英文字，深棕色#8B4513，粗笔画，毛边质感模拟钢笔书写，居中放置，字号占据画面宽度约60%，作为主标题/视觉第一层级，文字下方有轻微投影增加立体感。\",\n        \"bbox\": [100, 150, 350, 850]\n      },\n      {\n        \"type\": \"obj\",\n        \"bbox\": [200, 780, 350, 950],\n        \"desc\": \"极简咖啡杯剪影，深棕色#2F1810，轮廓清晰，位于主标题右侧作为装饰元素，尺寸约为主标题高度的1/3。\",\n        \"color_palette\": [\"#2F1810\"]\n      },\n      {\n        \"type\": \"text\",\n        \"text\": \"ARTISAN BREWS\",\n        \"desc\": \"中号无衬线英文字，深棕色#8B4513，常规粗细，居中放置于主标题下方约150px处，字号约为主标题的40%，字距宽松，作为品牌名/视觉第二层级。\",\n        \"bbox\": [380, 250, 480, 750]\n      },\n      {\n        \"type\": \"text\",\n        \"text\": \"EST. 2024\",\n        \"desc\": \"小号衬线英文字，浅棕色#D2691E，细体，居中放置于品牌名下方约100px处，字号约为品牌名的50%，作为辅助信息/视觉第三层级。\",\n        \"bbox\": [520, 350, 600, 650]\n      }\n    ]\n  }\n}"
        },
        {
            "category": "logo/名片",
            "natural": "一张极简商务名片设计——纯白背景像一张无暇的画布，左侧的几何logo以深色圆形轮廓包裹着抽象图形，稳重而克制。右侧，信息从上到下清晰排列：姓名“张小明”以大号粗体无衬线字呈现，黑色，视觉上最重；其下，“设计总监”以中号细体无衬线字呈现，深灰色，与姓名形成粗细和视觉重量的对比；最下方，邮箱地址以小号无衬线英文字收尾，深灰色，字号最小但清晰可读。整个布局左右分明，上下有序，没有一丝多余的线条或色彩，却通过字号、字重和间距的变化，让信息一目了然。这不是一张名片，而是一个关于秩序与克制的设计宣言。",
            "structured": "{\n  \"high_level_description\": \"一张极简主义商务名片，白色背景，左侧几何logo，右侧姓名+职位+邮箱垂直排列，专业商务风格。\",\n  \"style_description\": {\n    \"aesthetics\": \"minimalist, professional, clean, corporate\",\n    \"lighting\": \"soft ambient lighting, no shadows, crisp clean edges\",\n    \"medium\": \"graphic_design\",\n    \"photo\": \"\",\n    \"art_style\": \"minimalist corporate design, clean sans-serif typography, precise alignment, high contrast\",\n    \"color_palette\": [\"#FFFFFF\", \"#000000\", \"#333333\"]\n  },\n  \"compositional_deconstruction\": {\n    \"background\": \"纯白色背景，干净无杂质，作为底层衬托前景信息。\",\n    \"elements\": [\n      {\n        \"type\": \"obj\",\n        \"bbox\": [100, 100, 350, 350],\n        \"desc\": \"简约几何公司logo，黑色#000000，圆形轮廓直径约占名片高度的20%，内部抽象几何图形，居中放置于名片左侧。\",\n        \"color_palette\": [\"#000000\"]\n      },\n      {\n        \"type\": \"text\",\n        \"text\": \"张小明\",\n        \"desc\": \"大号粗体无衬线中文字，黑色#000000，字号约占名片高度的8%，位于名片右侧上部，左对齐作为视觉第一层级。\",\n        \"bbox\": [120, 500, 220, 950]\n      },\n      {\n        \"type\": \"text\",\n        \"text\": \"设计总监\",\n        \"desc\": \"中号细体无衬线中文字，深灰色#333333，字号约占名片高度的5%，位于姓名下方间距约20px，左对齐作为视觉第二层级。\",\n        \"bbox\": [250, 520, 330, 850]\n      },\n      {\n        \"type\": \"text\",\n        \"text\": \"xiaoming.zhang@company.com\",\n        \"desc\": \"小号无衬线英文字，深灰色#333333，字号约占名片高度的3.5%，位于职位下方间距约15px，左对齐作为辅助信息/视觉第三层级。\",\n        \"bbox\": [370, 450, 440, 950]\n      }\n    ]\n  }\n}"
        },
        {
            "category": "人像",
            "natural": "一张棚拍人像特写，正面平拍视角，中画幅的细腻质感将亚洲男性的面部细节呈现得淋漓尽致。纯灰色背景干净而克制，让所有的注意力都集中在人物脸上。他的面部结构立体——眉弓清晰，鼻梁高挺，下颌线分明——经典的蝴蝶光从正前方略高处打下，在鼻翼两侧形成对称的浅阴影，眼窝和颧骨下方有柔和的光影过渡，让五官的每一个转折都显得深邃而自然。他的皮肤是健康的小麦色，在光线下泛着自然的光泽，额头发际线处有细微的绒毛，下巴上是两三天未剃的短胡茬，比头发颜色略浅，为这张棱角分明的脸增添了几分粗粝的真实感。他眼神坚定而放松，深棕色的瞳孔里映着主光源的反光，像是一种安静的笃定。他的嘴唇自然闭合，唇色偏深粉，细微的唇纹清晰可见。整张照片没有刻意的修饰，只有光、影和一个人的本来面目。",
            "structured": "{\n  \"high_level_description\": \"棚拍人像特写，经典蝴蝶光照明，亚洲男性面部结构立体，细节丰富，还原真实肤色。\",\n  \"style_description\": {\n    \"aesthetics\": \"professional, natural, clean, realistic\",\n    \"lighting\": \"Paramount lighting (butterfly lighting) from above-center, subtle shadows under cheekbones and eyes, natural skin texture preserved, gentle highlight on forehead\",\n    \"medium\": \"photograph\",\n    \"photo\": \"studio portrait with medium format quality, natural skin tone, shallow depth of field, soft natural light\",\n    \"art_style\": \"\",\n    \"color_palette\": [\"#8B7355\", \"#F5DEB3\", \"#808080\", \"#2F1810\", \"#FFDAB9\"]\n  },\n  \"compositional_deconstruction\": {\n    \"background\": \"纯灰色无缝摄影背景纸，距主体约2米，均匀无反光，整体背景亮度与面部曝光一致。\",\n    \"elements\": [\n      {\n        \"type\": \"obj\",\n        \"bbox\": [150, 200, 850, 800],\n        \"desc\": \"亚洲男性面部特写，正面平拍，额头、发际线细节完整，下颌线清晰，颈部可见喉结但肩部以下未入镜。小麦色健康肤色，蝴蝶光照明下毛孔细腻可见但皮肤整体质感真实，额头发际线处有细微绒毛，眉毛浓密有型略带杂毛，眉弓立体，眼睛瞳孔深棕色虹膜纹理清晰，下眼睑有轻微细纹，鼻梁高挺轮廓分明，嘴唇唇色自然偏深粉，唇纹细微，两三天未剃短胡茬，无配饰。整体表情放松，眼神坚定，零数字锐化。\",\n        \"color_palette\": [\"#8B7355\", \"#2F1810\", \"#FFDAB9\", \"#F5DEB3\"]\n      }\n    ]\n  }\n}"
        }
    ]
}

IDEOGRAM4_EN = {
    "name": "Structured Prompt Generator (Visual Narrative Edition)",
    "description": "As a professional Ideogram-4 structured prompt engineer, I create precise JSON-formatted prompts ensuring clear typographic hierarchy and readability. My expertise covers visual design principles, typography, color theory, and multi-text scene optimization. I excel at orchestrating composition, light, color, and texture to convey emotion, turning each frame into a visual story worth revisiting.",
    "input_template": "Based on user input, generate {mode} Ideogram-4 structured prompt. User input: #\n\nOutput format is specified below.\n\nCore Creative Principles:\n- Light as emotional language: direction, softness, warmth tell the story; highlight-to-shadow transitions should be soft and natural\n- Texture over sharpness: authentic beauty lies in fine textures (pores, fabric, wood grain), not mechanical edge sharpness\n- Spatial layering as depth: foreground elements should partially obscure midground or background to create depth\n- Text as information and design: position, size, color, font style serve the overall composition\n- Color as emotional palette: dominant sets the tone, secondary adds depth, accent creates visual surprise",
    "output_format_suffix": {
        "natural": "Natural paragraphs (2-3). First: overall scene and composition. Second: subject and details. Third: light, color, and atmosphere. Vivid, artistic language, no data parameters.",
        "structured": "{\n  \"high_level_description\": \"One or two sentences summarizing the overall image and visual narrative core.\",\n  \"style_description\": {\n    \"aesthetics\": \"Aesthetic keywords (e.g., cinematic, dreamy, warm, ethereal).\",\n    \"lighting\": \"Lighting description (e.g., warm golden hour glow, soft diffused window light, dramatic side lighting), including direction, color temperature, and emotional impact.\",\n    \"medium\": \"Medium type (photograph / painting / illustration / 3d_render / graphic_design).\",\n    \"photo\": \"Photography style description (only when medium is photograph), e.g., 'portrait photography with natural window light, shallow depth of field'—no specific focal length or aperture values.\",\n    \"art_style\": \"Art style description (only when medium is not photograph), e.g., 'digital oil painting, visible brushstrokes, fantasy illustration'.\",\n    \"color_palette\": [\"#RRGGBB\", \"#RRGGBB\"]\n  },\n  \"compositional_deconstruction\": {\n    \"background\": \"Background environment description, including distant elements and spatial depth.\",\n    \"elements\": [\n      {\n        \"type\": \"obj\",\n        \"bbox\": [y_min, x_min, y_max, x_max],\n        \"desc\": \"Detailed element description, including texture, light, spatial relationships, and how it interacts with surrounding elements.\",\n        \"color_palette\": [\"#RRGGBB\"]\n      },\n      {\n        \"type\": \"text\",\n        \"text\": \"Text content to render.\",\n        \"desc\": \"Text style description (font style, size hierarchy, alignment, visual effects like shadow/glow/gradient, and its role in the composition).\",\n        \"bbox\": [y_min, x_min, y_max, x_max]\n      }\n    ]\n  }\n}"
    },
    "task_requirements": [
        "high_level_description is required—one or two sentences summarizing the visual narrative core",
        "style_description is required—must include aesthetics, lighting, and medium fields",
        "When medium is photograph, use photo field (natural language description of photography style) and leave art_style empty; when medium is not photograph, use art_style field and leave photo empty",
        "compositional_deconstruction is required—background and elements are both required",
        "At least one element required in elements—type must be obj or text",
        "color_palette colors must be uppercase #RRGGBB format, max 16 for global, max 5 per element",
        "bbox coordinates normalized to 0-1000 integers, format [y_min, x_min, y_max, x_max], ensuring y_min<y_max and x_min<x_max",
        "Must distinguish foreground, midground, background spatial layers:\n  - Foreground elements (y_min in 0-300 range): should be partially cropped at edges, obscuring midground elements to create framing and depth\n  - Midground elements (y in 200-700 range): typically the subject, should be fully or mostly visible\n  - Background elements: described in background field as softened/simplified to create depth",
        "Photographic images should describe depth of field layers (foreground/midground/background focus relationships) and natural light transitions",
        "Illustration works should describe foreground-midground-background occlusion relationships and spatial layering",
        "Text element desc must include: font style, size hierarchy (primary/secondary/tertiary), alignment, visual effects (shadow/glow/gradient/texture)",
        "For posters/logos with dense text, specify primary-secondary typographic hierarchy and layout, limit text colors to 3 or fewer",
        "natural mode outputs 2-3 natural paragraphs; structured mode outputs JSON"
    ],
    "constraints": {"max_length": 800},
    "positive_constraints": "Subject is prominent and clear, forms and proportions accurate, texture realistic and delicate, lighting layered and narrative, color ratios harmonious and unified, composition logically clear with visual guidance. The frame is clean and restrained, retaining only core narrative elements, no redundant clutter. Portrait style recognizability is strong: Realistic Style retains natural texture and asymmetric features, Influencer Style presents flawless refined filter quality; other categories comply with their corresponding visual language, combining aesthetics and generation stability, authentic natural and breathable.",
    "negative_prompts": "Subject distortion or deformation, fake plastic texture, messy overexposed lighting, dirty color overflow, redundant element stacking, unbalanced chaotic composition, incorrect perspective and proportion, low-resolution blur, extraneous objects or passers-by, subtitles or watermarks, harsh lighting discontinuities, over-sharpening, jagged rough edges. Portrait: Realistic Style over-smoothing with no texture, Influencer Style distorted fake facial features; Scene: cluttered layers, chaotic spatial logic; Product: false reflections, distorted material.",
    "examples": [
        {
            "category": "Photography",
            "natural": "A cinematic portrait with a low angle, medium telephoto perspective offering smooth spatial compression, and shallow depth of field that melts the background into dreamy bokeh. The composition is framed—a neon sign in the lower-left foreground (red and cyan tubes intertwining) is softly blurred, like a warm veil partially covering the lens, guiding the eye toward the Asian woman at center. She stands on the wet city street, looking back over her shoulder, the collar of her beige trench coat lifted slightly by the breeze. A few strands of her hair catch the warm streetlight. Her skin is naturally translucent, with faint sun spots on her cheekbones, visible pores beside her nose, and subtle lines under her eyes—unretouched details that make her feel real and story-worthy. Her gaze is gentle and deep, as if recalling something from a distant past. Behind her, the city dissolves into warm bokeh—long reflections of streetlights stretch across the wet pavement, distant buildings softened by mist. The whole image exudes a warm, bittersweet urban mood, like the frame before a character turns away in a film.",
            "structured": "{\n  \"high_level_description\": \"An Asian woman looks back on a neon-lit city street, with a blurred neon sign in the foreground framing the composition and dreamy bokeh in the background.\",\n  \"style_description\": {\n    \"aesthetics\": \"cinematic, film grain, nostalgic, warm, intimate\",\n    \"lighting\": \"warm street lamp side light from upper right, gentle rim light on hair, soft bokeh background, natural shadow transitions\",\n    \"medium\": \"photograph\",\n    \"photo\": \"portrait photography with medium telephoto perspective, shallow depth of field, low angle eye-level shot, natural urban light\",\n    \"art_style\": \"\",\n    \"color_palette\": [\"#FFD700\", \"#FF6B6B\", \"#1A1A2E\", \"#F5F5F5\", \"#4A4A4A\"]\n  },\n  \"compositional_deconstruction\": {\n    \"background\": \"Neon-lit city street, distant buildings softened by mist, warm streetlights creating creamy bokeh, wet pavement reflecting neon, all softly blurred by shallow depth of field.\",\n    \"elements\": [\n      {\n        \"type\": \"obj\",\n        \"bbox\": [0, 0, 300, 500],\n        \"desc\": \"Foreground neon sign fragment, red and cyan tubes, lower-left corner partially cropped, highly blurred as soft light patches, serving as a framing element for depth.\",\n        \"color_palette\": [\"#FF6B6B\", \"#00CED1\"]\n      },\n      {\n        \"type\": \"obj\",\n        \"bbox\": [150, 250, 850, 750],\n        \"desc\": \"Asian woman, midground subject, soft side lighting, oval face, natural warm skin tone with faint freckles on cheeks, visible pores beside nose, subtle under-eye lines, hair lifted by breeze, beige trench coat collar slightly open, gentle deep gaze, natural lip color with fine lip lines.\",\n        \"color_palette\": [\"#FFDAB9\", \"#F5F5DC\", \"#8B4513\"]\n      }\n    ]\n  }\n}"
        },
        {
            "category": "Illustration",
            "natural": "A fantasy forest illustration with a low-angle upward view. In the foreground, giant glowing mushrooms frame the scene—their translucent caps revealing vein-like luminescent patterns, reaching in from the bottom and sides like an arched gateway, drawing the eye toward the center. Midground, an elf maiden sits on a thick tree trunk, silver-white hair cascading past her waist, her translucent wings catching the light. She turns slightly, as if about to look back. Background, the forest dissolves into mist—distant tree trunks and ferns, a waterfall’s mist diffusing into blue-purple haze. The palette is dominated by blue-violet and teal-green, with thick brushstrokes preserving the texture of the canvas. At high resolution, fluorescent particles on the mushroom caps and fine scales drifting in the air are clearly visible.",
            "structured": "{\n  \"high_level_description\": \"A fantasy forest scene viewed from a low angle, with giant glowing mushrooms framing the foreground, an elf maiden on a tree trunk in the midground, and misty forest background.\",\n  \"style_description\": {\n    \"aesthetics\": \"fantasy, ethereal, dreamy, enchanting\",\n    \"lighting\": \"bioluminescent glow from mushrooms casting upward light, soft ambient fill, volumetric fog with rim light on wings, cool blue-purple atmosphere\",\n    \"medium\": \"painting\",\n    \"photo\": \"\",\n    \"art_style\": \"digital厚涂painting, visible brushstrokes, canvas texture, fantasy illustration, rich color layering\",\n    \"color_palette\": [\"#4B0082\", \"#00CED1\", \"#9370DB\", \"#98FB98\", \"#E6E6FA\"]\n  },\n  \"compositional_deconstruction\": {\n    \"background\": \"Deep fantasy forest with mist-shrouded trunks and ferns, distant waterfall mist diffusing into blue-purple light, low-saturation blue tones, distant elements blurred for depth.\",\n    \"elements\": [\n      {\n        \"type\": \"obj\",\n        \"bbox\": [300, 0, 700, 450],\n        \"desc\": \"Foreground giant glowing mushroom (right), cap spans about 1/4 of frame width, translucent with visible fluorescent veins, thick brushstrokes, partially obscuring the elf maiden's right shoulder as a framing element.\",\n        \"color_palette\": [\"#00FF7F\", \"#7CFC00\", \"#ADFF2F\"]\n      },\n      {\n        \"type\": \"obj\",\n        \"bbox\": [200, 0, 500, 400],\n        \"desc\": \"Foreground giant glowing mushroom (left), translucent fluorescent cap extending from the left edge, partially cropped, paired with the right mushroom as a framing device, leaving space for the midground subject.\",\n        \"color_palette\": [\"#00FF7F\", \"#7CFC00\"]\n      },\n      {\n        \"type\": \"obj\",\n        \"bbox\": [250, 250, 750, 800],\n        \"desc\": \"Elf maiden, midground subject, sitting on a thick tree trunk, body turned right but face toward viewer, delicate features, silver hair to waist with faint shimmer, translucent wings with visible veins, light semi-transparent dress with glowing particles drifting from the hem.\",\n        \"color_palette\": [\"#C0C0C0\", \"#E6E6FA\", \"#DDA0DD\"]\n      }\n    ]\n  }\n}"
        },
        {
            "category": "Poster",
            "natural": "A warm-toned coffee brand promotional poster on a rice paper-textured cream background, with browns running through the entire palette. The headline \"COFFEE\" dominates the upper center in oversized hand-lettered script—bold, flowing strokes with slightly rough edges, as if written with a fountain pen, the deep brown text anchoring the composition against the warm backdrop. To the upper right, a minimalist coffee cup silhouette sits quietly beside the title. Below, \"ARTISAN BREWS\" in medium sans-serif deep brown sits with generous letter-spacing. At the very bottom, \"EST. 2024\" in small serif light brown finishes the hierarchy—from primary to secondary to tertiary, from bold to fine, from dark to light. No excess decoration, yet every space and every line tells a story of time and warmth.",
            "structured": "{\n  \"high_level_description\": \"A warm vintage-style coffee brand promotional poster with hand-lettered 'COFFEE' as the central visual anchor, with descending typographic hierarchy below.\",\n  \"style_description\": {\n    \"aesthetics\": \"vintage, warm, cozy, minimalistic, handcrafted\",\n    \"lighting\": \"soft ambient lighting, warm brown tones, subtle shadow effects, organic paper texture\",\n    \"medium\": \"graphic_design\",\n    \"photo\": \"\",\n    \"art_style\": \"vintage poster design, hand lettering, organic textures, warm color palette\",\n    \"color_palette\": [\"#F5E6D3\", \"#8B4513\", \"#D2691E\", \"#F5DEB3\", \"#2F1810\"]\n  },\n  \"compositional_deconstruction\": {\n    \"background\": \"Cream rice paper texture background with faint coffee stain textures, warm and soft, serving as a quiet backdrop for the typography.\",\n    \"elements\": [\n      {\n        \"type\": \"text\",\n        \"text\": \"COFFEE\",\n        \"desc\": \"Oversized hand-lettered English text, deep brown #8B4513, bold strokes with rough edges simulating pen writing, centered, occupying about 60% of frame width, primary visual layer with subtle drop shadow.\",\n        \"bbox\": [100, 150, 350, 850]\n      },\n      {\n        \"type\": \"obj\",\n        \"bbox\": [200, 780, 350, 950],\n        \"desc\": \"Minimalist coffee cup silhouette, deep brown #2F1810, clean outline, positioned to the right of the main title as a decorative element, about 1/3 the height of the main title.\",\n        \"color_palette\": [\"#2F1810\"]\n      },\n      {\n        \"type\": \"text\",\n        \"text\": \"ARTISAN BREWS\",\n        \"desc\": \"Medium sans-serif English text, deep brown #8B4513, regular weight, centered 150px below main title, about 40% of main title size, generous letter-spacing, secondary visual layer.\",\n        \"bbox\": [380, 250, 480, 750]\n      },\n      {\n        \"type\": \"text\",\n        \"text\": \"EST. 2024\",\n        \"desc\": \"Small serif English text, light brown #D2691E, light weight, centered 100px below secondary text, about 50% of secondary text size, tertiary visual layer.\",\n        \"bbox\": [520, 350, 600, 650]\n      }\n    ]\n  }\n}"
        },
        {
            "category": "Logo/Business Card",
            "natural": "A minimalist business card on a pure white background—a clean canvas. On the left, a geometric logo in dark tones, a circular frame containing an abstract shape, restrained and solid. On the right, information arranged vertically from top to bottom: name \"Zhang Xiaoming\" in large bold sans-serif, black, visually heaviest; below it, \"Design Director\" in medium light sans-serif, dark gray, creating contrast in weight and visual hierarchy; at the bottom, an email address in small sans-serif, dark gray, smallest but still crisp and legible. The layout is divided left-right, ordered top-bottom. No excess lines or colors—yet through variations in size, weight, and spacing, the information hierarchy is crystal clear. This is not just a business card—it is a statement of order and restraint.",
            "structured": "{\n  \"high_level_description\": \"A minimalist business card on white background, with a geometric logo on the left and name+title+email vertically arranged on the right.\",\n  \"style_description\": {\n    \"aesthetics\": \"minimalist, professional, clean, corporate\",\n    \"lighting\": \"soft ambient lighting, no shadows, crisp clean edges\",\n    \"medium\": \"graphic_design\",\n    \"photo\": \"\",\n    \"art_style\": \"minimalist corporate design, clean sans-serif typography, precise alignment, high contrast\",\n    \"color_palette\": [\"#FFFFFF\", \"#000000\", \"#333333\"]\n  },\n  \"compositional_deconstruction\": {\n    \"background\": \"Pure white background, clean and free of impurities, serving as the base layer beneath foreground elements.\",\n    \"elements\": [\n      {\n        \"type\": \"obj\",\n        \"bbox\": [100, 100, 350, 350],\n        \"desc\": \"Minimalist geometric company logo, black #000000, circular outline about 20% of card height, abstract geometric shape inside, centered on the left side of the card.\",\n        \"color_palette\": [\"#000000\"]\n      },\n      {\n        \"type\": \"text\",\n        \"text\": \"张小明\",\n        \"desc\": \"Large bold sans-serif Chinese text, black #000000, about 8% of card height, positioned on the upper right side, left-aligned, primary visual layer.\",\n        \"bbox\": [120, 500, 220, 950]\n      },\n      {\n        \"type\": \"text\",\n        \"text\": \"设计总监\",\n        \"desc\": \"Medium light sans-serif Chinese text, dark gray #333333, about 5% of card height, positioned 20px below name, left-aligned, secondary visual layer.\",\n        \"bbox\": [250, 520, 330, 850]\n      },\n      {\n        \"type\": \"text\",\n        \"text\": \"xiaoming.zhang@company.com\",\n        \"desc\": \"Small sans-serif English text, dark gray #333333, about 3.5% of card height, positioned 15px below title, left-aligned, tertiary visual layer.\",\n        \"bbox\": [370, 450, 440, 950]\n      }\n    ]\n  }\n}"
        },
        {
            "category": "Portrait",
            "natural": "A studio portrait close-up, eye-level straight-on perspective, medium format resolution capturing every detail of an Asian male face. A pure gray background is clean and restrained, drawing all attention to the subject. His facial structure is defined—clear brow ridge, high nose bridge, sharp jawline—with classic butterfly lighting from slightly above-center creating symmetrical shadows beside the nose and soft transitions under the cheekbones and eye sockets, giving depth and dimension to every plane. His skin is a healthy wheat tone, naturally luminous under the light, with fine baby hairs along the hairline and two-day stubble on the chin, slightly lighter than his hair, adding an authentic roughness to his features. His gaze is steady and relaxed—the key light reflected in his dark brown pupils like quiet certainty. His lips are naturally closed, a deep pinkish tone, with fine lip lines clearly visible. No retouching, no enhancement—just light, shadow, and a face as it is.",
            "structured": "{\n  \"high_level_description\": \"Studio portrait close-up with classic butterfly lighting, Asian male with defined facial structure, rich detail, natural skin tone.\",\n  \"style_description\": {\n    \"aesthetics\": \"professional, natural, clean, realistic\",\n    \"lighting\": \"Paramount lighting (butterfly lighting) from above-center, subtle shadows under cheekbones and eyes, natural skin texture preserved, gentle highlight on forehead\",\n    \"medium\": \"photograph\",\n    \"photo\": \"studio portrait with medium format quality, natural skin tone, shallow depth of field, soft natural light\",\n    \"art_style\": \"\",\n    \"color_palette\": [\"#8B7355\", \"#F5DEB3\", \"#808080\", \"#2F1810\", \"#FFDAB9\"]\n  },\n  \"compositional_deconstruction\": {\n    \"background\": \"Solid gray seamless background paper, about 2 meters from subject, uniform and non-reflective, background brightness matched to face exposure.\",\n    \"elements\": [\n      {\n        \"type\": \"obj\",\n        \"bbox\": [150, 200, 850, 800],\n        \"desc\": \"Asian male face close-up, straight-on eye-level view, full forehead and hairline visible, clean jawline, neck visible but shoulders cropped. Healthy wheat skin tone, fine pores visible under butterfly lighting but skin texture remains natural, fine baby hairs along hairline, thick natural brows with slight stray hairs, defined brow ridge, dark brown eyes with visible iris texture, subtle fine lines under lower eyelids, high nose bridge, naturally pigmented lips with fine lip lines, 2-day stubble slightly lighter than hair, no accessories. Relaxed expression, steady gaze, zero digital sharpening.\",\n        \"color_palette\": [\"#8B7355\", \"#2F1810\", \"#FFDAB9\", \"#F5DEB3\"]\n      }\n    ]\n  }\n}"
        }
    ]
}